#+title: Still doing cases
#+slug: still-doing-cases
#+date: 2004-08-06T23:16:00+12:00
#+lastmod: 2004-08-06T23:16:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT302 Cases
#+draft: False

Today we discussed Branson's Virgin. What stands out for me is the two or three times that people actually began to talk to one another, rather than talking at me (or Rochelle). This is happening a little earlier in the course than normal, and that is great. I think next week I must ensure that people are linking to each others ideas-- hopefully that will foster more understanding and discussion, rather than people focusing on trying to score points.

I think it was Daneka who spotted when I wasn't engaging with one of the other students--I think that was pretty astute of her, and it gave me a good chance to model the importance of asking for clarification.

So what did I take away from today's discussion (and I've got to say it was different from any discussion I've been part of about Branson).

Alas, my notes are back in the office, so this really is what I've taken away.

Well, Branson's personality and style is manifested in the type strategist he is. This has further played itself out in the structure and culture of the organisation. This has significant implications for anyone seeking to replace Branson. For example, the large number of firms that make up Virgin have, in many ways, been kept entrepreneurial--quiet possibly beyond the usefulness of doing that. What is unresolved is the extent to which /luck/ has been an essential ingredient in the success of the organisation.
