#+title: Assessment
#+slug: assessment
#+date: 2017-03-06T15:25:34+13:00
#+lastmod: 2017-03-06T15:25:34+13:00
#+categories[]: Teaching
#+tags[]: BUSINESS304 Assessment
#+draft: False

How to assess what a persons knows? Or do I mean, how to assess what a person knows in an efficient and effective way?

Let us assume that we want to assess a person's vocabulary. How might we do that?

Various bit of research suggest that a two-year old has a vocabulary of about 300 words, growing to 5,000 words at five years old, and as many as 25,000--40,000 words as a graduate. At age sixty, an native English speakers vocabulary might be as much as 48,000 words.

One way to test a person's vocabulary would be to see how many of the 170,000 plus words from the Oxford English Dictionary are known? Whilst thorough (but maybe not comprehensive), such an approach would be time consuming. If testing took ten seconds per word, then testing would take nearly 12 days (at forty hours per week). Rather impractical.

A common approach is to use a much smaller selection of words, say 300, some of which are very common, some being less frequently used. It is possible to justify this approach quite robustly.

Where this method breaks down is when 'students' are told the list of words (or even a larger list of words, say 1,000) from which the test sample will be drawn. This is equivalent to 'teaching the test'. At this point one is no longer assessing the students vocabulary; one is assessing something much smaller than their real vocabulary, and doing so in a way that skews the results.

In many ways this is similar to be given the topics for an exam ...

A different problem with testing with a list of words (whether the student is given the list or not), is that whilst such a procedure can tell if a student knows a word or not, it does not reveal if they can use it well. When, for example, is it better to use convoluted versus complex?

An alternative approach is to engage the student in a wide ranging conversation and see what words they 'naturally' use (and how they are used). This gives a different measure of the persons vocabulary.

Now I would not want to conflate 'knowing words' with knowing a topic such as strategic management, but many of the principles are the same. Rather than testing the student's knowledge by seeing if they know words or not, it might be better to engage them in a somewhat open-ended strategic conversation and see how they 'talk' about strategic management.

That could be done either as an essay, or maybe by presenting a position on a case in a discussion in class.

That sounds a bit like BUSINESS 304.
