#+title: Lecturing
#+slug: lecturing
#+date: 2017-05-17T12:22:39+12:00
#+lastmod: 2017-05-17T12:22:39+12:00
#+categories[]: Teaching
#+tags[]: BUSINESS705
#+draft: False

Notes from:

#+BEGIN_QUOTE

Cooper, J. L. and Robinson, P. (2000). The argument for making large classes seem small. /New directions for teaching and learning/. p. 5-16.

#+END_QUOTE

The prevail reality is that "In undergraduate settings today, large-class environments are prevalent. On many campuses, dozens of classes are regularly enrolled at over fifty students, and many carry enrolments of one hundred, two hundred, and up to six hundred and even seven hundred students. The political realities of large universities are structured to have large-enrolment lower-division courses pay for small-enrolment upper-division and graduate classes."

Give that reality, I still think it behoves us to ask "Are lectures effective?"

The answer seems to be that, compared to discussion based classes, lectures are equally good at fostering the memorization of low-level factual material; i.e., surface learning. But in terms of deep learning---i.e., "long-term knowledge retention, transfer of knowledge to new situations, measures of higher-order thinking, attitude change, and motivation for further study"---lecturing comes off poorly.

This can be seen as a "/compact of disengagement/ between faculty members and students ... you leave me alone, and I'll leave you alone".

So, are there appropriate uses of lectures? Yes. Amongst them are:

#+BEGIN_QUOTE

- To organize, integrate, and update reading materials
- To relate course relevant personal experiences to the students
- To explain and develop complex concepts and ideas introduced in the reading
- To provide context for issues and ideas and information introduced in the readings
- To model problem solving and critical thinking as conducted by an advanced practitioner in the field
- To demonstrate enthusiasm for the subject matter

#+END_QUOTE

However, I suspect the last two, or maybe three, are best done in a lecture context; the other points can be addressed through supplemental reading notes or other non-lecture based delivery methods; i.e., where "material is readily available and comprehensible in print".

At the undergraduate level, I believe that much if not all of the "content" can be delivered outside of the classroom. Thinking of /the best use of students' and lecturers' time together/, classes should be used for:

#+BEGIN_QUOTE

- Promoting cognitive elaboration
- Enhancing critical thinking
- Providing feedback
- Promoting social and emotional development
- Appreciating diversity

#+END_QUOTE

In other words, doing things with the "content" of the course and getting immediate feedback (from peers and teaching staff) on their actions and thoughts.

As I design BUSINESS 705, these thoughts loom large.
