#+title: Project managing dependencies
#+date: 2021-10-25T19:10:00+1300
#+lastmod: 2021-10-25T19:10:00+1300
#+categories[]: Zettels
#+tags[]:  Coursera Project_management

Dependency management: The process of managing interrelated tasks and resources with the project to ensure the overall project is completed successfully, on time, and in budget.

Dependencies are the links that connect one project task to another, and are often the greatest source of risk to a project.

* Internal dependencies
The relations between two tasks within the same project.

* External dependencies
Tasks that are reliant on outside facts, like regulatory agencies or other projects.

* Mandatory dependencies
Tasks that are legally or contractually required.

* Discretionary dependencies
Tasks that could occur on their own, but the team chose to make them reliant on one another.

* Ways to manage dependencies
- Proper identification
- Recording dependencies: The *risk register* is a table or chart that contains your list of risks and dependencies.
- Continuous monitoring and control: check-in on processes and tasks
- Efficient communication

* Backlinks
- [[{{< ref "202110171207-project-risk-management" >}}][Project risk management]]

