#+title: Back to work
#+slug: back-to-work
#+date: 2008-09-07T17:06:00+12:00
#+lastmod: 2008-09-07T17:06:00+12:00
#+categories[]: Research
#+tags[]: PhD Productivity CSS
#+draft: False

Having spent a lot of the weekend sorting out the styles and templates for the blog, I think it's about time to get back to work; i.e., the [[{{< ref "phd-topic" >}}][PhD]].

However, before I abandon this "diversion' I thought I'd make a few notes about what still might need to be done on the site:

- The main page of the blog just lists the ten, or so, most recent posts. At the bottom of the page there is a link to the site's archives. I wonder if I need something upfront, such as a search box, to allow people to find old material more easily.
- I've done away entirely with the sidebar. That gives the page a cleaner look, but it doesn't invite people to explore more of the site.
- Finally, I've started using the hierarchical categories. I had planned to do this earlier. But, having now installed the latest version of the (software](https://www.movabletype.com/), it's been so easy to do. Now I'm wondering if I should use tags as well as categories.

I'm amazed at my capacity to get distracted by something. Such as fixing these templates and styles. I could easily spend much more time doing this. But at the end of the day, I wouldn't be moving forwards on what is really important; my teaching and my research.

Actually, it has taken me less time than I expected to do the changes I -needed- wanted to make. That's all down to [[https://www.google.com/googlebooks/chrome/][Google's]] new web browser [[https://www.google.com/chrome][Chrome]]. It's a slick and tidy piece of software. I would make it my main browser except that it doesn't (yet) support /ad blocking/, and two essential [[https://www.mozilla.com/firefox/][Firefox]] add-ins ( [[https://www.zotero.org/][Zotero]] and [[https://www.libx.org/][libx]]) aren't available for it (Oh, and it isn't yet available for [[https://www.freebsd.org/][FreeBSD]].

Anyway, Chrome has this really neat feature that allows you to inspect elements of a web page to see which parts of your stylesheet are "active'. Without this, I would have spent a lot more time tweaking the site's CSS.

And now, back to the salt mine.

/Update/

[[https://staff.business.auckland.ac.nz/StaffDirectory/StaffProfile/tabid/542/upi/aebe001/Default.aspx][Andrew]] pointed me towards [[https://www.nicolashuon.info/?page=work&type=projects&id=cssviewer][CSSViewer]]. This neat [[https://addons.mozilla.org/extensions/moreinfo.php?id=2104&application=firefox][add-on]] for [[https://www.mozilla.com/en-US/firefox/][Firefox]] shows what the CSS is for a particular element on the screen.

Google's Chrome inspector shows which parts of the style sheet is being used (or overridden) so it is easier to tweak one's style-sheet.
