#+title: Feedback to team members
#+slug: feedback-to-team-members
#+date: 2015-08-13T10:40:00+12:00
#+lastmod: 2015-08-13T10:40:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT300
#+draft: False

#+BEGIN_QUOTE

Hey Peter,

Why is that we have to review the journals of people in our team?it is a little awkward/uncomfortable.

Regards.

Awkward and uncomfortable.

#+END_QUOTE


This was specifically requested by students from last semester. They gave a couple of reasons for wanting it (for part of the course). First, they argued that because it is people in your team you should be more committed to doing a good job of providing feedback; as opposed to giving feedback to people who they did not know and did not care about (and therefore, would not approach the task with such a high degree of commitment).

Secondly, in the spirit of mutual accountability, the thought it would be a way of driving higher performance both from the team and from individual members.

I am concerned that you find it a little awkward or uncomfortable. In your team you need to be able to give good feedback to one another if you hope to do well. This applies to the decisions/choices made as well as the actions people do. This is part of being a good team member. It doesn't mean you have to be harsh in giving your feedback. If you genuinely want your team members to do better in all aspects of MGMT 300, this will come through. Being able to give constructive feedback is a very useful transferable skill that most people find is useful in the workplace.
