#+title: Project tracking
#+date: 2021-10-20T18:27:00+1300
#+lastmod: 2021-10-20T18:27:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

* Tracking
A method of following the progress of project activities.
** Transparency
- It makes project information transparent
** Risk management
- Tracking is crucial for recognizing risks and issues that can derail the project's progress.
** Keeping the project on track
- Tracking keeps all members and stakeholders in touch with deadlines and goals.
- Tracking helps build confidence that the project is set to be delivered on time, in scope, and within budget.

* Deviation
Anything that alters your original course of action. Deviations from the project plan can be positive or negative.

* Common items to track
:PROPERTIES:
:ID:       6d510409-affa-4c26-8163-104637493aa1
:END:
- The project schedule
- Status of action items, key tasks, and activities
- Progress towards milestones
- Costs
- Key decisions, changes, dependencies and risks to the project


* Backlinks
- [[{{< ref "202109121934-project-phase-execution" >}}][Project phase - execution]]
