#+date: 2016-06-08T09:51:30+13:00
#+slug: project-scribe
#+lastmod: 2016-06-08T09:51:30+13:00
#+title: Project Scribe
#+categories[]: Research
#+tags[]: Writing RSL HEC
#+draft: False

The final step in much (most/all) research is writing up the research for some sort of publication. For me, this usually means writing a journal article or a conference paper. I have noted [[{{< ref "research-as-a-second-language" >}}][elsewhere]] about the power of the forty-paragraphs structure in putting together a journal article. But there is much more to getting ones work published.

So, I was delighted to find [[https://projectscrib.org/bios/][Charlotte Cloutier's]] excellent site [[https://projectscrib.org/][Project Scribe]].

There are a raft of resources here; mainly interviews with editors, authors, and reviewers in the academic world of 'organizational studies'. In doing so, it meets Charlotte's aspirations for the site:

#+BEGIN_QUOTE

Writing academic articles can be quite hard work, and academia, especially for those starting out, can be quite the lonely place. I see my personal investment in this blog as a means of trying to overcome a bit of that: to give you tips, ideas and inspiration to help you along when the going gets tough, and to share what others have experienced, so that we can all learn from it.

#+END_QUOTE

Thanks Charlotte (and your collaborators) for a great (and ongoing) resource.
