#+title: Reasons for blended learning
#+date: 2020-04-29T23:40:00+1300
#+lastmod: 2020-04-29T23:40:00+1300
#+categories[]: Zettels Articles
#+tags[]: Teaching

#+BEGIN_QUOTE

Bonk, C. J., Graham, C. R., Cross, J., & Moore, M. G. (2005). /The handbook of blended learning: Global perspectives, local designs/. Center for Creative Leadership. http://ebookcentral.proquest.com/lib/auckland/detail.action?docID=700321

#+END_QUOTE

There are six reasons one might choose to design or use a [[{{< ref "202004292310-blended-learning" >}}][blended learning]] approach:

1. pedagogical richness,
2. access to knowledge,
3. social interaction,
4. personal agency,
5. cost-effectiveness, and
6. ease of revision.

Osguthorpe and Graham (2003). Similarly \autocite[p. 4]{cleveland-innes_2018_GuideBlendedLearning} suggest that blended learning has the following benefits:

1. Opportunity for collaboration at a distance: Individual students work together virtually in an intellectual endeavour as a learning practice.

2. Increased flexibility: Technology-enabled learning allows for learning anytime and anywhere, letting students learn without the barriers of time and location but with the possible support of in-person engagement.

3. Increased interaction: Blended learning offers a platform to facilitate greater interactivity between students, as well as between students and teachers.

4. Enhanced learning: Additional types of learning activities improve engagement and can help students achieve higher and more meaningful levels of learning.

5. Learning to be virtual citizens: Learners practice the ability to project themselves socially and academically in an online community of inquiry. Digital learning skills are becoming essential to be a lifelong learner, and blended courses help learners master the skills for using a variety of technologies.

** Main reasons given for blending
That said, the three man reasons folk give for using blended learning are (1) improved pedagogy, (2) increase access and flexibility, and (3) increased cost-effectiveness.

*** Improved pedagogy
Blended learning tends to foster:
- active learning strategies
- peer-to-peer learning strategies, and
- learner-centred strategies.

*** Increase access and flexibility
Blended learning also allows greater access to programmes than there otherwise would be. They also permit greater flexibility and convenience re the student (especially for mature learners).

*** Increased cost-effectiveness
Typically, blended learning allows for reaching a larger (even international) audience quickly, with greater consistency.

** Categories of blended learning

*** Enabling blends
Primarily centred on addressing issues of access and convenience.

This is where the greatest focus is often found.

*** Enhancing blends
Incremental changes to pedagogy. This can occur anywhere along the spectrum mainly face-to-face through to mainly online.

*** Transforming blends
Allows for radical changes of pedagogy; e.g., from having students as passive receivers of information to having them activity construct knowledge.
