#+date: 2016-06-02T11:51:30+13:00
#+slug: theoretical-description
#+lastmod: 2016-06-02T11:51:30+13:00
#+title: Theoretical description
#+categories[]: Research
#+tags[]:  RSL HEC
#+draft: False

Today, I was lucky enough to attend a session of MOWW (Montreal Organizations Writing Workshop) at HEC Montreal. The session comprises of reviewing two papers that have been either rejected or, as was the case today, had R&Rs. Mike Pratt from Boston College (who is an editor for ASQ) was also here and provided some valuable feedback.

Coming out of the session were a few lessons that I wanted to capture.

First, both papers had very rich cases (Nortel and Faia lot of filesrtrade/sustainable development) at their heart, and both were written by folk who had been practitioners associated with those organisations. Both papers used theory to explain what was going on but failed to move the theory forward in some way. I think, they essentially came to an understanding of their own experiences, rather than using their experiences to show the shortcomings/improvements that could be made to the theory they were utilising.

Mike said that they were in "theoretical description mode", and I am certainly guilty of that a lot of the time. In revising the papers, he suggested that they needed to 'tear down the house' they had built, rather than 'adding new rooms' to it.

He also commented that all papers are labelled as 'high risk revisions'. It is what editors do to show how serious they are.

In hindsight, I think both sets of reviews were saying "What is the mystery here?" in regards to the theory, rather than the case per se. In other words, what does the case show that is not explained by the current theory.

Finally, he said that in looking at the reviews, one needs to separate out the issues that the reviewers highlight, from their suggestions how to deal with them. It is the issues that need addressing rather than the suggestions.
