#+title: Keeping to the point (what was the point anyway?)
#+slug: keeping-to-the-point-what-was-the-point-anyway
#+date: 2004-10-01T13:15:00+12:00
#+lastmod: 2004-10-01T13:15:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT302
#+draft: False

We have finished marking the /Peer Reviews/, and spent the morning comparing and contrasting everyone's assignments.

A number of things stand out when looking at the assignments as a whole.

- Many essays came with a meaningful title--super.
- The second paragraph often began with something like "I took the role of CEO ...", which is the same approach as the example essay in the Black Book. This got pretty tedious after awhile. Likewise, many assignments began by quote Socrates (or similar); again this was wearisome.
- A significant number assignments focused excessively on the team (as a whole), rather than on the author and the gap that the author has between their intended behaviour and their actual behaviour.
- Likewise, people focused on a wide range of theoretical bases but often ignored work that should be core in discussing the gap between intention and behaviour--Argyris and Schön (1974), or similar.
- A source of greater concern were the essays where theory was conspicuous by its absence.
- Despite the admonishment in the Black Book not to "write your reflections on the same form as your peers", it would seem that some people did do this. The result was (as predicted in the Black Book in feedback where they tended "to get their reaction to your reflection, i.e., 'I agree with you, but'"
- Generally, the use of theory tended to be superficial. That is, theory was used to label rather than to explain or predict. Or, theory was briefly mentioned, i.e., Argyris and Schön (1974) might be mentioned once---Look at your essay, how many of your references are cited only once in the essay? (or worse, only cited once and that is in the conclusion).

So, what might be a reasonable 'density' of theoretical concepts that might be appropriate to find in this assignment? (Stage III , 30% of your marks.) Well looking just at Argyris (and Schön for example:

- Espoused theory or theory-of-action
- Theory-in-use
- The gap between theory-of-action and theory-in-use and why it is
  important.
- Action strategies
- Governing variables
- Model I and Model I
- Single- and Double-loop learning Perhaps, this might led on to
  talking about:

  - Defensive reasoning, defensive routines
  - Skilled incompetence

So, for these two authors alone, there might be 20--60 citations (from two or three references). If you had actually read more widely about their ideas then perhaps this might blossom to 80 citations and four or five references. Add in a few more authors (as fitting) and the references could reach 10 or 12 references.
