#+title: A project manager role in change management
#+date: 2021-09-16T18:29:00+1300
#+lastmod: 2021-09-16T18:29:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

Your project’s success depends on the adoption and acceptance of your project whether that entails the launch of a new external tool or a process that will change operations at a production facility. In both cases, the greatest impact of the change will be on the people who use and interact with the product or process that is changing.

You can help ensure your project’s success by embracing changes as they come and by convincing the wider audience, whether that is the end user or members of the organization, to embrace changes, too. When you implement a careful approach to change management, you can address issues that might occur in the later stages of your project.

* Integrating project management and change management

Change management is a major undertaking and a project in and of itself. When it comes to change management, you may not always be responsible for leading and planning the entire end-to-end process. There will be times when your manager, a team member, or another senior leader might be responsible for taking on that transition and successfully implementing the changes. However, just because you're not the one directly leading the change, there are still ways in which you can support and participate in the successful adoption of your project.

As a project manager, you can think of change management as necessary for the successful outcome of your project. Both change management and project management aim to increase the likelihood of project success. They also incorporate tools and processes to accomplish that goal. The most effective way to achieve a project goal is to integrate project management and change management, and it is your responsibility as a project manager to do so.

When you are thinking about change management as it relates to your project, begin by asking yourself the following questions:

How will the organization react to change?

- Which influencers can affect change?
- What are the best means of communication?
- What change management practices will lead to the successful implementation of my project?

* Some best practices for approaching change management
** Be proactive
Proactive and inclusive change management planning can help keep any potentially impacted stakeholders aware of the upcoming changes.

- Incorporate change management into your project management steps. For example, you can schedule time during team meetings or create a feedback document to ensure that your team members know there is a place to voice their suggestions and concerns.
- You can also plan steps towards the end of your project to introduce the deliverable to stakeholders in the form of demonstrations, question and answer forums, or marketing videos. You can factor all of these decisions into your plan so that any potential changes are less likely to impact your timeline. If these steps have not been built into your plan, you can escalate and stress the importance of a change management plan to your stakeholders.

** Communicate about upcoming changes
Communication should occur regularly among impacted stakeholders, the change management team, and the project team. Check in and communicate throughout the project about how the changes will provide a better experience for end users of the project deliverables. In this way, you support the process by providing everyone with the information they need to feel prepared to adjust to changes once the project is ready to launch.

** Follow a consistent process
Following a clear change management process helps maintain consistency each time there is a change. The change management process should be established and documented early on in your project to guide how the project will handle change. Your organization may also have an overarching change management plan that can be adopted for your project. This may include when the promotion of the change should happen, when training should occur, when the launch or release will occur, and corresponding steps for each phase of the process.

** Practice empathy
Changes are inevitable, but we are often resistant to them. By being empathetic to the challenges and anxiety change can bring, you can support the process in subtle ways.

** Use tools
Incorporating tools to assist in the adoption of a change can be very helpful. Here are a few examples you can use on your next project:

- Feedback mechanisms, such as surveys, can capture input from stakeholders.

- Flowcharts can visualize the project's development process.

- Culture mapping can illustrate the company's culture and how the company's values, norms, and employees behavior may be affected by the change.

Change management is essential to your projects’ success.

* Backlinks
- [[{{< ref "202109111153-project-management-tasks" >}}][Project management tasks]]
- [[{{< ref "202109161818-change-management" >}}][Change management]]

* References


#+CATEGORY: Notes
#+STARTUP: showall
