#+title: My Web Sites on MSN
#+slug: my-web-sites-on-msn
#+date: 2005-06-06T20:01:00+12:00
#+lastmod: 2000-09-10T10:01:00+12:00
#+categories[]: Tech
#+tags[]: MSN website Movabletype
#+draft: False

Sometime ago I created a Passport account. In doing so a web folder was created in /My Network Places/. It appears as a /file/ called /My Web Sites on MSN/.

All well and good.

Now I have an iPod and I keep a copy of my "C:\Documents and Settings" as I figure all my documents, etc are stored there. Alas, every time I plug my iPod in to a Windows PC it finds the /web folder/ and stars prompting me to connect (using Passport) to the MSN network---and in doing so it blocks the correct mounting (and unmounting) of the iPod. This happens despite me telling Windows not to do anything with the disk drive that is the iPod.

Anyway, I've deleted the file /My Web Sites on MSN/ and now I no longer get Windows demanding that I login to Passport.

At one stage I thought that perhaps Microsoft was spying on the music that I had installed on my iPod. But, of course, they weren't.

/Update 10 September 2008/ This page is one of the most popular on my site. There are many "arrivals' here from people who have searched for"My Web Sites on MSN". Indeed, the search term"my web sites on msn" is the most search phrase that delivers people to this site.

If I [[https://www.google.co.nz/search?q=%22my+web+sites+on+MSN%22][Google]] the phrase [[https://support.microsoft.com/kb/308412][my web sites on MSN]], the first entry is a link to Microsoft, and the second one is a link to this page.

According to Microsoft:

#+BEGIN_QUOTE

The My Web Sites on MSN folder is added to My Network Places (and appears in common dialog boxes) after you use the Web Publishing Wizard or the Add Network Place Wizard to create or add files to your MSN Web site.

Microsoft offers free storage on the MSN Web site for Passport customers. If you do not have a Passport, you are prompted to create an account when you use the Web Publishing Wizard or the Add Network Place Wizard. If you are not signed in with your Passport account, you are prompted to sign in when you open the "My Web Sites on MSN" folder. A Passport account allows Microsoft to map your files to your security-enhanced Passport account, which helps add security and privacy to your files and makes sure that no one else can access your files.

#+END_QUOTE

With the change of version of [[({{< ref "yet-another-upgrade" >}}][Movable Type]] the words in the page names of this blog are now separated by a hyphen instead of an underline. I wonder how long it will be until this becomes a popular page again. So I have set up a redirect to ensure searches from Google end up on the right page and don't get a [[https://www.404errorpages.com/][404 error]]
