#+title: Project risk management techniques
#+date: 2021-10-25T19:22:00+1300
#+lastmod: 2021-10-25T19:22:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management


If your dependencies are met on time,your team is less likely to fall behind schedule.

If your scope is tightly-managed, you're less likely to incur changes to your budget or be forced to extend your timeline.

Techniques for risk management

* Brainstorming
Add to the *risk register*. Often done as if-then statements

Prioritise the risk register by considering *risk exposure* (a way to measure the potential future loss resulting from a specific event or activity).

Build an Inherent Risk matrix of Impact (low, medium, high) and Probability (low, medium, high).

* ROAM after risks arise
- Resolved: Consider this risk to be addressed. It is no longer a problem.
- Owned: Assign a team member ownership of the risk and monitor the risk through to completion.
- Accepted: Understand and accept the risk for what it is, because it can't be resolved.
- Mitigated: Formulate a plan to reduce the risk

* Escalating
The process of enlisting the help of higher level project leadership of management to remove and obstacle, clarify or reinforce priorities, and validate next steps.

Escalating is good because it:

- Acts as checks and balances
- Generates speedy decision making
- Reduces frustrations
- Encourages participation

Before starting work on a project, the project manager, the team, and the project sponsor should estabilish escalation standards and practices.

A project manager should escalate an issue at the first sign of critical problems in a project. I.e., andything that will affect the *triple constraints* of time, scope, and budget. E.g.,:
- Cause a delay on a major project milestone
- Cause budget overruns
- Can result in the loss of a customer
- Can push back the estimated project completion date

Escalation can stop these problems:
- *Trench wars* occur when two peers or groups cant' seem to come to an agreement, and neither party is willing to give in.
- *Bad compromise* occurs when two parties settle on a so-called solution, but the end product still suffers.


* Backlinks
- [[{{< ref "202110171207-project-risk-management" >}}][Project risk management]]
