#+title: Words
#+slug: words
#+date: 2007-09-27T09:53:00+12:00
#+lastmod: 2007-09-27T09:53:00+12:00
#+categories[]: Research
#+tags[]: Language
#+draft: False

Of late, I've been reading a number of things by Theodore Schatzki. In particular, I have just finished reading:

#+BEGIN_QUOTE

Schatzki, T. R. (2002). /The site of the social: A philosophical account of the constitution of social life and change/. University Park: PA: Pennsylvania State University Press.

#+END_QUOTE

I am continually struck by the subtle, but important, differences in the use of language in difference "genres' of academic writing. This fact will come as no surprise to those who study discourse. Schatzki, has a propensity to use two words that I rarely come across in my usual reading. He likes /qua/ and /pace/.

/Qua/: /In so far as; as; in the capacity of/ Example: When considering people qua strategists, one needs to distinguish "strategic practices'.

/Pace/ /With due deference to; despite/ Example: Pace, those who study discourse, discourse is just another practice.

I wonder how pretentious it would be to use those words in my own writing---after all they aren't really part of my "genre'. I think I answered my own question.
