#+title: Reading and chunking
#+slug: reading-and-chunking
#+date: 2015-04-12T12:51:00+12:00
#+lastmod: 2015-04-12T12:51:00+12:00
#+categories[]: Teaching
#+tags[]: BUSINESS304
#+draft: False

One relatively common comment from students in this course is about the challenge of 'getting on top' of the readings. There can be as many as 60 pages of readings each week and some students struggle with getting through it. More particularly, they find it hard to remember what is in the readings.

Many students find there is too much stuff in each reading. They spend hours trying to learn all the details, and making notes. But, they just do not seem to stick.

For years, I have advocated the following approach. First, skim the reading as fast as you can; your goal is to figure out what is the main message of the reading. Next, go through the reading again (and once again pretty quickly, but not as quickly as the first time). Your goal this time is to find the key ideas that support the main message. Typically, there are three to seven key supporting ideas. Finally, go through the reading again at a leisurely pace picking up on the details of the reading.

For a typical 20-page reading, the first step should around five to ten minutes. The second step might take 15 minutes. And the last step takes, say, 30 minutes.

The way this process works is that provides a framework for you to remember. The key ideas hang-off the main idea, and all the little ideas hang of the key-ideas. Even if you cannot remember all of the little ideas, you can often work them out because of the framework.

This process works because of chunking. Chunking works because the brain can handle big chunks of information better than lots of little (unconnected information). It is easier to remember a phone number as 923 7178 rather than 923718. The chunks (923) and (7178) are more memorable. For a fuller description have a look at the page on Wikipedia on [[https://en.wikipedia.org/wiki/Chunking_%28psychology%29][chunking]].

Anyway, it works. And it is one of the ways you can be more effective in your learning.
