#+title: Vinnies
#+slug: vinnies
#+date: 2004-08-12T22:06:00+12:00
#+lastmod: 2004-08-12T22:06:00+12:00
#+categories[]: Arts
#+tags[]: Dining
#+draft: False

It's the /glorious twelfth/, and that means it's Lisa's and mine wedding anniversary. So, we decided to have dinner at [[https://www.menus.co.nz/vinnies/][Vinnies]] To whet our appetites, we had a glass of Bollinger (non vintage), and the savoury cones. I particular liked the ostrich carpaccio with Japanese pickles, and the truffled hummus was a close second. For entree, I went for that old favourite of home-made paua sausage with kumara miso mash whilst Lisa opted for the crayfish ravioli with poached pacific rock oysters. Both were faultless.

The main course was a hard decision, but eventually Lisa settled on the roasted duck breast with fig tortellini (prompted by our cab driver on the way in), and I went for pan fried snapper. The fish was done to perfection, and Lisa commented on the high quality of the duck.

Because of our choice of food, I though that choosing the wine would be difficult. I was leaning towards the 1983 Marc Bredif Vouvray, but in the end we went with Stewart's, our waiter's, suggestion of the 2001 Leeuwin Art Series Chardonnay. I'm still wondering if the Vouvray (at pretty much the same price), would have been better. To finish, Lisa went for a selection of Italian biscuits and coffee, and I relented and indulged myself with the chocolate truffles.

All in all, a superb dinner. Hats off to Vinnies (again).
