#+title: On becoming a critically reflexive practitioner
#+slug: on-becoming-a-critically-reflexive-practitioner
#+date: 2004-07-27T12:36:00+12:00
#+lastmod: 2004-07-27T12:36:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301 Reflection
#+draft: False

I've just received the latest edition of the [[https://www.sagepub.com/journal.aspx?pid=181][Journal of Management Education]], and there is an element of sychronicity about it. The first article is:

#+BEGIN_QUOTE

Cunliffe, A. L. (2004). On becoming a critically reflective practitioner. /Journal of Management Education, 28/(4), 407--426.

#+END_QUOTE

In this article, she writes about many of the things I've discussed today, or over the past couple of days, as can be seen from the abstract:

#+BEGIN_QUOTE

Critically reflective practice embraces subjective understandings of reality as a basis for thinking more critically about the impact of our assumptions, values, and actions on others. Such practice is important to management education because it helps us to understand how we constitute our realities and identities in relational ways and how e can develop more collaborative and responsive ways of managing organizations. This article offers three ways to of stimulating critically reflective practice: (a) an exercise to help students think about the socially constructive nature of reality, (2) a map to help situate reflective and reflexive practice, and an outline and examples of critically reflexive journalling.

#+END_QUOTE

I think the articles literature review is very accessible. In particular, the idea of "knowing and being" (p. 409) that leads to the ideas that "Knowledge is not just theory or information; it also incorporates knowing from within, a tacit practical consciousness of everyday sense making in which we implicitly know things about our surroundings (people,places, actions) and act from this" (p. 410).

For me this is very much about /bricolage/ (Ortmann & Salzmann, 2002). It is something I hope to foster in the /Business Policy & Strategy/ course.

The links the author makes to Argyris & Schön are also very appropriate for the /Management Theory & Practice/ course--hopefully this will be seen later on in the course.

Those students who have been able to achieve a B+ with their journals (for Management Theory & Practice) might like to consider reading the article to see how they might take them to a new level. In fact, I think that anyone in MGMT 301[1] could improve their journals by reading the article. And, even better (for me), the article has implications for my own practice too.

* References

Cunliffe, A. L. (2004). On becoming a critically reflective practitioner. /Journal of Management Education/, 28(4), 407--426.

Ortmann, G., & Salzmann, H. (2002). Stumbling giants. The emptiness, fullness, and recursiveness of strategic management. /Soziale Systeme, 8/(2), 205--230.
