#+title: Scrum - Backlog refinement
#+date: 2021-10-01T19:06:00+1300
#+lastmod: 2021-10-01T19:06:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

The act of keeping the Backlog described, estimated, and prioritized so that the Scrum Team can operate effectively.

The product owner, and maybe some of the Scrum Team, review the Product Backlog to ensure:
- It contains the appropriate items, and that nothing new is needed or nothing needs to be removed.
- That the items are prioritized by the Product Owner, this is also called setting the order field
- That the items at the top of the Backlog are ready for delivery with clear acceptance criteria
- The Backlog items include estimates or an informed assessment of how much work a particular Backlog item will take.

It's up to the team to decide when and how often to do Backlog refinement.

** Estimation
Through estimation, the team knows how much work it will have ahead of them.

We tend to under-estimate how much effort is needed. To overcome this in Scrum, relative estimation is used instead of absolute estimation. In other words:

- Instead of trying to determine exactly how long a task will take, we compare the effort of that task to another task, and that becomes the estimate. Two methods are popular:
  - *T-Shirt sizes*
    Pick and item that seems like it is a medium workload, and call it medium. After that compare every other item to that task and label them as either Small, Medium, or Large.

  - *Story points* or Planning Poker.
    The team picks an item as their anchor item. All the other items are compared to that item and are allocated story points. Often the Fibonacci sequence is used (0, 1, 1, 2, 3, 5, 8, 13, 21 ...). The first 0, and 1 are skipped.

    As the estimates get bigger, the numbers grow more quickly because the risk and uncertainty goes up.

Story points are more powerful than the T-Shirt sizes, which is easier to do.

* Best practices

Some best practices, regardless of the technique you use, include:

- Asking the Product Owner questions about the user story or item to ensure that there is enough information to estimate it.

- Discussing divergent estimates from various team members so that everyone has a chance to understand how to implement the item.

- Agreeing on the final T-shirt sizes or points value and capturing it in the system.

- If certain items fall into the larger T-shirt size or story points value range, discussing whether it makes sense to break them down into smaller pieces before moving on.

* Backlinks
- [[{{< ref "202110011924-agile-effort-estimation-techniques" >}}][Agile effort estimation techniques]]
- [[{{< ref "202109301840-scrum-product-backlog" >}}][Scrum - Product Backlog]]

