#+title: Google mail
#+slug: google-mail
#+date: 2008-07-18T13:59:00+12:00
#+lastmod: 2008-07-18T13:59:00+12:00
#+categories[]: Tech
#+tags[]: Gmail
#+draft: False

It seems that the [[https://www.auckland.ac.nz][UoA]] has moved its student email services over to [[https://www.google.com/][Google's]] [[https://www.gmail.com/][gmail]] service.

This means that all the old address (UPI@ec.auckland.ac.nz) will move to the new domain aucklanduni.ac.nz. No doubt this has been done to ease the redirection of mail, but it does complicate searching from mail from the university; I used to just use =site:auckland.ac.nz= to get all UoA mail, but now that is broken.

Setting up Outlook to access gmail was relatively painless, except:

1. The instructions assumed a gmail addresses, e.g. UPI@googlemail.com, rather than UPI@aucklanduni.ac.nz, and
2. The SSL settings aren't fully specified in the instructions.

Aside from that, it was plain sailing. As an aside, I wonder how long it will be fore some spammer tries to send mail to upi@aucklanduni.ac.nz
