#+title: Scholarly works
#+slug: scholarly-works
#+date: 2004-03-26T22:49:00+12:00
#+lastmod: 2004-03-26T22:49:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301
#+draft: False

I received the following email:

#+BEGIN_QUOTE
Hi Peter,

I'm just writing to try and clarify a point about the first assignment due next Friday. We have been asked to make academic links between our groups' behaviour and the literature (scholarly, not textbooks). Does this mean all references must come from journals such as the course readings and other related ones and no text book references at all. Also, does /scholarly/ refer to peer reviewed articles only. If you could clarify these for me I would be very thankful.

Thanks heaps.

Dan
#+END_QUOTE

To which I replied:

#+BEGIN_QUOTE
Hi Dan,

Thanks for you email and your question it contains. I imagine others have the same question.

I don't remember if it was the first lecture, or the second one, but I do recall taking about depth of understanding and the need to read deeply. I'm always nervous of using examples; too often, in the past, I've given an example only to find that 40% of the class take up that issue, regardless of how fitting the example is to their situation.

With that 'disclaimer', let's look at an example:

The explanation of /group think/ in the stage I text book let's one know that the phenomena exists, but doesn't allow you to 'do' much with it--the text book isn't very helpful in a practical sense. The stage I text book (Organisational Behaviour), goes further and describes it better, but it is still somewhat superficial. So if you think your group, for example, is exhibiting 'group think' then perhaps it would be good to read Janis's original work to get the 'full story' (and maybe read a few articles that draw on Janis). Then, having that deeper understanding, you can more effectively explorer the extent to which your team is exhibiting Group Think.

Does that logic make sense?

It takes a judgement call as to what is scholarly--and part of any degree is reaching an understanding as to why something is scholarly. In general, peer reviewed articles are more scholarly than books. For the purposes, of this assignment you should consider textbooks as being books that have a primary role for teaching (as opposed to other books whose primary role is to report research, as opposed some books that provide a summary of the 'state of the art' (an example of this would be the Handbook of Organization Studies)). Text books are often a good place to start; they should point you to more scholarly works.

I hope all of this helps.

Regards

Peter

A rushed /Bibliography/ (You'd better double check these)

Janis, I. L., (1972). /Victims of Groupthink: Psychological study of foreign-policy decisions and fiascos/. Boston: Houghton Mifflin.

Janis, I. L. & Mann, L. (1977). /Decision making: A psychological analysis of conflict, choice, and commitment/. New York: Free-Press.

#+END_QUOTE
