#+title: Creaming it
#+slug: creaming-it
#+date: 2013-06-01T15:24:00+12:00
#+lastmod: 2013-06-01T15:24:00+12:00
#+categories[]: Home
#+tags[]: Shaving
#+draft: False

Meanwhile, back to the "petit plaisir' of the day (and every day), shaving.

A long time ago, I used to use Gillette shaving foam. Then I went to Gillette shaving gels. I had a long affair with Clinique's shaving gel. Very nice. $28 a pop, duty free. Then it was back to Gillette shaving gels.

But now I'm using a double-edge razor, I've used (and am using) a variety of shaving creams.

[[https://www.tayloroldbondst.co.uk/][Taylor's of Old Bond Street]]: Very nice. I certainly would use this again. Not much is needed for a really excellent lather.

[[https://www.edwinjagger.co.uk/][Edwin Jagger]] (Sandalwood): Good. Reminiscent of ToOBS

[[https://www.tedbaker.com][Ted Barker]]: Okay ... I like the dispenser, but the cream itself is just okay

L'Ocittane (Cade): One of my first creams. Solid, but I probably won't go back to it.

[[https://www.truefittandhill.co.uk][Truefitt & Hill]](Number 10): My faviourite so far. So little is needed, and the lather is so good. I'm keeping this for special occasions. I wish I could remember where I bought it from. Was it in the UK; I'm not sure. I'm keen to try some of their more expensive products.

[[https://www.proraso.it/][Proraso]] (original): Yet to be tried, but I like the eucalyptus and menthol smell.

I've not tried any shaving soaps. It seems like a lot of work to get a good lather together. Some folk report spending 10 minutes working up a lather. That's too much time for me. So, I'll be sticking with shaving creams for a while I think.
