#+title: Inclusive and accessible meetings
#+date: 2021-11-04T19:15:00+1300
#+lastmod: 2021-11-04T19:15:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

* Creating an inclusive environment

Inclusion of employees from different backgrounds and identities is extremely important for any organization looking to build a strong sense of connection in the workplace. Also, when team members feel included, they tend to want to do their best work. This is great for the organization, too. Creating an inclusive environment can be particularly challenging in meetings because they can be intimidating for participants. As a project manager, it is part of your job to facilitate meetings that are inclusive of all participants and that create a sense of emotional safety and value for everyone’s active input. In order to help facilitate inclusive meetings that feel empowering to everyone, you should put procedures in place that are consistently followed and predictable.

- Formalize initial check-ins for the group that build understanding and ensure everyone knows their input is needed. Create a process that consistently asks each person for an update on their work and/or how they are doing in their daily lives. Questions should be open-ended and vary over time to include some humor, analogies, and “finish the sentence” opportunities. As the project manager, your modeling will set the tone for the team dynamic, so always check-in with your team and model professionalism, vulnerability, and empathy. Popular check-ins include: “A highlight of my week has been . . .” and “This week I have gratitude for . . .”

- Give everyone your full attention. Listen carefully to what everyone has to say and be careful not to interrupt someone who is speaking. Body languagesuch as maintaining eye contact and turning your body in the direction of a speakercan help someone feel safe in voicing their opinion. Avoid head shaking, looking away, or looking at your phone when someone is speaking.

- Help all participants to be heard. Solicit ideas from participants, and ask questions to encourage participation. If someone gets interrupted, redirect everyone’s attention to that person and prompt them to finish their thought. If someone has not spoken yet, ask them what they think. It is important to note that, for some people, speaking up in meetings can be daunting. This can be especially true in virtual meetings or conference calls. This is also true for people who are not the majority in the room and may feel like they are representing an entire group of people who look, sound, or present like them. You may also find that people who are entry-level may be nervous about speaking up too since they are just beginning their careers. You can help people feel more comfortable and supported by letting them know ahead of time that they will be asked to share during a meeting so that they can prepare in advance. You can also solicit input after a meeting from anyone who did not speak.

- Help participants feel comfortable sharing different perspectives. Encourage differing or opposing ideas by making clear that alternate viewpoints are valued. To set the tone for this, start the meeting by encouraging competing perspectives. Try to get at least three points of view on an issue that might have some variation in the room. Follow up after the meeting with a request for additional thoughts.

- Use images that reflect the diversity of the world. In your presentation materials and handouts, select images that illustrate diversity in race, gender, age, ability, cultural background, religion, geographical location, and so on. The people in your images should represent diverse backgrounds to further support inclusion, allowing everyone in the room to feel welcome and represented.

* Making meetings accessible to everyone

Meetings can’t be inclusive if not everyone can fully participate. It is important to make sure that your meetings are accessible to everyone. Accessible means that something is easily used, accessed, or adapted for use by people experiencing disabilities. In meetings, this means that people experiencing disabilities are not excluded from participating or understanding the information shared.

When planning your meetings, you should consider the needs of people experiencing the following types of disabilities:

- Visual impairments and blindness
- Hearing loss and deafness
- Mobility disabilities, which means having difficulty getting around, such as people who require wheelchairs or canes

These tips can help you ensure that the following participants have full access to your meetings:
People with visual impairments
Presentation materials

- Use a large font size (minimum 22 points).
- Use high-contrast colors.
- Provide alternative text descriptions for all images, pictures, graphics, tables, and so on.
- Provide low-vision or blind attendees with an accessible electronic format of the presentation.
- Provide presentation materials in an accessible electronic format to participants ahead of time.
- Describe all meaningful graphics in your presentation (such as photos, images, charts, and illustrations).

Handouts and printed materials

- Use a large font size (minimum 18 points).
- Use black lettering on white, matte paper.
- Use a simple font and avoid compressed fonts and italics.
- Use 1.25 to double spacing between lines.

** People with hearing impairments

- Always face the person you are communicating with. This is especially helpful for audience members who are speech readers.
- Speak clearly, at a moderate pace and volume, and allow the other person time to respond. Avoid exaggerating, slowing your speech, or speaking loudly.
- Ask for clarification if you don’t understand something the person is communicating.
- Include all of the information presented in a spoken presentation on slides.
- Add closed captions or subtitles to videos. YouTube Help provides instructions for adding your own closed captions to your videos.

** People with mobility impairments

- Provide ample circulation space in your meeting room so that people using mobility devices can easily pass through.
- Offer accessible seating locations throughout the room.
- For presentations, use half-round seating so that all participants may face in the direction of the speaker.


* Backlinks
- [[{{< ref "202111041851-project-communication" >}}][Project communication]]
