#+title: The Ugly
#+slug: the-ugly
#+date: 2004-04-08T13:05:00+12:00
#+lastmod: 2004-04-08T13:05:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301 Plagiarism
#+draft: False

I subscribe to the the [[https://www.jiscmail.ac.uk/lists/PLAGIARIS.html][JIS Plagiarism mailing list]] and a couple of interesting articles can be found there.

In the first [[https://www.ejel.org][The Journal of E-Learning]] has an article called [[https://www.ejel.org/volume-2/vol2-issue1/issue1-art25.htm][Plagiarism and Poor Academic Practice? A Threat to the Extension of e-Learning in Higher Education]] which provides some interesting facts on the size of the problem.

According to the article, in the UK:

#+BEGIN_QUOTE

... Franklyn-Stokes and Newstead (1995) and Newstead et.al. (1996) have attempted to ascertain the frequencies of a range of non-academic practices. Students were asked to report whether they had engaged in a range of behaviour at least once in the previous academic year.

#+END_QUOTE

And their table looked like this (allowing for translation between mediums) table.

| Behaviour                                                        | Percentage |
|                                                                  |  reporting |
|                                                                  |  behaviour |
|------------------------------------------------------------------+------------|
| Paraphrasing material from another source without acknowledging  |            |
| the author                                                       |         54 |
| Inventing data                                                   |         48 |
| Allowing coursework to be copied by another student              |         46 |
| Copying material for coursework from a book or other publication |            |
| without acknowledging the source                                 |         42 |
| Copying another student's coursework with their knowledge        |         36 |
| Doing another student?s coursework for them                      |         16 |
| Copying from a neighbour during an exam without them realising   |         13 |

Anyway it makes interesting reading. Another thing that is interesting to read is the [[https://tass-plagiarism.blogspot.com/][The Plagiarism Blog]]. For example, one of the [[https://www.canada.com/calgary/calgaryherald/news/story.html?id49ee48c-7aae-4551-9cc9-7ad274743c4c][stories]] on the Blog talks about a Canadian university that has given up using take home essays as a form of assessment as an means to counter, what they see, as increased plagiarism.

I watch with curiosity what will happen.
