baseURL = "https://petersmith.org/"
languageCode = "en-us"
title = "PeterSmith.org"
theme = "NewPapyrus"

relativeURLS = false
canonifyURLs = false

[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepQuotes = true

[frontmatter]
  lastmod = ['lastmod', ':fileModTime', ':default']

[taxonomies]
  category = 'categories'
  tag = 'tags'


[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"
    notes = "/notes/:year/:month/:day/:slug/"
    resources = "/resources/:slug/"
    mention = "/mentions/:year/:month:/:day/:slug/"


[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[languages]
[languages.en]
    contentDir = "content"
    languageName = "English"
    languageCode = "en"

[Privacy]

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Peter Smith"
    photo = "images/PeterInTheOffice-2020-small.jpg"
    profile = "https://google.com/+XXX"
    email = "mail@petersmith.org"
    nick = "Peter"
    licence = "CC BY-NC-SA"
    licenceURL = "https://creativecommons.org/licenses/by-nc-sa/4.0/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 4



[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 5

[[menu.main]]
  name = "Mentions"
  url = "/mentions"
  weight = 10

[[menu.main]]
  name = "Resources"
  url = "/resources/"
  weight = 15

[[menu.main]]
  name = "Site info"
  url = "/site-info/"
  weight = 99



[[menu.indieweb]]
  name = "Orid"
  url = "https://orcid.org/0000-0002-6382-7051"
  post = "<i class='fab fa-orcid'></i>"
  weight = 5
[[menu.indieweb]]
  name = "SSRN"
  url = "https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=657683"
  post = "<img src='/images/ssrn.svg' alt='SSRN logo' style='display:inline-block; height:1.5em; top:0.2em; position:relative;' class='fab'>"
  weight = 10
[[menu.indieweb]]
[[menu.indieweb]]
  name = "Github"
  url = "https://github.com/psmith1303"
  post = "<i class='fab fa-github'></i>"
  weight = 90




[[menu.badges]]
  name = "html5"
  url = "http://validator.w3.org/check/referer"
  post = "/images/w3c-valid-html.png"
  weight = 5
[[menu.badges]]
  name = "html7"
  url = "http://validator.w3.org/check/referer"
  post = "/images/w3c-valid-html.png"
  weight = 10

[Params]
  subtitle = "Some kind of bucket for bits and bytes"
  description = "Peter's IndieWeb hub"

[[Params.plugins.css]]
link = "/css/normalize.css"
[[Params.plugins.css]]
link = "/css/stylesheet.css"
[[Params.plugins.css]]
link = "/css/fontawesome.css"
[[Params.plugins.css]]
link = "/css/webmention.css"
