baseURL = 'https://petersmith.org/'
languageCode = 'en-us'
title = 'PeterSmith.org'
theme = 'NewPapyrus'

relativeURLS = true

footnoteReturnLinkContents = '↩'



[frontmatter]
  lastmod = ['lastmod', ':fileModTime', ':default']

[taxonomies]
  category = 'categories'
  tag = 'tags'


[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
  journal = "/journal/:year/:month/:day/:slug/"
  teaching = "/teaching/:year/:month/:slug/"
  notes = "/notes/:year/:month/:slug/"
  run = "/running/:year/:month/:day/:slug:"
  resources = "/resources/:slug/"


[sitemap]
        changefreq = "monthly"
        priority = 0.5
        filename = "sitemap.xml"

[languages]
[languages.en]
    contentDir = "content"
    languageName = "English"
    languageCode = "en"

[Privacy]

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Peter Smith"
    photo = "images/PeterInTheOffice-2020-small.jpg"
    profile = "https://google.com/+XXX"
    email = "mail@petersmith.org"
    nick = "Peter"
    licence = "CC BY-NC-SA"
    licenceURL = "https://creativecommons.org/licenses/by-nc-sa/4.0/"




[[menu.main]]
  name = "Journal"
  url = "/journal"
  weight = 5

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 10

[[menu.main]]
  name = "Resources"
  url = "/resources/"
  weight = 15

[[menu.main]]
  name = "Site info"
  url = "/site-info/"
  weight = 99



[[menu.indieweb]]
  name = "Orid"
  url = "https://orcid.org/0000-0002-6382-7051"
  post = "<i class='fab fa-orcid'></i>"
  weight = 5
[[menu.indieweb]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/peter-smith-00b7891b5"
  post = "<i class='fab fa-linkedin'></i>"
  weight = 10
[[menu.indieweb]]
  name = "Twitter"
  url = "https://twitter.com/JustAnotherCog"
  post = "<i class='fab fa-twitter'></i>"
  weight = 15
[[menu.indieweb]]
  name = "Github"
  url = "https://github.com/psmith1303"
  post = "<i class='fab fa-github'></i>"
  weight = 20



[[menu.badges]]
  name = "html5"
  url = "http://validator.w3.org/check/referer"
  post = "/images/w3c-valid-html.png"
  weight = 5
[[menu.badges]]
  name = "html7"
  url = "http://validator.w3.org/check/referer"
  post = "/images/w3c-valid-html.png"
  weight = 10
