#+title: Replacing running shoes
#+slug: replacing-running-shoes
#+date: 2010-12-30T15:48:00+12:00
#+lastmod: 2010-12-30T15:48:00+12:00
#+categories[]: Home
#+tags[]: Fitness Running Shoes
#+draft: False

[[https://runkeeper.com/user/justplodit][JustPlodIt]], over at [[https://runkeeper.com/][RunKeeper]] asked about [[https://runkeeper.com/user/justplodit/activity/21714311][replacing shoes]]. He said:

#+BEGIN_QUOTE

I read somewhere you should change your shoes every few months (depending on your mileage), to protect your joints. I guess I've done 750k in the current pair. Do I need to change? Any shoes you recommend?

#+END_QUOTE

I don't know about every few months, but (depending on the brand) I hear that retiring them after about 350 to 550 miles (550Km--880Km) is a good thing. How quickly they wear is also a function of your weight. When I was 105Kg I would have worn out shoes quicker than now (78Kg). Most people start a new pair at about half-life (say, at 400Km), and use both until the old pair is dead---at which stage they should be half-way through the life of the new pair---and so they'll get new shoes then. That way you always have a newer and older pair to run on (that's one way to tell if the shoes are shot---the older pair will feel different to the newer pair). If you take your shoes into any good shop they'll tell you if they are end of life.

I'm currently working my way through a couple of New Balance shoes (1063, 1064), but the actual model of course depends on how much support, /etc./ you need. I'm a "neutral' runner, but I get myself test at Shoe Science (or similar) each time I'm thinking of changing shoes. [[https://www.andrewisgettingfit.com/][Andrew]] has three of four different brands he uses (as he tries to find the"perfect' pair). I'm just using something that suits my feet and doesn't cause any problems. (Then again, Andrew is planning to do an ultra-marathon in March ... that's about 70k too far for me.) Nevertheless, I do thing it's possible to become fetishised over finding the "right' or"best' shoe.

I'm a "masters runner' (over 40 to say the least) and most of the twitches/aches/pains are down to non-shoe issues ... I've had ITB problems, but a bit of physio and exercise to build up the related muscles fixed that. I've had a stress fracture, again that's not the shoes, that's me putting too much stress (training too much) on my body. I've also had an Achilles' problem ... once again physio and some strengthening exercises put that right (after a month or so ... Achilles can be real problems).

Mind you, if I was running in the "wrong shoe" I'm sure it would create problems.

One thing I have found, is that sometimes, what I think is a knee problem is caused by running on a pavement with too much of camber for too long. If that happens, I switch sides of the road; that often fixes it.

Anyway, the short answer to your question is it's likely it's time to change your shoes, although they may not be end of life yet.
