#+title: Project budgets - maintaining
#+date: 2021-10-10T09:49:00+1300
#+lastmod: 2021-10-10T09:49:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

This how you manage your budget.

Monitoring the budget is crucial for a project management to enforce accountability in terms of spending.

Milestones are a great point in a project to re-review the budget, to identify if anything needs to be reset or revisited throughout the project.

* Contract types
** Fixed contracts
Normally paid when milestones are achieved
** Time and materials contracts
Paid monthly based on the hours worked and other fees associated with the work, such as travel and meal

* Cost control
A practice where a project manager identifies factors that might have an impact on their budget and then creates effective actions to minimize variances.


- In order to control costs, you should establish a sign-off plan and inform the appropriate stakeholders of any changes that occur.
- Make changes as they occur
- Tracking everything
- Accept budget misses will happen
- Adequately account for, adapt, and manage your budget with that risk in mind

* Overcoming budgeting challenges

Let's discuss some of the most common budgeting challenges you may encounter as a project manager and how to manage them.

** Challenge 1: Budget pre-allocation

You may encounter situations where your budget is already set before you even start the project. This is known as budget pre-allocation. Some organizations follow strict budgeting cycles, which can lead to cost estimations taking place before the scope of the project is completely defined.

If you are given a pre-allocated budget, it is important to work with your customer to set expectations on scope and deliverables within the allocated budget. To deliver a great product within your allocated budget will require detailed planning.

A pre-allocated budget should also be routinely monitored to ensure the amounts you have budgeted are sufficient to meet your costs. Be sure to carefully track all expenses in your budget. Regularly match these expenses against your pre-allocated budget to ensure you have sufficient funds for the remainder of your project.

Part of that planning includes making sure that you are tracking fixed and time- and materials-based expenses. Fixed contracts are usually paid for when certain milestones are reached. Time and materials contracts are usually paid for monthly, based on the hours worked and other fees associated with the work, such as travel and meal expenses.

** Challenge 2: Inaccurately calculating TCO
:PROPERTIES:
:ID:       d83152fc-f381-45c3-bdcc-06987ffcd3f9
:END:

Another budgeting pitfall you should try to avoid is underestimating the total cost of ownership (TCO) for project resources. TCO takes into account multiple elements that contribute to the cost of an item. It factors in the expenses associated with a product or service over its lifetime, rather than just upfront costs.

Let’s relate TCO to something more common, like owning a vehicle. Let’s say you buy a vehicle for a certain price, but then you also pay for things related to the vehicle, such as license fees, registration fees, and maintenance. If you add all of this up, you have your TCO for that vehicle. So now that you know what your TCO is, you may consider those fees before you buy your next vehicle. For example, you might opt for a vehicle with fewer maintenance requirements than one that requires more frequent service, since you know that will save you money overall.

The same concept applies to budgeting on a project. If you have a service requirement for a software technology that your team is using, for example, then it is important to budget for the costs of maintenance for that service. Additional types of costs you may need to account for when calculating TCO include warranties, supplies, required add-on costs, and upgrade costs.

** Challenge 3: Scope creep

Scope creep is when changes, growth, and other factors affect the project’s scope at any point after the project begins. Scope creep causes additional work that wasn’t planned for, so scope creep can also impact your budget.

There are several factors that can lead to scope creep, such as:

- A vague Statement of Work (SoW)
- Conversations and agreements about the project that aren’t officially documented
- Unattainable timeframes and deadlines
- Last-minute asks from priority stakeholders

Addressing these factors as you plan your project can help prevent scope creep from impacting your budget.

* Backlinks
- [[{{< ref "202110091614-project-budgets" >}}][Project budgets]]
