#+title: Planning for next year
#+slug: planning-for-next-year
#+date: 2004-11-09T20:32:00+12:00
#+lastmod: 2004-11-09T20:32:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT101
#+draft: False

I think the students sit their final examination tomorrow. And so Friday and Monday will be taken up with exam marking. The team will be 'locked up' and not allowed out until it is finished.

But we have already begun planning for next year. I'll be teaching this course at summer school. Since summer school only lasts six weeks, we pack in twice the number of lectures into each week.

Anyway, there are some changes in the pipeline. Perhaps the biggest is the shift to a new text book by Samson & Daft called /Management/. It will be replacing /Management: A New Zealand perspective/ by Inkson & Kolb. The old book has served us well, but a new edition isn't available yet. So, it is onto Samson & Daft.

This means we need to re-work the lectures (and the tutorials) so they match the emphasis (and the structure) of the book. After all, trying to do things in a different sequence to the book can often be confusing because the book has its own internal logic.

I'm spending tonight working out some sample assignments for the course. Because of the tight time-frame, assignments need to be well crafted so that they can be turned-around quickly enough--the students do need to get their feedback before each assignment.

Anyway, enough chat. I have questions to-write.
