#+title: Patterns in the sand
#+slug: patterns-in-the-sand
#+date: 2004-11-05T16:13:00+12:00
#+lastmod: 2004-11-05T16:13:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301
#+draft: False

Most of the marking of the Case and Annotated Bibliographies are done. We, DPE, will meet next week to review the marks before releasing them. Unsurprisingly some are very good, and some are not. What is surprising is the patterns that we've seen occurring in the cases and bibliographies.

Firstly, the members of each team seem to write about the same thing. E.g. Zoom and takeovers.

Secondly, the pattern of the case and the bibliography amongst the poorer cases often the same. The case goes along the lines of "We didn't do [planning], and so we had problems". The bibliography then often the consists of article saying "[Planning] is good" and the link that gets made is "We should have done more [planning]". You can substitute what you like instead of planning, be it leadership, sensemaking, strategy, etc. My question tends to be, where is the insight that the article generates about the case?

Finally, the issue that gets chosen is often very broad, i.e. "Things did not work out for company X, I wonder what they could have done differently". This results in bibliographies that are they general (covering everything from strategy to leadership, etc). There is a variation on this where the case that is just a history of the company with a rather general issue bolted on the end. The better cases ended with a very specific question "i.e. Should company X try to takeover company Y", the bibliography is then focused on the pros and cons of takeovers ... which is much more interesting.
