#+title: Scum - Roles
#+date: 2021-09-29T19:03:00+1300
#+lastmod: 2021-09-29T19:03:00+1300
#+categories[]: Zettels
#+tags[]:  Coursera Project_management Scrum Roles

* Roles

** Product owner
The Product Owner is responsible for maximizing the value of the product and the work of the team. The Product Owner owns the inventory of work and has the final say on how to prioritize the work.

The product owner is responsible for what the team builds.

"To build the right thing" (Value - cost)

** Scrum master
This role is responsible for ensuring that the team lives Agile values and principles, follows the processes and practices that the team agreed to, sharing information to the larger project team, and they also help the team focus on doing their best work.

"To build things fast" (Speed)

** The development team
The Development Team is responsible for how a team will deliver that product.

"To build the thing right" (Quality)

* Team characteristics
- Cross-functional
- Self-organizing

* Backlinks
- [[{{< ref "202109131858-scrum" >}}][Scrum]]

