#+title: The planning fallacy
#+date: 2021-10-06T19:50:00+1300
#+lastmod: 2021-10-06T19:50:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

The idea of the planning fallacy was first introduced in a 1977 paper written by Daniel Kahneman and Amos Tversky, two foundational figures in the field of behavioral economics. The planning fallacy describes our tendency to underestimate the amount of time it will take to complete a task, as well as the costs and risks associated with that task, due to optimism bias. Optimism bias is when a person believes that they are less likely to experience a negative event. For example, when you are planning to walk your dog in between meetings, you might think that you can do it faster than you actually can. Optimism bias is what tells you that you are going to be able to walk your dog without being late for your next meeting. If you don’t consider things that might affect the time it will take you to walk your dogthe weather, the chance of them running into another dog and wanting to play, or the fact that they frequently get distracted while sniffing aroundyou might be late for your next meeting, or you might miss it altogether!

The planning fallacy can happen to anyone, regardless of whether or not they have experience completing similar tasks. Whether this is your first time walking your dog or your hundredth, you still have to consider the different factors that can affect how long it will take you to complete the walk. This same principle applies in project management. You may be brand new to this kind of project or you may have managed tons of similar projects before; either way, you still need to be careful not to underestimate the time it will take to complete each task on this particular project. As a project manager, you should aim to balance being aware of the planning fallacy with keeping an optimistic attitude about the project, even as things change. Be optimistically realistic: Push for the best outcomes while planning for the proper time it may take to accomplish each task.

* Backlinks
- [[{{< ref "202110061926-project-time-estimation" >}}][Project time estimation]]
- [[{{< ref "202110040711-project-plans" >}}][Project plans]]
