#+title: Professional Doctorates
#+slug: professional-doctorates
#+date: 2004-12-08T19:54:00+12:00
#+lastmod: 2004-12-08T19:54:00+12:00
#+categories[]: Teaching
#+tags[]: PhD DBA
#+draft: False

One of the workshops I attended whilst at [[https://www.anzam.uts.edu.au/][ANZAM]] was entitled /Best practices framework in doctoral education/. It was 'hosted' by Ronel Erwee from the [[https://www.usq.edu.au/][University of Southern Queensland]]. In principle, the workshop was about the requirements that Australian universities have to meet for their professional (taught?) doctorate programs, namely for DBs. Being in charge of the USQ program since '97, Ronel has been active in this area for awhile and has written on it [[https://www.usq.edu.au/resources/erwee2004vol1.pdf][too]].

Most of the participants are actively involved in DBA programs (mainly in Australia), but main of these programs are offered (very profitably) as distance education in Asia. In this regard, of particular interest was [[https://www.adelaide.edu.au/][Aldelaide's]] [[https://web.archive.org/web/20041210040725/https://business.unisa.edu.au/igsm/dba/default.asp][program]] which has 50 local students and about 450 overseas! In addition, Clive Smallman, who has a lot of experience in the UK and Europe, is looking at what [[https://www.lincoln.ac.nz/][Lincoln]] might do.

Most of the programs are three years long. The first year comprising of a number of 'papers', and the remaining two years being spent of a dissertation. The Australian best practice requirements are that two-thirds of the degree consists of research. Entry requirements are an MBA, or other masters' degree (or a really good Bachelors degree). Full time students are expected to complete in three years (or maybe a little longer), and part-time students are limited to five years.

Typically, the papers (i.e., four of them) cover topics such are The Philosophy of Research, Quantitative Methods, Qualitative Methods, and Literature reviews. On completion of the papers there is a formal award such as a Diploma in Research Methods. This is often used as a tool to get people out of the program who are unlikely to complete the DBA. Having completed the papers, the student should have a well defined research question and a completed literature review.

Unlike the PhD, the topic of DBA research is often an applied industry problem, and consequently the research leads to the student's own network and mana being enhanced. Consequently, the DBA topic is often smaller in scale and scope when compared to a PhD. However, that isn't to say it is any less work--it just means it is more applied (and less theoretical).

One feature of the applied nature of the DBA is the issue of intellectual property.

A DBA is often results in the generation of valuable IP, but because of the nature of the DBA (often being embedded in the students host organisation or industry) ownership of the IP is often unclear. Thus for many institutions the I issue is dealt with up-front with the ethics process. In this way everyone knows who will own which parts of the IP.

On the downside, there is some concern regarding the difficulty in publishing DBA research. It is not well loved by journals because of its heavily applied nature. Having said that, for many jobs (see the Economist), a PhD and a DBA can be treated as equivalent (but perhaps not for University positions).
