#+title: Research as a second language
#+slug: research-as-a-second-language
#+date: 2009-12-13T07:10:00+12:00
#+lastmod: 2009-12-13T07:10:00+12:00
#+categories[]: Research
#+tags[]: Writing
#+draft: False

One blog I always find myself going back to is by [[https://www.cbs.dk/staff/basboll/%28language%29/dan-DK][Thomas Basbøll]], who is the Resident Writing Consultant at [[https://www.cbs.dk/cbs_international][Copenhagen Business School]]. He calls his blog [[https://secondlanguage.blogspot.com/][Research as a second language]].

I was prompted to mention it now as I was reading his article [[https://secondlanguage.blogspot.com/2009/12/free-time-blank-pages-and-other.html][Free Time, Blank Pages, and other Catastrophes]].

As I hurtle/stumble towards the end of my thesis, I find myself wondering about the practices associated with "doing" a PhD. Here, at the [[https://www.business.auckland.ac.nz/][University of Auckland Business]], or at least in [[https://www.business.auckland.ac.nz/Schoolhome/ManagementInternationalBusiness/tabid/867/Default.aspx][this part of the Business School]], a thesis seems to be a largely individual exercise. And yet it doesn't have to be that way. A colleague has some theses from a renowned Swedish institution. The detailed structure of each PhD thesis is very similar to each other ... down to the number of paragraphs per section.

Clearly there has to be a greater level of congruence between practices there than, say, where Saku Mantere did his [[https://lib.tkk.fi/Diss/2003/isbn9512263297/][thesis]] (which exhibits some lovely ideosyncracies).
