#+title: Synchronous teaching
#+subtitle: Is it really better
#+date: 2020-09-09
#+categories[]: teaching, online

* Synchronous versus asynchronous learning events

It seems like I have been saying it for a long time now, but my sense is that there are very few times (relatively speaking) when some form of synchronous teaching activity is better than an asynchronous teaching activity. And, within that small pool of synchronous activity there is an even smaller subset of activities that are best done face-to-face or  [[{{< ref "20200824-face-to-face-teaching.org"  >}}][in-person teaching]]. 

I need to say, that I have little evidence to back that assertion up, so I was interested to see this piece entitled [[http://stevendkrause.com/2020/09/07/synch-video-is-bad-perhaps-a-new-research-project/][“Synch Video is Bad,” perhaps a new research project?]] that notes that:

#+BEGIN_QUOTE
After teaching online since about 2005, after doing a lot of research on best practices for online teaching, after doing a lot of writing and research about MOOCs, I’ve learned at least two things about teaching online:

 - Asynchronous instruction works better than synchronous instruction because of the affordances (and limitations) of the medium.

-  Video---particularly videos of professors just lecturing into a webcam while students (supposedly) sit and pay attention---is not very effective.
#+END_QUOTE

The question that then emerges is, why---given what we know---have "many (most?) of my colleagues have decided on their own to teach their classes with Zoom and synchronously". An experience which seems to have been true here too.

I suspect that whilst it is true that asynchronous instruction generally works better than synchronous approaches, the practicalities of quickly "getting online" say many people taking what was the easiest route. Note, I don't think anyone would say it was an easy route; it was just easier than the alternatives  (and probably substantially so).

* Single-step learning

What worries me is that, having taken this path, many people make take away the lesson that synchronous (sometimes called Zoom lectures) are the way to go when it comes to online teaching; after all it has worked has hasn't it? Hasn't it; maybe not the way our students would have wanted. Yes, like us they have been tolerate of the situation and (often) appreciative of what we have tried to do in these circumstances, but going forward I think we need to get better both at the ongoing 'emergency response' to online teaching and in what we think good online teaching and learning looks like.


