#+title: A wake up call
#+date: 2004-05-08T14:24:00+12:00
#+lastmod: 2004-05-08T14:24:00+12:00
#+categories[]: Home
#+tags[]: Fitness
#+slug: a-wake-up-call
#+draft: False

I've been away from school most of this week. It has been an exhausting week, to say the least. I've been feeling under the weather for the past month or so, and I seemed to be getting worse rather than better. So, on Monday, after my first class, I paid a visit to the doctor. Fairly quickly, he'd organised an ambulance to take me to hospital---I tried to protest that I could take a taxi, but he wouldn't consider that option. So, I spent all of Monday, Tuesday, and some of Wednesday hooked up to an ECG because they thought I might be having an angina attack, or worse still I might have had a heart attack. After two days in the "High Dependency Unit' and what seems like endless tests, they came to the conclusion that the problem was my"rampantly high' blood pressure.

I've always had slightly high blood pressure, but it's never needed treating. I think the expression used was ?top of the normal range?. Anyway, it isn't like that any more. More like ?top of the top range?. Having spent to and a bit days with nothing to do but watch my heart monitor I now know what happens. My blood pressure starts to go up, I begin to get a cracking headache (I've had those for a long time, at least now we know why). The pressure keeps on going up, I start to get pains in my chest. It keeps going up, and my left arm begins to go numb (that's why the doctor rushed me in to hospital). Alas, I've not been given any clear reason for what triggers the episode---but sometimes, that's just the way it is.

Just to make sure that the heart hasn't been damage I've had an ordinary treadmill test which was inconclusive. A [[https://www.aucklandradiology.co.nz/services/attachments/aug_2003.pdf][scintigram]] (strangely enough, it was done by a private company down in Penrose). Basically, they inject you with an isotope and measure its uptake around the heart (the scan takes 15 minutes). Later that same day the do a [[https://www.med.miami.edu/med/cardiology/non-invasive.asp#1][Bruce protocol treadmill test]]. Of course it isn't quite as straight forward as an ordinary treadmill test. No. For the scintigram, when you just about reach exhaustion, they inject more isotopes and make you go on for another minute. Even with the 10 minutes to relax, and the 15 minute scan afterwards, I was very "worn'. Alas, the results haven't arrived with the doctor yet, so he is sending me for a 'stress echo'. Another treadmill exercise, but they'll do a ultrasound of the heart.

Anyway, it's all been a bit of a wake up call. Not as bad as Erling's but a wake up call nevertheless. So, I've got to make some changes. Firstly, lifestyle. No more 60--80 hour weeks. I've got to get back to 40 hours;that will help with my stress levels somewhat. Exercise: an hour a day, says the doctor. A low sodium diet (and low fat). Weight loss: An immediate target of 95Kg, a goal of 80Kg over the next couple of years. And, of course medication. It seems I have no option on this. Some of it will be for the rest of my life, some might just be while we are getting things settled down (i.e. The next few years). Well, I've started doing all this, and at the moment I feel awful. But, its like that when you start with strong medicine. But, I should pick up over the next few weeks. At least the chest pains and the headaches have abated.
