#+date: 2016-05-23T14:18:30+13:00
#+slug: write-that-article
#+lastmod: 2016-05-23T14:18:30+13:00
#+title: Write that article
#+categories[]: Research
#+tags[]: Productivity Writing
#+draft: False

I these notes are based on the presentation [[https://www.slideshare.net/ingermewburn/write-that-journal-article-in-7-days-12742195][Write that article in 7 days]] by Dr Inger Meburn and Dr Judy Maxwell.

First, if you have data, artefacts or ideas, prelim analysis or thoughts then it is possible to churn out an article quickly.

Where will I publish? The journals are the top of the list are definitely my natural home. Those at the bottom are less of a fit--but could still be important.

- Journal of Management Studies
- Organization Studies
- Scandinavian Journal of Management
- Strategic Organization
- Academy of Management Learning & Education
- Management Learning
- Human Relations
- Academy of Management Journal
- British Journal of Management
- Strategic Management Journal

#+BEGIN_QUOTE

Rugg and Petre (2004) claim that journal articles can be understood as falling into genres: * Data driven * Methods papers * Agenda setting / Consciousness raising papers * Review papers * Theory papers

#+END_QUOTE

Generally, we most familiar with the data driven paper and its structure.

- What is the method
- How does the method work
- What is the method good for -- both in terms of utility and how it is
  different
- Any constraints

#+BEGIN_QUOTE

Are usually written every ten years or so--when someone ... "bothers to read everything in a filed" and again summarises it and provides evaluative judgement.

#+END_QUOTE

Write an abstract, paying attention to the verbs (what will the paper do?). Then add a title. For me, the start of the forty-paragraph framework will work well.

Just write .. .ideally from notes (avoids accidental plagiarism).

In the mornings, try 25 minute sprints with 10 minute breaks. In the afternoons do something else. In the evenings, outline, edit, and rearrange the text.

Do a more structured outline based on what works for you; e.g., Lists, mind maps, etc.

#+BEGIN_QUOTE

Look at the strengths and weaknesses of your work so far. Ask yourself:
- Do I have enough literature?
- Am I making 'knowledge claims' or just reporting?
- Is this an argument---or a manifesto?
- Is my data sufficient to the claims I am making?
- Am I being sufficiently speculative?

#+END_QUOTE

But remember, too much tinkering is just avoiding the problem. Move on!

#+BEGIN_QUOTE

Steven King once said: "... kill your darlings, kill your darlings, even when it breaks your egocentric little scribbler's heart, kill your darlings."

#+END_QUOTE

And then let it rest.

I do no think this process will take seven days, but it will certainly
take way less than my normal prating around takes :)
