#+title: Kickoff videos
#+slug: kickoff-videos
#+date: 2015-04-30T07:22:00+12:00
#+lastmod: 2015-04-30T07:22:00+12:00
#+categories[]: Teaching
#+tags[]: BUSINESS304
#+draft: False

Ahead of teaching BUSINESS 304 (Strategic Management), I thought I would produce a short introductory video about the course. The idea was to give the students a sense of the topics and of how I teach before the actual start of classes.

When I mentioned the idea to Susan Geertshuis (Professor of Lifelong Learning and Director of Learning and Teaching), she pointed me toward a series of highly successful videos produced at Macquarie University (link), and offered to provide some help from the Innovative Learning Team.

So, with a great deal of input from Lyn Collie, this video was produced:

{{< youtube r8c-y6Q9sCE >}}

So what did the students get out of it? So what did the students get out of it?

A week before the start of semester, I emailed the video to each student enrolled in BUSINESS 304.

Then, a few weeks after the course had started, I sought feedback from the students about what they thought. The first thing they suggested was that /all classes should have a similar video/. This was because the video orientated them to the long-term benefits of the course (beyond the exam and the assignments). It helped them understand how the course could be useful in business.

The video also helped the students to understand what to expect from the course; especially given it is a case-based course, so it's different to most of the other courses they have had.

Finally, students commented on the high production value (their words, not mine), although a few did notice that some of the classroom scenes came from INTBUS 202 (because they were there during the original shoot!).

So what did I get out of it?

First, I learned about the importance of time. The video is under 2 1/2 minutes long, and yet I spent more than 8 hours in front of the camera. I have the impression that Lyn spent more than twice that editing it. You cannot rush doing one of these videos.

To be clear, that time was not spent doing a 10-minute video and cutting it down. No. Lyn gave me clear guidance as to the number of words required for the duration we wanted, so the original script was about 400 words (and could have been shorter ... actually the first couple of versions were a bit longer). Script editing was mainly to get things into my 'speaking' voice rather than my 'writing voice'. What works great on paper (and great for a reader) is quite different to what works well when it is spoken. For the next course I am doing, my first version of the script will be no longer than 300 words ... and that is still about 2 words per second. That's a lot! Perhaps I only need 200 words. Lyn has taught me that less is better.

The second challenge is being able to smile and talk. I can do it in class easily enough. But in front of the camera I turn into a grumpy looking so-and-so. It was only Lyn's professional support that enabled me to come across as well as I did. It's not easy and I'll be doing a lot of practice before the next video.

Finally, I would say it is really important to work with a good director. Lyn encouraged, cajoled, and sometimes bullied me into getting it right. She was--in my humble opinion--an outstanding director. Despite the work required, I'm really looking forward to working with her on my next 2 minute video, this time for MGMT 300.
