#+title: Scrum - roles - Scrum master
#+date: 2021-09-29T19:12:00+1300
#+lastmod: 2021-09-29T19:12:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management Roles Scrum Scrum_master

The Scrum Master promotes and supports the Scrum process by helping everyone understand and implement Scrum. This includes its:

- practices,
- rules, and
- values.

The  Scrum Master is responsible for helping the team be their very best. They can achieve this by coaching individuals on the team to manage external forces, as well as maximizing the team's internal potential.

* Responsibilities
- Coaching team members on the Agile and Scrum practices, rules, and values
- Helping to find ways to manage the [[{{< ref "202109131858-scrum" >}}][Product Backlog effectively]].
- Facilitating Scrum events
- Help the team remove blockers
- Prevents unhelpful interactions from outside of the team

* Traits
- Organizational skills
- Supportive leaders
- Facilitative productivity and collaboration
- Coach team members
- Communication

* Comparison to a traditional PM
Are different to the traditional PM, but can be done a traditional PM

A Scrum Master is responsible for helping the team understand Scrum theory and practice. They ensure Scrum events take place and help the team focus on delivering value by removing impediments. But unlike a traditional project manager, they do not take on the management of changes in scope or priorities. Additionally, Scrum Masters do not maintain traditional project artifacts like GANTT charts.


* Backlinks
- [[{{< ref "202109291903-scum-roles" >}}][Scum - Roles]]
- [[{{< ref "202109131858-scrum" >}}][Scrum]]

