#+title: Born free
#+slug: born-free
#+date: 2005-06-16T22:10:00+12:00
#+lastmod: 2005-06-16T22:10:00+12:00
#+categories[]: Home
#+tags[]: Hedgehog
#+draft: False

Today we moved Hedgey down into the garden. I've modified his box so he can get out (and get back) if he wants to.

Hedgey, is the hedgehog we've been looking after for the past couple of months. I found him one lunchtime when I was out walking. Hedgehogs shouldn't be out during the day, so I knew he wasn't well. He was pretty mangey, and he stunk to high heaven.

So, I picked him up and carried on walking to our local vets, Animalz. Once there I said, if he can be saved I'm happy to pay for the treatment and to look after him, if not then please put him out of his misery. They told me they would have a look and give me a call back. The SPCA put me on to a wonderful women called Donette (I hope that's how to spell her name). She looks after lots of ill hedgehogs. She gave me a lot of good advice and was always available on the phone. Thanks Donnet.

Any way to cut a long story short, he needed some Ivomec injections (to kill the mites); I had to oil and clean all the dead and mangey skin off him; give him antibiotics (because the mange-crust was breaking his skin open causing it to bleed).

After a couple of days of oiling and washing we could see his face and eyes. But he was underweight (350 grammes) and wouldn't survive the winter---hogs need to be 600+ grammes to survive hibernation. Also, he lost a lot of his spines. I would guess about 90% of them. At one stage he drove us crazy. Although hedgehog mites can't live on people (for more than a day or two) they itch like crazy.

But that's all behind us now. Today Hedgey (that's the name the vet put on his medication) weighs over 800 grammes. He has the first wave of new spines coming through, and they are about 1 cm long now. So it's time to let him go.

I wonder if he will ever come back.
