#+title: Project risk identification
#+date: 2021-10-17T12:26:00+1300
#+lastmod: 2021-10-17T12:26:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

* Brainstorm
** Cause-and-effect diagram
A diagram that shows the possible causes of an event of risk

They identify all the possible causes of a risk.

* Risk register
A table or chart that contains a list of risks

* Risk assessment
The stage of risk management where the qualities of a risk are estimated or measured. E.g., how likely, and to what extent.

This can be done through a *probability and impact matrix*, as a means to prioritize project risk.

** Impact
The damage a risk could cause, if it occurs.

Impact is determined using a scale of high, medium, and low.

** Probability
The likelihood that the risk will occur.

Also assessed using a scale of high, medium, and low

** Inherent risk
The measure of a risk, calculated by its probability and impact.

Also assessed using a scale of high, medium, and low

High inherent risks are the ones you should focus on and create mitigation plans.

** Risk appetite
The willingness of an organization to accept the possible outcomes of a risk.


Once the risk assessment has been done, the risk register should be updated.

* Types of risk
** Time risks
Time risks refers to the possibility that project tasks will take longer than anticipated to complete.

You'll need to be aware of time risks because time is money. Poor time management may deplete your budget and
upset your stakeholders by causing delays.


** Budget risks
Budget risk refers to the possibility that the cost of a project will increase due to poor planning or expanding the project scope.

You need to be aware of budget risk since budgeting provides the basis for project costs control.

** Scope risks
Scope risk refers to the possibility that a project won't produce the results outlined in the project goals.

You need to be aware of scope risks because the deliverables of your project might not be acceptable to your stakeholders or customers, and that may defeat the purpose of the entire project.

** External risks
By external risks, we're referring to risks that result from factors outside of the company that you have little to no control over.

** Single point of failure
A risk that has the potential to be catastrophic and halt work across a project.

** Dependency
A relationship between two project tasks, where the start or completion of one task depends on the start or completion of another task.

Because dependencies are the links that connect one project task to another, they are often a /huge source of risk to a project/.

There are four types of task dependencies:

- Finish to Start
- Finish to Finish
- Start to Start
- Start to Finish

If you don't plan for dependencies, you might risk an impact to your budget, schedule, or the project outcome.
*** Internal dependencies
There are dependencies within the project that you and your team have control over.

*** External dependencies.
These are dependencies that you have no control over.



* Backlinks
- [[{{< ref "202110171207-project-risk-management" >}}][Project risk management]]
- [[{{< ref "202109121932-project-phase-planning" >}}][Project phase - planning]]
