#+title: Reviewing articles
#+slug: reviewing-articles
#+date: 2011-01-07T10:22:00+12:00
#+lastmod: 2011-01-07T10:22:00+12:00
#+categories[]: Research
#+tags[]: Reviewing
#+draft: False

There are many good items on how to review articles, /etc/. As [[{{< relref "20080925-reviewing" >}}][I've said before]], I particularly like Baruch, Sullivan, and Schepmyer (2006).

I've just signed up to review for the Academy of Management, and they require one to have read---and to confirm that one has read---Romanelli (1996), Leblebici (1996), and Schawb (1985).

These three articles are largely personal reflections, the describe how those authors go about the reviewing process and how they come to their decisions. These are insiders (Unruh, 1979; 1980) seeking to help those more at the periphery (/e.g.,/ me) to become more expert, more 'central' than they were/are. What's interesting here---aside from the usefulness of the articles themselves---is the manner in which they do it. This isn't prescriptive, in the way that Baruch is, this is more descriptive.

One has to, to a larger extent, work out or create ones own logic, to make sense of (Weick, 1995) what is going on. In other words, they are a guide for regulars rather than outsiders or tourists.

* References

/Winning reviews: A guide for evaluating scholarly writing/. (2006). Houndmills, Basingstoke, Hampshire: Palgrave Macmillan.

Leblebici, H. (1996). The act of reviewing and being a reviewer. In P. J. Frost & M. S. Taylor (Eds.), /Rhythms of academic life: Personal accounts of careers in academia/, Foundations for Organizational Science (pp. 269-273). Thousand Oaks, CA: SAGE Publications.

Roos, J. (2006). /Thinking from within: A hands-on strategy practice/. London: Palgrave Macmillan.

Schwab, D. P. (1985). Reviewing empirically based manuscripts: Perspectives on process. In P. J. Frost & L. L. Cummings (Eds.), /Publishing in the organizational sciences. Homewood, IL: Irwin/ (pp. 171-181). Homewood, IL: Richard D. Irwin Inc.

Unruh, D. R. (1979). Characteristics and types of participation in social worlds. /Symbolic Interaction/, 2(2), 115-130. doi:10.1525/si.1979.2.2.115

Unruh, D. R. (1980). The nature of social worlds. /The Pacific Sociological Review/, 23(3), 271-296.

Weick, K. E. (1995). /Sensemaking in organizations/. Thousand Oaks, CA: Sage Publications.
