#+title: Lean
#+date: 2021-09-14T19:11:00+1300
#+lastmod: 2021-09-14T19:11:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management Lean

Lean methodology is often referred to as Lean Manufacturing because it originated in the manufacturing world. The main principle in Lean methodology is the removal of waste within an operation. By optimizing process steps and eliminating waste, only value is added at each phase of production.

It emerged out of the Toyota factories.

Today, the Lean Manufacturing methodology recognizes eight types of waste within an operation: defects, excess processing, overproduction, waiting, inventory, transportation, motion, and non-utilized talent. In the manufacturing industry, these types of waste are often attributed to issues such as:

- Lack of proper documentation

- Lack of process standards

- Not understanding the customers’ needs

- Lack of effective communication

- Lack of process control

- Inefficient process design

- Failures of management

These same issues create waste in project management.

Implement Lean project management when you want to use limited resources, reduce waste, and streamline processes to gain maximum benefits.

You can achieve this by using the pillars of the Lean 5S quality tool. The term 5S refers to the five pillars that are required for good housekeeping: sort, set in order, shine, standardize, and sustain. Implementing the 5S method means cleaning up and organizing the workplace to achieve the smallest amount of wasted time and material. The 5S method includes these five steps:

* Summary
Lean uses the 5S quality tool to eliminate eight areas of waste, save money, improve quality, and streamline processes. Lean’s principles state that you can do more with less by addressing dysfunctions that create waste. Lean implements a Kanban scheduling system to manage production.

* Backlinks
- [[{{< ref "202109261600-principles-of-lean" >}}][Principles of Lean]]
- [[{{< ref "202109141908-lean-six-sigma" >}}][Lean Six Sigma]]
- [[{{< ref "202109131906-lean-six-sigma-project-management" >}}][Lean six sigma project management]]
- [[{{< ref "202109141856-pillars-of-the-lean-5s-quality-tool" >}}][Pillars of the Lean 5S quality tool]]
