#+title: From Outlook to Gmail
#+slug: from-outlook-to-gmail
#+date: 2009-01-16T08:17:00+12:00
#+lastmod: 2009-01-16T08:17:00+12:00
#+categories[]: Tech
#+tags[]: Gmail Outlook Spam
#+draft: False

I've taken the plunge and moved to [[https://mail.google.com/][gmail]] for all my email. I've exported all my email, contacts, and calendar, and notes and then imported them into gmail.

For all my non university email addresses, I've set up forwarding so it goes straight to my gmail account. The IT wonks at the [[https://www.auckland.ac.nz/][university]] are in the process of setting up the forwarding of their email to my gmail account. In the meantime I have a rule that moves my university email to gmail via imap folders. Once the proper redirection is in place, it will be interesting to see if my university email still gets processed by the University's spam filters (they just tag email as spam, allowing the recipient to decide what to do with it).

One little thing I have yet to solve has to do with filters. Gmail allows one to apply filters to messages (to label them, move them, delete them, etc). However, one can only match ordinary text (i.e. not the email message headers per se). Also, the =*= is a wild card. But the university tags spam with =****SPAM****=.

Now ideally, I would like to filter messages that have =****SPAM****= in subject line. Alas, I can't (because of the wild cards). If I just match on "spam", then I also select messages where I'm writing about spam; e.g., "How much spam do you get". Maybe in the future gmail will allow one to match on email header information such as "X-Spam: yes".

But really, that is a minor thing. So far I am really impressed with gmail, and as I learn the [[https://mail.google.com/support/bin/answer.py?hl=en-uk&answer=6594][shortcut keys]] I am even more impressed. Previously, I kept all my email in a series of folders (e.g., 2001, 2002, 2003, ...). But with gmail I've found the search so fast an powerful that I've done away with those somewhat arbitrary categories.
