#+title: Academic Honesty
#+slug: academic-honesty
#+date: 2004-04-09T11:31:00+12:00
#+lastmod: 2004-04-09T11:31:00+12:00
#+categories[]: Teaching
#+tags[]: Plagiarism AHA
#+draft: False

For the past eight months, in my spare time and with a small grant for technology development, I've been working with a small group of colleagues (three) to develop a self-paced package designed to:

- Define academic honesty.
- Explain the principles, logic, and need to being academically honest, rather than just saying "You must do this; Or else".
- Ensure that students understand the Universities policies in this area--can they interpret and apply the rules in a variety of situations; acting in the spirit of the 'law' rather than 'to the letter of the law'; the former being much harder to do than the latter.
- Provide students with a sufficient understanding of APA referencing so that they they can apply it in a variety of common situations.
- Allows students to test that they understand and can apply ideas such as referencing, quoting, and paraphrasing in a way that is consistent with the [[https://www.apa.org][Publication Manual of the APA]].

Conceptually, I don't think there is much new in the package -- all the information can be found in and around the university. What we're seeking to do is to bring it all together (in an academically honest way), so that it is conveniently accessible to students. (Oh, in case I haven't mentioned it before, check out the great article [[https://www.study-skills.net/][Beat the Witch-hunt! Peter Levin's Guide to Avoiding and Rebutting Accusations of Plagiarism, for Conscientious Student]]

This is all well and good, and we're just finalising the last few details/words before trialling it, BUT currently it takes about 10--15 hours to work through the whole package. So, I'm worried that it takes too long, and that students will 'skip to the end' and just learn the mechanics of referencing, etc, and not the under pinning logic behind it. That some students adopt instrumental strategies is not in doubt -- but does it matter? Should they be able to just do the referencing section, or should I be 'big brother' and compel them to work through the whole package? At the moment, I favour letting them do what they think they need (but provide some sign posts about what is 'best practice').

Time will tell how well it works.
