#+title: More on Carl Zeiss Jena
#+slug: more-on-carl-zeiss-jena
#+date: 2004-10-22T11:41:00+12:00
#+lastmod: 2004-10-22T11:41:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT302 Marking
#+draft: False

I'm still marking essays from /Business Policy & Strategy/. I'm surprised by how long it is taking me--what does that say?

Anyway, I've just finished marking Howie's essay (Howard Hunt); and I really enjoyed it.

It has a very different feel to Pene's excellent [[{{< ref "carl-zeiss-jena" >}}][essay]]. I think it goes to show how different answers can be and still be successful.

It's not faultless, but why not read it yourself and see what you think?

#+BEGIN_QUOTE

The goal of this essay is to demonstrate the depth of my understanding of the concept of strategy based on my learning from the course text book. Through analysis of the written case of Carl Zeiss Jena I will make recommendations on the future of strategic change within the company, utilizing the materials in the text book, written by de Wit and Meyer, to justify my assessment.

For the purpose of this assignment it makes sense to start by outlining strategy as I understand it. As is with most issues of a strategic nature, the case involving Carl Zeiss Jena can be classified as a problem of organized complexity. Mason and Mitroff (1981) would define it as a 'wicked' problem because the factors involved are mostly intertwined and very complicated. Since it is impossible to simply tame them this means that, whilst there is no one true path that will lead the company into the future I can, under the circumstances, formulate a path that I feel is justified. Kenichi Ohmae (1982) would agree when I say that there is no formula for strategic success.

This is also to assume that my reasoning is from a perspective of rational thinking. Naturally I am limited by a sense of bounded rationality (Simon, 1957, as cited by de Wit & Meyer, 1998), however any decision I make has been measured against my own consistent and rigorous use of logic. Interestingly it takes a certain amount of creative imagination to conceptualize a solution to the case of Carl Zeiss Jena. This requires a generative thinking perspective (the other end of the spectrum) to devise. This tradeoff on the spectrum could be linked to my own need for uncertainty avoidance (Hofstede, 1993). I must decide to what degree imagination and intuition must meet fact and logic within and around the constraints of the 'square' of reality. It is dilemmas of this magnitude that makes strategy both complex and difficult to define. With an understanding of the types of paradoxes that exist, one is able to better justify solutions to the problems that they face.

The case Carl Zeiss Jena brings an early issue to light. 'Continuity', in regards to strategy, is the issue of whether strategic changes should "gradually evolve out of the current state of affairs, or mark a radical departure from the organizations past?" (de Wit & Meyer, 1998, p. 237). In other words it is to suggest a paradox of evolution and revolution. This case analysis will further examine this tradeoff with an aim to identify just where on the continuum my solution will be focused.

Carl Zeiss Jena has seen some dramatic changes over the years. There are a few standout issues that I believe will be most crucial to the continuing prosperity of the company. To begin the consideration of continuity, in regards to further strategic change, I believe that these issues need to be addressed immediately. It is probably best to outline these ideas so that my stance on revolution in this case can be more clearly identified.

If I were in Dr Dierolf's shoes in 1991 I would be focusing on some very important factors that I think would contribute to the Jena subsidiaries continuation as going concerns.

Most importantly I feel is the change of mentality needed due to the macroeconomic changes in the environment. The 'cognitive maps' of the workers are heavily based on belief systems (de Wit & Meyer, 1998, p. 76). Primarily this is concerned with the disintegration of the communist state of East Germany and the subsequent reintroduction of the East to the West German Foundation. There are some key issues associated with this. First of all is the understanding of how Western economies operate. Capitalist ideals underlie these workings and a rapid re-education of the remaining employees will be key to transforming the morale and culture of the separate Jena identities. This undoubtedly requires a reprogramming of the cognitive maps to facilitate the shift to a free market. The challenging of these socially constructed paradigms will be the most important hurdle to overcome, as without this level of understanding, it will be very hard to defeat the long-term inefficiencies created by sluggish command economies. This requires a certain amount of re-education which leads me to my next point.

There is no doubt that for the entities to survive autonomously they must develop their own identities. This is noted by Dierolf. However for them to prosper in a free market economy, they need to understand the importance of efficiency and the different functions of a business that contribute to profit maximization. For this reason I would focus on using a combination of the knowledge of the West German managers and the independent consultants to increase the application of the AB retraining programs. These workshops need to be designed around each function of the business as well as incorporating a cross-functional focus. The aim of this is for employees to develop a holistic view of how a business could be more efficiently run. These programs particularly need applications in marketing, cost accounting, pricing strategies, customer service, product design and distribution. Whilst technical skills are already very high, they are a product of a socialist system and need to evolve to incorporate many more facets. This flow of knowledge is a benefit of a joint venture and can be seen as increasing capabilities whilst hopefully uncovering new ideas. As Gattner put it, ?You have to permit some chaos to encourage creativity? (de Wit & Meyer, p.1006).

The known entrepreneurial spirit that had been suppressed for so long could be better placed to flourish under the new structure.

With these early issues addressed, we can expect to see the building of these capabilities lead to the development of competencies. Prahalad and Hamel (1990) note that ?If core competence is about harmonizing streams of technology, it is also about the organization of work and the delivery of value? (de Wit & Meyer, 1998, p. 437). What this highlights in the case is that although Zeiss is technically apt, it lacks the skills to help develop and entrench the core value adding processes. How can this be achieved? Hamel and Prahalad (1990) would say that it is necessary to reform management principles which include issues of Human Resource management.

Human Resource policies are another such integral way of forming the necessary competencies. Due to the long-term instability of the worker environment it is essential that the remaining employees understand the structure and strategy of the staffing policy. The current strategy can be likened to a primarily polycentric approach. However the staff need to have clear communications about advancement opportunities and international strategy for growth. Transparency in communication and structure needs to be focused to boost morale and help the employees gain a long-term focus. Due to upheaval for so long, many have short-term orientations which only stability will change. Once staff have become aware of their place in the business and their ability to contribute to a greater picture, they may well become better assets themselves. This education should also help them understand the need for the earlier job cuts and may help ease tensions. At the same time this is in line with foundation principles, that is a commitment to the workers. Education is a commitment! With a longer term focus should come a shift towards a more geocentric approach. This involves selecting the best people for the job!

All these suggestions so far are heading towards a key conclusion. That is to provide some stability. This is to suggest that Dierolf should restrict revolutionary activities as soon as possible. It is acknowledged however, that the issues outlined so far are revolutionary in nature. I put it that this is for the greater good in the longer-term. As Gattnar observed, never "did we have the peace necessary to manage a business? We were always rushing from one crisis to another" (de Wit & Meyer, p.1006). With newfound knowledge and stability a focus can then shift towards growth in the much needed low and middle market segments. Overlapping of product lines can be eliminated and the expansion of global markets can be concentrated on. With regards to business portfolio analysis, it is clear that under the growth-share matrix of the four broad strategic categories (Hedley, 1977), analytical instruments are a dog that doesn't justify further investment. Since the companies are in a wide array of businesses, liquidation as opposed to divestment is the right option.

This restructuring of the company into two separate entities can be analysed further. Carl Zeiss Jena GmbH will concentrate on core product lines. It is the integration and leveraging of these capabilities that will add to long-term competitiveness. Exactly which are cash cows and which are stars is unclear but it would make considerable sense to consider the options of the firm under this framework.

This leads to the discussion of global strategy at a corporate level. Through exporting, an international strategy can be mapped out for extending market coverage. Due to the increase of knowledge and likely technology, it is fair to assume that the collapse of the Eastern markets will give way to the necessity to find international destinations for the high quality goods that are prided on. Obviously this is a reactive method of planning as opposed to a proactive approach to strategy. Paul Strebel (1994) would consider this situation to be a result of the interactions of both change and resistance forces. The change arena is characterized by forces that cannot be rolled back. Since most of the resistance was based on culture and a reactive turning point has forced adaption, it is fair to assume that a path of revitalization is valid. This involves using the macroeconomic changes to drive the internal organizational change process. This change is often slow, however it is all-encompassing and continuous. I believe that this is essential, especially as a framework for bringing about much needed organizational stability.

This can be linked to the idea that until 1991 the organization had been through enough revolution and the focus of strategy I believe should be now aiming towards a more continuous change perspective. Michael Hammer (1990) makes an interesting statement, "At the heart of reengineering is the notion of discontinuous thinking" of recognizing and breaking away from the outdated rules and fundamental assumptions that underlie operations? (de Wit & Meyer, 1998, p. 254). Why is this important? Well as has remained poignant throughout the case, political instability has constantly threatened the business. As the change force lowered resistance, re-engineering the structure of Carl Zeiss Jena and the appointment of West German management it will mean that for the first time the business has a chance to settle into a more stable position. A link from this statement can be made from the notion of 'discontinuous thinking' to De Wit and Meyers (1998) discussion on the perspective of discontinuous change. That is, a big change will equal a big shock and hence yearning for stability will also be big. Due to the magnitude of the changes in the environment of this case, I believe that the focus should be on establishing this stability.

Although there are many issues to discuss in this case, I have identified those which I consider to be most important initially. The suggestions in summary are as follows. Due to the need to re-educate and change the cognitive maps of the workers I believe that rapid re-training is most vital. This requires the increase of training programs and a focus on communication and inclusion. Raising staff morale will be the key to success. A focus on human resources will be crucial to seeing the transformation of the staff into the assets that they should be. I can say that due to the necessary restructuring and great instability, I would, in Dierolf's shoes, steer the company towards a position that would reduce the need for further revolutionary change. This includes the focus on incrementally developing the internal capabilities and re-establishing market development as a focus. By planning for incremental and evolutionary change, the need (once initial shocks have been overcome) for revolution will be reduced. In conclusion I can say that whilst I believe that Dierolf should be focusing on stability, it is clear that this may require big changes to occur first. My stance on the spectrum of evolution and revolution has shifted depending on the circumstances. This shows an understanding of the issues of strategy as I mentioned in the introduction. Depending on the circumstances, strategy will depend on the interpretation of issues by the strategist. With reference to the case, long-term, a focus of building the competitive facets of the business should bring about the ability of the company to look towards a plan of foreseeable profitability and growth. Hopefully enough revolution is enough.

* References

de Wit, B., & Meyer, R. (1998). Introduction. In B. de Wit & R. Meyer (Eds.), /Strategy process, content, context: An international perspective/ (2nd ed.). Minneapolis, MN: Thompson Learning.

Prahalad, C. K., & Hamel, G. (1990). The Core Competence of the Corporation. /Harvard Business Review/, 68(3), 79--91.

Hammer, M. (1990). Reengineering Work: Don't Automate, Obliterate. /Harvard Business Review, July/August, 104--112./

Hedley, B. (1977). Strategy and the "business portfolio". /Long Range Planning/, 10(1), 9--15.

Hofstede, G. (1993). Cultural constraints in management theories. A\_cademy of Management Executive\_, 7(1), 81--94. doi: Article.

Mason, R. O., & Mitroff, I. (1981). Complexity: The nature of real world problems. In /Challenging strategic planning assumptions: Theory, cases, and techniques/. New York: John Wiley.

Ohmae, K. (1982). Analysis: The starting point. In T\_he mind of the strategist: The art of japanese management\_. New York: McGraw-Hill.

Simon, H. A. (1957). /Models of man: Social and rational: Mathematical essays on rational human behavior in a social setting/ (p. 287). New York: Wiley.

Strebel, P. (1998). Choosing the right change path. In B. de Wit & R. Meyer (Eds.), /Strategy process, content, context: An international perspective/ (2nd ed.). Minneapolis, MN: Thompson Learning.

#+END_QUOTE
