#+title: Of mountaintops, magnets, and mandates
#+slug: of-mountaintops,-magnets,-and-mandates
#+date: 2019-10-07T09:58:02+13:00
#+lastmod: 2019-10-07T09:58:02+13:00
#+categories[]: Teaching
#+tags[]: Capstone
#+draft: False

This is probably, the first, in a series of posts about Capstone courses.

Notes from:

#+BEGIN_QUOTE

Connie J. Rowles, Daphene Cyr Koch, Stephen P. Hundley, Sharon J. Hamilton. (2004). Toward a Model for Capstone Experiences: Mountaintops, magnets, and mandates. In /Assessment update. 16/(1).

#+END_QUOTE

Extracted Annotations (7/10/2019, 10:19:37 AM)

"In recent years,capstones have grown in scope,importance,and necessity,as the result of institutions'heightened sense of accountability for documenting student learning outcomes and their recognition that thoughtful reflection on lessons learned is part of the foundation of lifelong learning." ( 2004:1). Typically, the focus of capstone courses is either on some kind of programme-wide summative "assessment" ( 2004, p.1) or on "student development" ( 2004, p.1).

"When student developmentis emphasized,capstone experiences are designed to provide culminating experiences at the baccalaureate level." ( 2004, p.1). "Such courses are often used to facilitate transition from the undergraduate student role to the post baccalaureate roles of employee,graduate student,civic-minded community member,and/or lifelong learner." ( 2004, p.1).

"When assessment is emphasized,capstones are used in assessing program-level student learning outcomes." ( 2004, p.1). "Essentially, capstones seek to answer the central questions: What does the student know? What can the student do? What evidence suggests what students know and can do? Results from capstones are aimed at improving instructional practices,and capstones are frequently used to provide accountability and documentation for a variety of audiences," ( 2004, p.1)

"Indiana University-Purdue University Indianapolis (IUPUI),a large urban institution,has been working on a campus-wide framework for baccalaureate capstone experiences" ( 2004, p.2) and has "developed a principles-based approach to general education." ( 2004, p.13). "Against this backdrop of diversity,decentralization,and dispersed general education,our campus has been on a journey to more fully develop capstone experiences that encompass both the student development and assessment emphases, while remaining somewhat flexible in their implementation." ( 2004, p.13)

The university "identified several assumptions that would guide its efforts" ( 2004, p.13). "First, there could be no overly prescriptive plan for capstone experiences,given the programmatic diversity of the campus. Second,the culture, values, structure, and financial operations of the campus support decentralized, discipline-based decision making, and these conditions would need to be respected in the development of capstones. Third, great effort should be undertaken to make explicit to faculty and administrators why capstones are important and how they connect to existing institutional initiatives. Finally, the principles of undergraduate learning should form the basis for activities that occur in capstone experiences" ( 2004, p.13)

"Mountaintops refer to capstone experiences that are interdisciplinary or mul" ( 2004, p.13). They are "multidisciplinary, in which students from two (or more) disparate majors ascend to the capstone experience from different,unique disciplinary perspectives,coming together at the summit; essentially,this is a capstone experience that makes use of the rich diversity of disciplines." ( 2004, p.13)

"Magnets refer to capstone experiences that are discipline-specific and that, like a magnet attracting precious metal, pull together the richness of content from the discipline in a summative manner." ( 2004, p.13).As such, "The capstone experiences occur in two separate classes: a professional development capstone, in which students," ( 2004, p.13). "among other activities, participate in a leadership assessment center, complete a comprehensive exam drawn from core course content, and develop a reflection paper on general education; and a research capstone,in which students propose a research topic, conduct a literature review, collect and analyze data,interpret and summarize results, develop conclusions and recommendations,and present findings to decision makers in the form of a thesis and multimedia presentation." ( 2004, p.14)

"Finally, mandates refer to capstone experiences that are organized around meeting the needs of an external constituency, typically when licensure, certification, or other circumstances require that competences be mastered and demonstrated in a summative manner." ( 2004, p.14)

"To help students and faculty maximize capstone effectiveness,we outline several keys to capstone experiences." ( 2004, p.14). Namely:

- "capstone experiences should be a culminating set of personal, academic, and professional experiences,and as such, the primary focus of capstone experiences should be on the synthesis,integration,or application of previously acquired knowledge rather than on the acquisition of new knowledge or skills." ( 2004, p.14).

- "The rationale for organizing the approach to capstones (mountaintops, magnets, or mandates) should be based largely on the specific needs of the discipline." ( 2004, p.14)

- "The capstone experience should be situated near the end of the
  program of study, should be required in order to graduate, and should not necessarily be thought of as just a single course." ( 2004, p.14)

- "capstone experiences should be facilitated, mentored,or coordinated by full-time faculty, thus ensuring that general education themes and discipline-specific requirements are addressed with reasonable consistency." ( 2004, p.14)

- "student ownership, responsibility,and engagement should be central to capstones,with ample opportunity for discussion,reflection,and demonstration of general education principles." ( 2004, p.14)

"However capstone experiences are structured, the pedagogical approaches necessary for student enjoyment and success depend on the presence of several of the following factors:collaborative learning; self-directed learning; problem-based learning; and other learner-centered instructional strategies that encourage critical thinking, integration, reflection, and synthesis." ( 2004, p.14).

"It is important to create an environment in which faculty can share their ideas openly and freely and can learn how their colleagues with equal claim to academic freedom can nonetheless work within faculty-developed curricular policies." ( 2004, p.15)
