#+title: Advancing innovation in professional service firms
#+date: 2013-07-07T13:13:38+13:00
#+lastmod: 2013-07-07T13:13:38+13:00
#+publishdate: 2013-07-07
#+author: Christof F. Breidbach, Peter Smith, Lisa Callagher
#+status: Published
#+type: published
#+citation: Breidbach, C. F., Smith, P., & Callagher, L. J. (2013). Advancing innovation in professional service firms: Insights from the service-dominant logic. _Service Science_, 5(3), 263--275.
#+doi: 10.1287/serv.2013.0053
#+file: advancing-innovation.pdf
#+tag: advancing-innovation
#+keywords[]: service_dominant logic professional_ service_firms innovation
#+comments: no
#+aliases[]: /publications/advancing-software-engineering/index.html

Innovation is of continuing interest to professional service firms (PSFs) and the scholars who study them. Nevertheless, innovation in PSFs remains under-researched within the wider canon of literature on service innovation, and existing studies typically take a firm-centric perspective on innovation, even though such approaches have been challenged extensively. Our study addresses the shortcomings related to service innovation research, particularly in the context of PSFs, by utilizing the service-dominant logic (SDL)---a framework considered particularly appropriate for understanding innovation in service from a customer-centric standpoint. We apply the SDL to a case of innovation in an engineering consulting firm, and we find that innovation in PSFs is, to a certain degree, unique. Specifically, this work contributes to the literature by identifying multiple beneficiary roles, termed 'customer as payer' and 'customer as end user,' with often competing and changing values in use. The notion of operant resources is extended to include social capital, and we show how social capital can enable innovation in PSFs. A preliminary model and five propositions that can guide future empirical research on innovation in PSFs, together with managerial implications, are delineated.
