#+title: Project plans
#+date: 2021-10-04T07:11:00+1300
#+lastmod: 2021-10-04T07:11:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

A project plan documents the scope, tasks, milestones, and overall activities of the project.

At the center of the project plan is the project schedule. The project schedule can help you estimate the amount of time it'll take to complete the project, and it can provide the team with a way to track the project's progress against your goals.

* Elements of a project plan
- Tasks: Activities to be accomplished within a set period time
- Milestones: Normal signal the completion of a deliverable
- People: The roles and responsibilities, and creating a sense of responsibility
- Documentation: E.g., RACI chart, Project charter, Budget, Risk management
- Time:  Estimated time that will be spent on the project. This forms the basis of the schedule, which is the anchor of your project plan


Every project plan is a living artifact that serves as your team’s roadmap throughout the project. We have covered some common elements of project plans, including tasks, milestones, people, documentation, and time. Let’s look at how these elements intersect with other important components to create a comprehensive plan for your project.
How project plan components are connected

You have learned that at the center of the project plan is the project schedule, which helps you estimate the amount of time it will take to complete the project and provides the team with a way to track the project’s progress against your goals. In addition to the schedule, you should also include the following components in your project plan:

- Scope and goals
- Work Breakdown Structure (WBS)
- Budget
- Management plans

** Project scope and goals

Both the project scope and goals will be captured initially in your project charter, the document that clearly defines the key details of your project. You can link your project charter in your project plan. Having details about the project’s scope and goals easily accessible can help remind your team of the objectives they are trying to accomplish and if anything is asked of them that goes beyond what was initially agreed upon in order to achieve those objectives.

** Work Breakdown Structure (WBS)

As a reminder, a Work Breakdown Structure is a tool that sorts the milestones and tasks of a project in a hierarchy, in the order they need to be completed.  The WBS is key to your project plan since it breaks the work down into more manageable pieces. In your project plan, the tasks should be visible in one place with clear descriptions, owners, and due dates. This will allow you and your team to understand who is responsible for which tasks and when each task is supposed to be completed. Your project plan should also contain detailed milestones and statuses related to these tasks, which will help you and your team members visualize project progress.

In addition to the WBS, further documentationsuch as a RACI chartwill help define roles and responsibilities and would be useful to add to your project plan. Keeping this documentation stored or linked in one place is a best practice for transparency and effective communication.

** Budget
:PROPERTIES:
:ID:       4fffb2a3-eea8-42bb-adf7-881c0c87464c
:END:

Throughout the life cycle of your project, the budget will need to be managed and monitored. The project budget is often linked to the project plan because it is heavily dependent on key elements of the project. Linking these components allows for smoother management and visibility.

Depending on the size of your project and your organization, you may not be the primary person responsible for managing the project budget. For instance, if your project is at a large organization and the funds are managed by another department, you may not have as much autonomy or insight into all of the budget elements. As a result, you may not be able to monitor the budget closely. If someone in another department is managing the budget, make sure to have regular check-ins with them to ensure that you are aware of how you are tracking.

** Management plans

Management planssuch as the change management plan, risk management plan, and communication planare all integral to keeping a project organized and on track and should be linked in your project plan. These plans will be discussed in detail in the coming lessons of this course.

* Key takeaway

Project scope and goals, the Work Breakdown Structure (WBS), the budget, and management plans are all important components of your project plan. They help define how basic project plan elementsincluding tasks, milestones, people, documentation, and timewill be structured and utilized in your project. However, no one project plan will be the same. At Google, we work with a variety of different tools and templates to create and manage project plans. It is important to know your end goals and what is essential to you and your team in order to pull the relevant pieces of the project together.

* Best practices
- Carefully review deliverables, milestones, and tasks

- Give yourself time to plan
   Allow for buffer time

- Recognizing and plan for the inevitable: things will go wrong
  Identify likely risks

- Stay curious
  Ask lots of question of the team mates. Understand the expectations, priorities, risk assessments, and communication styles of your stakeholders and vendors.

- Championing your plan
  Make sure what you are going is clear. Can they use the chosen tools?

  Explain the benefits of the plan.

* Tips for defining project tasks
:PROPERTIES:
:ID:       377b0f4b-ac0f-459c-b052-9ecd1ae882e5
:END:

The process of identifying project tasks and defining them is one that requires practice. Breaking tasks down into workable parts is challenging because you have to decide which tasks may require additional subtasks and which tasks do not. For instance, if you are managing a cross-country move, you do not need to break down the task of unloading boxes from the car into which box should be moved first. However, you may need to break down the movers’ tasks into smaller, more detailed steps. As you progress in your career, you will get better at breaking tasks down. In the interim, here are some guidelines to help you improve this very important project management skill.
Define project tasks in one or two sentences

When writing descriptions of project tasks, keep them to one or two sentences long. If you find that a certain task description needs to be longer than one or two sentences, this indicates that the task is complex and could be broken down into smaller tasks or that it may need further clarification.
Look at project task dependencies

When looking at how you might break certain parts of the project down into tasks, consider task dependencies, or what has to be completed or handed off from one person to another before work on each task can begin. Identifying dependencies can help you decide how much a task needs to be broken down. For instance, if you are managing a project that includes an awards ceremony and one of the tasks is to set up the stage, the dependencies for this task could include getting estimates from an audiovisual (AV) contractor, procuring necessary equipment, and constructing the stage backdrop.

* Enlist help from team members

It is often helpful for your team to be involved in the task breakdown process. You might have a meeting where you discuss each broad goal or major task with the team. This way, team members can present varying perspectives as they work together to break down tasks. For example, if someone on your team has had experience on a similar project,  they may suggest a certain task actually be broken down into three different tasks.
Define project tasks by the amount of time they will take to complete

Defining project tasks by the amount of time they’re expected to take will reveal any especially lengthy tasks. If a task is expected to take a long time, it could indicate that there are additional subtasks that need to be defined. Identifying tasks by time is helpful for scheduling other tasks or events around the longer tasks. This strategy also helps you determine appropriate milestones, as milestones are often the culmination of a series of tasks. Acknowledging the completion of a large and lengthy task is also a great way to celebrate success, learn from the process, and keep the project on track.
Identify project tasks by their “done” factors

Begin with the end in mind: What does it mean for the task to be considered “done”? From there, you can work backwards to see if you’ve missed any steps and identify checkpoints for completion along the way.

* Backlinks
- [[{{< ref "202109121932-project-phase-planning" >}}][Project phase - planning]]

