#+title: Lean Six Sigma
#+date: 2021-09-14T19:08:00+1300
#+lastmod: 2021-09-14T19:08:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management Lean Six_Sigma

After both Lean and Six Sigma were put into practice, it was discovered that the two methodologies could be combined to increase benefits. The tools used in Lean, such as Kanban boards and 5S, build quality in processes from the beginning. Products developed using Lean methods are then inspected or tested using Six Sigma standards. The products that do not meet these standards are rejected.

The largest difference between these methodologies is that Lean streamlines processes while Six Sigma reduces variation in products by building in quality from the beginning and inspecting products to ensure quality standards are met. You may find that one of these two methodsor using them both togethercan improve the efficiency of your projects.

* Backlinks
- [[{{< ref "202109141906-six-sigma" >}}][Six Sigma]]
- [[{{< ref "202109131906-lean-six-sigma-project-management" >}}][Lean six sigma project management]]
