#+title: Ethical decision making
#+date: 2021-11-03T19:35:00+1300
#+lastmod: 2021-11-03T19:35:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

* A framework for ethical decision-making

Ethical leadership is a form of leadership that promotes and values honesty, justice, respect, community, and integrity. As the leader of a project team, you will be expected to help your team succeed by leading with ethics. Building respect and trust with the teams you work withfrom individuals to external partners to project stakeholdersbegins with practicing ethical conduct.

In this reading, you’ll gain an understanding of a common framework for ethical decision-making that can help you ensure your actions align with the ethical standards of your organization.
* Ethics within your organization

Ethics can be defined as the principles of conduct governing an individual or a group. However, there is no single, universally-accepted grouping of ethical standardsthese definitions differ based on the culture and community at your company. In the working world, ethical standards may differ based on profession, industry, and organization. Usually, an organization will have its own code of conduct which specifies the standards to which it holds its employees accountable.

Here at Google, our code of conduct makes clear the expectations that we have for our employees and board members. It is possible that the organizations you will join throughout your career will have codes of conduct, too.

Part of the challenge of leading with ethics is ensuring that your actions align with the ethical standards of your community, both within your organization and beyond it. In your role as a project manager, a clear framework for ethical decision-making can help guide you to make positive decisions throughout your project.

* A common framework for ethical decision-making

The Markkula Center for Applied Ethics at Santa Clara University developed the following framework as a helpful guide for ethical decision-making.

** Recognize an ethical issue

According to this framework, you can begin to question the ethics of an issue by asking yourself questions about the nature of the issue. Could your decision negatively impact another person or group of people? Does the issue go beyond what is legal or efficient? From there, you can proceed onto fact gathering.

    Example: A vendor you have worked with in the past sends you a generous holiday gift shortly before you are about to select a vendor for a particular task in your project. If you accept the gift, would others be negatively impacted? To determine the answer to this question, get more facts.

** Get the facts

Decide what you should do about the issue, and seek answers as needed. Consult with the right people to consider all of the options available to you.

    Example: Continuing with the example above, you should check to see if your company has ethics guidelines regarding accepting gifts from external parties. If not, consult with your HR representative about the matter.

** Evaluate alternative actions

You can evaluate alternative actions by asking yourself the following questions:

- “Which option will produce the most good and do the least harm?”
- “Which option best respects the rights of all who have a stake?”
- “Which option treats people equally or proportionally?”
- “Which option best serves the community as a whole, not just some members?”
- “Which option leads me to act as the sort of person I want to be?”

Note that your answers to these questions are subjective, and you may want to elicit the opinion of others before deciding on an alternative action.

- Example: In the case of the vendor gift example, the answer to the question “Which option treats people equally or proportionally?” might be “decline the gift,” given that accepting it might influence your decision about who to award the contract to.

** Make a decision and test it

Once you have chosen an option, test it by imagining the reaction to your choice from a person whose opinion you value.

- Example: Once you have decided to decline the gift, discuss your decision with your manager, HR representative, or a trusted colleague.

** Act and reflect on the outcome

Consider how to carry out your decision with thoughtfulness and care, and after you act, consider the results of your decision.

- Example: Respectfully decline the vendor’s gift, noting your reason (for example, your company’s ethical guidelines state that employees are not permitted to accept gifts valued at more than $20 from vendors or contractors).


* Backlinks
- [[{{< ref "202109121934-project-phase-execution" >}}][Project phase - execution]]

