#+title: Open strategy - Case studies
#+date: 2021-11-18T11:48:00+1300
#+lastmod: 2021-11-18T11:48:00+1300
#+categories[]: Zettels
#+tags[]: Strategy Cases

A list of some of the [[{{< ref "202111181135-open-strategy" >}}][Open strategy]] cases that have been done:

* DialogTage
"A project by an Austrian car manufacturer, engaged top managers, employees and academics (inclusiveness). The strategy process itself was transparent: the strategy process set-up was conducted openly, and idea discussions and the final management letter including actions were made available (transparency). The strategy process of the project used a custom-built IT platform for idea pooling and for the calculation of an “impact factor” (IT-enabledness). (Stieger et al. 2012)" (Tavakoli et al., 2015, p.7).

* Daimler
(Binder and Bertram, 2010)

* HypoVereinsbank
(Matzler et al., 2014a)

* IBM
"involved top management and other employees as well as external partners, competitors and industry experts (inclusiveness). An initial vision was defined, synthesizing insights from 1,100 internal/external executives, thus building the framework for open gap analysis and idea discussions. The resulting strategy was announced in the form of reports and priority projects (transparency). Use of an IT platform provided idea pooling and algorithmic idea aggregation (ITenabledness). (Bjelland and Wood 2008; Matzler et al. 2014a; Matzler et al. 2014b)" (Tavakoli et al., 2015, p.7).

* Premium Cola
(Luedicke et al., 2016)

* Redhat
"involved top management and employees in its strategy process (inclusiveness). Pre-defined priority areas, ideas and discussions were visible. Specific ideas were selected for implementation through consensus in dedicated focus groups (transparency). A range of IT tools (wiki, chat, a platform for idea pooling and evaluation) was used to access, generate and communicate strategic ideas and outcomes. (Gast and Zanini 2012; Yeaney 2011)" (Tavakoli et al., 2015, p.7).

* Wikimedia Foundation
"involved top management, employees, consultants and its user community (inclusiveness). The strategy process, inputs, intermediate results, final strategy and operationalization were visible (transparency). Wikis and an IT platform were appropriated for idea pooling, discussion and implementation. (Dobusch and Kapeller 2013; Dobusch and Müller-Seitz 2015)" (Tavakoli et al., 2015, p.7).
