#+title: A capstone for the  capstone: An experiential exercise in strategic management
#+date: 2020-04-06T23:10:00+1300
#+lastmod: 2020-04-06T23:10:00+1300
#+categories[]: Zettels Articles
#+tags[]: InstructionalDesign Capstones

#+BEGIN_QUOTE

Carter, W. R., & Stickney, L. T. (2019). A capstone for the capstone: An experiential exercise in strategic management. /Journal of Management Education, 43/(3), 233-261. https://doi.org/10/ggm4pn

#+END_QUOTE

* Introduction
[[{{< ref "202004062300-capstone-courses" >}}][Capstone courses]] are an attempt to fix a particular problem.

The context. The problem. The attempt at a solution (and why).

* Theoretical background
Expand the context (a little) and locate the 'content' aspect of the course. The three things that the literature says should work in fixing this.

- [[{{< ref "202004062330-integrative-thinking" >}}][Integrative thinking]]

- Experiential thinking

- Reflective thinking

* The exercise
Overview of the exercise, then the glorious details. The details also include recommendations as to how to do the various bits of the programme and experiences of students responses to the exercise.

Diagram of the exercise with major steps.

- Preparation
  - Timing
  - Instructions
  - Case selection
- Phase 1: Individual preparation assignment
- Phase 2: Functional teams (session 1)
- Phase 3: Integrated teams

- Common observations
  What tends to go on in the exercise are class management issues.

* Assessment efficacy
Assessment of the efficacy of the exercise against the learning objectives.
- Analysis and results
  Details against the LOs from formally collected research
- Additional evidence of efficacy
  From course evaluations and instructor reflections
- Discussion
  No connection back to the literature !
