#+title: Paradox
#+date: 2020-06-23T23:00:00+1300
#+lastmod: 2020-06-23T23:00:00+1300
#+categories[]: Zettels
#+tags[]: Theory

* Defining a paradox

What is a paradox? There are a number of differing notions as to the nature of a paradox. From the Oxford English Dictionary, we have:

#+BEGIN_QUOTE

A statement or tenet contrary to received opinion or belief, /esp/. one that is difficult to believe. /Obsolete/.

#+END_QUOTE

There are a number of similar definitions, but those meanings are--by and large--rare or obsolete.

A more common notion of a paradox is:

#+BEGIN_QUOTE
An apparently absurd or self-contradictory statement or proposition, or a strongly counter-intuitive one, which investigation, analysis, or explanation may nevertheless prove to be well-founded or true.

#+END_QUOTE

For me, this boils down to a statement (or two statements) which, on the face of it, cannot be true. Some well-know examples include:

- Deep down, you're really shallow.
- Save money by spending it.
- If I know one thing, it's that I know nothing.
- I'm a compulsive liar.

This is very much the notion used by /Poole and van de Ven/ (1998) in their landmark paper on paradoxes and organization theories, where they not that, a paradox "consists of two contrary or even contradictory propositions to which we are led by apparently sound arguments" (van Heigenoort, 1972, p. 45 cited by Poole & van de Ven, p. 563).


In strategy, following on from /de Wit & Meyer/ (2005) a paradox are two rather contradictory positions (or tensions as they call them) between, say:

- Deliberate and emergent strategy
- Cooperation and competition
- Responsiveness and synergy between business units

De Wit & Meyer suggest there are three forms of 'resolving' such tensions.

First, one might treat them as a /puzzle/, where there is /one best way/ to solve them. When the puzzle is fully understood, the contradiction will no longer exist.

Secondly, one can treat it as a /dilemma/ where there are /only two possible solutions/, and neither of them is logically the best. These are often framed as an either/or situation.

The third approach is to treat it as a /trade-off/, in which there are /many possible/ solutions and the solutions involves striking a balance between, say, the amount of work-time and leisure-time.

Finally, in a /paradox/, there is no logical way to integrate the tensions as one factor is true and contradictory to the other factor which is also true. The question then become how to do two things that cannot be done together.

There are a number of approaches to working with a paradox (Pool & van de Ven, 1989) between say A and B.

1. Keep A and B separate and appreciate their differences.

2. Situate A and B either at different locations or levels in the social world.

3. Separate A and B temporally in the same location.

4. Find a new perspective that eliminates the opposition of A and B.

The last option is perhaps the hardest to do as one seeks to find a synthesis between the thesis and its antithesis.
