#+title: A refresh: Back to paper
#+slug: a-refresh
#+date: 2020-09-06T12:00:00+13:00
#+lastmod: 2020-09-06T12:00:00+13:00
#+categories[]: Tech
#+tags[]: Blogging Emacs Hugo
#+draft: False

** It's time to redecorate

I have been doing some work tidying things up with [[https://www.gnu.org/software/emacs/][Emacs]]; doing things like sorting out my fonts and [[https://protesilaos.com/modus-themes/][themes]], and trying to get [[https://www.emacswiki.org/emacs/ArtistMode][Artist Mode]] to work properly. It's still broken for me under Windows 10 and I can't be bothered (just yet) to sort it.

But in tootling around, looking for options I came across the website of [[https://zeekat.nl/][Joost Diepenmaat]]. At first I thought I was looking a PDF. Then I realised he was generating the page directly from [[https://orgmode.org/][Org]]. Interesting.

** Creating a Hugo theme

Updating/changing my sites look and feel has been on my (org-mode) TO DO list for some time. But, I'm not sure I want to go to using Org to generate this site; I have too many posts that would need converting from Markdown to ".org".

Instead, I have started to create a [[https://gohugo.io/][Hugo]] theme to replicate some of the look and feel of Joot's site. So far, I am pretty happy with the outcome. That doesn't mean I finished. Although I have spent a good chunk of the weekend working on the theme, it isn't perfect yet. There is still a good amount of work to be done to make it sing. But it's good enough for me to take the theme live.
