#+title: Some notes on institutional fields
#+date: 2004-09-07T15:32:00+12:00
#+lastmod: 2004-09-07T15:32:00+12:00
#+categories[]: Research
#+tags[]: Institutions
#+slug: some-notes-on-institutional-fields
#+draft: False

Defining a field:

#+BEGIN_QUOTE

identify communities of organizations that participate in the same meaning systems, are defined by similar symbolic processes, and are subject to common regulatory processes" (Scott, 1994, 71) "those organizations that, in aggregate, constitute a recognized area of institutional life: key suppliers, resource and product consumers, regulatory agencies, and other organizations that produce similar services and products (DiMaggio, P. J., & Powell, 1983, p. 143)

#+END_QUOTE

#+BEGIN_QUOTE

a field may be defined as a network, or a configuration, of object relations between positions (Bourdieu & Wacquant, 1992, p. 97)

#+END_QUOTE

#+BEGIN_QUOTE

a socially constructed structured space in which agents struggle (Wacquant, 1992, p. 17)

#+END_QUOTE

How do fields change? According to Powell (1991) there are three ways:

- Changes emanating from the periphery of the field
- The failure of isomorphism to regulate firms choices
- Political or legal upheavals that redefine the boundaries of the field

Furthermore, Scott (2000) suggests that transformation of a field arises
from:

- Changes in the relationships between firms
- Boundary changes of existing firms
- The arrival of new populations
- Changes in the boundaries of the field itself
- Changes in the governance structures of firms

** References

Bourdieu, P., & Wacquant, L. J. D. (1992). The purpose of reflexive sociology: The Chicago workshop. In P. Bourdieu & L. J. D. Wacquant (Eds.), /An invitation to reflexive sociology/. Chicago: University of Chicago Press.

DiMaggio, P. J., & Powell, W. W. (1983). The iron cage revisited: Institutional isomorphism and collective rationality in organizational fields. /American Sociology Review, 48/, 147---160.

Powell, W. W. (1991). Expanding the scope of institutional analysis. In W. W. Powell & P. J. DiMaggio (Eds.), /The new institutionalism in organizational analysis/ (pp. 183---203). Chicago: Chicago University-Press.

Scott, W. R. (1994). Institutions and organizations: Towards a theoretical synthesis. In W. R. Scott & J. W. Meyer (Eds.), /Institutional environments and organizations: Structural complexity and individualism/. Thousand Oaks, CA:-Sage.

Scott, W. R., Ruef, M., Mendel, P. J., & Caronna, C. A. (2000). /Institutional change and healthcare organizations: From professional dominance to managed care/. Chicago: University of Chicago Press.

Wacquant, L. J. D. (1992). Towards a social praxeology: The structure and logic of Bourdieu's sociology. In P. Bourdieu & L. J. D. Wacquant (Eds.), /An invitation to reflexive sociology/. Chicago: University of Chicago Press. <span
