#+title: Core skills of a project manager
#+date: 2021-09-12T12:15:00+1300
#+lastmod: 2021-09-12T12:15:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management Skills

The core skills that a project manager should bring to the role.

* Enabling decision making
- Gather information
- Make informed decisions
- Communicate decisions

  You can help team members feel empowered from the start of your project by making the decision-making process collaborative. For example, state the goals of specific deliverables and elicit input from your team on how to achieve those goals. You may have an idea of how you would like certain tasks to be accomplished, but your team members may have more creative or efficient approaches. Empowering your team to express their opinions and make their own decisions allows you to focus on the overarching management tasks and prioritize them in order of importance. Additionally, when you allow team members to have a voice in decisions, it helps foster an environment of responsibility, accountability, and team closeness.

* Communicating and escalating
- Documenting plans
- Sending emails about the status of the project
- Escalating risks or issues to stakeholders

Project management requires clearly communicating project goals and expectations, team member roles and responsibilities, and constructive feedback. Knowing how to effectively communicate and when to escalate issues to management is key to keeping you, your team, and your organization on the path to success. When escalation is required, try to approach management with both the problem and the potential solution or suggestions. This will show that you’re taking initiative as a project manager.

* Flexibility
- Know when and how to be flexible

** Flexible planning

Change is inevitable, and the more flexible you are as a project manager, the more successful you will be throughout your career. These flexible planning strategies can help you manage your project during times of unpredictability:

- Assess external constraints. When planning your project, take external events into account, such as national holidays and team member vacations and sick leave. Leaving extra time in the schedule for these inevitable events up front can help minimize the impact to your project.

- Plan for risks and challenges. If you consider the risks that may occur, you may be able to find solutions for them in advance. For example, what if someone on your team gets sick or decides to quit? Are you able to replace them within the company? If not, can you hire an independent contractor? Come up with a list of people who may be able to join your team if one of your team members becomes unavailable. You can also assess risks by looking at historical data. Review your past projects and examine the challenges you faced. Then evaluate if similar challenges could occur in this project and prepare accordingly. We will discuss risk management at length later in this program.

- Calculate “float” in your schedule. Float, or slack, refers to the amount of time you can wait to begin a task before it impacts the project schedule and threatens the project outcome. Identifying float in your schedule can help with resource management, scheduling, and keeping your project on track. You will learn more about calculating float in a later course, when we discuss creating a critical path for your project tasks.

** Handling ambiguity

Ambiguity can be a big challenge in managing projects. Project managers often face ambiguity in goals, requirements, schedules, vision, or other areas related to the project. Your team will look to you to lead during times of ambiguity and change, and flexibility is especially important during these instances. Here are some different ways to help your team deal with ambiguity:

- Keep calm. In uncertain times, handling ambiguity with grace and poise will help inspire the members of your team to do the same.

- Express empathy. As a project manager, it is important to try to understand what your team is thinking and feeling, especially during times of ambiguity. Let your team members know that you care about the challenges they are facing and are there to support them.

- Communicate what you know clearly. Define the aspects of the project that are confirmed and will not change. This helps your team get a better sense of what to expect, regardless of any aspects of the project that are still unknown or changing.

- Make decisions and stick to them. Try not to second-guess your decisions in front of your team since this can lead to greater uncertainty. If you need to change course, clearly explain why you have chosen to do so to your team.

- Trust the expertise of your team. Increase clarity by having everyone on your team discuss what they already know or believe to be true about components of your project, such as what is involved in specific tasks or resources needed, based on their areas of expertise. Then, discuss what you still don’t know and brainstorm ways to gather more information.

* Strong organizational skills
- Use process to keep the project on track
- Make sure nothing gets lost or overlooked
- Knowledge of helpful tools and templates
- Familiarity with popular project management styles
  - Waterfall
  - Agile

 If you demonstrate that it is important for you, as a leader, to stay organized through efficient tracking and communications, your team will follow suit. One way to do this is by utilizing the abundance of organizational tools available, such as:

- Planning and scheduling software (templates, workflows, calendars)
- Collaboration tools (email, collaboration software, dashboards)
- Documentation (files, plans, spreadsheets)
- Quality assurance tools (evaluations, productivity trackers, reports)

You may need to experiment with different organizational approaches to determine what works best for you and your team

* Backlinks
- [[{{< ref "202109111201-project-managers" >}}][Project manager]]
- [[{{< ref "202109111153-project-management-tasks" >}}][Project manager tasks]]

