#+title: Scrum - roles - Product owner
#+date: 2021-09-29T19:15:00+1300
#+lastmod: 2021-09-29T19:15:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management Product_owner

A product owner is tasked with ensuring that the team is building the right product or service.

* Responsibilities
- Continuously maximizes the value of the product delivered by the Scrum Team (they own the [[{{< ref "202109131858-scrum" >}}][Product Backlog]]).
- Helps the Scrum Team understand why their work matters within the overall goal and mission
- Prioritize the Product Backlog to optimize delivery and value to the customer
- Ensure that the Product Backlog is transparent and visible to all
- Makes sure the product or service fulfils the customers' needs

* Traits
- Customer focused
- Decisive
- Flexible
- Optimistic and positive
- Available (e.g., to evaluate the iterations)
- Collaborative

* Product Owner vs. project manager

In traditional project management, scope management is the primary responsibility of the project manager. But in Scrum, the definition and management of product scope falls to the Product Owner. Conversely, the Product Owner isn’t responsible for team performancethey aren’t considered to be a manager. The project manager leads the project team to meet the project’s objectives and oversees tasks and progress.

There are also similarities between the Product Owner and project manager roles. For instance, both roles are tasked with stakeholder management. This means they both must practice and facilitate effective communication among team members and stakeholders.

Additionally, in many companies including Google the definition of product or solution scope is the responsibility of a separate role called a product manager. So, it is important when joining any new company to discover how that company approaches the area of product definition, requirements development, and user research to understand what they consider to be the domain of the project manager.


* Backlinks
- [[{{< ref "202109291903-scum-roles" >}}][Scum - Roles]]
- [[{{< ref "202109131858-scrum" >}}][Scrum]]
