#+title: Novices and experts
#+slug: novices-and-experts
#+date: 2004-09-23T09:13:00+12:00
#+lastmod: 2004-09-23T09:13:00+12:00
#+categories[]: Teaching
#+tags[]: Reflection
#+draft: False

It doesn't seem so long ago that I was [[{{< ref "on-becoming-a-critically-reflexive-practitioner" >}}][commenting]] on a recent edition of the [[https://www.sagepub.com/journal.aspx?pid=181][JoM]] (well actually it was a couple of months). Anyway, I'm just reading the latest edition 28(5), that is a special edition on /problem based learning/.

The editors' introduction, Citing Gijselaers and Woltjer, talks about the different ways of /knowing/ that seem to apply to novices and experts. They say:

#+BEGIN_QUOTE

... novices tend to organise their knowledge representations around the specifics of the problem, where as experts move to the more abstract level to see the general principles.

#+END_QUOTE

How true this rang with my own experience. In my classes /Business policy & strategy/ and /Management theory & practice/, (and to a lesser extent /Organisation & Management/), I constantly see students anchoring on the details of a problem and finding it hard to work with the more abstract concepts. My experience has been that the more abstract a concept is, the bigger a 'lever' it is, and the more universal it is. Alas, I've never found a satisfactory way to get this across, and I suppose it is to be expected as it is hard to shift one's anchor (there are some strong links here to sense-making etc).
