#+title: Harnessing the diversity of strategy-as-practice research
#+slug: harnessing-the-diversity-of-strategy-as-practice-research
#+date: 2021-10-15T14:24:03+13:00
#+lastmod: 2021-10-15T14:24:02+13:00
#+categories[]: Research
#+tags[]: Articles Strategy EGOS
#+draft: false

#+BEGIN_QUOTE

Kohtamäki, M., Whittington, R., Vaara, E., & Rabetino, R. (2021). Making connections: Harnessing the diversity of strategy-as-practice research. /International Journal of Management Reviews/. https://doi.org/10/gk9bfs

#+END_QUOTE

This paper 'takes stock' of where we are with strategy-as-practice research. Through a tidy systematic literature review they identify six central themes, that they label as: (1) praxis, (2) sensemaking, (3) discursive, (4) sociomaterial, (5) institutional, and (6) process. For each of these they consider the theme itself, the key theoretical influences, and the characteristic methodological approaches.

# more

All-in-all, it provides a well considered snapshot of where we are.

One thing that stood out for me was the comment that:

#+BEGIN_QUOTE

However, advocates of ‘flat ontologies’ are sceptical of the hierarchical layering of the world into micro and macro, warning against a narrow concern for the local and a curtailed understanding of broader connections (Gond et al., 2018; Latour, 2005). (p.11-12).

#+END_QUOTE

The work that I've been doing with [[ https://orcid.org/0000-0002-7709-7643][Eli]] [[linkedin.com/in/elisabethkrull][Krull]] using microfoundations would seem to hold a lot of promise in addressing that. Perhaps that should be the next paper we do.  I think this could be good as the authors of the paper explicitly mention microfoundations as one of the 'blindspots' of S-a-P.

Similarly:

#+BEGIN_QUOTE
Indeed, the ‘micro’ focus on empirical detail in much praxis-orientated SAP research has prompted accusations of ‘micro-isolationism’, a tendency to explain activities entirely in local terms (Seidl & Whittington, 2014). Micro-isolationism underplays the influences of practices that extend beyond the particular organization at hand (p. 12).
#+END_QUOTE

I had, sometime ago, theorised this problem away, but I never got around to publishing it (although I have talk with colleges at [[https://egos.org/][EGOS]] about it on a few occasions, including one on-line event last year. Maybe it's time to put /pen to paper/ on it.

Time to start writing.
