#+title: Site policies
#+date: 2011-01-04T11:10:00+12:00
#+lastmod: 2021-12-31T18:59:31+13:00
#+categories[]: SiteInfo
#+tags[]: SiteInfo
#+slug: site-policies
#+draft: False
#+weight: 300

Here you will find details of the this site's policies, /etc.,/ such as copyright, usage, privacy, and so on.

# more

* Copyright

The contents of this site are copyright 1996--{{< year >}} by Peter Smith. This site is licensed under a [Creative Commons License](https://creativecommons.org/licenses/by-nc-sa/1.0/).


* Usage policy

This system is monitored to ensure proper operation, to verify the functioning of applicable security features, and for other like purposes. Anyone using this system expressly consents to such monitoring and is advised that if such monitoring reveals evidence of possible criminal activity, system personnel may provide the evidence of such activity to law enforcement officials. Unauthorized attempts to upload or change information; to defeat or circumvent security features; or to utilize this system for other than its intended purposes are prohibited.

* Privacy
I take your privacy seriously. Please read the following to learn more about my privacy policy.

** What this Privacy Policy Covers

- This Privacy Policy covers my treatment of personally identifiable information that is collect when you are on the our site, and when you use my services.
- This policy does not apply to the practices of companies that I do not own or control, or to people that I do not employ or manage.

** Information Collection and Use

- I automatically receive and record information on my server logs from your browser including your IP address, cookie information and the page you requested.
- I use information for two general purposes: to customise the content you see, and to fulfil your requests for some products and services.

** Information Sharing and Disclosure

- I will not sell or rent your personally identifiable information to anyone.
- I will not send personally identifiable information about you to other companies or people unless:
- I have your consent to share the information;
- I need to share your information to provide the product or service you have requested;
- I respond to subpoenas, court orders or legal process; or
- I find that your actions on my web sites violate the any of my usage guidelines.

** Cookies

- I may set and access cookies on your computer for authentication purposes. These cookies are not used for tracking or profiling of any kind.
- I do not use web beacons.(Web pages may contain electronic images (called a "single-pixel GIF" or "web beacon") that allow a web site to count users who have visited that page or to access certain cookies)

** Changes to this Privacy Policy

- I may amend this policy from time to time. If I make any substantial changes in the way I use your personal information I will notify you by posting a prominent announcement on my pages.
