#+title: Foundations of strategy
#+slug: foundations-of-strategy
#+date: 2008-07-24T14:26:00+12:00
#+lastmod: 2008-07-24T14:26:00+12:00
#+categories[]: Teaching
#+tags[]: INTBUS202
#+draft: False

I am currently involved with a class known as INTBUS 202: Foundations of strategy. The course is intended to get people experienced in using the main tools of strategy; such as SWOT, Porter's five forces, and so on.

As I've noted [[{{< relref "20080611-judgement" >}}][elsewhere]], [[{{< relref "20080616-judgement-2" >}}][here]], and a bit [[{{< relref "20080624-self-review-of-intbus-202" >}}][here]], For me, one of the consequential overarching themes, is good judgement. Thus, participants in the course need to practice their judgement--and get feedback on it--so as to refine it.

One of the ways in which we ([[https://web.archive.org/web/20081014042125/https://staff.business.auckland.ac.nz/StaffDirectory/StaffProfile/tabid/542/upi/dtis001/Default.aspx][Dan Tisch]] and I) have students exercise their judgement is by getting them to "do" cases.

Today's case was Edward Marshall Boehm (that classic by "James Quinn"). I was really pleased at how the students handled the case and the quality of the contributions they made. I think after today's session they had a good understanding of the situation (the business, the industry, and the customers) facing the company. From that, I think they could then build a strong position as they addressed the somewhat conflicting goals presented by Edward and Helen.

What was nice was the people at the back of the class (often a quiet area) contributed. There was one woman who was able to bring in her own detailed knowledge of a similar situation here in New Zealand ([[https://www.morrisandjames.co.nz/][Morris and James]]). I hope others in the class will take there cue from her, and bring their 'expert' knowledge to bear when they can.
