#+title: Ambiguity
#+slug: ambiguity
#+date: 2004-03-29T21:03:00+12:00
#+lastmod: 2004-03-29T21:03:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301 Essays
#+draft: False

I found today's class very revealing. I was a little surprised to find out how difficult students are finding it to select a particular topic for their upcoming assignment this week. I spent some time after the formal part of the class, going around the four or five teams that stayed in the class room, talking about the assignment. There seems to be a lot of concern about choosing the /right/ topic and about find /theory/ to go with it. Some students are also daunted by the length of the assignment (2,500 words).

So here are my "consolidated" comments from those discussions today. My standard disclaimer at this point is that I hope this isn't used a formula for writing the assignment---it is really only to some approaches; I recall one stage I student, having been told by the tutor that the short (1000 word) assignment needed about five paragraphs, getting very upset because she could only work out what four of the paragraphs were about. Anyway, thinking about /the length of the assignment/, 2,500 words may seem like a lot of words, and it may be tempting to try and address several issues rather than just one (as a way to 'pad' the assignment). But my recommendation is that one issue is all that is needed.

Allowing one or two pages for a rich description of the situation (500 words), and some reflection on it (500 words) that is 1,000 words.

We're half way there. Bring some theory to bear on the situation--- well that has to be 250--500 words to show you know what you're talking about that all totals 1,250--1,500 words. Now, the introduction is likely to be a page long (250 words), and the conclusion is probably going to be two pages (500 words). That's another 750 words. Giving a grand total of 2,000--2,250 words. This is close enough, especially when the reference list is added in. Of course, I'm not sure I would structure it exactly that way, we all have our own style; I'd probably interleave the theory and the reflection---but I would probably write them separately first.

The next issue is /references/. Again, I reluctant to give a specific number, but 12 isn't unreasonable at stage II, but it is possible to do an excellent job with a third of that number. (It's also possible to do a bad job with 12.) Think about why you are using references---what is the point? They aren't there to please the reader. I've more to say about the references, and theory, later.

Choosing the /topic/ doesn't have to be hard. I think one of the easiest ways is to look back at your journals and see what seems important to you. I'll use one of [[https://www.thereflectivepractitioner.org/armi/archives/000274.html][Amit's journals]] as an example. In that entry he mentions the issue of power ((As I write this, I'm wondering how many essays on power we might now get.)). It would be fairly straight forward, I imagine, for Amit to write a longer more reflective description around that. Using his Organisation Behaviour textbook, he could readily identify two or three key authors (if he doesn't remember them from O), and their main works. He could read those, and immediately have refreshed his /existing knowledge/ about power. Add in a couple of other things that impact on power (maybe leadership---again taken from O), and he is done. The trick, if there is one, is to /build on what you know/ rather than learning something completely new ((There is some research that shows that learning something completely new for an assignment results in sub-optimal results.)) (unless, of course you are really interested in the specific issue).

Alternative, Amit could look at the issue of incrementalist approaches to strategy in his group. Drawing on the readings he is doing in another class, most of his theoretical background is complete---it's just a matter of making sense of his experiences, thus far, in those terms. i.e. Why does he value one over the other.

Of course, if something of particular interest to you, say mental maps, then do that. Both readings are good starting points and other can be found; I was pleased to hear two students talking about this, and one guided the other to a specific book that introduces the topic.
