#+title: Agile - Maximizing value-driven delivery
#+date: 2021-10-03T15:53:00+1300
#+lastmod: 2021-10-03T15:53:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

Value can mean different things for each customer based on what they expect the product to accomplish.

The number one Agile principle is to satisfy the customer by delivering valuable software. You can always replace the term software with the words product or solution for non-software related projects.

he term "value-driven delivery" means you and your team are focused on delivering a product of high value. Just because you deliver a product, that doesn't mean it's valuable

To ensure value-driven delivery:
1. Build the right thing
   - Understand what customers what (vis-a-vis their goals)
2. Build the thing right
   - The team only builds the requested or approved features
3. Run it right
   - You team has thought through how the user will interact with the product once it's delivered.
     - How do users get support?
     - How does the product add value to users long after they initially received it?
     - How do you make sure that new features and capabilities reach the existing users?


* Backlinks
- [[{{< ref "202109131850-agile-project-management" >}}][Agile project management]]
