#+title: Confronting the brutal truth
#+slug: confronting-the-brutal-truth
#+date: 2004-09-21T21:25:00+12:00
#+lastmod: 2004-09-21T21:25:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT302
#+draft: False

I think one of the most powerful readings of the course, /particular at this point in time/ (with the Commerce Commission, take-overs, insolvent firms, firms who are just realising that they might not win) is the one that is indicated in the Black Book (and in the Red Book?) by Jim Collins.

/Also see website on [[https://www.jimcollins.com][Confronting the brutal truth]]/

Alas, out of all the journals I've read today, only one person seems to have made use of it (in fact no one else even mentioned it). Which is strange, because last semester, I'm pretty sure that most people read it (and it was 'advertised' much the same way). Is it a matter of timing--were there just too many other things happening? Perhaps you could let me know for next time.

Anyway, I recommend the reading to you.

(Oh, BTW, everytime I read this article I'm reminded of the Vietnam veteran in [[https://www.imdb.com/title/tt0110912/][Pulp Fiction]])
