#+title: MMICC: McGill Management International Case Competition
#+slug: mmicc-mcgill-management-international-case-competition
#+date: 2006-07-29T11:34:00+12:00
#+lastmod: 2006-07-29T11:34:00+12:00
#+categories[]: Teaching
#+tags[]: CaseComps
#+draft: False

I received and email today from Baris to let me know he has a [[https://barisinhk.blogspot.com/][blog]]. Baris was one of the students from Maastricht University who competed in the [[https://www.mmicc.org/][MMICC]] in March this year.

His site lead me to [[https://manuelkoser.wordpress.com/2006/06/04/recap-mmicc-competition-in-montreal/#more-8][Manu's site]] who was also part of the Maastricht team.

The interesting thing about the Maastricht team was that many of the students were from Germany (rather than the Netherlands). That's a bit like our own Valeria Biurrun and Christian Zaum, who I think are also Germans who studied at Maastricht (and are now studying here at [[https://www.auckland.ac.nz/][Auckland]]).

They, Valeria and Christian were part of the team---with Lincoln Kyne, Pravin d'Lima, and Barbara Wilkinson---that competed in the [[https://web.archive.org/web/20061008041108/https://www.business.auckland.ac.nz/comwebcontent/index.cfm?fs=pgv&seminar_ID=1229&pageID=29][regional round]] of the BCG case competition. Alas, in this postgraduate compeition the two teams that were placed were from AUT and Canterbury.
