#+title: Frameworks revisited
#+slug: frameworks-revisited
#+date: 2005-06-09T10:58:00+12:00
#+lastmod: 2005-06-09T10:58:00+12:00
#+categories[]: Teaching
#+tags[]: MBA Strategy Frameworks
#+draft: False

I've just had my feedback from the MBA class /Integrating Strategy/.
Everyone one seems pretty happy except one person who gave me very low
ratings. I struggled to make sense of this disparity until I read the
comments that the student had made.

#+BEGIN_QUOTE

- Robust framework
- Some of the cases are so vague
- Lecturer should have a framework for each/most cases. Most of the time/cases we did not have any focus during class discussions.
- Business case competition organization was a complete disaster

#+END_QUOTE

I struck out the last comment, because that wasn't really about the course.

So, I'm left wondering why I didn't manage to connect with this person, and more importantly why they they didn't feel there was nearly enough frameworks for them. For my part, I thought I had given a structure to the discussion (which mirrored in many ways how I had tackled the case, and hence my framework). However, the approach I took was no better than some of the approaches the class took. I wonder if that person wanted something more like the [[{{< relref "20050525-frameworks" >}}][7s framework]]. Clearly, with this person I failed to get my message across---every case is unique, there is no simple framework (or small set of frameworks) that you can routinely apply to understanding either a case or, more realistically, a business. What is necessary is the analysis of each situation, determining the critical issue, and then some creativity to address the issue (okay, this is rough paraphrase of Kenichi Ohmae, 1982---but it probably isn't enough of a framework for this particular student).

Each firm is unique, and therefore the choice of model needs to be based on judgement and ones own strengths, rather than a ritualistic application of a standard solution.

Interestingly, I've been reviewing a book for Wiley this week, and that would be my main criticism---it tries to provide a /stock/ solution/approach for strategy. Such an approach is fine at an undergraduate level, but it doesn't stand up in the face of MBA students who have to make sense of such models in live settings (i.e., for practitioners).

So, I'll have to go back to the drawing board and see how I can get my message across more clearly and more convincingly.

P.S. I wonder why they didn't draw on the numerous models and frameworks from the Mintzberg et al (2003) text book if they wanted more frameworks.

* References

Mintzberg, H., Lampel, J., Quinn, J. B., & Ghoshal, S. (2003). /The strategy process: Concepts, contexts, cases/ (4th ed.). Upper Saddle River, NJ: Prentice-Hall.
