#+title: Boots and all
#+slug: boots-and-all
#+date: 2011-03-03T20:06:00+12:00
#+lastmod: 2011-03-03T20:06:00+12:00
#+categories[]: Teaching
#+tags[]: BUSINESS101
#+draft: False

This semester I'm teaching [[https://www.calendar.auckland.ac.nz/courses/prescriptions/business/business.html][BUSINESS 101 *aka* Business and enterprise 1]], here at [[https://www.auckland.ac.nz/][school]].

We have a [[https://web.archive.org/web/20081014045835/https://forums.isom.auckland.ac.nz/][discussion forum]] that is used within the course--but it may not work for no UoA people. Anyway, there is a section for introductions, and, having seen the first half-dozen entries, such as:

#+BEGIN_QUOTE

Woo 1st 1 to reply and find out bout this forum

#+END_QUOTE

and

#+BEGIN_QUOTE

second one

#+END_QUOTE

or

#+BEGIN_QUOTE

hey ya...

#+END_QUOTE

I waded in with a rather heavy handed comment with references to Erving Goffman's, /The presentation of self in everyday life/. Despite my own comment about, "having thought about it", I then put on my size 10 boots, and did a rather long introduction post about me.

Oops. As one of the students thoughtfully said:

#+BEGIN_QUOTE

you may have killed off some students who may now perceive you as somewhat uhh ... intimidating to approach in person.

#+END_QUOTE

And they a probably right, I can be intimidating---until one gets to know me. I can imagine that those who have known me for a while would agree, and as I reflect back on years of comments from students, I can see that this does come up from time to time.

And yet. And yet I did think about it. I do want the students to be think about what they write, and where they write it, and what it means. I want them to appreciate the fact that as they leave their "digital footprints" on the Internet, their trail will last much longer than many of them might realise. Furthermore, those footprints will be used by all kinds of people (say, recruiters).

I found an interesting post last week, regarding a student who had--over the years--made a series of anonymous (and innocuous) comments, postings, and so on through many websites. Some geek (maybe like me), had sifted the web and was able to work out the student's name, where they were studying, and a whole heap more personal information.

The wake we leave in the internet is pretty big.

There was a [[https://encrypted.google.com/url?sa=t&source=web&cd=5&ved=0CC4QFjAE&url=https%3A%2F%2Fpanopticlick.eff.org%2Fbrowser-uniqueness.pdf][posting last year]] on identifying people through their browsers and tracking them without the need for cookies. One only had to look at the "fingerprint" presented by the browser. I seem to recall that there were about 16 different pieces of information that could be used collectively to uniquely identify the "user". See [[https://www.freedom-to-tinker.com/blog/harlanyu/traceability-anonymous-online-comment][this]] too.

Only this week there was an article about [[https://radar.oreilly.com/2011/03/device-identification-bluecava.html][BlueCava]] that is commercialising such a system. They say that they can:

#+BEGIN_QUOTE

build information about each device [connected to the Internet]. One of the things we can tell about a device is if it's a shared computer being used by multiples users. We can also determine the specific level of use---whether it's a household computer in the kitchen with a handful of users or an Internet café computer with hundreds of users.

#+END_QUOTE

So these issues are top of my mind at the moment ...

... but it was boots and all.

* References

Goffman, E. (1971). /The presentation of self in everyday life/. Harmondsworth: Penguin.

