#+title: Back to the future
#+slug: back-to-the-future
#+date: 2006-03-06T21:42:00+12:00
#+lastmod: 2006-03-06T21:42:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301 Journalling
#+draft: False

Today, I had to stand-in for Darl (who had to go overseas rather unexpectedly).

It was nice being back in undergraduate teaching--it was a warm comfortable feel (for me at least). I wonder how they felt about it. The first couple of weeks of Mike's Bikes is often a shock to the system.

As prep, I re-read the readings for this week--a piece by Daudelin (1996) on Reflection for managers, and good ol' Kolb on his learning cycle. I also went back and looked at some of the excellent journals that were done by Amit, Kelly, SV and others. Ah, happy memories.

After class, I had a really interesting talk with one student (and a couple of others who largely just listened) about doing journals. I worry that I made her feel that I thought finance was dull--that isn't true--nor was it my intent. What I was trying to get at was the essence of good journalling (see also [[{{< ref "/blog/2004/03/08/journalling" >}}][journalling]]). I remember the hours I spent one year working with an engineering student trying help him "get" journalling.

The message I was trying to get across today, is that the successful firms (in Net Mike and often in business) are those where the management team have good processes in place. Whilst in the short-term wiz-kids might be able to produce extraordinary returns, a team with good processes will normally out perform them. So, the process consultants should add a lot of value to their teams if they use them well. I need to trust my instinct with teams; I had suspected that there would be difficulties, but I had not been able to articulate the logic behind my nagging doubt. What I realise now is how difficult it is for the new teams to shift their focus from one another (who are very immediate and present) to the consultants who are distant and remote (and often delayed). I think I need to find a better model than this next time. Perhaps the teams could form, and then they seek to make contact with the consultants later in the week.

Taking about instinct, I caught myself making some huge assumptive leaps with people and teams. That's a bit of a talent of mine, but sometimes I think I make leaps that are too large. Anyway, I'll find out in the coming weeks when I visit the teams (from time to time). I was talking to another student about this and about how quickly we make judgements. Any way I mentioned a book, and I thought others might find it interesting. It is:

#+BEGIN_QUOTE

Goffman, E. (1971). /The presentation of self in everyday life/. Harmondsworth: Penguin.

#+END_QUOTE

The author's blurb on the front say exactly what the book is about:

#+BEGIN_QUOTE

I shall consider the way in which the individual in everyday work situations presents himself and his activity to others, the ways in which he guides and controls the impression they form of him, and the kinds of things he may and may not do while sustaining his performance before them.

#+END_QUOTE

I also mentioned David Thomas's thesis:

#+BEGIN_QUOTE

Thomas, D. (2002). /Defining the oubliette: Simulated business practice/.

#+END_QUOTE

His piece on events as cues or clues is really quite good (and I think it was his original idea too).

There were a few questions about team agreements. I have talked about these once or twice before. At the beginning, journals are often hard to do. With practice (and dare I say) with age, we get better at reflection and hence better at journalling.

Oh, well, as often happens I have spent more time than I intended going on about MGMT 301. however, it is nice to be writing here again.
