#+title: Powerpoint and practice
#+slug: powerpoint-and-practice
#+date: 2012-05-15T14:16:00+12:00
#+lastmod: 2012-05-15T14:16:00+12:00
#+categories[]: Research
#+tags[]: Technology Practice
#+draft: False

Despite being "pervasive", technology is somewhat absent from organization studies literature (Orlikowski, 2007, p. 125). This is rather odd given the importance of technology in (modern) everyday life (Orlikowski, 2007). It's absence from the literature is also striking given that most conceptualisations of practice include an acknowledgement of the role of 'things' in practices. For example, that Reckwitz (2002, p. 249) describes practice as being:

#+BEGIN_QUOTE

a routinised type of behaviour which consist of several elements, interconnected to one another: forms of bodily activities, forms of mental activities, 'things' and their use, a background knowledge in the form of understanding, know-how, states of emotion and motivational knowledge.

#+END_QUOTE

Although there are a number of approaches to understanding how the material (technology) and the social are /constitutively entangled/ Orlikowski argues that it is necessary to "give up on treating the social and the material as distinct and largely independent spheres of organizational life" (p. 1438). Instead, in acknowledgement of that entanglement, she puts forward the ideas that pratices should be seen as 'sociomaterial'. Such an approach:

#+BEGIN_QUOTE

challenges the deeply taken-for-granted assumption that technology, work, and organizations should be conceptualized separately, and advances the view that there is an inherent inseparability between the technical and the social (Orlikowski, 2007, p. 434).

#+END_QUOTE

Indeed, Orlikowski proposes "that we recognize that all practices are always and everywhere sociomaterial, and that this sociomateriality is constitutive, shaping the contours and possibilities of everyday organizing" (p. 1444).

Within the community using strategy-as-practice, the work of Kaplan (2011) is cited as an exemplar because of its adoption of sociomateriality. In her paper, Kaplan considers both the dicusive and technological components evident in the use of PowerPoint ((As Kaplan points out, PowerPoint is a registered trademark of the Microsoft Corporation.)), or as she says "this study analyzes PowerPoint as part of the epistemic machinery that undergirds the knowledge production culture in one organization" (p. 342).

The research shows how the production of knowledge, through an 'epistemic machinery' "serve to stabilize and naturalize facts and define acceptable courses of action" (Kaplan, 2010, p. 343).

So, what is at stake in this paper, and is it truly an exemplar in its use of sociomateriality?

The answer to both questions is that Kaplan clearly demonstrates the entanglement of the social and the material, and in doing so she demonstrates how 'things' can be a (necessary) component of a practice. Her main finding is that strategy practices are about collaboration and cartography ((For Kaplan, cartography is the drawing of boundaries as to what is in- and out-of-scope)).

What is unclear to me is the difference between the creation/production of knowledge--by epistemic machinery--versus the creation of discourse. Are these two thing really different?

* References

Kaplan, S. (2011). Strategy and Powerpoint: An inquiry into the epistemic culture and machinery of strategy making. /Organization Science/, /22/(2), 320--346. doi:[10.1287/orsc.1100.0531]

Orlikowski, W. J. (2010). The sociomateriality of organisational life: Considering technology in management research. /Cambridge Journal of Economics/, /34/(1), 125--141. doi:[10.1093/cje/bep058]

Reckwitz, A. (2002). Toward a theory of social practices: A development in culturalist theorizing. /European Journal of Social Theory/, /5/(2), 243--263. doi:[10.1177/13684310222225432]
