#+title: Recording on the iPod
#+slug: recording-on-the-ipod
#+date: 2005-03-22T20:59:00+12:00
#+lastmod: 2005-03-22T20:59:00+12:00
#+categories[]: Research
#+tags[]: iPod Recording
#+draft: False

A few months ago, I brought a [[https://www.apple.com/ipodphoto/][Photo iPod]]. As I was buying it, I noticed the [[https://www.griffintechnology.com/products/italk/][iTalk]] recorder adaptor and thought "How cool, I can use the iPod as a dictation machine too". For dictating notes and memos, I've found the iTalk to offer pretty good quality recording. Somewhat belatedly I found out that the iPod is constrained to a sampling rate of 8Khz 16 bit mono .WAV files. Nevertheless, the it worked fine for the odd bit of dictating.

As it happens, I have to do a fair number of interviews and observing meetings for my research on strategising. Would the iPod be any good at that. A few told that the iPod would record for about three hours off its internal battery, but what about the sound quality. Well, to be blunt it was a little too quiet, and the microphone wasn't very omni-directional.

The iTalk will hand an external microphone, and so, a little bit of research later (probably not enough) and I had a [[https://www.crownaudio.com/][Crown]] [[https://www.crownaudio.com/mic_web/soundgrabber.htm][Sound Grabber II]] microphone in my hands.

The result---terrible. The sound level was so low as to be useless. I emailed the microphone forum at Crown and got some good suggestions, e.g. Being a mono microphone it is TS (tip and sleeve), alas many products expect TRS (tip-ring-sleeve), with power appearing on the ring. So, the TS of the microphone could be shorting out the ring of the iPod (I'll never know is this is true, because there are no detailed specifications for the iTalk on the net). On their (Crown's) advice I also tried using a 6 volt battery instead of the 1.5 volt AAA that is normally used. Still not enough sound level.

Somewhere, in reading about recording interviews for research purposes, I cam across a site (whose details I can't find again), that suggested that a company in the UK, [[https://www.felmicamps.co.uk/][FEL Communications]], did a range of microphone pre-amplifies that were pretty good---"Did I need a pre-amp?", I wondered.

Anyway, I email FEL explaining my problem. They responded that they didn't know for certain if any of their products (and in particular their [[https://www.felmicamps.co.uk/products/felmp3preamp.html][MP3 amplifier]]) would do the job. But, kindly they said, order the product, and if it doesn't work you can return it for a full refund (including the air mail). What did I have to lose?

Four days later, I've been doing some tests. The level is excellent --- before I was at -36 dB, now it's up to -3dB (as shown by CoolEdit on my laptop). The results on the iPod are excellent. In one test, it even picked up me talking in another room!

So, thanks to Bruce at Crown for his help, and /many thanks/ to /Nick Roast/ at FEL for his help. I can now record my interviews with confidence that I'll be able to hear what was said.

This isn't quite the end of the story. One idea I had was to use something like DragonDictate (aka [[https://www.scansoft.com/naturallyspeaking/][Dragon Naturally Speaking]]) to transcribe the files. Alas, whilst Dragon will transcribe files, it won't do the 8Khz files produced by the iPod and (tucked away in the documentation) there is the admonishment that it can only hand single speakers. No doubt someone will suggest that I should convert the 8Khnz signal to a higher level (e.g. 22KHz). Unfortunately, if the quality isn't there to begin with, it is still low quality (albeit at 22Khz).
