#+title: Value roadmap
#+date: 2021-10-03T16:20:00+1300
#+lastmod: 2021-10-03T16:20:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

A value roadmap maps out a product idea and the strategy for how to deliver it.

- An Agile way of mapping out the product development process
- Can be used for all types of business
- Is a guide that demonstrates
  + Where to go
  + How to get there
  + What to accomplish along the way
- Helps the team explain the vision of the product
- Used to identify important milestones


A typical value roadmap has three components: a product vision, a product roadmap, and release plans.

* Product vision
- What the product is
- How it supports the customer's business strategy
- Who will use it

* Product roadmap
Created by the product owner
- A high-level view of the expected product and its requirements
- Estimated schedule for reaching milestones

It is key to ensure the team is building the right thing.

* Release plans
The Product Owner and Project Manager work together to develop these plans.

Product releases occur when the team has developed a basic working version of a given feature or requirement. A release plan includes the approximate date when the team is expected to release and deliver certain features to the customer or user.

A release plan contains:
- Release goal,  which is an overall business goal for the features you plan to include in the release
- List of backlog items required for that release goal
- Other relevant dates that impact a release

A release plan is a living document. It might change if:
- Team velocity changes
- Change in the product scope
- Improving the understanding of how much effort in needed to build certain features

* Backlinks
- [[{{< ref "202110031553-agile-maximizing-value-driven-delivery" >}}][Agile - Maximizing value-driven delivery]]
- [[{{< ref "202110031626-product-roadmap" >}}][Product roadmap]]
