#+title: Book review and response
#+slug: book-review-and-response
#+date: 2004-04-15T07:40:00+12:00
#+lastmod: 2004-04-15T07:40:00+12:00
#+categories[]: Research
#+tags[]: Structure
#+draft: False

Getting back to the series of articles I'm reading that use Ranson, Greenwood & & Hinings article "The structuring of organizational structures", today I've chosen a book review and response. Review is by Kenneth Starkey, and is of Andrew Pettigrew's (now well know) book /The awakening giant: Continuity and change at ICI/. Starkey's review and Pettigrew's response appeared in the /Journal of Management Studies, 24/(4) a couple of years after the books publication---the book was published in 1985, the review in 1987. I think the gap in time between the two events is a measure of the amount of time it takes to get an article (even a book review) published.  (Some of my own reviews have taken over two years from when the final version was submitted, to when they appeared in print---the wheels of academic publication grind exceeding slowly and maybe not all that finely.)

Any back to the book review and response. What stands out for me is Starkey's "iron fist in a velvet glove' approach. He starts off by saying how good and important the book is (that's the first page) then spends six pages explaining why Pettigrew got it wrong (for example, he did pay enough attention to Starkey's own work!).  Anyway, Pettigrew is not shy in defending his work. In a four part defence "exposing some of the confusions and inconsistencies in Starkey's critical review" (p. 420), and at one stage challenging Starkey over Starkey's own work; "where is this growing body of evidence?" (p. 421).

In many ways I found Pettigrew's response to Starkey more illuminating about the book, than Starkey's own review of the book.  Nevertheless, what stands out for me is the way in which both authors promote their own work and how they both call on the "gods' of Freeman, March & Olsen, Chandler, Giddens and Minitzberg (oh, and of course Ranson, Greenwood & Hinings); but yet they seem to talk past one another. It reminds me of a documentary about Michael Porter where his critics (and him) don't actually hear one another---the just keep pushing their own "party line'. This is one of the great problems of management literature (and perhaps more generally, sociological literature). It is too easy to come at things from a different perspective that prevents one from understanding the-other.
