#+title: Psychodrama
#+slug: psychodrama
#+date: 2003-03-28T09:36:00+12:00
#+lastmod: 2003-03-28T09:36:00+12:00
#+categories[]: Home
#+tags[]: Psychodrama Moreno
#+draft: False

Well I have signed up for an introductory course (well they call it the /Core curriculum/)in [[https://www.psychodrama.org.nz][psychodrama]].  It will be interesting to see what happens.

I know relatively little about psychodrama, other than what I've [[https://www.users.on.net/\~iam/Pdis.html)][read]] and the fact that Judith McMorland has demonstrated it a couple of times.

Any way the first class is to night, and continues tomorrow and Sunday. There are four /experiential/ weekends like this through out the year, plus a number of evening sessions.

There should be nine of us on the course (myself included), and out of the nine the majority (7) are women. I wonder why that might be.

Really, I should spend sometime reading up on J. L. Moreno, who seems to be the founder of the method. Surprisingly though, a quick search of the Internet throws up nothing of use---there are just too many Morenos out their.

