#+title: Waterfall project management
#+date: 2021-09-13T18:38:00+1300
#+lastmod: 2021-09-13T18:38:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management Waterfall Project_methodology

Waterfall project management is one of the most popular [[{{< ref "202109121956-project-management-methodology" >}}][project management methodologies]].

- Created in the 1970s and is based on a [[{{< ref "202109121956-project-management-methodology" >}}][linear approach]].

- Based on a sequential order of phases, that are completed one at a time.

- Initially used in the physical disciplines like engineering, then move on to software development

- It still used a lot in engineering fields including product feature design and application (app) design.

- There are many flavours of waterfall project management, but they are all based on an ordered sequence of steps.

- It is still based on the normal life cycle of a project, namely: [[{{< ref "202109121327-project-life-cycle" >}}][initiating, planning, executing, and closing]].

* Why use a Waterfall approach to project management?
- When the phases of the project are clearly defined, or
- When there are tasks to complete before another can begin, or
- When changes to the project are very expensive to implement once it's started.

For example, if you are catering an event for a client on a very tight budget you might want to use Waterfall methodology

A well-thought-out traditional approach to managing a project can help you reach your desired outcome with as little pain as possible during the project implementation.

By spending extra effort thinking through the entire project upfront, you'll set yourself up for success. In an ideal world, following this approach will help you identify the right people and tasks, plan accordingly to avoid any hiccups along the way, create room for documenting your plans and progress, and enable you to hit that goal.

However, this doesn't suit every project. In such cases, an [[{{< ref "202109131850-agile-project-management" >}}][agile]] methodology might be more suitable.

* Summary
Waterfall is a traditional methodology in which tasks and phases are completed in a linear, sequential manner, and each stage of the project must be completed before the next begins. The project manager is responsible for prioritizing and assigning tasks to team members. In Waterfall, the criteria used to measure quality is clearly defined at the beginning of the project.
