#+title: Journaling
#+slug: journaling
#+date: 2004-03-08T19:54:00+12:00
#+lastmod: 2004-03-08T19:54:00+12:00
#+categories[]: Teaching
#+tags[]: Journaling MGMT301
#+draft: False

As we ([[{{< relref "20040308-dpe" >}}][DPE]]) know it is hard to journal well. It doesn't come naturally to every. So, I thought it would be useful to do some of my own journaling for everyone, especially in the [[{{< relref "20040308-mgmt-301" >}}][class]], to see. My hope is that it will help the students to develop their own practice of journaling.

By practice, I should say that my idea isn't for them to copy what I'm doing in some version of /monkey see, monkey do/ , but rather it is to help them to develop their own practice in the sense of bricolage (As an aside, the notion of /bricolage/ is very important to me in my own research and study of [[https://www.strategy-as-practice.org/][strategy-as-practice]].)

In the following reflections, I shall refer to /me/ or /I/ a lot.

That doesn't mean I am claiming credit for the ideas, events, etc. Rather, I am honouring that these thoughts are mine, and that it would be unfair of me to assume I know what the others of DPE think about this.

My first hint for those new to journaling is /Writing a journal isn't the same as writing down one's stream of consciousness/. I've spent some time thinking about what I want to say. So far, I spent about 20 minutes, as I walked to my car, thinking about what stood out for me in today's class. I spent the drive home, another 30 minutes, thinking in more detail about the topics I would cover. And in actually writing (pen to paper, or hand to keyboard) it has taken me about 40 minutes so far. That's not to say I'm crafting every word, and worrying about every punctuation mark; I'm not. I imagine this journal is rife with typos, etc. But, I am taking care of what I'm thinking, and that takes time.

I was pretty pleased with the choice of music for today's class. /Duelling banjos/ from [[https://www.imdb.com/title/tt0068473/][Deliverance]] hinted at many of the themes I wanted to explore in the presentation of today's topic of teams. Note here, I was concerned with /how/ we would present--the process of the delivery, and the music was to accompany that, rather than the /content/ of class. There has been a lot written on teams (today's topic), and the question in my mind was, How do I get the class interested in knowing more about teams? Clearly, I can't tell them everything that is known about teams--there just isn't enough time (and it would be pretty inefficient). So, the aim was to get them engaged with the topic, to the extent that they would read some of the recommended readings.

Overall, I was pretty pleased with all the class. However, there were two parts that didn't work well for me. Firstly, I was rather overwhelmed by the number of students who hadn't hit $20 SHV (Shareholder Value. This is a simple measure of peoples' proficiency with the simulation). Consequently, I'm not sure how much those people who had problems with their SHV, actually 'got' what I was saying in the computer lab. Based on the results from other years, perhaps I could have predicted this; but then again, the lab session was added at the last moment--next time we can consider structuring it differently --maybe a prepared work sheet, or a structured discussion on what the students found that works. Still thinking about the SHV, I was surprised by the number of people who got just over the required $20, e.g. $21.60 or even $20.22, and stopped. I hindsight I can understand why this would be, and, I if it had been me, I would have stopped like that too.

The other thing that didn't work well for me was sending the groups away for Team Time (Team Time is a period when the students are schedule to be working together, but independently. Thus, we can always be relatively sure that teams can (and do) meet). This was a flow on the problems with the lab--we didn't get back in time, and, in order to vacate the classroom on time, we were somewhat brief in our instructions for Team Time.

The thing I was most happy with was the dialogue with Darl during the first hour. I think that flowed well and the students generally seemed engaged. There was enough structure there to ensure we covered the territory we wanted to; but not so much that it seemed forced.

I'm really looking forward to next week's class to see how that plays out.

Well, I've been writing this for several hours now. So I think I will draw it too a-close.
