#+title: Animation Now
#+slug: animation-now
#+date: 2006-07-16T16:05:00+12:00
#+lastmod: 2006-07-16T16:05:00+12:00
#+categories[]: Arts
#+tags[]: Movies
#+draft: False

The first film of the [[https://www.nzff.telecom.co.nz/][film festival]] (for me any way) was /Animation Now/; a collection of "animated gems"[fn:1]. I agree with someone else who was there, who said it wasn't as good as last year.

Nevertheless, there was some good material. The best of the collection were:

- /McLaren's Negatives/: I liked this as it gave me a better insight into how some forms of animation are done
- /Son of Satan/: I bet those who confused this with /Animation for Kids/ regretted it. An interesting exposition of violence.
- /The True Story of Sawney Beane/: A lovely Scottish tail of cannibals.
- /At the Quinte Hotel/: After all, /I am a sensitive man/ as Al Purdy puts it.

Although judging by the applause, the audience also liked /In My Day/ The film /The Man of the Hour/ started of really well and then lost the plot (well, lost me anyway).

All in all, well worth seeing.

[fn:1] Their words not mine.
