#+title: A few new projects
#+slug: a-few-new-projects
#+date: 2006-04-08T11:53:00+12:00
#+lastmod: 2006-04-08T11:53:00+12:00
#+categories[]: Teaching
#+tags[]: MBA Audacity Wiki
#+draft: False

I'm working on a few projects at the moment.

Firstly, I'm setting up a couple of [[https://en.wikipedia.org/wiki/Wiki][Wikis]]. One I'll use to create a resource for students doing the [[https://www.mbanotebook.ac.nz/index.php/Main_Page][MBA Research Project]].

The other will provide an overall guide [[https://www.mbanotebook.ac.nz/][The Auckland MBA™]] programme.

Secondly, I'm playing around with podcasts. I think it might be a useful way to promote the MBA programme to potential students, and keep existing students informed of what is happening.

Both the wiki and the podcasts have fairly steep learning curves. Besides get the necessary software set up ([[https://moinmoin.wikiwikiweb.de/][MoinMoin]] for the wiki, and [[https://audacity.sourceforge.net/][Audacity]] for recording and editing the podcasts) the issues of how to structure both are quite interesting. For the Wiki the issue is one of loose-tight structure; after all the site can be edited and structured by almost anyone. For the podcast, whilst there are some fairly specific "rules" on the format, selecting and creating the content is tricky (given the structure).
