#+title: Dead drive
#+slug: dead-drive
#+date: 2020-09-27T12:00:00+13:00
#+lastmod: 2020-09-27T12:00:00+13:00
#+categories[]: Tech
#+tags[]: Hardware NAS
#+draft: False

** They're dead, Dave

I woke-up to find an email from my NAS saying:

#+BEGIN_QUOTE

Dear user,

Storage pool 1 (SHR, ext4) on P3000 has degraded (total number of drives: 3; number of active drives: 2).

Information of the drives in abnormal status is shown below:
Drive 10
Model: ST4000DM004-2CV104
Serial number: WFN2XYEG

Several reasons may result in storage pool degradation. Please go to Storage Manager > Storage Pool to understand the cause of degradation, or refer to [[https://www.synology.com/knowledgebase/DSM/help/DSM/StorageManager/storage_pool_repair][this article]] to learn how to repair the storage pool.

#+END_QUOTE

*Oops*

That drive isn't even six months old.

When I check in the /Storage Manager/, it says that it has crash. Oh dear.

Off to PB Tech for a replacement, not swap the drive, add the drive back into the storage pool and ... time passes (12 hours or so) ... the new drive is integrated into the pool, and it all works. Pretty seamless and painless (except having to go out to get a new drive).

I love redundancy.
