#+title: The copycat syndrome: Plagiarists at work
#+slug: the-copycat-syndrome-plagiarists-at-work
#+date: 2007-01-14T17:03:00+12:00
#+lastmod: 2007-01-14T17:03:00+12:00
#+categories[]: Teaching
#+tags[]: Plagiarism
#+draft: False

On the [[https://www.jiscpas.ac.uk/][JISC Plagiarism]] mailing list, I came across an [[https://www.slate.com/id/2157435/][interesting article]] at [[https://www.slate.com/][Slate]] by Meghan O'Rourke.

Not wishing to step on anyone's copyright, I haven't reproduced the article here; rather here is a quote from the opening of the article to get you interested enough to visit Slate.

#+BEGIN_QUOTE

We may know pornography when we see it, but the same can't be said of plagiarism. Ever since it was revealed last month that several passages in Ian McEwan's Atonement closely resemble sections of Lucilla Andrews' World War I memoir, No Time For Romance, critics have debated whether the similarities constitute wholesale "plagiarism" or mere literary "discourtesy." The one thing everyone does agree on, apparently, is the necessity of policing plagiarism, whatever it may be. A partial list of authors recently accused (rightly or wrongly) includes Dan Brown, Yann Martel, Kaavya Viswanathan, J.K. Rowling, playwright Bryony Lavery, Doris Kearns Goodwin, Stephen Ambrose, and Alan Dershowitz. In an op-ed in early 2003, Condoleezza Rice even cited Saddam Hussein's habitual plagiarism as evidence of the leader's fundamental treachery.

#+END_QUOTE

Anyway, the [[https://www.slate.com/id/2157435/][article]] is a good read; I commend it to you.
