#+title: Some might call it andragogy
#+slug: some-might-call-it-androgogy
#+date: 2014-03-24T20:07:00+12:00
#+lastmod: 2014-03-24T20:07:00+12:00
#+categories[]: Teaching
#+tags[]: ACADPRAC701 Androgogy pedagogy
#+draft: False

I already have an espoused [[https://www.petersmith.org/portfolio/3-philosophy/][Teaching Philosophy]] that I make available to all, but for this activity in ACADPRAC 701, I have sought to set it aside and begin from scratch.

The starting point for any articulation regarding teaching begins with a notion of what it means to learn. I have noted [[{{< ref "defining-learning" >}}][elsewhere]] some of my current thoughts on teaching, however, on further reflection I would amend that statement to say:

#+BEGIN_QUOTE

Learning is the ability to use knowledge after a significant period of disuse

and

It is the ability to use the knowledge to solve problems in a context different (if only slightly) from the context in which the information was originally learnt

#+END_QUOTE

Being something of a practice theorist (see, for example, Schatzki, Knorr Cetina, & von Savigny, 2001; Schatzki, 2002; Turner, 1994, 2002) and one for whom practice is an ontological/epistemological position (Orlikowski, 2003), I believe that knowledge is socially constructed and somewhat field/domain specific. Knowledge is typically what others--and in particular insiders (Unruh, 1979, 1980)--regard as knowledge and that any knowledge is somewhat contested. Thus, I accept an embrace the idea that what is seen as knowledge in, say, organisation studies would not necessarily be accepted as such in medicine. For example, the characteristics of a /good/ meta-analysis are different between those two fields. And yet, meta-analysis is used effectively in both domains to solve problems. In other words, knowledge is situated (Suchman, 1988).

None of this would be controversial within my discipline/sub-discipline other than, perhaps, some novelty in that I transfer my research interests into my teaching interests. In discussions with colleagues, there are few whose research interest underpin /how/ they teach rather than /what/ (content) they teach; an example to the contrary would be someone like Joe Realin (2009, 2011) who also uses the practice perspective.

My next point of departure is that I focus on the teaching of adults--/e.g/., say, andragogy--rather than pedagogy /per se/; for me pedagogy (the teaching of children) has a different focus and explanations ... and here we can loop back to the notion that knowledge is field specific. The needs and abilities of adults, and the tactics and strategies to foster their learning are often different to those that are efficacious with children. Of course, I am cognisant that some of those I teach may be in transition.

Having said all of that, I do seek to treat my students as adults. I do tend to explain what I am trying to achieve with them (as in, in conjunction with them). To that end, I will often make my teaching strategies and tactics explicit to them.

To foster learning, my teaching frequently involves a significant amount of repetition ... doing similar tasks over again. For example, when I teach using the case method, we--the class--will do cases every week for that learning to become deeply embedded and to allow for higher levels of proficiency in 'doing' cases. Likewise, when using simulations there is repeated engagement/use with the simulation, for the same reasons.

Generally, I think my teaching is both theory informed. What is less evident from this discussion is how my own experiences--both as a teacher and as a student, and as one who has moved from being a stranger (Unruh, 1979, 1980) a regular within my own field--have also shaped my thinking on teaching. That, perhaps, is a reflection for another day; suffice to say that those experiences are congruent with my theoretical orientation.

* References

Orlikowski, W. J. (2003). /Using a practice lens: Challenges and opportunities/. Presented at the Strategy as Practice Workshop, Glasgow University.

Raelin, J. A. (2009). The practice turn-away: Forty years of spoon-feeding in management education. /Management Learning, 40/(4), 401--410. doi:10.1177/1350507609335850

Raelin, J. A. (2011). From leadership-as-practice to leaderful practice. /Leadership/, /7/(2), 195--211. doi:10.1177/1742715010394808

Schatzki, T. R. (2002). /The site of the social: A philosophical account of the constitution of social life and change/. University Park: PA: Pennsylvania State University Press.

Schatzki, T. R., Knorr Cetina, K., & von Savigny, E. (2001). /The practice turn in contemporary theory/. New York: Routledge. Retrieved from https://site.ebrary.com.ezproxy.auckland.ac.nz/lib/auckland/docDetail.action?docID=10095826

Suchman, L. A. (1988). Representing practice in cognitive science. /Human Studies/, /11/(2-3), 305--325. doi:10.1007/BF00177307

Turner, S. P. (1994). /The social theory of practices: Tradition, tacit knowledge and presuppositions/. Cambridge: Polity Press.

Turner, S. P. (2002). /Brains/practices/relativism: Social theory after cognitive science/. Chicago: University of Chicago Press.

Unruh, D. R. (1979). Characteristics and types of participation in social worlds. /Symbolic Interaction/, /2/(2), 115--130. doi:10.1525/si.1979.2.2.115

Unruh, D. R. (1980). The nature of social worlds. /The Pacific Sociological Review/, /23/(3), 271--296.
