#+title: Cholesterol too low?
#+date: 2004-07-30T09:41:00+12:00
#+lastmod: 2004-07-30T09:41:00+12:00
#+categories[]: Home
#+tags[]: Fitness
#+slug: cholesterol-too-low
#+draft: False

It's been three months since I last saw the doctor, so it was time for a check up today.

My blood pressure is still high, but the Doc thinks its the "white coat effect'. I only have to see a Doctor, and that drives up my blood peruse. I get lower readings during my monthly checks with the nurse.

It seems I've lost 8Kg in the last three months. Thats good news. The walking is paying off. Now I think I'll start going to the gym so I don't "plateau' off.

Of course, this improvement wouldn't have happened with out the support of Lisa, my darling wife.

We had an interesting conversation about my cholesterol level. Currently, it is 3.4 mmol/l (and a good figure is less than 5). Whilst my LDL cholesterol is good (2.0 mmol/l and they like it below 3.0[fn::Actually, he said for heart attack patients with bad arteries (not me really), they like it to below 2.5 mmol/l so I feel pretty good about it overall.]), my HDL is only 1.0 mmol/l. Alas, they like it /over/ 1. So, I have to start eating more oily fish and exercise some more---so I'm double sure to go to the gym.

Just for completeness, I'll say that my fasting triglyceride level is 0.7 mmol/l (less than 2.0---good), and my total cholesterol to HDL ratio is 3.4 (and they like it below 4.5). So, generally, it sounds good. I had hope he might have reduced the Inhibace, but no, not yet. In fact he's put me on folic acid too. I'll have to do some [[https://www.qmw.ac.uk/poffice/nr221102.shtml][reading]] on that.


