#+title: What makes an incident 'critical'?
#+slug: what-makes-an-incident-critical
#+date: 2004-06-02T15:48:00+12:00
#+lastmod: 2004-06-02T15:48:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301 Critical-incident
#+draft: False

Reflecting back on the assignments I have marked so far, there are some interesting interpretations of the /critical/ part of /critical incidents/. The on-line [[https://web.archive.org/web/20040701014413/https://www.m-w.com/home.htm][Merriam-Webster dictionary]] says:

#+BEGIN_QUOTE

of, relating to, or being a turning point or specially important juncture : as (1) : relating to or being the stage of a disease at which an abrupt change for better or worse may be expected; also : being or relating to an illness or condition involving danger of death And it is in this type of sense that many students have interpreted the word critical. However, in academic work we often use words in very particular/specific ways, and this is a good example of that (sometimes subtle) difference.

#+END_QUOTE

Flanagan, in talking about critical incidents, is very precise in what he means by the word 'critical'. As was said in an earlier [[{{< ref "critical-incidents-and-maps" >}}][post]] (which was based on Twelker citing Flanagan):

#+BEGIN_QUOTE

In order for the incident to be considered critical, it "must occur in a situation where the purpose or intent of the act seems fairly clear to the observer and where its consequences are sufficiently definite to leave little doubt concerning its effects."

#+END_QUOTE

Now this is a very different meaning to the word critical than is in common or garden usage as given by the dictionary above Flanagan does not use the word critical to man "a specially important junction". By critical he means that these is a clear link between what was intended to be done and what actually happened are pretty clear. There is little ambiguity between that action took place, and there was a consequence. In our complex world often we do things and there isn't a clear link between the action and the consequence. For example, each day I check my email, but what (if any) is the link to the level of my research output? Thus, checking my email is not critical (in Flanagan's sense) with regard to my research output.

However, sometimes actions and consequences are much more clearly linked. E.g. "We met with the intention to talk about the future of the firm, and by the end of the meeting we had written a new strategy document", or "we met to address the issue of the declining number distribution outlets--subsequently we increased the margin to the retailers, but in two rollovers this had little effect". There is a deliberate action and a consequence.

Thus, in the last example, the questions/reflection/analysis/etc would revolve around understanding how it came to pass that the decision was made in increase the retailers' margin--even though it was ineffective. (Oh, well. I'm aware that many of these postings are a desire on my part to take a break from marking. So, back to the salt mine, I guess).

Talking of Flanagan. I wonder how many people actually bothered to track the article down and read it before they casually inserted a reference to him (when all they did was read it on the web-here)?
