#+title: CEO Summit
#+slug: ceo-summit
#+date: 2004-08-10T20:46:00+12:00
#+lastmod: 2004-08-10T20:46:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301 Mikesbikes
#+draft: False

The first (of many?) summits was held with the CEOs of the various companies that inhabit the [[https://www.smartsims.com][Mike's Bikes]] world. A little over half the CEOs attended, and all the regions were represented.

Listening to them (I don't always do the talking), what struck me was how similar the problems they face, viz:

- Not being clear on what their own role was; however, some people were very clear on this.
- How to manage/support team members who are having problems; either because they don't understand their role, or because they aren't "putting in the work".
- What to do about an uncertain future.

There are enough resources (smart people) making up the CEOs that they can probably deal with the first two types of problems themselves, and I was very impressed that some of the CEOs intend to keep on meeting. As I said at the summit, it is normal-in the outside world-for CEOs to meet and discuss the issues that they are facing; it's also normal for other professionals to meet and talk about their shared problems.

The third issue is somewhat more difficult, because I think the people's ability to tolerate (maybe even enjoy) ambiguity (aka an uncertain future) is a characteristic of ones personality and therefore its harder for people to /manage/ it. The most frequent technique that people (in this class and outside) employed to deal with this issue is to seek more information. At the /uncertainty of the moment/ is "How will the teams be rearranged after the last practice roll-over?"

Let's see, whilst not [[{{< relref "20040810-mece" >}}][MECE]] some of the ways that students have suggested might be used are:

- /Let's see if you really did learn anything, or were you just lucky/: No change; everything is reset to just the way it was at the start, same regions, same competitors.
- /Equity and equality/. Teams are grouped based on their rank after the last roll-over.
- /The forces of chaos/: Some process of random allocation.
- /The brave new world/: New/more competitors, new regions.
- /You made your bed now lay in it/: The simulation just continues the way it is, those who have an advantage still have an advantage.
- /Just when you thought it was safe to go back in the water/: Something innocuous reset (maybe the forces of chaos) but there some kind of big change later on.

I wonder what the class would like to happen (and why)? What would be a rational approach, that also had some logical consistency with the real world?

Frankly, I've been a little caught out by the lengths some people are going to in order to "work out" what might happen. I know of one CF who has tracked down four or five past 'winners' to see what they did and what DPE (or the equivalent) did. I suspect that whatever I say at this junction will make no difference at all to the rumour mill.

As the [[https://www.dorisday.net/The_Man_Who_Knew_Too_Much/Que_Sera_Sera/que_sera_sera.htm][song]] goes, "Que sera sera. What ever will be, will be. The future's not ours to see. Que sera, sera."
