#+title: Alt-MBA
#+slug: alt-mba
#+date: 2009-12-24T16:13:00+12:00
#+lastmod: 2009-12-24T16:13:00+12:00
#+categories[]: Teaching
#+tags[]: MBA
#+draft: False

The [[https://www.alt-mba.com/][Alt-MBA]] is:

#+BEGIN_QUOTE

The Alt-MBA program is a group of motivated and connected learners, leapers and agents of change who want to build better brains with other likeminded people from around the world. The group was originally inspired by the Alternative MBA program created by Seth Godin in December 2008.

A handful of applicants that were not selected to work with him in New York decided to launch their own version of the program. Two of the founding members put the idea out to the pool of unaccepted applicants on December 15th and since that time the group has grown to 100+ members (including Seth Godin).

#+END_QUOTE

Having read this, and [[https://www.squidoo.com/Alternative-MBA][Seth Godin's original offer]] I am thinking "I wonder how it might work here in New Zealand".

Recently there has been much debate on the future role of Business School. In the face of rise of corporate universities (Blass, 2005) and consulting firms doing high quality research (e.g. MckKinsey & Co), it is easy to imagine that Business Schools are under threat (Tinker, 2004). As typified by Mintzberg (2003) the problem arises because of the seeming lack of relevance in what Business Schools typically do.

In the face of a "I want it now" generation, something that sounds like an MBA and yet only takes 6 months, with credible mentors must be attractive (to some niche in the market). Much of what has been written has been directed at MBA and MBA-like education. However, one has to consider if the forces at work at that level might also be evident at undergraduate level (which, for the [[https://www.business.auckland.ac.nz/][University of Auckland Business School]], is the largest part of what it does). The simple answer seems to be yes, these forces are at work. The example I would give are the rumours about [[https://www.nzica.com/][NZICA]] (The New Zealand Institute of Chartered Accountants); currently NZICA require accountants to do a four year degree followed by two years of professional training (on-the-job training, followed by PAS-Professional Accounting School---then assessed through PCE2---Professional Competence Exam 2). Back to the rumour: the change would move from this 4+2 model to a 3+3 model (i.e. a three-year degree and three years of professional training). No doubt such a move would make a noticeable dent in income stream for universities. Of course some universities or polytechnics would be better off; they do training/coaching for people undertaking PCE2, but overall one can imagine a nett decrease in revenue for the sector.

I'm sure if I spent some time looking I could find more evidence that undergraduate business education is under some threat. Given the /vocational/ nature of much undergraduate business education, one shouldn't be surprised that some students/employers don't necessarily believe that three or four years at university is the only mechanism for delivering greater economic wealth.

* References

Blass, E. (2005). The rise and rise of the corporate university. /Journal of European Industrial Training, 29/(1), 58--74. doi:10.1108/03090590510576217.

Mintzberg, H. (2003). /Managers not MBAs: A hard look at the soft practice of managing and management development/. San Francisco: Berren-Kochler.

Tinker, T. (2004). "The end of business schools?" More than meets the eye. /Social Text, 22/(2), 67-80.
