#+title: The challenges of blended learning
#+date: 2020-04-29T23:50:00+1300
#+lastmod: 2020-04-29T23:50:00+1300
#+categories[]: Zettels Books
#+tags[]: Teaching

#+BEGIN_QUOTE

Bonk, C. J., Graham, C. R., Cross, J., & Moore, M. G. (2005). /The handbook of blended learning: Global perspectives, local designs/. Center for Creative Leadership. http://ebookcentral.proquest.com/lib/auckland/detail.action?docID=700321

#+END_QUOTE

** The role of live interaction
- Some learners prefer face-to-face.
- Research suggests that face-to-face is unnecessary---online can be its equivalent---and face-to-face is often used 'just' for socialisation.

** The role of learner choice and self-regulation
- Learners often select blended learning for reasons of convenience and access.
- How much guidance do learners need in making the choice, as often, online learning requires more self-discipline or self-regulation on their part.
- There is a need to foster increasing learner maturity and self-regulation.

** Models of support and training
- Blended learning can demand more instructor time.
- Learners can need more technological skills.
- Teachers need more skills/professional development re delivering online.

** The digital divide
- Online learning is often seen a favouring the better off/more advantaged learners.

** Cultural adaptation
- To what extent should blended learning adapt material for local audiences? This is particularly salient when thinking about international delivery.
- Face-to-face instructors often used to 'localise' material, or to re-contextualise it.
- This characteristic of providing context for the learner is often done through face-to-face work.


** The balance between innovation and production
- Due to the constant changes in technology, it can be hard to find a balance between innovation and production.


* Backlinks
:PROPERTIES:
:ID:       b6f3df04-f774-4877-8d60-f2b944f3bde2
:END:
- [[{{< ref "202004292310-blended-learning" >}}][Defining blended learning]]
- [[{{< ref "202004292340-reasons-for-blended-learning" >}}][Reasons for blended learning]]
