#+title: Thinking about capstone courses
#+slug: thinking-about-capstone-courses
#+date: 2019-10-08T09:53:17+13:0
#+lastmod: 2019-10-08T09:53:17+13:00
#+categories[]: Teaching
#+tags[]: Capstones
#+draft: False

What should a capstone course do? Perhaps more fundamentally, what is a capstone course?

I the second question comes from a number of my academic colleagues, and others outside of academe (but who, nevertheless, have a lot to do with the recruitment of graduates). I can't pretend I know enough of the literature to answer either of those questions (yet)?

But so far, it seems that there are three types of capstones. As I note in [[{{< relref "20191007-of-mountaintops-magnets-and-mandates" >}}][this post]], a capstone may be some kind of interdisciplinary culmination experience (a mountaintop), an opportunity to dive in deeply to some---already known---topic (a magnet), or it can be as a way to verify/assure that specific outcomes have been met for the purpose of accreditation (a
mandate).

Regardless, as editors of Assessment Update (2004), Karen E. Black and Stephen P. Hundley note:

#+BEGIN_QUOTE

Through capstone courses, students take that second look at their own learning throughout their college experiences, and during the course of this look provide invaluable information to faculty about the quality of instruction and of programs.

#+END_QUOTE

This suggest that we need to specifically attend to the feedback from capstone courses in a way that different to regular course reviews by students. The when we seek feedback from a capstone course can (should?) be especially framed to obtain programme-level feedback.
