#+title: Paycheck
#+tags[]: Movies
#+slug: paycheck
#+date: 2004-03-28T16:22:00+12:00
#+lastmod: 2004-03-28T16:22:00+12:00
#+categories[]: Arts
#+draft: False

Took a few hours off from writing new application for [[https://www.auckland.ac.nz/cir_research/index.cfm?action=display_page&\>page_title=res_approval][ethics approval]] to see Ben Affleck and Uma Thurman in [[https://www.imdb.com/title/tt0338337/][Paycheck]]. I quite enjoyed it; but it certainly is in the /ironing movie/ genre. Since we had free tickets, I wasn't too disappointed by it.

Lisa thought the plot was weak, and I tend to agree with her. Not only that but the action sequences were "over-engineered'. I feel that Jonny Woo's style is showing its age.

Interestingly enough though, it did raise a topic I've mentioned here before of structuralism vs. existentialism. Maybe not in those words, and I'm sure a philosopher would debate my use of the terms and their applicability to /Paycheck/. But, it did look at how much we can shape the future, if the future is know to us. For example, suppose a firm has detailed information about its sole competitor, what are the outcomes? And if they know that the other knows, what then? I suspect that game theorists would have a ball (and would consider the films "logic' to be rather weak too).

I haven't seen [[https://www.imdb.com/title/tt0289879/][The butterfly effect]] yet, but I image that, like /Paycheck/ it cause me wonder about points of leverage and how little needs to change in order to have a large effect. (The old, /if a butterfly flaps its wings in a rain forest it can cause a hurricane on the other side of the world/, line.)

