#+title: Friday already
#+slug: friday-already
#+date: 2004-04-23T06:50:00+12:00
#+lastmod: 2004-04-23T06:50:00+12:00
#+categories[]: Social
#+tags[]: Friday_fives
#+draft: False

And here is this week's [[https://www.fridayfive.org/][Friday Five]]
(Okay, I've recycled an old one, as there is no new F5).

- What was the last song you heard? Ya-Ya by Buckwheat Zydeco Ils sont Partis Band
- What were the last two movies you saw? Girl with a pearl earing and Paycheck
- What were the last three things you purchased? The /Queer Eye/ music CD, a MP3 player/radio/voice recorder (for Lisa), and a telephone extension cable (problems with the ADSL line).
- What four things do you need to do this weekend? Write more for my PhD, See /Kill Bill: Part 2/, Brunch out, and the MBA reunion dinner.
- Who are the last five people you talked to? Lisa, John Briers, Marie Wilson, Darl Kolb, Emma Dawson. I've just realised that when I'm working at home I talk to very few people except Lisa---to complete this item on the list people I had to go back to /Tuesday/.  

This was recycled from last year's F5.
