#+title: Selected sound bites
#+slug: selected-sound-bites
#+date: 2004-08-26T16:44:00+12:00
#+lastmod: 2004-08-26T16:44:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT302
#+draft: False

A few Porterian quotes taken from:

Harfield, T. (1997). Strategic management and Michael Porter: A postmodern reading. /Electronic Journal of Radical Oranizational Theory, 4/(1).

#+BEGIN_QUOTE

Competitive advantage is hardly a new subject.... marketing, production, control, finance, and many other activities in a firm have a role in competitive advantage. ... Competitive advantage cannot be truly understood without combining all these disciplines into a holistic view of the entire firm.

#+END_QUOTE

#+BEGIN_QUOTE

In practice, a firm must understand where each of its competitors falls on the spectrum from good to bad and behave accordingly. A good competitor understands and plays by the rules of competition in an industry, and can recognize and read market signals. Some bad competitors will never become good competitors. A firm must be prepared to fight battles in order to convert bad competitors into good ones. For example, a foreign competitor entering what it perceives to be a strategic market is usually a bad competitor. Its stakes are too high, and it may also not understand the rules of the game.

These considerations suggest that a firm must continually work to manage its competitors' expectations and assumptions.

#+END_QUOTE

#+BEGIN_QUOTE

Competitive strategy is about being different.

#+END_QUOTE

#+BEGIN_QUOTE

... a firm can achieve and sustain overall cost leadership, then it will be an above-average performer in its industry provided it can command prices at or near the industry average. A firm that can achieve and sustain differentiation will be an above-average performer in its industry if its price premium exceeds the extra costs incurred in being unique.

#+END_QUOTE

#+BEGIN_QUOTE

A firm that is stuck in the middle will earn attractive profits only if the structure of its industry is highly favourable, or if the firm is fortunate enough to have competitors that are also stuck in the middle. Becoming stuck in the middle also affects successful firms, who compromise their generic strategy for the sake of growth or prestige.

#+END_QUOTE

#+BEGIN_QUOTE

If a firm can achieve cost leadership and differentiation simultaneously, the rewards are great because the benefits are additive--differentiation leads to premium prices at the same time that cost leadership implies lower costs.

#+END_QUOTE

So, I wonder, what is your firm doing? How would you describe its strategy?
