#+title: Market shaping
#+slug: market-shaping
#+date: 2018-08-30T10:51:45+12:00
#+lastmod: 2018-08-30T10:51:45+12:00
#+categories[]: Research
#+tags[]: Market-shaping
#+draft: False

I have just spent the past 70 minutes, or so, talking with [[https://scholar.google.com/citations?user=OZ-0drUAAAAJ][Charlotta Windahl]] and [[https://scholar.google.com/citations?user=b5k1364AAAAJ][Johnny Chan]] about their (potential) project on *market shaping*. Okay, I must confess here, that I am supervising a PhD student who is looking at nonmarket strategy (which think is a form of market shaping) and that has biased my thinking somewhat--see Dorobantu, Kaul, and Zelner (2017) for an example of nonmarket strategy.

Much of the discussion revolved around the question, "What is market shaping?"

For me, the brief answer is that market shaping is a teleological activity--an intentional, purposeful activity--that leads to market's the /rules of the game/ changing. This definition is a little incomplete as it does not directly address market creation or its destruction, but I see those events as also being representative of the rules of the game changing or coming into (or out of) existence.

As to what are the rules of the game. Here I fall back on Charlotta's statement that they are the "regulative, normative, and cognitive" rules of the market. The generally accepted "must do", "ought to do", and "want to" of the market. Such a stance (on the 'rules of the game') is entirely consistent with, and based on, Scott's (1994) views on institutions.

Of course other views, such as Charlotta's and Johnny's are available. But this is the state of my thinking at the moment.

One implication of the stance taken here is that it is a mistake to take /any/ changes in a market to be an example of market shaping.

In the face of competitive moves, firms may respond by either direct competitive responses (e.g., dropping prices) or by indirect competitive response (e.g., successful lobbying to change regulation to reduce price competition). Thus, the trigger for an organization to pursue market shaping might be anything that is felt as change in competitive pressure.

Markets (as a form of institution) are always in a state of flux. They may be changing as a result of market shaping activity of a player in the market, but market shaping can only be said to be successful once the rules of the game have changed.

Until that point, the market shaping attempts might be labelled either as nascent or maybe even failing.

I like the idea that the actions of the Japanese car industry in, regard to quality/reliability, was market shaping. They change entirely what the market saw as the norm around quality/reliability in cars. What we expected in reliability (in any car, at any price) profoundly shifted.

Another example, would be changes in regulation to prevent the collection of rainwater for drinking. This move, driven by water companies, reduced/removed a major 'substitute' for their more expensive product (albeit in the guise of public safety).

* References

Dorobantu, S., Kaul, A., & Zelner, B. (2017). Nonmarket strategy research through the lens of new institutional economics: An integrative review and future directions. /Strategic Management Journal/, /38/(1), 114--140. https://doi.org/10.1002/smj.2590

Scott, W. R. (1994). /Institutions and organizations: Towards a theoretical synthesis./ In W. R. Scott & J. W. Meyer (Eds.), Institutional environments and organizations: Structural complexity and individualism. Thousand Oaks, CA: Sage.
