#+title: Lewin and Change
#+slug: lewin-and-change
#+date: 2012-01-14T16:01:00+12:00
#+lastmod: 2012-01-14T16:01:00+12:00
#+categories[]: Research
#+tags[]: Conference
#+draft: False

Last year, I attended a practice workshop at the [[https://sydney.edu.au/][University of Sydney]]. Afterwards, there was an interesting presentation by [[https://web.archive.org/web/20130326112217/https://www1.aston.ac.uk/aston-business-school/staff/academic/esg/prof-paula-jarzabkowski/][Paula Jarzbakowski]]" called "Towards a theory of coordinating: Creating coordinating mechanisms in practice". At the end of the presentation, I was left wondering what these coordinating mechanisms add to our existing understanding--do they really go beyond what Lewin (1994) said.

Paula's on-the-spot response was that Lewin's model was static, inasmuch as it presupposed there were stable conditions (for the unfreezing, moving, re-freezing to occur). In other words, her contention was that Lewin's model didn't handle continuous change well--in modern life there are no periods of stability. However, I seem to recall that Lewin's model assumed /quasi-stable/ conditions, and not actual stability.

It then occurred to me that many (most) people have not read Lewin in the original; they rely on others interpretations. Over the years, this may have resulted in a overly simplistic understand of Lewin and his work. It also reminded me that it had been a long time since I read Lewin myself. So, I thought I should briefly revisit his work.

My starting point turned out to be a Manford Kuhn's (1951) review of a collection of Lewin's works. Kuhn argues three things.

1. Field theory has not advanced much since it was first articulated in the 1930s (recall, the review was done in 1951).
2. Many of the concepts from field theory have counterparts in symbolic interactionism (/i.e/., the social). However, it is not the case that all of symbolic interactionism can be readily translated into field theory.
3. There has been considerable more impact by field theory on the consideration of the individual (/e.g./, the psychological).

Overall, Kuhn seems to argue that Lewin and his field theory can span both the micro (individualist) and macro (societist) approaches in the creation of a "general school of social psychology" (p.147).

And now I need to re-read Lewin's work ...

* References
Lewin, K. (1994). The field approach: Culture and group life as quasi-stationary processes. In W. L. French, C. H. Bell Jr, & R. A. Zawacki (Eds.), /Organization development and transformation: Managing effective change/ (4th ed.). Burr Ridge, IL: Irwin.

Lewin, K. (1951). /Field theory in social science: Selected theoretical papers/. (D. Cartwright, Ed.). London: Tavistock Publications.
