#+title: Communities of practice
#+slug: communities-of-practice
#+date: 2008-11-24T11:18:00+12:00
#+lastmod: 2008-11-24T11:18:00+12:00
#+categories[]: Research
#+tags[]: Practice
#+draft: False


It is so nice when ones research and teaching interests intersect. As I've been studying practices, I've become increasing interested in the "situated" nature of practices (Suchman, 1987; Sharrock & Button, 2003; Lave 1991). This has led me to become increasing interested in the notion of [[https://www.ewenger.com/theory/communities_of_practice_intro.htm][Communities of practice]] This lead me to some reports about [[https://leaderswedeserve.wordpress.com/2007/05/22/the-manchester-method-as-an-educational-innovation/][The Manchester Method]] as a means of teaching (especially with regard to MBA students). There is a helpful [[https://leaderswedeserve.files.wordpress.com/2007/05/manchester-method.ppt][PowerPoint sideshow]] that puts the method into context (of course---where would we be without context).

* References

Lave, J. (1991). Situating learning in communities of practice. In L. B. Resnick, J. M. Levine, & S. D. Teasley (Eds.), /Perspectives on socially shared cognition/ (pp. 63--82). Washington, DC: American Psychological Association.

Sharrock, W., & Button, G. (2003). Plans and Situated Action Ten Years On. /Journal of the Learning Sciences/, 12(2), 259. doi: 10.1207/S15327809JLS1202\_5.

Suchman, L. A. (1987). /Plans and Situated Actions: The Problem of Human-Machine Communication/ (p. 203). Cambridge, UK: Cambridge University-Press.
