#+title: Some notes on the assignment (for next time)
#+slug: some-notes-on-the-assignment-for-next-time
#+date: 2004-05-19T15:07:00+12:00
#+lastmod: 2004-05-19T15:07:00+12:00
#+categories[]: Teching
#+tags[]: MGMT301 Assignments
#+draft: False

It's strange the things that stand out in this recent assignment.

Firstly, many people chose to use the /360 degree feedback/ type of forms. This is fine, but a disproportionate number of people emphasised the topic of emotional intelligence field. My guess is that came from peoples previous experience with EI or EQ in MGMT 201.

As Darl said a few weeks ago in class, to many people are engaging with stage I topics and not moving into the stage III content of this course. I suspect that, as a consequence, they are often engaging at a stage I /level/, rather than at a more sophisticated stage III level. e.g. So, did anyone who focused on EI or EQ consider that it is a socially constructed map (possible based on other, more established, personality factors from the [[https://www.uwmc.uwc.edu/psychology/big_five.htm][big five]])?

Anyway, I think for next time we should remove that topic from the survey and replace it with something else.

Also, people are not indicating on their cover-sheets to which team they belong--despite it being in the /Black book/[fn::The /Black Book/ is the course syllabus and handbook for MGMT 301: Management Theory & Practice.]. For next time, Darl thinks we should put a sample coversheet in the black book.

I'm not sure if this will make a significant difference to the problem. Having said that, a number of people seem to have slavishly copied the form (and even the style of the opening paragraph) from the essay exemplars in the Black Book. I, on the other hand, think it is just a mater of some negative reinforcement (e.g. explicitly taking away marks). I wonder which is would be more effective. "Comments anyone?"


