#+title: Project stakeholder analysis
#+date: 2021-09-25T15:26:00+1300
#+lastmod: 2021-09-25T15:26:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management Stakeholder_analysis

There are three key steps to kicking off a stakeholder analysis.
1. Make a list of all the stakeholders that the project impacts.
2. Determine the level of interest and influence for each stakeholder.
3. Assess their ability to participate, and find ways to involve them.

In the second step, we talk about influence and interests
- Influence measures how much power a stakeholder has and how much the stakeholder's actions affect the project outcome. Influence = power
- Interest is pretty much what it sounds like: How much are the needs of the stakeholder affected by the project operations and outcomes?

The higher the interest and influence, the more important the stakeholder is to the project's success.


|                | Low interest | High interest        |
|----------------+--------------+----------------------|
| High influence | *Meet needs* | *Key players*        |
|                |              |                      |
| Low influence  | *Monitor*    | *Show consideration* |


Stakeholder buy-in is the process of involving these people in decision-making to hopefully reach a broader consensus on the organization's future

*Pro tip*: You might want to form a *steering committee* during some projects. A steering committee is a collection of key stakeholders who have a high level of power and interest in a project. A steering committee can influence multiple departments within the organization, which means that they have the potential to release a greater number of resources to the project manager.

*Pro tip*: While these tools help organize information, they do not necessarily make the difference between successful and unsuccessful stakeholder engagement. What will make for successful stakeholder engagement is the project manager’s ability to know their stakeholders’ motivations and inspirations. This takes time, interpersonal skills, and insight into the organization’s internal political workings. Remember, each project is different, and your project may need tweaks along the way as you grow as a project manager. Making necessary changes means you are doing something right. Just make sure to check in and ensure that you are well on track, engaging your stakeholders successfully, and delivering on your project.

* Generating stakeholder buy-in

Once you organize and assess your stakeholders, it is time to start making some decisions on whose buy-in is absolutely necessary for success, whose requirements deserve the most attention, and what level of communication each stakeholder will require.

Gaining key stakeholder buy-in is essential to ensuring that your project is not deprioritized or deprived of resources.

Tips for gaining key stakeholder buy-in include:

- Clearly mapping the work of the project to the goals of the stakeholder.
- Describing how the project aligns with the goals of the stakeholder's department or team.
- Listening to feedback from the stakeholder and finding ways to incorporate their feedback into the project's charter where appropriate.

Manage your stakeholders’ expectations by presenting a realistic view of your team’s abilities. Do not over-promise and under-deliver!

* Stakeholder management: Tips and takeaways

Stakeholder management is the process of maintaining good relationships with the people who have the most influence on your work. Efficiently managing stakeholders is an integral part of every project because it encourages good communication, teamwork, trust among members, and so much more. Without effective stakeholder management, a project is less likely to be successful. Read on for some tips and best practices for effective stakeholder management.

** Stakeholder management during project initiation

- Identify all the stakeholders at the beginning of your project or initiative. Get everyone involved as early as possible to set clear expectations, responsibilities, and boundaries. Identifying your stakeholders early on gives them ample time to voice any concerns they may have about the project or their role within it. If they feel a sense of ownership from the beginning, your stakeholders may be more likely to embrace their roles, give appropriate input, and help remove barriers to allow the project to move forward.

- Keep the project vision clear. The project vision describes the need the project is fulfilling. It is important to have a clear, specific project vision because, as we have learned, stakeholders may apply pressure to increase the requirements, shorten the timeline, or cut resources. Ensuring that stakeholders have agreed upon the visionand, more specifically, what "done" looks likeprovides clarity for everyone involved with the project. Including highly-influential stakeholders in the strategic planning processes will make sure that all team members are aligned with project vision.

- Equip your stakeholders with user-friendly resources at all times. This could mean creating a one-pager (a one-page document that provides an overview of your project) or weekly status report with the latest information and links to the main project artifacts. It may also mean ensuring everyone has access to necessary documentation.

* * Stakeholder management throughout the project life cycle

As you work your way through the project life cycle, you will have to maintain good relationships with all of your stakeholders to ensure they are satisfied and contributing to the team. The following strategies can help you get to know your stakeholders’ interests, concerns, and communication preferences and enlist their help throughout your project’s life cycle:

- Find out what stakeholders care about and why. Ask your stakeholders: What are your most important priorities and goals? What role would you like to play in this project? How will this project support you and your most important priorities?

- Adjust your communication frequency and approach based on stakeholder roles and preferences. Tell your stakeholders: Here’s how I plan to keep you informeddoes that work for you?

- Enlist the help of senior stakeholders when necessary. Ask your stakeholders: Who else do you recommend I reach out to regarding this project?

- Once stakeholders have a vested interest, bring project problems to them. Ask your stakeholders: How would you handle this situation? What solutions come to mind?

* Backlinks
- [[{{< ref "202109251428-project-stakeholders" >}}][Project stakeholders]]

