#+title: Reply to https://evgenykuznetsov.org/en/reactions/2022/re-010174726/
#+slug: reply-to-https-evgenykuznetsov-org-en-reactions-2022-re-010174726-
#+date: 2022-01-11T15:51:13+13:00
#+lastmod: 2022-01-11T15:51:13+13:00
#+categories[]: Tech IndieWeb
#+tags[]: Hugo IndieWeb
#+draft: False

[[https://evgenykuznetsov.org/en/reactions/2022/re-010174726/][Evgeny]], yes, I thought that would be the problem. I have been using [[https://gohugo.io/content-management/urls/#permalinks][permalinks]] like that ever since I started using Hugo back in [[{{ relref "20160314-more-static" }}][2016]]. It's messier than it might first appear, because as you can see from this 'snip' of my =config.toml= only some content is laid out that way.

#+BEGIN_SRC toml

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"
    notes = "/notes/:year/:month:/:day/:slug/"
    mentions = "/mentions/:year/:month:/:day/:slug/"
    resources = "/resources/:slug/"
    pages = "/pages/:slug/"

#+END_SRC

I suppose, it would be easy enough for me, =bash=, and =sed= to move to a directory structure like yours (fixing up any [[Start here][relref]] on the way). Then, the structure 'on-disk' of all my content would be consistent across all the sections (blog, notes, mentions, etc.) with how it is presented on the web.

# more

This all makes me think my architecture of webmentions/IndieWeb isn't right in my head yet. These 'mentions' on my side aren't being threaded back to the original post. I'll have to sort that --- and then come back and fix-up these somewhat broken mentions.

What I think I will do---for mentions like this---is put a couple of links in my [[https://gohugo.io/content-management/front-matter/][front matter]]. One for the original  source, and maybe one for the mention my mention is responding to. Then I'll have the template spew out the correct URLs. I guess that's how you and others do it. Arrg, I need to go back to [[https://indieweb.org/][IndieWeb]] and see how its meant to be done.
