#+title: DOI
#+slug: doi
#+date: 2011-03-15T09:02:00+12:00
#+lastmod: 2011-03-15T09:02:00+12:00
#+categories[]: Tech
#+tags[]: Zotero APA DOI
#+draft: False

I'm an avid user of [[https://www.zotero.org/][Zotero]] for the management of my bibliography, and for much of my note taking on what I have read. Sometime ago, DOIs started to appear in my references.

Indeed, the [[https://books.apa.org/books.cfm?id=4210509][APA Style Guide to Electronic References]]) in June 2007 made DOI an official part of the citation.

In case you were wondering, according to [[https://www.apastyle.org/learn/faqs/what-is-doi.aspx][APA Style]]:

#+BEGIN_QUOTE

A digital object identifier (DOI) is a unique alphanumeric string assigned by a registration agency (the International DOI Foundation) to identify content and provide a persistent link to its location on the Internet. The publisher assigns a DOI when your article is published and made available electronically.

All DOI numbers begin with a 10 and contain a prefix and a suffix separated by a slash. The prefix is a unique number of four or more digits assigned to organizations; the suffix is assigned by the publisher and was designed to be flexible with publisher identification standards.

We recommend that when DOIs are available, you include them for both print and electronic sources. The DOI is typically located on the first page of the electronic journal article, near the copyright notice. The DOI can also be found on the database landing page for the article.

#+END_QUOTE

So, I can understand why they are there (it's good practice), but I'm left wondering as to how much effort I should put into updating all my references with DOIs. With nearly 2,000 references in my database it could be pretty time consuming if I were to do it manually. At the moment I do it on an "as needed" basis, updating those references that I actually use in new pieces of writing. But it would be really nice to have a way to automagically update most/all of the references that I have. Maybe I should ask the Zotero folk if there is a way to do it programatically.
