#+title: A question of rollover
#+slug: a-question-of-rollover
#+date: 2004-07-11T18:08:00+12:00
#+lastmod: 2004-07-11T18:08:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301 Mikesbikes
#+draft: False

As we move towards a new semester, Darl and I are pondering "When is the best time to rollover the simulation?" In our [[{{< ref "mgmt-301" >}}][class]], we use the business simulation [[https://www.smartsims.com/][NetMike]] as a practice field for our students. Typically we simulate between seven and ten years. Each simulated year occurs when we /rollover/ the simulation to a new year.

In the past we have done the rollovers every Monday at mid-day or, alternatively, at 4:00 on a Friday. Thus each simulated year takes a week in real time. The advantages of doing the rollover on a Monday is that it allows teams to meet over the weekend to make their decisions. However, do we really want to encourage students to work during the weekend? Are we facilitating bad habits? That is why we have also tried to have rollovers on a Friday, so that students are constrained to stay within the /working week/, so to speak.

On top of that, I suspect that when we have a Monday rollover, some students are being 'coerced' into working at weekends when they would rather not. I'd be interested to hear from past and current students as to what their 'take' is on this-issue.
