#+title: Practitioners
#+slug: practitioners
#+date: 2011-03-10T21:17:00+12:00
#+lastmod: 2011-03-10T21:17:00+12:00
#+categories[]: Research
#+tags[]: Practice Academics
#+draft: False

One of my favourite writers on practice---[[https://johnpostill.wordpress.com/][John Postill]]---made an interesting [[https://johnpostill.wordpress.com/2010/02/16/academics-are-practitioners/][reflection on practitioners and academics]]. He notes that:

#+BEGIN_QUOTE

The conventional divide between "theorists' (e.g. media scholars) and"practitioners' (e.g. journalists who teach at academic institutions) that we find in higher education parlance is unhelpful. Both scholars and non-scholars are practitioners, albeit of different kinds. That is, both operate within fields of practice that require long years of learning and secondary socialisation.

#+END_QUOTE

But I'm left wondering if the problem he expresses (more eloquently in his full posting) is the consequence of how people overload meanings on to words. For example, we use the word accident in our every day lives and most of us recognise the meaning (which is often associated with blame or responsibility). However, in medicine the word has a different meaning ([[https://www.oed.com/view/Entry/1051?rskey=tPHQMm&result=1&isAdvanced=false#][An occurring symptom; esp. an unfavourable symptom]]). And yet the medical profession routinely distinguishes between that meaning and the more usual meaning.
