#+title: Another new pedometer
#+slug: another-new-pedometer
#+date: 2004-07-29T14:15:00+12:00
#+lastmod: 2004-07-29T14:15:00+12:00
#+categories[]: Home
#+tags[]: Fitness Walking
#+draft: False

I bought a new [[{{< ref "a-new-toy-or-not" >}}][pedometer/stepmeter]] a few weeks ago. Alas, the new one doesn't do a good job. I finally figured out that it was under reporting by 20 to 50 per cent. i.e. it was missing as many as half of my steps. I'd dropped it a few times so I decided to take it to pieces. Nothing obviously wrong there---the pendulum seemed fine. Even so, I though the problem was probably the result of dropping it.

Off to [[https://www.tisdalls.co.nz/][Tisdall's]] to get a new one. But, I decided to check out all the different models (I'm still choosing [[https://www.silva.se/][Silva]]). After much shaking and tipping of all the different models, both I and the sales assistant agreed that the pendulums in the cheapest model is definitely lighter and, I suspect, less reliable. My first pedometer was not the cheaper model. My second one was. So, maybe the problem was the pedometer design rather than it being dropped.

Oh well. I'll let Tisdall's know.

This means that my last two weeks "peds' are probably grossly in accurate.
