#+title: House for sale
#+slug: house-for-sale
#+date: 2003-05-19T21:30:00+12:00
#+lastmod: 2003-05-19T21:30:00+12:00
#+categories[]: Home
#+tags[]: Moving
#+draft: False

We've decided to sell our house. We've engaged an agent and now we're sitting back waiting for the qualified buyers to start rolling in. However, before signing on the dotted line we both read /Don't sign anything/ by Neil Jenman. It is a very interesting tail of how some real estate agents operate. It opened our eyes to many practices that could be considered suspect, if not down-right fraudulent.

But, I'm happy to report, that our agent has been pretty good so far. What price to put the house on at? Well, we've no idea. Comparing recently sold properties in the area didn't help much. So we decided to use the services of a registered valuation agent. Most peculiarly, they seem to charge based on the value of the house, rather than on the amount of work. Does a 300k house really take more time than a 250k house. I don't know, but it will be interesting when we find out what they have valued the house-at.

