#+date: 2016-03-16T05:02:30+13:00
#+slug: ISPIM-2016
#+lastmod: 2016-03-16T05:02:30+13:00
#+title: ISPIM 2016
#+categories[]: Research
#+tags[]: Conferences ISPIM
#+draft: False

A short report from ISPIM 2016. For those who don't know, ISPIM is the [[https://ispim.org/][International Society for Professional Innovation Management]] and its official publication is the [[https://www.worldscientific.com/worldscinet/ijim][International Journal of Innovation Management]]. That link will go stale fast as the journal has just been taken over by Emerald Publishing.

What I like about the conference is the blend academic and practitioner work. It makes for rich conversations that have practical implications. I confess, that I find some academic discussions involve a little too much 'counting angels on the head of a pin'. The format of the conference is quite different too. There are sessions for fully developed papers, papers in progress, and ideas for papers. In addition, this time, there have been daily 'site visits' to places such as the Fidelity Center for Applied Finance, or to MIT. In this way, everyone gets good exposure to what's happening in the world. If there is a downside, it is that some of the trips occur at the same time, so hard choices have to be made.

The location of the conference in Boston has enabled access to some world's leading centres of innovation (as mentioned above). These have included not only industry but also educational destinations; MIT, NorthEastern, etc.

As always, there has been good global representation. Of course there are a lot of folk from the US, but Europe is also well represented. And there are a few of us from the Antipodes too.

I have had some really good conversations about peoples work ... at times I/we even skipped sessions to keep the conversation going. One is always time poor at a good conference and (again) choices have to be made.
