#+title: Cold rice pudding with apples
#+date: 2023-01-27T16:07:22+13:00
#+lastmod: 2023-01-27T16:07:22+13:00
#+categories[]: Recipes
#+tags[]: Food Pudding

For the rice pudding
- 50g pudding rice
- 1 cinnamon stick
- 1 vanilla pod, split lengthways
- 30g golden caster sugar
- A large pinch of flaky salt
- 550ml whole milk
- 200ml double cream

For the apples
- 350g bramley apples, peeled, cored and roughly chopped into 2cm pieces
- 60g light brown sugar or golden caster sugar
- 1 tsp vanilla bean paste (optional)

Put the rice, cinnamon, vanilla, caster sugar, salt, 400ml of the milk and the double cream in a medium saucepan and bring to a gentle simmer over a medium heat. Turn down the heat and stir frequently until the rice starts to float towards the surface. Turn down the heat to low and cook, stirring occasionally to prevent the rice sticking to the pan, for an hour to 90 minutes. Test that it’s cooked – it shouldn’t have any chalkiness, nor be too mushy: a small amount of bite is good – then take off the heat and stir in the remaining 150ml milk. Leave to cool, fish out and discard the vanilla pod, then chill.

While the rice is cooking, make the apples. Put the fruit in a pan with the sugar and vanilla bean paste, if using, and cook on a low-medium heat, stirring frequently, for 15 to 20 minutes, or until the apples are translucent. Leave to cool before serving.

Serve the cold rice pudding in bowls and dollop a generous spoonful of the apples on top.

Source: [[https://www.theguardian.com/profile/ravneet-gill][Ravneet Gill]]

* Notes
1. The rice pudding ends up very creamy
2. The cinnamon in the rice pairs well with the apples. Without the apples, it feels as if something is missing.
