#+title: Critical incidents and maps
#+slug: critical-incidents-and-maps
#+date: 2004-05-20T16:50:00+12:00
#+lastmod: 2004-05-20T16:50:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301
#+draft: False

There have been a number of questions about the up coming assignment and especially about /critical incidents/. So, what is a critical incident. Well it isn't what common sense might tell you.

[[https://www.tiu.edu/psychology/Twelker/critical_incident_technique.htm][Paul A. Twelker]] has a pretty good definition of a critical incident:

#+BEGIN_QUOTE

An "incident" is best thought as "any observable human activity that is sufficiently complete in itself to permit inferences and predictions to be made about the person performing the act." In order for the incident to be considered "critical," it "must occur in a situation where the purpose or intent of the act seems fairly clear to the observer and where its consequences are sufficiently definite to leave little doubt concerning its effects [[https://www.apa.org/psycinfo/special/cit-article.pdf][(Flanagan, 1954)]].

#+END_QUOTE

And that's about it. I wouldn't get sidetracked by the /Critical Incident Technique/ (or it's plethora of uses in medicine). That's probably not helpful for this assignment--too much of a distraction.

There are also some questions about maps. Alas, I don't have a short answer for that one. If you missed the class then you'd best start with revisiting the readings.
