#+title: Girl with a Pearl Earring
#+slug: girl-with-a-pearl-earring
#+date: 2004-04-11T22:52:00+12:00
#+lastmod: 2004-04-11T22:52:00+12:00
#+categories[]: Arts
#+tags[]: Movies
#+draft: False

We went and saw [[https://www.imdb.com/title/tt0335119/][Girl with a Pearl Earring]] today. Lisa's read the [[https://www.amazon.com/exec/obidos/tg/detail/-/0452282152][book]] and was pretty happy with the film adaptation. However, she did point out that a few important parts of the book were missing; for example, the opening scene with the plate of vegetables---that all makes sense if you know that Vermeer hires Griet because of her arrangement (and its explanation) of the vegetables.

We both thought that when we (the audience) looked in the Camera Obscura, the picture should have been projected either upside down or reversed (this depends on the exact nature of Vermeer's camera).  Perhaps the film makers were taking poetic licence?  For more details of Vermeer's camera have a look [[https://essentialvermeer.20m.com/camera_obscura/camera_obscura_part_two.htm][here]] Anyway, back to the movie. Apart from three other males, the audience in the cinema was entirely female. The film was beautifully crafted.  I particular liked the attention to detail with the ice on the canals.

All-in-all, a pleasant way to spend a couple of hours.  After the movie, we spent half an hour wandering around the local [[https://www.bordersstores.com/stores/store_pg.jsp?storeID=366][Borders]].  I still can decide if I have time to read anything other than material for my PhD (and that's plain sad).

