#+title: Walk for Isobella and EB
#+slug: walk-for-isobella-and-eb
#+date: 2011-10-27T15:19:00+12:00
#+lastmod: 2011-10-27T15:19:00+12:00
#+categories[]: Home
#+tags[]: Fitness Running
#+draft: False

I'm running the Auckland Marathon on Sunday. I'm looking forward to it, and it should be fun. A few weeks later, I'll be in [[https://maps.google.com/maps?q=kerikeri&hl=en&sll=37.0625,--95.677068&sspn=62.057085,62.490234&vpsrc=0&hnear=Kerikeri,+Northland,+New+Zealand&t=m&z=11][Kerikeri]] running the [[https://www.runwalkseries.co.nz/default.asp?PageID=22925][KeriKeri half marathon]].

I'm doing the run at KeriKeri to raise awareness about Epidermylosis Bullosa and to raise money for Debra New Zealand, a [[https://www.facebook.com/pages/Walk-for-Isobella-EB/201005623259849?sk=info][support group for sufferers of EB]] and their families. Most of the information here, I've taken from the [[https://www.facebook.com/pages/Walk-for-Isobella-EB/201005623259849][Walk for Isobella and EB]] pages.

#+BEGIN_QUOTE

Epidermolysis Bullosa is medical Latin for skin that blisters and tears easily. /Epidermal/ describes "outer skin layers'; /lysis/ means"tearing and shearing'; and the /Bulla/ are the "blisters' that develop.

If you have EB then your skin is more delicate, it blisters or tears more easily. In severe EB the slightest touch can cause skin to blister or come off and leave wounds like burns. It's as if there's no glue between the skin and the tissue below. It can also occur in the mucous membranes, particularly inside the mouth and throat causing > major issues with nutrition.

There are three main types of EB --- /Dystrophic, Simplex-/ an\_d Junctional.\_ Each type can be mild or severe, and each is made up of many different sub-types. In fact just about everyone living with EB is affected differently.

The type of EB relates to where weakness occurs in the skin cell layers.

- /Dystrophic EB/ skin comes apart at the bottom layer.Coming
"unglued' down near the flesh below, amongst the live basal skin cells. With live regenerative cells lost, wounds have to heal growing in from the sides. Dystrophic EB also affects the body's internal skin. Dystrophic means scarring.
- /Simplex EB/ skin comes apart in the upper layers.Wound healing is
"simpler' with a full compliment of live cells still in the right place to fix the wound with less scarring. Simplex EB can be worse when the weather is hot and humid.
- /Junctional EB/ skin comes apart at the "junction' between the upper
layer and the live lower cells. Surprisingly these wounds can take the longest to heal.

More than 150 New Zealanders have this genetic disorder. While most have mild to moderate symptoms, many require specialist and ongoing clinical care to varying degrees.

Currently 11 New Zealanders live with severe EB, which has an incidence of 1 in 300,000.

#+END_QUOTE

At KeriKeri many people will be walking to raise money. Me, I'll be running ... that's what I do.

I'm doing this to raise money, because a dear friend's niece had the worst form of this, and only lived six weeks. So, if you'd like to /sponsor me/ (whatever the amount), please contact me.

To my colleagues, many of whom have sponsored me at $105 each (21k at $5), thank you. To Thomas and Andrew, who have sponsored me at $2 per K, rising to $4 per K if I complete in under 1:40, and rising to $8 per K ($168) if I do it under 1:35, a special thanks---you know how to motivate me.
