#+title: Law firm survey
#+date: 2004-06-16T10:25:00+12:00
#+lastmod: 2004-06-16T10:25:00+12:00
#+categories[]: Research
#+tags[]: PSFs 
#+slug: law-firm-survey
#+draft: False

As I've mentioned [[{{< relref "20040319-the-rumour-mill/index.org" >}}][before]], one of the things I'm researching is the organisation and management of law firms. This research is based on work done by [[https://www.aegis.uws.edu.au/Staff/TEXT/John%20Gray.htm][John Gray]].

It's taken almost a year to get everything into place but last Friday we sent out the surveys. I had a couple of emails yesterday about the survey, but today, completed survey forms have started to arrive. So far I have a 2 per cent response rate---I hope to get that up to over 80 per cent. Once I get back from [[https://www.egosnet.org][EGOS]], and my Research Assistant gets back from Australia, we'll start following up with the outstanding firms. /It really is nice/ that the firms have responded so promptly, and that they have taken the time to complete the survey.

On a technical level, the research is really designed to do two things. Firstly, we hope to find the extent to which law firms are moving from the P2 form (professional partnership) towards the MPB (managed professional business). I'd also like to compare the aggregated results with the results from Australia and Canada (and maybe the UK if they are ready). There are some practical implications of this which I will discuss at a later date. It is also design to confirm some results of [[https://www.cob.sjsu.edu/malos_s/][Stan Malos'es]] work on Options Theory in law firms and on they way the firms manage progression of professional staff through the firm.

My hope is that in doing this work, beside producing useful research outputs, I'll be kept at the forefront of the literature of professional service firms---which will be a big pay-off for my PhD.

** Bibliography

Gray, J. (2002). Reflexivity and emerging forms in law firms, in D. Brock, C. (Bob). Hinings, M. Powell (eds). /Restructuring Professional Organizations/. London: Routledge.

Gray, J. (2002). Stars or question marks: Strategically organising small law firms. /Business Quest Georgia/, USA: Georgia State University Press.

Gray, J., McAllister. G. & Hinings, C. R. (2002). Why aren't Australian law firms confined by national boundaries?. /Paper presented to the ACSANZ Conference/, 'Converging Futures', National Convention Centre, Canberra, 12--15 September.

Malos, S. B. & Campion, M. A. (1995). An options-based model of career mobility in professional service firms. /Academy of Management Review. 20/. 611---644

Malos, S. B. & Campion, M. A. (2000). Human resource strategy and career mobility in professional service firms: A test of an options-based model. /Academy of Management Journal 43/. 749---760.

Malos, S. B. (1996). Individual mobility in the downsizing age: An options-based strategy for career survival. /Proceedings of the Institute of Behavioral and Applied Management/. 63---66.

Malos, S. B. (1996). Promotions, up-or-out strictness, and career development in professional service firms: An investigation of linkages suggested by an options-based approach. /Academy of Management Best Paper Proceedings/. 76---80.

McAllister, G. & Gray. J. (2002) Why are Large Australian Law Firms Merging? /Paper presented to the Workshop on Professional Services Firms at the University of Alberta/, Alberta, 15---17 August.
