#+title: Project quality management
!#+date: 2021-10-26T18:28:00+1300
#+lastmod: 2021-10-26T18:28:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_ management

Quality is when you fulfill the outlined requirements for the deliverable and meet or exceed the needs or expectations of your customers.

* Quality management
** Quality standards
Provide requirements, specifications, or guidelines that can be used to ensure that products, processes, or services are fit for achieving the desired outcome.

Quality standards provide requirements, specifications, or guidelines that can be used to ensure that products, processes, or services are fit for achieving the desired outcome. These standards must be met in order for the product, process, or service to be considered successful by the organization and the customer. You will set quality standards with your team and your customer at the beginning of your project. Well-defined standards lead to less rework and schedule delays throughout your project.

- Set at the beginning of the project.
- Check as the project proceeds

Can include things like:
- Usability standards
- Safety standards
- Reliability standards

** Quality planning
:PROPERTIES:
:ID:       3c0458c2-d491-4385-83c6-28b5f156eb59
:END:
The actions of the project manager or the team to establish a process for identifying and determining exactly which standards of quality are relevant to the project as a whole.

Quality planning involves the actions of you or your team to establish and conduct a process for identifying and determining exactly which standards of quality are relevant to the project as a whole and how to satisfy them. During this process, you'll plan the procedures to achieve the quality standards for your project

Based on questions such as:
- What outcomes do my customers want?
- What does quality look like for them?
- How can I meet their expectations?
- How will I determine if the quality measure will lead to project success?

** Quality assurance (QA)
Evaluating if your project is moving towards delivering a high-quality service of product.

QA spans the whole [[{{< ref "202109121327-project-life-cycle" >}}][Project life cycle]] not just the execution phase.

Quality assurance, or QA, is a review process that evaluates whether the project is moving toward delivering a high-quality service or product. It includes regular audits to confirm that everything is going to plan and that the necessary procedures are being followed. Quality assurance helps you make sure that you and your customers are getting the exact product you contracted for.

** Quality control (QC)
Involves monitoring project results and delivery to determine if they are meeting desired results (standards) or not.

QC helps with making a successful landing of the project.

Quality control, or QC, involves monitoring project results and delivery to determine if they are meeting desired results. It includes the techniques that are used to ensure quality standards are maintained when a problem is identified. Quality control is a subset of quality assurance activities. While QA seeks to prevent defects before they occur, QC aims to identify defects after they have happened and also entails taking corrective action to resolve these issues.


* Backlinks
- [[{{< ref "202109121934-project-phase-execution" >}}][Project phase - execution]]

