#+title: Echoes of Karl Weick: A few notes on sense making.
#+date: 2004-03-12T22:53:00+12:00
#+lastmod: 2004-03-12T22:53:00+12:00
#+categories[]: Research
#+slug: echoes-of-karl-weick-a-few-notes-on-sense-making
#+draft: False

I've just finished reading an article by Karl Weick (1996). In it, he discusses Norman Maclean "s 1992 book, /Young men and Fire/. I'm not going to dwell on the story of the Mann Gulch disaster that forms the story at the core of the article. Rather, I'd like to recapitulate a few of his ideas regarding sense making.

Firstly, he points out that sense making is about "contextual rationality'. That is to say, the sense making perspective accepts that rationality takes place within a context, and that context is often grounded in ambiguity and imprecision. Thus, the decisions that get made in such an environment are, necessarily, shaped by that, confused and confusing, context.

For Weick, the solution is in leadership that fosters four things: improvisation, wisdom, respectful interaction, and communication. As often happens in the writings of academics he imbues each of these attributes with meanings that are specific rather than relying on their common-or-garden meanings.

- Improvisation: "bringing to the surface, testing, and restructuring of one's intuitive understanding of phenomena on the spot, at a time when action can still make a difference" (p. 147).
- Wisdom: "ignorance and wisdom grow together. The more people learn about a particular domain, the more questions they raise about other areas of the same domain" (p. 148).
- Respectful interaction: This really comprises of three things: - Trust: "respect the reports of others and be willing to base believes and actions on them" (p.148).
- Honesty: "report so that others may use your observations in coming to valid beliefs" (p.148).
- Self-respect: " respect your own perceptions and beliefs and integrate them with reports of others without depreciating them or yourself" (p.148).
- Communication: "non-stop talk is a crucial source of coordination in complex systems that are susceptible to disasters" (p.148).

Whilst we, that is [[{{< relref "20040308-dpe.md" >}}][DPE]], didn't have this specific article in mind at the time, I feel that much of these ideas are reflected in the learning outcomes for this course.

I wonder how many of the teams in the class will wrestle with this four things over the coming weeks?

For completeness, I'd just like to make a link between this article and one of the recommended readings for the course. Weick does also say in this article that "People are often thrust into unfamiliar roles to fulfil difficult tasks, and small mistakes can combine into something monstrous" (1996, p. 144). This idea foreshadows his later work on High Reliability Organizations (HROs); as is discussed in Diane Coutu's conversation with Weick, entitled /Sense
and reliability/.

** References

Coutu, D. L. (2003). Sense and reliability. /Harvard Business Review, 81/(4), 84-90.

Weick, K. E. (1996). Prepare your organization to fight fires. /Harvard Business Review, 74/(3), 143-148.

