#+title: No so 'high speed' Internet
#+slug: no-so-high-speed-internet
#+date: 2007-09-23T18:04:00+12:00
#+lastmod: 2007-09-23T18:04:00+12:00
#+categories[]: Tech
#+tags[]: ADSL Speedtest
#+draft: False

I notice that in [[https://www.orcon.net.nz/][Orcon's]] /Terms and Conditions/ for broadband, there is a paragraph that says:

#+BEGIN_QUOTE

6.1 You acknowledge that any claims made about speed of service are best effort peaks and not guarantees. Speed claims are line speeds only and no guarantees are made for national and international traffic, or any particular type of traffic.

#+END_QUOTE

For sometime, I have been experiencing significant "slow-downs' at peak periods for international traffic. For example, most of the time for national traffic I get about 4,000kbs downstream and 500kbs upstream (I'm on their max/max plan, so that seems reasonable). At off-peak, I get similar speeds (using [[https://www.speedtest.net/][SpeedTest]] to Australia and the US.

Alas, at peak times, my downstream speed is often lower than my upstream speed (i.e. less than 400kbs). In other words, I'm getting at least a 90% reduction in speed.

I've been talking to Orcon for sometime about this, and I'm not sure I'm making progress. They seem to be taking the line about there being "no guarantees are made for national and international traffic".

However, what they don't seem to be talking about their "best efforts" at all.

My feeling is that a 90% reduction is well beyond what might reasonably be expected---on any plan, let alone a max/max plan---and there is little evidence of them using their best efforts.

Oh well, we'll see how this plays out.
