#+title: Approaches to research
#+slug: approaches-to-research
#+date: 2007-01-12T17:28:00+12:00
#+lastmod: 2007-01-12T17:28:00+12:00
#+categories[]: Research
#+tags[]: Methodology
#+draft: False

It occurs to me that that in any research there are three elements to the process, namely:

- The question
- The data
- The answer

Any one of these elements can be used to drive the research process. Of course all three elements have to be present in any successful research project. But, one element is the driver; one element is the point of departure for the researcher's activities.

Traditionally, and firstly, there is the approach that is question driven. This /question centric/ approach can be characterised as "Given everything I know about X what unresolved questions remain?" The question centric approach is typical of many idealised approaches to research---as seen in theses, journal articles, and in many textbooks on research. Classically, the question centric approach is drive by a question (hypothesis) that arises out of the literature. The researcher, having come to terms with a body of literature is left wondering about a particular /curiosity/. I.e. why is related diversification generally more successful than unrelated diversification? From here, the researcher collects the data to test/prove/investigate the question, and come to some answer. The pathway in the question centric approach is: question → data collection → answer.

The second approach is /data driven/. It can be characterised as "Given all of this data [that I have to hand], what question(s) can be answered?" This is often an approach orientated to wards convenience and is much beloved of students and those new to research. In this approach, when confronted with requirement to do research, the researcher's point of departure is "To what data can I easily gain access?" or "What data do I already have?" For example, possibly having spent a lot of time collecting data for another project the research begins to wonder what else the data might reveal. This approach is often associated with poorly enacted or open-ended qualitative research, where the original research question wasn't tightly defined and data collection went ahead because it was possible/practical to so do, rather than because there was a clear need for the data. Here the pathway is typically: data → question → answer.

The final approach, the /know it/ approach, is answer driven. This approach can charactered as "I know X to be true, what do I have to do in order to prove it". The researcher, having been immersed in the literature (or more likely) embedded in the field comes to realise (or assert) that a particular thing is true and that no-one has done much (any) work on it. The researcher then works backwards, from the answer, to the data, then thence to the question (which they ground in the literature). Having the answer in mind, they begin collecting data to prove[fn:1] their contention. They will then ground the question (and ultimately the data and the question) in the appropriate literature. Thus the pathway in this approach is: answer → data → question.

The question I will leave you with is, which approach is best/most effective/most efficient?

[fn:1] Of course, the researcher who is scientifically orientated will be a good falsificationist, and will be looking for evidence to disprove the assertion.
