#+title: How to write an article
#+slug: how-to-write-an-article
#+date: 2011-03-05T11:59:00+12:00
#+lastmod: 2011-03-05T11:59:00+12:00
#+categories[]: Research
#+tags[]: Writing
#+draft: False

Once again, from the excellent [[https://secondlanguage.blogspot.com/2010/02/materials-and-craft-skills.html][Research as a second language]], here is a guide to assembling an article.

#+BEGIN_QUOTE

Here's a way of getting started:

1. Articulate an empirical claim in one simple declarative sentence.
2. Articulate a theoretical claim that is somehow implied by the empirical one in another simple declarative sentence.
3. Identify a body of scholarship that is interested in the theoretical claim. You can write a couple sentences about this area of the literature at whatever level of generality your knowledge allows. Try to name specific authors.
4. Within that body of scholarship, identify an acceptable methodology to license the empirical claim. This will likely resemble the method you are thinking of using for your own project: will you be reading documents, conducting interviews, doing surveys, or making on-site observations?
5. Identify the general area of human concern (usually some corner of managerial reality) which makes 1--4 important. Write a couple of sentences about "the time in which we live" that anticipates the much more specific claims you have just made.
6. Identify two or three journals that publish stuff along the lines of 1--5.

OK. Now write about 1,000 words elaborating each of 1--5 with the journals (see 6) in mind. That ought to give you everything you need to fill out the following outline:

- Introduction
- Background
- Theory
- Method
- Results
- Conclusion

#+END_QUOTE

I think that in regard to students who are planning to do a masters thesis, completing the first five steps would be a good basis for a research proposal.
