#+title: Some notes on ethics
#+slug: some-notes-on-ethics
#+date: 2004-07-29T11:52:00+12:00
#+lastmod: 2004-07-29T11:52:00+12:00
#+categories[]: Research
#+tags[]: Ethics MGMT301
#+draft: False

I briefly mentioned, [[{{< relref "20040727-post-exec" >}}][elsewhere,]] about teams seeking to deliberately sabotaging other teams. I don't know if this happens in [[{{< relref "20040308-mgmt-301" >}}][MGMT 301]] or not, but I was thinking about those comments when I read:


#+BEGIN_QUOTE

White, J., & Taft, S. (2004). Frameworks for teaching and learning business ethics with the global context: Background of ethical theories. /Journal of Management Education, 28/(4), 463---477.

#+END_QUOTE

So, I'd thought I'd recount a few of thier ideas, and see if anyone found they relate to the way in which they approach things in general, or the course in particular.

In the article two general Western approaches to ethics are discussed; teleological and deontological. Teleological[fn::Teleology---to do with purposeful action; explaining phenomena by looking at final results.] approaches to ethics focus on the consequences of actions. It is the consequences themselves, whether they result in harm or not, that are evaluated rather than the actions themselves. The major teleological theories of ethics include /utilitarianism/, /egoism/, and care. Utilitarianism[fn::See the works of John Stuart Mill and Jeremy Bentham.] focuses on the social costs or benefits of decisions. A common version of utilitarianism is the idea of /the greatest good for the greatest number of people/. Thus utilitarianism, considers everyone, even if it doesn't benefit everyone. On the other hand, egoism is about obtaining the greatest good for oneself, and doesn't consider anyone else. The ethic of care, whilst also deontological, considers the impact of one's actions on others, and not only considers harm but also peoples feelings. The interesting thing with the ethic of care, is that it explicitly requires one to consider the context in which actions/decisions take place. E.g. are there some conditions where it is okay to kill someone?

Deontological[fn::Deontology---regarding moral obligations.] approaches to ethics sometimes referred to as /the categorical imperative/. That is to say, there are some actions that, in themselves, are intrinsically good. Thus, "A moral person makes an ethical decision based on what is right, using moral principles or rules, /regardless of circumstances or consequences/" (emphasis added, p. 466). But what should these principles or rules be? Citing Kant's view, the categorical imperative is "Every person should act only on those principles that he or she would prescribe as universal laws, applied toe everyone, assuming what is right for one person is right for all persons" (p. 467). There are a number of "regimes' that come from this approach. The /rights perspective/ is based on the notion of basic human rights, such as those articulated in the American Constitution. Similarly, the /justice/ approach seeks to use universal principles to judge what is fair (with variations for compensatory, redistributive, and retributive justice). Finally, the /virtue ethic/ desires that people follow agreed upon rules--- i.e. they live their lives by specific virtues. For me, I tend to use a mixture of both approaches. In some areas (particularly when dealing with students), I tend toward Utilitarian approaches. However, I'm also aware that there are times when I've /bent the rules/ for students because of the situation/context. Then again, if you look at the [[https://qa.cecil.auckland.ac.nz:8000/][Academic Honesty Assistance tutorial]] (Aha---which I helped to develop) you'll see elements of deontology. And no doubt, from time to time, I fall back on egoism. Truth be told, I suspect that we all use a variety of ethical guides for our behaviour. But, I wonder how much our choices, say taking the ethic of care approach, or a justice approach, is driven by a muted reliance on egoism?
