#+title: Times, they are a'changing
#+slug: times-they-are-achanging
#+date: 2004-11-17T19:43:00+12:00
#+lastmod: 2004-11-17T19:43:00+12:00
#+categories[]: Service
#+tags[]: MBA
#+draft: False

Somewhat unexpectedly, the Dean, [[https://staff.business.auckland.ac.nz/b.spicer][Barry Spicer]] sent out an email to the faculty about "Changes at the Graduate School of Business". I say unexpectedly, because tucked at the end of the email was the following:

#+BEGIN_QUOTE

/Peter Smith/, presently Lecturer in Strategy in the Department of Management and Employment Relations, will take over the role of Deputy Director of the MBA from 1 February 2005 as well as teaching in the MBA programme. Peter has had significant business experience in Europe and is himself a graduate of The Auckland MBA programme. He is also the recipient of a distinguished teaching award.

#+END_QUOTE

Whilst this is entirely true, I didn't think it would be announced for another week; and even then, I expected something more "low key'. Anyway, what Barry failed to mentioned was the"why" behind my decision. In essence, I am taking up a part-time role to allow me to devote more time to my PhD. From my point of view it seems like a good plan. Nevertheless, I do regret the work that others will have to pick up (and prepare) for MGMT 301 and MGMT 302. On the plus side, I get to spend more time (and do more teaching) with MBA students.

I don't feel that I am leaving my current department. It is more of a temporary /auf wiedersehen/ until we are all united in the [[https://www.newschool.business.auckland.ac.nz/index.cfm][new building]]. So, after teaching summer school (MGMT 101, Organisation & Management), I'll be off to the GSB. Between now and then, I suspect there is a fair bit of work-to-do.
