+++
title = "Design for learning"
date = 2019-05-30T10:02:29+13:00
draft = "False"
categories = [ 
	"Jottings", 
	"Learning", 
    "Capstone"
	]
+++

This is my application for a CLeaR Fellowship for 2020 in the theme
'Design for learning.

Overview
========

As a result of Faculty of Business and Economics review of the
Bachelor of Commerce and the Bachelor of Property, the faculty has
recently given approval, in principal, for the piloting and
introduction of a range of capstone courses. Capstone courses
represent an important thrust by the Faculty to address a range of
pressing issues.

In particular, as the paperwork accepted by Faculty notes, the justification of capstones are: 

* Provides opportunity for students to demonstrate achievement of
  graduate capabilities and enhance employability skills as well as
  assist their transition to work.
* Incorporating work-related experiences into the degree will improve
  performance in rankings and student surveys
* Greater flexibility to be more experientially based if sits outside
  the major(s)

A range of options supported provides the flexibility to accommodate
the diversity of student capabilities (feasible to set specific
prerequisites, limitations and minimum GPA requirements to manage
selection) including  cross-disciplinary capstone options that enable
students to bridge their two fields of interest. 

The Faculty of
Business and Economics is not the only faculty to begin moving down
this pathway; for example, the Faculty of Science is already in the
process of developing its own suite of disciplinary-based capstone
courses. With regard to the 2020 Fellowship them of _Designing for
Learning_, capstones implicitly are concerned with issues of
equity, engagement, motivation, graduate attributes, and
employability, and personal growth. Anyone of these presents
significant challenges in a regular course; in a capstone
course---when many stakeholders have competing conceptualisations of
what they are meant to do and to deliver---the heady mix of these
aspirations is challenging (to say the least). Given the aspirations
for capstone courses and the challenges the present, there are three
components to the fellowship proposed here. 

1. As a particular approach to teaching and learning, capstone courses
are under researched. Nevertheless, an important first step in to
undertake a literature to review to understand the evidence that
supports the design and deliver of capstone courses (in particular,
rather than in general), with a view to publishing that literature
review.
2. Furthermore, capstone present a variety of design challenges that
either do not exist in 'regular' courses or are less important. For
example, under what conditions should a capstone course focus on
knowledge coordination between students versus knowledge integration
(given students from different majors will be working together). Thus,
it is necessary to develop an understanding of the gaps that exist in
the literature and the programmes of research that might address the
most pressing of those gaps.
3. Finally, it is important to map out, record, and disseminate the
learning that occurs across the University as capstone courses are
piloted and then fully rolled out. In doing so a network of colleagues
working on similar problems---beyond the Fellowship programme, e.g.
Dr Julia Novak in Science---may emerge, increasing the success of the
capstone initiatives.


Current achievements in teaching
================================

With regards to teaching, I am a multi-award winning academic (with
teaching excellence awards both at the faculty level, and the
university level) for curriculum design, innovation in teaching, and
collaboration in learning. Colleagues who have won University and
National teaching excellence awards often cite my influence in their
teaching portfolios (e.g., A/Prof Christine Woods, Andrew Eberhard). I
have successfully completed the certificate in Academic Practice.

Alignment with Fellowship aims and university plans
===================================================

The justifications for capstone courses, presented in the earlier
section are necessarily directly connected to the Business School's
Strategic Plan, the University's Strategic Plan, and University's
Learning and Teaching Plan and Strategic Plan. Given that this
fellowship is in direct support of those justifications, this
fellowship is also aligned with those planning documents.

Desirable outcomes from the Fellowship year
==========================================

1. A published literature review of teaching and learning in capstone
   course;
2. Identification of a programme of research to address gaps in the
   literature vis-a-vis the 'peculiarities' of capstone courses;
3. The documentation and publication of the University's learning
   around captstone courses, and; 4 The creation of a community (of
   excellence?) regarding capstone courses across the university.
