#+title: My Unsolicited Commercial Email (UCE or spam) Policy
#+date: 2003-02-18T13:43:00+12:00
#+lastmod: 2003-02-18T13:43:00+12:00
#+categories[]: Tech
#+tags[]: Spam
#+slug: my-unsolicited-commercial-email-uce-or-spam-policy
#+draft: False

It is our strong belief that Unsolicited Commercial Email (UCE) or SPAM is one of the biggest problems facing internet users today. To combat SPAM we have set up a fairly intensive series of tests that all email through this developmental server must-pass.  First, the mail must pass through Vipul's Razor, which is a collaborative SPAM-detection and filtering network. Next, the mail must pass through a series of Procmail recipes (courtesy of Concordia University's IITS). Once that mail has passed these rigorous tests, it is delivered to the mailing list, developer, or other user it is intended for.  This system is not perfect. It will not filter out all SPAM sent through this server (though, it will hopefully do a sufficient job of it). It may also filter out legitimate messages. If you find that your mail is being filtered, please see the note below.  Another way we combat SPAM is by reporting any and every abuse that is sent to us back to Vipul's Razor. For this purpose, we have set up a "SPAM Trollbox", which is an account that no legitimate mail should be sent to.

*HELP! My mail is being filtered but it isn't SPAM!*

First of all, don't panic. There are many reasons why a perfectly legitimate email is filtered as if it were SPAM.

The most common reason is that your ISP, web host, or email server is a known sender or relayer of SPAM. If this is the case, then it is not your fault, but the fault of whomever is responsible for the server that handles your email. To rectify this situation, you may have to contact your ISP, web host, or system administrator and have them tighten their restrictions against abuse.  In extreme cases, you may even have to switch who handles your email server.

If you suspect that your valid e-mail is being filtered as SPAM, then please contact me.

