#+title: Project charter
#+date: 2021-09-19T16:42:00+1300
#+lastmod: 2021-09-19T16:42:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management Project_Charter

A project charter is a document that contains all the details of the project. Project charters clearly define the project and its goals and outline what is needed to accomplish them.

A project charter allows you to get organized, set up a framework for what needs to be done and communicate those details to others.

Once you've drafted the charter, it should be reviewed with key stakeholders to get their approval to move into the [[{{< ref "202109121932-project-phase-planning" >}}][planning phase]].

The project charter:
- Helps organize vital project information
- Helps create a framework for the work that needs to be done
- Helps communicates those details to the necessary people
- Is useful as a reference

 The project charter contains:
  - Summary: provides an overview of the project and outlines the goals it is hoped to accomplish
  - Goals: The desired result of the project
    - Determined by input from the Stakeholders and the Project Manager
  - Deliverables: The specific tasks and tangible outcomes that enable the team to meet project goals
  - Scope: The boundaries of the project (and what's out of scope)

A project charter is also a tool to get alignment between stakeholders.

* Backlinks
- [[{{< ref "202109191630-project-initiation-components" >}}][Project initiation - components]]
- [[{{< ref "202109121932-project-phase-planning" >}}][Project phase - planning]]
