#+title: Now
#+date: 2023-01-23T11:47:52+13:00
#+lastmod: 2023-01-23T11:47:52+13:00
#+categories[]: Social
#+tags[]: Reflection
#+draft: False
#+weight: 110
#+url: /now

My [[{{< ref "about-me" >}}][About Me]] page provides a thumbnail sketch of who I am. This page, is more about what I'm doing and planning to do now.

# more

* Travel plans
I am now back in New Zealand having spent most of last year travelling as part of my sabbatical/Research and Study Leave.

This year I hope to go to:

- [X] Brisbane for a workshop
- [ ]Byron Bay, to see relatives
- [ ] Zurich, to catch up with colleagues and attend an Open Strategy Workshop
- [ ] Milan, for the EGOS Conference
- +[ ] Istanbul (very unlikely) for the SMS conference.+


* Research projects
1. Orchestrating multi-sided platforms (Journal of Information Technology)
2. The microfoundations of strategy tools (British Journal of Management; an early version has been accepted for this year's Academy of Management Conference in Chicago)
3. The communication of science. This was reject and is now being reworked to address its shortcomings.
4. Thoughtworlds (Human Relations)
5. Revises EGOS paper on Open Strategy and boundary-crossing


* Activities
- Learning backgammon


* Watching
- +The Gone+ This was an outstanding show.
- Some cosy crime

* Listening to
- My own playlist of what I like to most
- I'm in the process of re-recording all my music using the .flac format (having previously been in the Apple ecosystem). This is a long process.

* Reading
- The joys of [[https://libbyapp.com/library/auckland][Libby]]; listening to too many audio books ::smile::
