#+title: Now
#+date: 2023-01-23T11:47:52+13:00
#+lastmod: 2023-01-23T11:47:52+13:00
#+categories[]: Social
#+tags[]: Reflection
#+draft: False
#+weight: 110
#+url: /now

My [[{{< ref "about-me" >}}][About Me]] page provides a thumbnail sketch of who I am. This page, is more about what I'm doing and planning to do now.

The biggest thing is that I'm now on Research and Study Leave (RSL/sabbatical) for a year (until 23 January 2023). So much of what I'm doing now---work wise---is about my research projects.

Other things are sort of hanging off that big endeavour.
# more

* Travel plans
- Visit to the University of Zurich

  From April to August, I'll be visiting with [[https://www.business.uzh.ch/en/research/professorships/om/team/staff/seidl.html][David]] [[https://scholar.google.cz/citations?user=vdrx0DIAAAAJ][Seidl]] and his research group at the [[https://www.uzh.ch/en.htm][Univserity of Zurich]].

- Visit to the [[https://www.uio.no/english/][University of Oslo]], June 2023.

  The plan is to work with my co-authors on our paper on multi-sided platforms.

- [[https://www.egos.org/2023_Cagliari/General-Theme][European Group on Organizational Studies]] (EGOS), 6th--8th July 2023 in Sardinia,

  I regard EGOS as my intellectual home as far as conferences are concerned. With Covid-19 and other things it's been a few years since I was last at one ([[https://www.egos.org/2016_naples/general_theme][Naples, 2016]]).

- [[https://aom.org/events/annual-meeting][Academy of Management Annual General Meeting]] (AoM), 4th--8th August 2023 in Boston.

  This will be my first time at AoM. Normally, it would clash with my teaching obligations, but this year, as I'm on Research and Study leave ...

* Research projects
1. The comminication of science  - Rejected, reworking for resubmission
2. Instructional design for interdisciplinary learning (AoM) - submitted
3. DAOs, Open-strategy, and trust (EGOS)
4. Orchestrating multi-sided platforms (Journal of Information Technology)
5. Thoughtworlds (Human Relations)
6. Wayfinding and internationalisation (Oxford Professional Service conference)
7. +Multiple commitments and+ Inovative Work Behaviours

* Activities
- (re)Learning German.

* Watching
- Beef
  I thought this was going to be more fun. But being a 'completist' I'll see it through.
- Anatomy of a scandal

* Listening to
- My own playlist of what I like to most

* Reading
- Graham Allcott --- How to be a productivity ninja: Worry less, achieve more and love what you do
- A. C. Grayling --- The frontiers of knowledge: What we know about science, history and the mind
  I am mainly reading this for the last section on the mind and cognitive neuroscience.
