#+title: What I look for in a learning journal
#+slug: what-i-look-for-in-a-learning-journal
#+date: 2015-08-13T14:30:00+12:00
#+lastmod: 2015-08-13T14:30:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT300
#+draft: False

A student asked me what I look for in a learning journal.

Ultimately, what I hope to see is one thing that the student will do differently as a result of the week (doing MGMT 300). In other words, have they demonstrated that learning has taken place.

My general approach in reading learning journals is to look for:

- Is it clear what problem the author is tackling
- Is it clear what the author will do differently (or decide not to do)
- If, those are in place, I then look for the connecting logic (steps, 2 and 3 of Daudelin's approach).

With regards to feedback from peers, overall, what I am currently seeing is a lot of people being overly nice in their feedback (as they try to avoid being 'harsh'). They are giving a lot of "positive strokes" around things in the learning journals that are not necessarily about the degree of learning that the journal demonstrates. This is happening even in the face of some rather ho-hum learning journals
