#+title: Scrum - Sprints
#+date: 2021-10-02T11:52:00+1300
#+lastmod: 2021-10-02T11:52:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management Scrum

Within a Sprint (aka an iteration), the amount of work is planned based on the historical capacity of the team and is made ready for the Sprint Planning event.

Each sprint is a mini-project comprising: planning, execution, delivery, closing, and a retrospective.

There are five events in Scrum, but they all revolve around the Sprint. They are:
- The Sprint (1 to 4 weeks long)
- Sprint planning
- Daily Scrum
- Sprint Review
- Sprint Retrospective

Each of these events have a *Timebox*. These provide:
- A sense of urgency which will drive prioritization
- A window of focus which will translate into productivity
- Help the team develop a predictable rhythm to their work.

The timebox for a Sprint is driven by:
1. What you expect the frequency of changes to be
2. How much time focused time the 'developers' need to build a Product Backlog ite,
3. How much overhead goes into the delivery of the product

During the Sprint:

- No changes are made that would endanger the Sprint Goal;
- Quality does not decrease;
- The Product Backlog is refined as needed; and,
- Scope may be clarified and renegotiated with the Product Owner as more is learned.

Sprints enable predictability by ensuring inspection and adaptation of progress toward a Product Goal at least every calendar month. When a Sprint’s horizon is too long the Sprint Goal may become invalid, complexity may rise, and risk may increase. Shorter Sprints can be employed to generate more learning cycles and limit risk of cost and effort to a smaller time frame. Each Sprint may be considered a short project.

Various practices exist to forecast progress, like burn-downs, burn-ups, or cumulative flows. While proven useful, these do not replace the importance of empiricism. In complex environments, what will happen is unknown. Only what has already happened may be used for forward-looking decision making.

A Sprint could be cancelled if the Sprint Goal becomes obsolete. Only the Product Owner has the authority to cancel the Sprint.


* Backlinks
- [[{{< ref "202109131858-scrum" >}}][Scrum]]
