#+title: Argentina
#+slug: argentina
#+date: 2006-04-05T09:43:00+12:00
#+lastmod: 2006-04-05T09:43:00+12:00
#+categories[]: Teaching
#+tags[]: MBA
#+draft: False

I had an interesting and thought provoking email from a student regarding the choice of Argentina as the destination for the trip that takes place as part of the /International Business/ (IB) course. He said:

#+BEGIN_QUOTE

Sorry if I sounded dismissive of your enthusiasm for South America. I am sure that you have a good plan in place. But I do believe strongly That the plan should surely be based on what to do first, rather than where to do it ...

I personally would be very excited to visit South America ... But I would be somewhat uneasy that you perhaps cited some exceptions of trade there proving the rule that NZ's isolation really places its trade base first in the Pacific Rim (which of course includes quite a bit of S America before you say it).

I hope to make links throughout the MBA course within and beyond NZ in the hope of using them into the future for careers, business, etc. I kind of figured that the natural 'address' of such links would be closer to SE Asia, China, India, Malaysia, Indonesia, or the USA before Argentina. Perhaps you are performing the function of broadening my horizons.

Not that I am anti your plan---as I say, I am sure there are good things to do and good bases for the trip.

#+END_QUOTE

The student is asking an excellent question, "What is the purpose behind choosing Argentina?"

I think the "what to do" is well understood; but within that framework there is considerable flexibility as to "where to do it". That doesn't mean that the two parts, are independent of one another; they are also interlinked. As I outline my thinking, I hope that this becomes apparent.

I may be being defensive, but my use of examples in Chile and Argentina were intended show the plausibility and practicality of having a relationship with those countries, whether it be through trade or FDI etc., rather than to say they were a natural choice. Perhaps, I could have said more that that, and so I welcome the student's email as a chance to expound the choice of Argentina.

Let's begin by looking at the "the natural address" for such a trip. That is to say, on the basis of trade, where are the links between N and the rest of world. Grabbing the first set of figures I could find (2004), the pattern looks like this:

#+BEGIN_QUOTE

  Exports: Australia 21%, U 14.4%, Japan 11.3%, China 5.7%, U 4.7%

  Imports: Australia 22.4%, U 11.3%, Japan 11.2%, China 9.7%, Germany 5.2%

#+END_QUOTE

On that crude basis it would seem that the natural address would be Australia or maybe the U. But, when you look at individual industries (let alone individual firms) the pattern is quite different. I'm sure if we were to consider each student's firm and their probable strategies, there wouldn't be an overall natural choice of destination. (And so, maybe going for the 'aggregate' natural address isn't a bad idea.)

Given a specific firm's unique situation, to load the dice by saying that there is a 'natural linkage' may lead to problems. Albeit based on anecdotal evidence, I feel that too often New Zealand firms move into Australia because "that's what everyone one else does", rather than having a clear strategic purpose in doing business with that country. CER and other free-trade deals are great if there is a strategic advantage in trying to build a strategy around them[\^1].

For example, yesterday, I was talking to a CEO who is in exactly this predicament, and is the process of unwinding a decision his predecessor made to enter Australia. Even though Australia is our largest trading partner (and probably will be for some time) it behoves a strategist to consider other alternatives too[\^2].

But before looking in any more depth at the 'natural addresses' for the I trip, I wonder:

- To what extent should the IB trip mirror that pattern of export/import activities?
- What allowance should be made for the anticipated future trends in trade relationships?
- Should we help students to consider other "non-traditional" areas where N might be able to exploit an advantage?
- To what extent are the experiences and learning from the IB trip/project transferable to other international contexts?

Taking such questions into consideration seems to expand the option set rather than narrowing it down.

But, the last point is probably the most important. I would hope that the I course gives the student ways to understand the wider implications of doing business international; rather than a narrower, for example, "How do I trade with China".

Pragmatically, I know that the preference for some of the class is to go to China, others to the UK, and so on. I also know that, unsurprisingly, the educational objectives behind our choice of destination, and students (sometimes focusing on the more immediate needs of their firm) result in different "answers".
