#+title: Extreme Programming (XP)
#+date: 2021-09-26T15:47:00+1300
#+lastmod: 2021-09-26T15:47:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management XP

Another agile methodology.

Since XP came out of the software industry, it refers to specific software terms and activities like coding and programming, but the XP method can be used in lots of non software environments as well. The XP methodology aims to improve product quality and the ability to respond to changing customer needs. It does this by taking best practices for the development process to extreme levels.

- Test first development
-

* Core XP activities
- Designing: in software development, this is where you write a design document describing the parts of the code or instructions for the product and how it will function. In non-software environments
- Coding: XP demands clear and concise code, so that others can easily read and understand the program. This makes it easier to troubleshoot problems and come up with solutions.
- Testing: This means checking the product for flaws so they don't end up in the final product. In XP, more is better. So if a little bit of testing can eliminate a few flaws, lots of testing will eliminate even more. The goal is to test for and eliminate any flaws in a feature before building it and continuing on.
- Listening: This is about listening to the customer and ensuring that the requirements are integrated into the product. This relates to agile in the way that it values customer collaboration, frequent communication and regular feedback.

* Innovative practices
- Pair programming
  Two team members work together at the same time on one task
- Continuous integration and Continuous refactoring
  Merging product changes into a shared version of the product.
- Avoid big design upfront
  Design just enough to get started, and should be continuously improved as product evolves
- Write tests not requirements
  Embedded product requirements into the test plan

* Backlinks
- [[{{< ref "202109131850-agile-project-management" >}}][Agile project management]]
