#+title: Recruiting and CVs
#+slug: recruiting-and-cvs
#+date: 2004-07-21T10:23:00+12:00
#+lastmod: 2004-07-21T10:23:00+12:00
#+categories[]: Teaching
#+tags[]: Teams MGMT301 Mikesbikes
#+draft: False

As part of the course [[{{< relref "20040308-mgmt-301" >}}][MGMT 302]] student's have to prepare a CV (well, complete a form that asks for some specific details) and get some /work experience/ using Solo Mike (aka Mike's Bikes Advanced--Single Player).

A few people seem to be having problems in raising their shareholder value (SHV) from about $9 to $25 in four of five years. In the past we have seen students who are able to double their SHV every year. E.g. in four years, their SHV will be over $70.

Anyway, what is worth noting is that when Solo Mike is started, there is an area in the simulation where a record can be made of the strategy that the player intends to use--and in this area a default strategy has been filled in already--and its a good strategy. If students follow it (in Solo Mike anyway) they should do okay. Thinking of CVs I'm reminded of a time a few years ago. Imagine someone sitting at home. They have five identical positions for an entry level economist to fill, and over 300 people have applied for the job. So, they have a box (or two) containing 300 CVs. Each CV has been 'stripped'. Any fancy binding has been removed, as has any fancy covers--doing that it makes it easier to handle and file the CVs. They create three piles:

- Definitely not
- Maybe
- Yes--go forward

In the next three or four hours they are going to go through the CVs (that's as many as 100 an hour, or just over 40 seconds each). Any flaws in the CV (spelling mistakes, missing information, poor grades) go straight in the /Definitely not/ pile.

The covering letter is used to distinguish between those in the /Maybe/ and those in the /Yes/ piles. At the end of the evening there are 40 CVs in the /yes/ pile, 80 in the /maybe/, and the rest are definitely not. Given the number of CVs that got a /Yes/, the /Maybes/ are never looked at again. (Oh, they never mentioned it in the advert, but they a looking for people who have worked well in teams; in undergrads, this often means they look for people who have played a lot of team sports, or have worked in a team--no team experience results in the CV being a /Maybe/ instead of a /yes/.)

The next day, the 40 CVs are whittled down to 20, those twenty go forward for psych testing. Not even an interview yet ... At least in MGMT 301 we have exactly the same number of jobs as there are students.
