#+title: The Sharp GX17
#+slug: the-sharp-gx17
#+date: 2006-07-21T21:40:00+12:00
#+lastmod: 2006-07-21T21:40:00+12:00
#+categories[]: Tech
#+tags[]: Phones
#+draft: False

I've replaced my old phone. My [[https://www.nokia.co.uk/nokia/0,8764,18177,00.html][Nokia 6310]] has been retired.

I tend to only use my phone in the car (with a [[https://www.blueant.com.au/][Blue Ant]] [[https://www.blueant.com.au/supertooth2.htm][car kit]] but I've always wanted to use the old Nokia with my laptop. Alas, the bluetooth implementation on the Nokia seems to be a bit flaky to say the least. Firmware upgrades, new PC software had no effect; the connection to the PC was always difficult (aka impossible).

Everyone else around me seems to be getting new phones (and the [[https://www.motorola.com/motoinfo/product/details/069,00.html][Motorola Razr]] seems particular popular), but all I want is a phone that does bluetooth well and that I can /manage/ through my PC. I don't particular want a camera, play games, download, ring-tones. Bluetooth is all I really need.

Anyway, I was passing [[https://www.coolmobile.net.nz/][Cool Mobile]] in the city and went in and had a look at their parallel imported products. I was pleasantly surprised to bump into a former MGMT 101 student working there. The end result is that I've brought a Sharp GX17. Not a new model by any means. Not G3. But I think it will do want I want it to do.

Being an impulse buyer, I didn't stop to check the price with [[https://www.vodafone.co.nz/][Vodafone]]. After the event I found I could get it $20 cheaper through Vodafone. Que sera.
