#+title: Mike's Bikes Message Board
#+slug: mikes-bikes-message-board
#+date: 2004-04-02T10:17:00+12:00
#+lastmod: 2004-04-02T10:17:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301 Mikesbikes
#+draft: False

Every Friday, when teaching MGMT 301, I check [[https://www.smartsims.com][Net Mike]] to see if everything is ready for the roll-over later in the day. If I have time on my hands I also read the message board that is built into Net Mike.

I wonder what sense an ethnographer would make from the messages that are left there? What verbs would she or he use to describe the type of messages? What purpose would he or she ascribe to the messages? Over the years, I've seen that there are patterns. Overwhelmingly, the messages are from the males--so far that means /96% of the messages/! Rarely, do the messages rise above the level of graffiti.

However, from time to time individuals and teams do something different, more meaningful (that's a value judgement on my part). However, the general pattern of content at the team, region, and world level goes as follows.

- /At the team level/, that is to say those messages that can only be seen by a single team, the messages to be of the type "Hi", or "Did we do well", or "Aren't we doing badly".
- /At the region level/, e.g. only the teams in Auckland can see the message, or only the teams in Napier can see them, the messages seem to be loaded with bravado "Don't mess with us", is a frequent statement.
- /At the world level,/ which everyone cans see, the messages are quite aggressive with calls for companies to get together and "take /so and so/ down".

I wonder what drives this. Is it escalating commitment of some type? Testosterone? Or is it as simple as a need to leave a mark saying "We were-here".
