#+title: Project risk management
#+date: 2021-10-17T12:07:00+1300
#+lastmod: 2021-10-17T12:07:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

The process of identifying potential risks and issues which could impact a project, and evaluating and appling steps to address the effects of the identified risks and issues.

A *risk* a potential event which can occur and can impact your project.

Whereas an *issue* is a known or real problem that can affect the ability to complete a task.

Risk management provides an understanding of:
- What could go wrong
- Who you will need to consult
- How the risks could be mitigated

By failing to plan for risk, you also fail to think through the many different ways that your project could pivot and still meet its goals if an issue does arise.

When an issue arises, it is important to /keep calm/ figure out the root cause of the problem, and come up with a solution.

* Phases of risk management

Risk management is an ongoing practice throughout the life cycle of your project. It typically involves some variation of these five steps:

- Identify the risk.
- Analyze the risk.
- Evaluate the risk.
- Treat the risk.
- Monitor and control the risk.

Let’s break these down:

1. Identify the risk. The first phase of the risk management process is to identify and define potential project risks with your team. After all, you can only manage risks if you know what they are.

2. Analyze the risk. After identifying the risks, determine their likelihood and potential impact to your project. Serious risks with a high probability of occurring pose the greatest threat.

3. Evaluate the risk. Next, use the results of your risk analysis to determine which risks to prioritize.

4. Treat the risk. During this phase, make a plan for how to treat and manage each risk. You might choose to ignore minor risks, but serious risks need detailed mitigation plans.

5. Monitor and control the risk. Finally, assign team members to monitor, track, and mitigate risks if the need arises.

* Uncover opportunities using risk management

When you think about risks, it is likely that you automatically think of potential negative events. But when identifying risks, it is important to also consider the good things that could happen, which are considered opportunities. An opportunity is a potential positive outcome of a risk. It is important to recognize opportunities and to capitalize on them as they appear so you can reach your project goals faster, more cheaply, or with less effort. Some examples of opportunities include:

- Completing a milestone ahead of schedule
- Discounted materials
- Availability of additional resources (people, investments, equipment)

** How to recognize an opportunity

An opportunity is a potential positive outcome that may bring additional value to a project. You can use the same tools and techniques that you use in risk managementidentify, analyze, evaluate, treat, and controlto add potential opportunities to your risk management plan. You need to know what to do if things go wrong, but you should also make plans to seize opportunities. By using techniques such as brainstorming and drawing on project history or prior experience, you can identify potential opportunities and outline how you will take advantage of them if they occur.

As a project manager, you should always be on the lookout for potential opportunities when developing your risk management plan. Review the following article for further information on using risk management strategies to identify and take advantage of opportunities that may occur during your projects:  [[https://www.pmi.org/learning/library/effective-strategies-exploiting-opportunities-7947][Effective strategies for exploiting opportunities]]


** Risk Response PlanningCurrent Practice

Most risk management guidelines recognize at least four types of strategy in responding to identified risks. Hillson (1999a, 1999b) defines risk response strategy types as:

- Avoids---seeking to eliminate uncertainty
- Transfer---passing ownership and/or liability to a third party
- Mitigate---reducing the probability and/or severity of the risk below a threshold of acceptability
- Acceptre---cognizing residual risks and devising responses to control and monitor them

* Backlinks
- [[{{< ref "202109121932-project-phase-planning" >}}][Project phase - planning]]
