#+title: National League Case Competition
#+slug: national-league-case-competition
#+date: 2008-09-08T18:12:00+12:00
#+lastmod: 2008-09-08T18:12:00+12:00
#+categories[]: Teaching
#+tags[]: CaseComps
#+draft: False

[[https://web.archive.org/web/20081014045333/https://mcc.auckland.ac.nz/][We]] won the first [[https://web.archive.org/web/20081014113353/https://www.business.otago.ac.nz/com/usergroups/currentstudents/buscasecomp/index.html][National League Case Competition]].

As [[https://www.auckland.ac.nz/uoa/about/news/articles/2008/06/business_school.cfm][the new Dean]] said:

#+BEGIN_QUOTE

The University of Auckland Business School has been crowned Champions of the inaugural National League Case Competition sponsored by Deloitte.

The league began at Otago University on May 9th with three more preliminary rounds in Christchurch, Hamilton and Wellington before a three-round final held last week at Massey.

Auckland went into the final week 5 points behind the University of Waikato. The scoring system for the League placed a greater weighting on the final rounds, so the team had to deliver in every round to be successful. They started well with two close seconds on Monday and Wednesday and although Auckland had a 50 point lead over Otago going into the final day the outcome was still uncertain.

The fledgling New Zealand Feijoa Industry was the subject of the final case and the team produced another strong performance to once again, finish a close second! Their consistency of performance was ultimately what carried the day..

#+END_QUOTE

Well done to "head coach" Brendon Potter and to the students in the teams.
