#+title: Strategic management and the philosophy of science
#+slug: strategic-management-and-the-philosophy-of-science
#+date: 2004-09-07T14:47:00+12:00
#+lastmod: 2004-09-07T14:47:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301 Knowledge Ontology Epistemology
#+draft: False

Paula Jarzabkowski (2004) has recently had one of articles published in Organization Studies. Her article is based on an earlier [[https://research.abs.aston.ac.uk/working_papers/0212.pdf][working paper]] she wrote a few years ago. Good on her for getting it in to a tier-one journal. As it happens, Paula will be visiting the [[https://web-beta.archive.org/web/20100505010923/https://www.business.auckland.ac.nz][department]] in November and will be giving a couple of seminars. If you're interested in strategy (and who isn't), then I would commend her seminars to you.

Anyway, as I was reading her article, my attention was drawn to:

#+BEGIN_QUOTE

Mir, R., & Watson, A. (2000). Strategic management and the philosophy of science: The case for a constructivist methodology. /Strategic Management Journal/, 21(9), 941--953.

#+END_QUOTE

The abstract for Mir & Watson article goes like:

#+BEGIN_QUOTE

  In this paper, we suggest that constructivism has the potential to inform research in strategic management. The realist paradigm currently dominates strategy research, and constructivism, a well-established tradition in the philosophy of science, is often ignored. However, a study of strategy literature and research reveals that it is drawn upon more frequently than is explicitly acknowledged. Constructivism occupies a methodological space characterized by ontological realism and epistemological relativism. Ontological realism is an important cornerstone of a field as applied as strategy, while epistemological relativism helps us explore the constructed nature of the field, where the researcher is an active participant rather than a reactor or information processor. In this paper, we demonstrate the precedents and possibilities for constructivist research in strategic management. We examine some of the existent constructivist works in the strategy literature, and point to specific techniques, including historical analysis, to demonstrate how this perspective may advance the boundaries of strategy research.

#+END_QUOTE

For the constructivists, researchers are seen as skillful craftsmen [sic], much in the same way as strategists are seen in strategy-as-practices (no wonder Paula used this article in her work). Whilst there isn't total agreement as too the nitty-gritty of constructivism, Mir & Watson say there is agreement on six main principles, viz:

- Knowledge is theory driven
- The separation of researcher and the phenomena under investigation is not possible
- The separation between theory and practice is not equally unfeasible
- Researchers are never 'objective' or value-neutral
- Research occurs within a 'community' of scholarship where mutually held assumptions are deployed to create 'conversations'
- Constructivism constitutes a 'methodology' [rather than a method]

It is interesting to counterpoint /constructivism/ with /realism/. Citing Leplin, the authors say that realism is typified by ideas such as:

- the best theories are those that are close to the truth;
- the truth of a theory explains (and is the only explanation of) its predictive validity;
- we are moving progressively towards a true account of a phenomena
- the claims made by any theory are either true or false
- only through the deployment of 'reason' can a theory be proven or refuted

It's interesting to contrast (and compare) those views with [[{{< ref "what-use-is-theory" >}}][my own]] about theories. So despite having some constructivist tendencies, there are still elements of realism in the way I think. Nevertheless, I do reject the notion that there are abstract universal principles[fn::Nomothetic, by another name.] when it comes to research.

As it happened, I used this article as an opportunity to revisit my understanding of classic research issues of ontology[fn::Ontology--a theories of objects and things. More particularly, what things are knowable and what things can't be known. Main types of ontology are empiricism, rationalism, pragmatism, constructivism.] and epistemology[fn::Epistemology--regarding the truth or falsehood of knowledge. How can we prove if something is true or false (given what we can know... ontology). I hope I've got these round the right-way.].

I liked the quote from Foucault that was used:

#+BEGIN_QUOTE

We must not imagine that the world turns towards us a legible face, which we would have only to decipher; the world is not an accomplice to our knowledge; there is no prediscursive providence which disposes the world in our favor. /We must conceive analysis as a violence we do to things, or in any case as practice which we impose on them/ (emphasise added).

#+END_QUOTE

That strongly reminded me of David Thomas'es /clues/ or /cues/ comments. Anyway, this will be a helpful article when I write the method chapter of my thesis.

* References

Jarzabkowski, P. (2004). Strategy as practice: Recursiveness, adaptation and practices-in-use. /Organization Studies, 25/(4), 529--560.
