#+title: Project kick-off meeting
#+date: 2021-09-27T18:58:00+1300
#+lastmod: 2021-09-27T18:58:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

Serves as a formal start to the project initiation

* Project kick-off meeting
The first meeting in which a project team comes together to ground everyone in a shared vision, gain a shared understanding of the project's goals and scope, and to understand each person;s individual roles within the team.

* Attendees
- Project team - identified in the [[{{< ref "202109251549-raci-charts" >}}][RACI charts]]
- Project stakeholders
- Project sponsor

* The importance of the meeting
- To establish a shared vision
- To align on scope
- To build team rapport
- To allow team members to ask questions and offer insights
- To set expectations

  This is all extra important on large project.

* Kick-off meeting structure
There are lots of templates online, but most are like this. Most last about an hour

- Introductions
- Background to the project
  - How the project came to be
  - Why the project matters
  - Set a shared vision
- Share goals and the scope of the project
  - What's in-scope
  - What's out-of-scope
  - Target launch date
  - Important milestones
- Roles
  - What work everyone is responsible for throughout the project
- Collaboration
  - Shared project tools and documents
  - How the team will communicate
- What comes next
  - Set expectations and actions items
- Questions from the group
  - Gain clarity on meeting topics
  - Ensure the project benefits from diversity of thoughts, experiences, and ideas.

* Best practices
- *Set the right time*. Choose a meeting time that works for everyone. Be mindful of time zone differences.

- *Set the right length*. Choose an appropriate meeting length no more than one hour. You don’t want to waste people’s time, but you also don’t want to run out of time. Kick-off meetings work best when you first share key information and then spend any additional time on questions and team building.

- *Invite the right people*. Be strategic about including the appropriate people. The goal is to invite attendees who play a role in the development and execution of the project, such as all team members, stakeholders, and the project sponsor. You don’t want to leave anyone out, but you also don’t want to invite people who shouldn’t be there.

- *Designate a notetaker*. The discussion that takes place during the meeting is important. It is critical that you document any feedback, changes, or questions asked by attendees. If you are leading the meeting, designate someone else to take notes before the meeting starts. You can also use tools like Chorus Notetaker, Google Keep, Google Docs, or Microsoft OneNote.

- *Set the agenda*. To recap what we discussed in the video, a kick-off meeting agenda should generally include: introductions, the project background and purpose, project goals and scope, roles and responsibilities, the collaboration process and project tools, what comes next (expectations and action items), and time for questions and discussion.

- *Share the agenda*. Prior to the meeting, share the agenda with attendees via email and identify speakers for each topic. By sending the agenda in advance, everyone will have an idea of what to expect, time to prepare for anything they may need to present or discuss, and time to generate questions or ideas.

- *Stick to the agenda*. During meetings, discussions can sometimes go off topic or take longer than expected. As a project manager, it is your job to keep the meeting on track by redirecting discussions to the items on the agenda.

- *Follow up after the meeting*. After the meeting, make sure to send out a meeting summary featuring the meeting notes and any action items.

* Backlinks
- [[{{< ref "202109121932-project-phase-planning" >}}][Project phase - planning]]
