#+title: Literature and management
#+slug: literature-and-management
#+date: 2004-04-11T12:00:00+12:00
#+lastmod: 2004-04-11T12:00:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301 Double-loop
#+draft: False

I was reading [[https://www.mediatinker.com/blog/archives/008326.html][Media Tinker]] when I came across the quote /A foolish consistency is the hobgoblin of little minds/ by Ralph Waldo Emerson. A quick trip to [[https://www.bartleby.com/59/3/foolishconsi.html][Bartleby]] confirmed its providence as coming from his 1841 essay [[https://www.farid-hajji.net/books/en/Emerson_Ralph_Waldo/es1-selfreliance.html][Self-reliance]].

It would be easy to make some half-baked link from this quotation to the topic for next week's class on /single and double loop learning/. But, his essay is neither short, nor a straightforward; and such a link would do little credit to me (and no credit to Emerson). Taking these few words out of their complete context is a naive thing to do. I seem to recall [[https://www.handels.gu.se/gri/gribcza.html][Barbara Czarniawska]] (who likes to link management and [[https://www.amazon.com/exec/obidos/ASI/0198296142][literature]]) once saying that a good way to study management is through great novels and stories. I'm not an aficionado of Emerson---he wasn't on my reading list at school---but what I do know about him makes me think that Barbara would be happy to engage with his work.

Thus, I think it would be really interesting for someone to weave the Emerson essay and the issues that will be presented in next week's class (and indeed throughout the whole course) together.
