#+title: Project initiation - components
#+date: 2021-09-19T16:30:00+1300
#+lastmod: 2021-09-19T16:30:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

The key components of project initiation are:

*** Goals
The goal is what you have been asked to do and what you are trying to achieve.

- Benefits from "very in depth active listening"

*** Scope
The process to define the work that needs to happen to complete the project.

*** Deliverables
Products and services that you will create for your customer, client, or project sponsor.

May be:
- tangible or,
- in-tangible.

*** Success criteria
The standards by which you measure how successful a project was in reaching its goals.

*** Stakeholders
The people who both have an interest in, and are affected by, the completion and success of the project.

Often many of the other key components are determined with the stakeholders.

Need to understand all this, and ensure alignment between the various stakeholders.

Consequently, "When you initiate project, you can't invest enough time in meeting with stakeholders".

*** Resources
:PROPERTIES:
:ID:       919e7251-a51e-4603-b859-5bd1eb64ef83
:END:
For example:
- Budget,
- People,
- Materials, and
- other things that will be needed to complete the project.

This forms the basis of the [[{{< ref "202109191642-project-charter" >}}][project charter]].


* Backlinks
- [[{{< ref "202109121929-project-phase-initiation" >}}][Project phase - initiation]]
- [[{{< ref "202109191642-project-charter" >}}][Project charter]]
- [[{{< ref "202109191731-project-goals" >}}][Project goals]]
- [[{{< ref "202109191732-project-deliverables" >}}][Project deliverables]]
