#+title: Abigail's Party
#+slug: abigails-party
#+date: 2004-03-28T09:25:00+12:00
#+lastmod: 2004-03-28T09:25:00+12:00
#+categories[]: Arts
#+tags[]: Theater
#+draft: False

Last night, Lisa and I went to see /Abigail's Party/ at the [[https://www.maidment.auckland.ac.nz/][Maidment Studio]]. As the program says:

#+BEGIN_QUOTE

North London, 1997---the year of the Queen's Silver Jubilee. The Sex Pistols are gearing up to blow Donna Summer and Jose Feliciano out of the charts forever. The neighbours have been invited around for a few drinks, maybe a bit of dancing, and if you're lucky, light snobbery, relentless bullying and social humiliation.

#+END_QUOTE

Yes, it's a /get the guest/ play. I do enjoy those. Perhaps my chums at [[https://www.psychodrama.org.nz/atcp.html][ATCP]] will have some thoughts on that.

We really enjoyed the play. It was very well done.

Two of the players stand out for a special mention. Bernadette Brewer played Beverly. She was wonderfully over the top, and her dress was a feat of engineering. Also, Linda Johns was marvellous as Sue, the divorced neighbour. Her timing and demeanour were perfect.

Whilst we were at the theatre, I bumped into Tony. He was in the first cohort of the [[https://www.bbim.auckland.ac.nz/][BBIM]] at [[https://www.business.auckland.ac.nz/comwebContent/index.cfm?fs=pgv&pageid=8031][Tamaki Campus]]. I was surprised that I remembered his name as it has been over four years since I taught him. He must have completed his degree and be in the first graduating year of the BBIM. That is a great achievement. /Well done, Tony/. I'll be looking forward to seeing him cross the stage at the [[https://www.auckland.ac.nz/cir_students/index.cfm?action=display_page&page_title=studentadmin_graduation][graduation ceremony]] in May.

Anyway, he seems to be working for [[https://www.business.auckland.ac.nz/departments/techsite/index.cfm?fuseaction=rebuild&subaction=home][Tech Site Services]], so I guess the IM part of his degree is paying off.

