#+title: Future orientated sensemaking
#+date: 2020-05-12T23:30:00+1300
#+lastmod: 2020-05-12T23:30:00+1300
#+categories[]: Zettels Articles
#+tags[]: Sensemaking Theory

#+BEGIN_QUOTE

  Gephart, R. P., Topal, C., & Zhang, Z. (2011). Future‐oriented sensemaking: Temporalities and institutional legitimation. In T. Hernes & S. Maitlis (Eds.), /Process, sensemaking, and organizing/. Oxford University Press, Incorporated. http://ebookcentral.proquest.com/lib/auckland/detail.action?docID=3055841

#+END_QUOTE

This paper takes a stance that is ontologically different to Weick's approach to sensemaking.

For Gephart, sensemaking is an inherently social process, unlike Wieck who has a cognitive view as to what happens in making sense of the world.

It's not clear to me that the two views are actually compatible.

Gerphart draws on Emirbayer and Minch re Agency and Structure, Ethnomethodology, and Institutional rhetoric in setting up their take on sensemaking. Indeed, many of the cites---particular re ethnomethodology---seem to pre-date and somewhat anticipate Weick's work.
