#+title: Project resources
#+date: 2021-09-25T19:06:00+1300
#+lastmod: 2021-09-25T19:06:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management Resources

The three main project resources are:

1. Budget: An estimate of the amount of money a project will cost
2. People: The team of people who execute the project
3. Materials: Items you need to get the project done

** Budget

With only a certain amount of funding to cover each expense, it is important to closely monitor your spending to avoid going over budget.

Common aspects of your project budget will include:

- Team: the cost of the people performing the work
- Services: any outside vendors helping your project
- Materials: any tangible items purchased to complete the project

Throughout your project management career, you will encounter various types of projects with a wide range of budgets. Some budgets will have no margin for error, whereas other budgets may be more flexible. Regardless of this variability, budget issues will inevitably arise, so it is important to make sure that the budget is aligned with the project scope and the stakeholders’ asks.

** People

People are a vital resource on your project; you cannot complete your project on your own! You will need to rely on a strong team of people with a variety of skill sets and specialties to get the job done. As a project manager, make sure that you have commitment and buy-in on the number of hours it will take for your resources to complete their tasks. Additionally, you will find the best partners on a project are people who are aligned to the goals of the project or who are most interested in the project's work.

** Materials

Materials can be different on every project. For example, if you were working on an IT project, materials could include hard drives and computers to handle the coding efforts. You can also have materials that are intangible. For example, on the same IT project, online storage, software programs, or employee training may also be considered materials. It is important to account for any and all potential materials in order to execute a successful project with the right people and within budget.

* Key takeaway

Your project resources include things like the budget, people, and materials. As a project manager, remembering that your resources are dependent on one another is key to understanding the function of each resource and determining how to manage all of them. Take the time to interview stakeholders and potential team members about what resources they think they will need in order to deliver the project. They may have an idea of materials they require that you may not have accounted for within the budget, for example, or can identify people with expertise that would make them an asset to the project team.


* Backlinks

- [[{{< ref "202109121929-project-phase-initiation" >}}][Project phase - initiation]]
- [[{{< ref "202109251428-project-stakeholders" >}}][Project stakeholders]]
- [[{{< ref "202109251908-project-charter" >}}][Project charter]]
- [[{{< ref "202109251912-project-tools" >}}][Project tools]]

