#+title: Project milestones
#+date: 2021-10-03T12:02:00+1300
#+lastmod: 2021-10-03T12:02:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

*Milestones*: An important point within the project schedule that indicates progress and usually signals the completion of a deliverable or phase of the project.

* The need/importance for milestones
- Setting milestones gives you a clear understanding of the amount of work your project will require.
- Help keep your project on track (it sets deadlines)
- Help uncover areas where you might need to adjust scope, timelines, or resources to meet your goals.
- Reaching milestones can seriously motivate your team, and illustrate real progress to your stakeholders
  - A great check-in point with stakeholders to highlight your progress
- Milestones must be completed on time and in sequential order

Note some deadlines may be flexible, and some may be non-negotiable.

* Setting milestones
1. Evaluate your project as a whole --- refer back to the project charter and the project goal
2. Make a list of the big items needed to achieve that goal
   - The big items that indicate progress are your milestones.
   - The small items, that a stakeholder won't need to review, are tasks

* Assigning milestone deadlines
- Milestones need to be spaced out to give your team room to complete their work.
- To get a good sense of timing, you can connect with teammates to discuss the tasks required to reach each milestone and get their estimates for how long these tasks will take.
- With those estimates in mind, you can make an informed decision about reasonable deadlines for each milestone.
- When you set deadlines for milestones, you will also want to consider the needs of your stakeholders.
- Understand when stakeholders will reasonably want to see progress/milestones.

* Setting tasks to identify milestones

Setting tasks can help you clearly define milestones. You can do this in two ways:

- *Top-down scheduling*: In this approach, the project manager lays out the higher-level milestones, then works to break down the effort into project tasks. The project manager works with their team to ensure that all tasks are captured.

- *Bottom-up scheduling*: In this approach, the project manager looks at all of the individual tasks that need to be completed and then rolls those tasks into manageable chunks that lead to a milestone.

Most projects have many tasks that lead to milestones. For instance, if your milestone is to receive approval on the first draft of an article that you are writing, you might complete tasks such as “develop outline,” “write first draft,” and “send to the editor.” Then, you may have another set of tasks to achieve before reaching the milestone of revising the article. Milestones serve as check-in points along your project to make sure that you are headed in the right direction toward the end goal. Milestones also make projects more manageable.

* Milestone-setting pitfalls

- Don’t set too many milestones. When there are too many milestones, their importance is downplayed. And, if milestones are too small or too specific, you may end up with too many, making the project look much bigger than it really is to your team and stakeholders.

- Don’t mistake tasks for milestones. Remember that milestones should represent moments in time, and in order to map out how you will get to those moments, you need to assign smaller tasks to each milestone.

- Don’t list your milestones and tasks separately. Make sure that tasks and milestones can be visualized together in one place, such as a project plan. This will help ensure that you are hitting your deadlines and milestones.

* Backlinks
- [[{{< ref "202109121932-project-phase-planning" >}}][Project phase - planning]]

