#+title: That hurt
#+slug: that-hurt
#+date: 2008-05-04T19:05:00+12:00
#+lastmod: 2008-05-04T19:05:00+12:00
#+categories[]: Home
#+tags[]: Fitness Accident
#+draft: False

I went ice skating with my brother and his children (Mac, Oscar, and Stevie). The rink ([[https://www.paradice.co.nz/][Paradice]] at Botnay Downs), looked pretty nice and I decided to upgrade to "Platinum' skates. Alas, they only do"Platinum' for hockey skates, and I'm a figure-skating sort of a guy. So, I ended up with a very average pair or rental skates.

Anyway, to cut to the chase, so to speak, I took a tumble and ended up with my left arm in plaster. It's only a small break so I should be out of the cast in three weeks time---and I'm counting the days already. Having an arm in a cast is no fun at-all.

Bill was highly amused by it all. He has taken some pictures and I'll post them if he ever sends them-to-me.

Actually, I thought I had just jarred the joint, so I kept skating for about an hour. It was only when I got into the car and tried to change gear that I said "that-hurt".

So, Ascot Hospital was the nearest A&E. What a long wait. Wait to see a nurse. Wait to see the doctor. Wait to see the radiologist. Wait to see the doctor (again). Wait to get plastered.

All in all, I was there for over three-hours.
