#+title: TinyTex
#+date: 2018-06-14T11:05:54+12:00
#+lastmod: 2018-06-14T11:05:54+12:00
#+categories[]: Tech
#+tags[]: Tinytex Tex Bookdown
#+slug: tinytex
#+draft: False

I have had ongoing problems using =biber= =bookdown= and =laxtex= to produce PDFs. So, I decided to throw out the package =texlive-full= and start again. That didn't work and I uninstalled it again and went looking for an alternative.

I knew that [[https://yihui.name/][Yihui Xie]] had produced a distribution of LaTex called [[https://yihui.name/tinytex/][TinyTex]]. So I thought I'd give it a go.

Well that was journey. Here are some notes for anyone else trying to get this excellent looking package to work under FreeBSD 11.1

First, deinstalling =texlive-full= (the FreeBSD package) leaves traces all over the system. It's messy to find the bits. In the end I had to search the =~/.TinyTex= tree and delete anything on the rest of the system that matched names (crude but effective).

Secondly, during installation I got a number of errors, e.g.,

#+BEGIN_SRC sh

fmtutil: running `xetex -ini -jobname=xetex -progname=xetex -etex xetex.ini' ... Shared object "libfreetype.so.9" not found, required by "xetex"

#+END_SRC

On this particular installation, l have:

#+BEGIN_SRC sh

/usr/local/lib/libfreetype.so

/usr/local/lib/libfreetype.so.6

#+END_SRC

So I cheated and linked libfreetype.so to libfreetype.so.9. That allowed the package to install cleanly.

Finally, to =bookdown= to compile to a PDF (the whole point of the exercise)

I kept on getting errors about =biblatex= not finding apa (my referencing style of choice/necessity). Because I erroneously believed it was installed, it took forever for me to figure out I need to do:

#+BEGIN_SRC sh

  tlmgr install biblatex-apa

#+END_SRC

and then, being British, it was easy to do

#+BEGIN_SRC sh

  tlmgr install babel-english

  #+END_SRC

And now it all seems to work. That said, I've not tried producing any PDFs from the other .tex and .md files I have laying around.
