#+title: Average Grades--The average of grades
#+slug: average-grades-the-average-of-grades
#+date: 2006-10-07T08:59:00+12:00
#+lastmod: 2006-10-07T08:59:00+12:00
#+categories[]: Teaching
#+tags[]: MBA Grading
#+draft: False

Entry in to the Auckland MBA™ programme, and progress through the programme is regulated by the use of average grades. For example, to move from the first year of the programme to the second year, one needs to achieve an average grade of B or better. Likewise, to enter the programme from the Postgraduate Diploma in Business, one also needs a similar grade.

As I've discussed [[{{< relref "20060422-grading" >}}][elsewhere]] the combining of grades is not straightforward, and consequently neither is "averaging".

So how do I do it when looking at the grades of students. As a pragmatic response I look at both the mean and the median. The advantage is that the median reduces the impact of outliers, but there are problems with the median when the marks are quiet divergent. Overall, I'm looking for the central tendency ... is the student really a B student (or better). So, like most things it is down to a bit of math and some good judgement.
