#+title: Principles of email communication
#+date: 2021-11-04T18:55:00+1300
#+lastmod: 2021-11-04T18:55:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

Email has long been the primary method of communication for many people in business, yet messages are easy to misunderstand or ignore. In this reading, we will discuss four principles of effective email writing that will help your emails to stand out, be remembered, and elicit the response you need. These principles are:

- State what you want clearly.
- Keep the content short and concise.
- Structure your writing.
- Check grammar, punctuation, and spelling.

* Principles of effective email writing

** State what you want clearly

When you set out to compose an email, it is because there is something that you want from your reader. You might want to receive a simple answer, to persuade someone of something, or to arrange a meeting. Before composing an email, think about what you want, when you need what you want, and the best way to get what you want when you want it. 

Here are some tips on how to clearly state what you want in your email:

- Include your request in the subject line of your email.
- State your request within the first two paragraphs of your email message.
- Indicate the specific call-to-action associated with your request (for example, reply, review, RSVP).
- Write clear, concise sentences when providing details.
- Define terms. Avoid using acronyms and terminology that users may not know. Provide additional information as necessary to avoid misunderstanding. 

** Keep the content concise

Make your words work for you. Remove any writing that doesn’t help to define what you want or contribute to your reader's needs.

- Summarize the content you want to convey, and remove anything in your email that doesn’t contribute to your goal.
- Aim to write “question-less” and “self-standing” emails. This means that the message contains enough information to stand on its own. The reader shouldn’t have any questions about what you want and when you want it.
- Know your audience. Some peoplesuch as executives and other busy leadershipmay not want to read emails of more than a few sentences or click on external links for further information. Try to tailor your emails accordingly.

** Structure your writing

Structure has to do with the visual flow, or aesthetics, of your email. A well-structured email conveys critical information to the reader quickly and allows them to scan the explanatory textor ignore it altogether. Here are some tips for effectively structuring your email:

- Use bullets. Bullets break up the visual flow. If you have more than one of something, consider using bullets. Write strong action verbs at the start of each bullet.
- Use labels. Labels help guide the reader to what information is most important. 
- Add hyperlinks. Hyperlinks allow readers to directly access additional information, rather than adding lengthy details to your email.
- Write a strong topic sentence. Place the main idea of the paragraph in the topic sentence. 

** Check grammar, punctuation, and spelling

Grammar, punctuation, and spelling are critical. Turning grammar and spelling suggestions on in your email application can help you quickly identify errors. Be sure to correct any errors before sending off. 
Applying effective email writing principles

* Key takeaway

When you write an email, think about the people you are sending it to and what they need in order to quickly read and correctly understand it. Remember to:

- State what you want clearly.

- Keep the content concise.

- Structure your writing.

- Check grammar, punctuation, and spelling.

Keeping these principles in mind when you draft emails will help you communicate more effectively with your team members, stakeholders, customers, and others. It can also demonstrate your level of professionalism and competence and inspire others’ confidence in your abilities. 



* Backlinks
- [[{{< ref "202111041851-project-communication" >}}][Project communication]]

