#+title: Operational effectiveness: Necessary but not sufficient
#+slug: operational-effectiveness-necessary-but-not-sufficient
#+date: 2008-10-18T16:12:00+12:00
#+lastmod: 2008-10-18T16:12:00+12:00
#+categories[]: Research
#+tags[]:  Strategy Porter
#+draft: False

In his HBR article /What Is Strategy/, Porter argues that operational effectiveness does not represent a strategy. In other words, planning to be the most "operationally effective" is not a strategy.

But I wonder how true this is. Having looked at, and worked with, many SME (Small and medium enterprises), they often have low levels of operational effectiveness. However, much of the time it doesn't matter because /they are as effective as the firms with whom they compete/. Operational effectiveness is a relative term. Providing a firm is similar to its rivals in operational effectiveness, operational effectiveness cannot provide an edge.

In large firms, management has often paid been a lot of attention to operational effectiveness. Consequently, any further improvement is likely to have limited impact; all the firms tend to be very good, so the cost/benefits of becoming more operationally efficient is limited.

However, this isn't the case in SME. Because they are often relatively operationally inefficient (compared to their larger brethren), there are significant improvements that can be achieved at relatively low cost. Thus, such improvements can be a source of significant "differentiation" for a firm.

* References
Porter, M. E. (1996). What is strategy? /Harvard Business Review, 74/(6), 61--78.
