#+title: Fast writing
#+slug: fast-writing
#+date: 2007-06-07T12:12:00+12:00
#+lastmod: 2007-06-07T12:12:00+12:00
#+categories[]: Research
#+tags[]: PhD
#+draft: False

At yesterday's [[https://www.phd.business.auckland.ac.nz/][PhD Club]] meeting, [[https://www.auckland.ac.nz/uoa/cpd/about/ourpeople/barbaragrant.cfm][Barbara Grant]] from the Academic Practice Group of the [[https://www.cad.auckland.ac.nz/][Centre for Academic Development]] came along to talk about [[https://phd.business.auckland.ac.nz/node/39][Embedding writing in the PhD process]]. Many people know Barbara; she runs a number of writing retreats (for women) and she has a great "rep' for helping people with their writing. One techniques she talked about was /fast writing/. In fast writing one writes, non-stop, for about 10 minutes. One doesn't worry about the typos or getting the words right. It is just a matter of getting the words out on to paper (or as in this case on to the screen).

This blog entry started as a piece of fast writing---although I did go back and tidy it up a little (but not too much). The purpose of fast writing is too fold, firstly and perhaps most importantly, it gets one more practised in the writing process. To of tern we spend time worrying about "is that word the right/best one", or "what am I really trying to say". And when we do that that, we don't actually put anything down on paper--- we simply tinker with what's on the screen/paper.So, fast writing gets one to actually start producing content. As a side effect, sometimes one will be surprised by the insights that come out during fast writing---when one is really thinking about the material and not about the get the expression "just right".

Secondly, fast writing does what? I'm not sure what the second thing is. I could go back and refer to my notes, but then I'd have to stop writing; and writing is what its about. Ah yes. That's it. Fast writing gets you to keep on going, to get past the blockages that come up (rather like the one here---which wasn't a pre-considered example, it really happened).

So, given the advantages of fast writing, Barbara recommends that is becomes part of ones practice as an academic. She says, that one should try and do five sessions of fast writing each week (i.e. one each working day). Mentally, I had to laugh at that---I don't know any of my fellow PhD candidates who limit their work to the five-day working week.

Having said that, my supervisor, Peter Boxall, is there keen that his PhD students (such as myself) do find a healthy work-life balance.

Anyway, my 10 minutes of fast writing up so, I'm ending here, and go back and tidy up this entry.
