#+title: Kill Bill
#+date: 2004-05-01T09:36:00+12:00
#+lastmod: 2004-05-01T09:36:00+12:00
#+categories[]: Arts
#+tags[]: Movies
#+slug: kill-bill
#+draft: False

Well at last I saw [[https://www.imdb.com/title/tt0378194/][Kill Bill Volume 2]]. I was going to buy [[https://www.imdb.com/title/tt0266697/][Kill Bill Volume 1]] and watch it first, but alas I couldn't find a copy. I had assumed because it was for rent at Videon that I was on general release---but alas no luck. It seems that there are a few Zone 1 recordings available (at a price) and few Japanese recordings too (which come with a "free' sword). Of course, the move has been cut differently for the two markets. Anyway, back to Kill Bill Volume 2. I do wish I'd seen Volume 1 again first. The movie pretty much starts where the second one ends, and there isn't a lot of scene setting---it really is a second volume, rather than a sequel.

Much of the movie is stylised after other (obscure) genres, and there are many "in jokes'. At one stage, I reminded of every"Kung Fu' movie I'd ever seen when living in Germany[fn::Back then, most movies were dubbed into German, and, to start with my German was so good. But I found that I could enjoy Chinese movies because of the style signalled the meaning of what was going on, so the words were less important. Bring back the [[https://www.imdb.com/title/tt0061597/][One armed swordsman]]].

Some of the scenes where quite harrowing; for example the entombment of Beatrix Kiddo (Uma Thurman) was masterfully done. As I was watching the credits at the end[fn::Is that a surprise? That I watch movies all the way through? E.g. For a laugh, watch [[https://www.imdb.com/title/tt0268380/][Iceage]] (a cartoon) and see who the caters are.], I noticed that the writing credits were to /Q+U/, which Lisa quickly pointed our was [[https://www.imdb.com/name/nm0000233/][Quentin]] (which I had guessed) and [[https://www.imdb.com/name/nm0000235/][Uma]].

That started me off wondering about the film-makers art. It seems that nowadays, many movies are written a produced (and sometimes acted) by the same person. I wonder why that is? What is the impact on the person who aspires to be a writer, only to find that a "star' has their ideas accepted over the writers.

How might this play our in organisations? Or is it playing out in them now?

Oh well, tomorrow it's going to be comedy with [[https://www.gregproops.com/][Greg Proops]]. That'll be a change from the carnage of Kill-Bill.
