#+title: A desire to be assessed
#+slug: a-desire-to-be-assessed
#+date: 2008-08-06T12:49:00+12:00
#+lastmod: 2008-08-06T12:49:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT302
#+draft: False

My /Strategic Thinking/ class (MGMT 302) is going reasonably well.

Nevertheless, there are a couple of things that are noticeable in the class. Firstly, in the first class of the week--which is based on a test to motivate the students to read the text in a timely fashion--the students are reluctant to engage in conversation about the readings they have done. It's not clear to me why that is. At this stage my two hypotheses are:

- They have other things they want to do, and see focusing on the test as a way to get the class over quickly.
- They have crammed for the test, and the what to get to it before they forget anything they have "learnt".

Obviously, these are just guesses on my part. But why does it matter.

It matters, because experience tells me that if they engage in 30 minutes of discussion about the readings the average class mark goes up: indeed most students do better as a result of such discussions (it's not just the less prepared learning more). Furthermore, talking about the readings helps to cement the 'information' and makes deeper connections about the material for them.

I think in class today, I'll try and engage them on this.

The second thing I noticed, is that there is little evidence, in the subsequent case discussions, that they have looked at the figures in any meaningful way (or looked at them at all). I might leave this issue for next week--although I'll let them know that it can be a sure-fire way of bumping up one's grade in this course.
