#+title: Bye bye Facebook
#+slug: bye-bye-facebook
#+date: 2017-06-08T15:38:11+12:00
#+lastmod: 2017-06-08T15:38:11+12:00
#+categories[]: Social
#+tags[]: Facebook
#+draft: False

I have decided to leave Facebook, and to leave it properly. I have deleted most of my content, and instructed Facebook to [[https://www.facebook.com/help/delete_account][delete my account]]. So, after a withholding period of a couple of weeks, all my data Facebook should deleted. Interestingly, it is hard to find the *delete* link on the Facebook site. Everything seems to point to 'just' deactivating the account, as opposed to permanently expunging it.

That said, I have downloaded an archive of my posts, etc, from Facebook, and will be merging the interesting ones back into my blog.

I particular, I will spin out all my running posts and any interesting photo-based posts. I will also scan all the exported posts to see if there is anything of note that should go up in my blog.

But why have I chosen to leave?

There are two main reasons. Firstly, the folk at Facebook are very good at getting me to spend time on their site; indeed, I have wasted far to many hours 'facebook-ing'. Secondly, I am increasingly concerned about how Facebook uses my data (and my meta-data), how Facebook shares that data (and thus how others use that data). There are plenty of very credible sources of the influence that Facebook driven 'interventions' in processes such as voting can have. (See for example, the Panorama special on Facebook, or the reports of how Cambridge Consulting uses Facebook data).

So, I am out of here.
