#+title: PhD Seminar
#+draft: False
#+date: 2004-06-17T20:29:00+12:00
#+lastmod: 2004-06-17T20:29:00+12:00
#+categories[]: Research
#+tags[]: PhD PSFs
#+slug: phd-seminar

Today, I gave a department seminar on my PhD topic /Strategising in professional service firms/. I've posted a copy of the [[file:files/Dept_Seminar.pdf][slides]] in case anyone in interested.

If found it strangely nerve wrecking. As I said at the start of the presentation "How do I know what I think until I've said it". With such a view, I suppose it is unsurprising that I was nervous. On a technical note, I had a few problems with the presentation. I decided to use a tree-like structure for the slides, i.e. a main trunk, of about four slides, branching of to many supporting slides. This was all done using hyperlinks. Alas, I found the hard way that you can't hyperlink (in PowerPoint) to a slide whose title contains an apostrophe. E.g. A title such as /The people's choice/. This made some of the slide titles clunky, to say the least. Secondly, I set up a transparent block as a hyperlink on each of the branches, that should have returned me to the main "trunk'. Oddly, sometimes it is really easy to"select' the block (i.e. to click on it), but on some slides it only works if you click on the edge of the block. This is most frustrating and I haven't gotten to the bottom of the problem yet. But overall, I was please with the mechanics of the presentation. The general feedback I had (from the small, but select audience) was that it was a solid presentation. I found the discussion we had at the end very useful. Special thanks need to go to [[https://staff.business.auckland.ac.nz/bcarroll][Brigid]] and [[https://staff.business.auckland.ac.nz/rwolfgramm][Rachel]] for their helpful comments.
