#+title: Sociodrama
#+date: 2004-03-11T14:23:00+12:00
#+lastmod: 2004-03-11T14:23:00+12:00
#+slug: sociodrama
#+categories[]: Home
#+tags[]: Psychodrama
#+draft: False

[[https://web.archive.org/web/20050307052941/https://www.colearnz.co.nz/][Judith McMorland]] and I have decided to run a short seminar or workshop for postgrad students, Doctoral candidates, and staff. The title of the seminar is /Exploring the year ahead: creating responses to challenges and
change/ and the flyer promises:

#+BEGIN_QUOTE
An experiential participatory workshop for PhD and Masters students journeying into 'unknown territory' of postgraduate study (thesis writing, data gathering, interviewing, maintaining self, holding it all together?). We will identify typical and specific challenges and changes and explore ways of devising enlivening responses.
#+END_QUOTE

The basic plan is to do some role training. And before you ask, what's
role training:

#+BEGIN_QUOTE
Role training is an effort to help us perform adequately in future situations. It is a method of learning that aims to bring about a rise in the spontaneity level of an individual and combine this with practice of a new expression. Making an apparently minor change in an area of our functioning, which we recognise as a role or part role, can result in a ripple effect in a larger sphere or system. Role training focuses on the development of one aspect of a role, but has in its larger view the transformation of the groups and culture in which we live.

[[https://web.archive.org/web/20041114040426/https://psychodrama.org.nz/programme_wpti_training.html][Wellington Psychodrama Training Institute]].
#+END_QUOTE

Anyway, at the bottom of the flyer is says that I'm a /sociodramatist in training/. So, I shouldn't be surprised that some (thanks Karla) has asked "what's a sociodramatist"? So, as a trainee, I suppose it would be generally a /good thing/ if I briefly outlined what sociodrama is about. Firstly, let me start by saying that sociodrama is not intended to be the therapeutic; whereas psychodrama, which is from the same stable, is intended to therapeutically useful. Thus, the sociodramatist tends to work more with typical roles, e.g. a student who is Peter, rather than psychodramatic roles e.g. Peter as a student. Secondly, sociodrama is an action method---there is a lot of "doing", as situations are enacted out at various levels of abstraction and concreteness.

The sociodramatist is concerned with the social networks of the protagonist; and so overall the sociodramatist seeks to improve the efficacy of people in groups. It is a method that helps one work with groups---this is probably a gross simplification, and perhaps those who are more experienced would say it differently, but it is my current working definition.

I've been doing sociodrama for a little over a year know, and I am slowly "getting it'. But, I suspect it will take many more years before it really makes sense; hence the title "sociodramatist in training".

