#+title: Face-to-face contact in teaching: Some lessons
#+slug: face-to-face-contact-in-teaching
#+date: 2020-08-24T08:50:47+13:00
#+lastmod: 2020-08-24T08:50:47+13:00
#+categories[]: Teaching
#+tags[]: Online
#+draft: False

* In-person teaching

I have been thinking about how much face-to-face contact (or more correctly, in-person contact) matters when teaching. Given we know that there is no statistical difference in learning outcome between on-line and in-person education. What I'm why does the 'fact-to-face' issue keep surfacing. To that end, I've been reading.

#+BEGIN_QUOTE

Muilenburg, L. Y., & Berge, Z. L. (2005). Student barriers to online learning: A factor analytic study. /Distance Education/, 26(1), 29–48. https://doi.org/10.1080/01587910500081269

#+END_QUOTE


* Factors affecting student satisfaction with online learning

 Looking at what students perceive to be the barriers to online education, it identifies eight factors that explain 62% of the variance in the results of their survey. They are:

#+CAPTION: Source: Muilenburg and Berge (2005)
| <l>                              |   <r> |           <r> |          <r> |
| Component                        | Total | % of variance | Cumulative % |
|----------------------------------+-------+---------------+--------------|
| Administrative/instructor issues | 13.04 |         13.19 |        13.19 |
| Social interactions              |  4.81 |          9.54 |        22.73 |
| Academic skills                  |  2.97 |          8.68 |        31.41 |
| Technical skills                 |  2.43 |          8.16 |        39.56 |
| Learner motivation               |  2.07 |          7.46 |        47.02 |
| Time and support for studies     |  1.66 |          6.10 |        53.12 |
| Cost and access to the Internet  |  1.29 |          5.15 |        58.28 |
| Technical problems               |  1.06 |          4.13 |        62.41 |

# more

 In more detail, those factors are:

 1. /Administrative/instructor issues/. Students perceive barriers that administrators and instructors control, such as course materials not always being delivered on time, lack of sufficient academic advisors online, and lack of timely feedback from the instructor.
 2. /Social interactions/. These are obstacles to online learning that students perceive as being caused by a lack of interaction with peers or the instructor, such as the lack of student collaboration online, the lack of social context cues, or their being afraid of feeling isolated in online courses.
 3. /Academic skills/. This factor concerns respondents’ perceived barriers to online learning due to their lack of academic skills in such areas as writing, reading, or communication.
 4. /Technical skills/. This factor concerns respondents’ perceived barriers to online learning due to their lack of technical skills such as fearing new tools for online learning, lack of software skills, or their unfamiliarity with online learning technical tools.
 5. /Learner motivation/. Respondents answered whether they had certain characteristics that would affect their motivation in online courses such as whether they procrastinate, choose easier aspects of an assignment to complete, or feel the online learning environment is not inherently motivating.
 6. /Time and support for studies/. This factor concerns the respondents’ perspectives on whether a lack of time or support from family, friends, or people in the work place causes barriers to their online learning.
 7. /Cost and access to the Internet/. This factor concerns whether the respondents find access to the Internet too expensive, fear the loss of privacy, confidence, or property rights, or otherwise find access to the Internet limited to the point of raising barriers to them.
 8. /Technical problems/. This factor concerns such things as a lack of consistent plat forms, browsers, and software, or the lack of technical assistance that causes obstacles to online learning.

 So perhaps rather than thinking about this in terms of a lack of face-to-face interaction, it is more about perceived lack of social interaction with peers and instructors. Intuitively, that makes more sense.

 This factor---Social interaction---is driven by six sub-items:

 - Lack of interaction/communication among students
 - Online learning seems impersonal
 - Afraid of feeling isolated
 - Lack of social context cues
 - Lack of student collaboration
 - Prefer to learn in person


 The authors do some further analysis to assess the priority (rather than the importance) of the items, and /Social interaction/ comes top of that list.


 What is perhaps more interesting is that the /Social interaction/ item halves in it's effect the more courses someone has done on-line. I.e., once they find out that those six-sub items are not necessarily a problem when doing on-line courses.

 There was also a strong correlation between enjoyment of the course and /Social interaction/.

 It's all food for thought.
