#+title: Globalization
#+slug: globalization
#+date: 2004-08-04T10:10:00+12:00
#+lastmod: 2004-08-04T10:10:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT302
#+draft: False

I subscribe to a number of journals, so every week or so, something new to read appears in my mail box. It's often hard to keep up with the volume of reading (and I'm not even reading some "standards", such as AMJ). Anyway, the latest edition of /Strategic Organization/ has landed on my desk. I've recommended it to the library but judging by the library's catalogue it isn't generally available in the University.

Each issue contains an editorial essay, and I thought the following one would be very useful to my strategy students (albeit for later in the course). The article is called:

#+BEGIN_QUOTE

Delacroix, J. (2004). Another monkey on our backs: Falsehoods and truth about globalization. /Strategic Organization, 2/(3), 313--322.

#+END_QUOTE

Unlike the readings in the MGMT 302 textbook, which argues about the tension between globalisation and localisation, this article focuses on the bad press that globalisation has been getting (as /demonstrated/ at Seattle, Cancun, etc).

Having read the article, I can't help feeling that like the myth of globalisation as a source of [[https://www.hartford-hwp.com/archives/25/046.html][evil]] (as it is portrayed on many [[https://www.google.com/search?q=globalization+evil][websites]]) needs to be properly considered, rather than accepted (as politically driven rhetoric). It reminds me of the claims that the pace of change is faster than ever before ... I'm still waiting to see the /hard/ evidence.
