#+title: Project procurement documentation
#+date: 2021-10-13T07:16:00+1300
#+lastmod: 2021-10-13T07:16:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

* Non-disclosure agreement (NDA)
The purpose of an NDA is to keep confidential information within the organization.

Doesn't change as the project goes on.

* Request for proposal (RFP)
A document that outlines the details of the project to be passed on to vendors to solicit bids
- Overview
- Goals
- Scope of work
- Milestones
- Submission requirements
- Questions for the vendor to answer

  Doesn't change as the project goes on.

* Statement of Work (SOW)
A document that clearly lays out the products and services a vendor or contractor will provide for the organization.

Often SME (subject matter experts) provide input for things in which the project manager is not an expert.

Often reviewed by the organization's legal advisors.

The SoW will often go through several rounds of reviews and they should be record.

* Backlinks
- [[{{< ref "202110121942-project-procurement" >}}][Project procurement]]
