#+title: Project Scope
#+date: 2021-09-23T16:34:00+1300
#+lastmod: 2021-09-23T16:34:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

"an agreed upon understanding as to what is included or excluded from a project."

Scope helps ensure that your project is clearly defined and mapped out. That means knowing exactly who the project will be delivered to and who will be using the end result of the project.

How do you actually figure out the scope of your project? It's simple: talk to your sponsors and stakeholders, understand what their goals are, and find out what is, and this is really important, what is not included in the project.

A clearly defined scope describes all the details of a project and regulates what can be added or removed as it progresses.

Scope creep.


* Scope management best practices
:PROPERTIES:
:ID:       839c5198-45f4-4462-83c5-161b575454a3
:END:

The scope of a project can get out of control quicklyso quickly that you may not even notice it. Scope creep is when a project’s work starts to grow beyond what was originally agreed upon during the initiation phase. Scope creep can put stress on you, your team, and your organization, and it can put your project at risk. The effects of scope creep can hinder every aspect of the project, from the schedule to the budget to the resources, and ultimately, its overall success.

Here are some best practices for scope management and controlling scope creep:

- Define your project’s requirements. Communicate with your stakeholders or customers to find out exactly what they want from the project and document those requirements during the initiation phase.

- Set a clear project schedule. Time and task management are essential for sticking to your project’s scope. Your schedule should outline all of your project’s requirements and the tasks that are necessary to achieve them.

- Determine what is out of scope. Make sure your stakeholders, customers, and project team understand when proposed changes are out of scope. Come to a clear agreement about the potential impacts to the project and document your agreement.

- Provide alternatives. Suggest alternative solutions to your customer or stakeholder. You can also help them consider how their proposed changes might create additional risks. Perform a cost-benefit analysis, if necessary.

- Set up a change control process. During the course of your project, some changes are inevitable. Determine the process for how each change will be defined, reviewed, and approved (or rejected) before you add it to your project plan. Make sure your project team is aware of this process.

- Learn how to say no. Sometimes you will have to say no to proposed changes. Saying no to a key stakeholder or customer can be uncomfortable, but it can be necessary to protect your project’s scope and its overall quality. If you are asked to take on additional tasks, explain how they will interfere with the budget, timeline, and/or resources defined in your initial project requirements.

- Collect costs for out-of-scope work. If out-of-scope work is required, be sure to document all costs incurred. That includes costs for work indirectly impacted by the increased scope. Be sure to indicate what the charges are for.

* Key takeaway

You can only avoid scope creep if everyone involved in the project understands and agrees on responsibilities, boundaries, and timelines. Avoiding scope creep also requires clear communication, expectation management, and a well-defined path to your desired outcome. Following the strategies discussed here can help you proactively manage scope creep before it creeps into your project!

* Backlinks
- [[{{< ref "202109121929-project-phase-initiation" >}}][Project phase - initiation]]
