#+title: Bye bye Confluence
#+slug: bye-bye-confluence
#+date: 2021-12-18T10:43:28+13:00
#+lastmod: 2021-12-18T10:43:39+13:00
#+categories[]: Tech
#+tags[]: Confluence Wiki MGMT300 Teaching Mikesbikes
#+draft: False

I have been using a Confluence wiki space in my teaching of MGMT300 since at least 2013.

Before that I used a self-host version of Mediawiki. That worked really well, and I had it integrated with our SSO (Single Sign On) which was Shibboleth at that time. I only stopped using Mediawiki when they discontinued the blogging component; I guess it wasn't really needed for Wikipedia (which runs on Mediawiki).

Before that I used self-hosted MovableType blogs.

It all came about because I got one or two students in the class to start blogging about what they were doing with Mikesbikes (which was the central experiential component of MGMT300). This grew into me having the whole class do it and framing it as a learning journal.

Anyway, tens of thousands of student posts later (say 10 years, of 10 posts per semester, across 100 students is about 10,000 posts plus double that amount of comments makes it 30,000 contributions to the wiki), I'm finally moving away from the course that Darl Kolb, Joline Francoeur, and I first re-invented in 1999. That's a long time to be teaching a course (especially as it has remained largely unchanged -- the basic formula worked so well).

The new folk taking over the course---who should do an excellent job---won't be using the wiki. So, I have backed up the wiki, and kicked of the deletion of the MGMT300 wiki space.

I guess it's the end of an era.
