#+title: Dealing with plagiarism in the digital age
#+slug: dealing-with-plagiarism-in-the-digital-age
#+date: 2009-12-16T07:57:00+12:00
#+lastmod: 2009-12-16T07:57:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT101 Plagiarism
#+draft: False

[[https://drbadgr.wordpress.com/][Jo Badge]] and [[https://www2.le.ac.uk/departments/cpp/staff/scott][Jon Scott]] have produced a very interesting paper entitled [[https://evidencenet.pbworks.com/Dealing-with-plagiarism-in-the-digital-age][Dealing with plagiarism in the digital age]].

In their concluding remarks, they argue that there is "little solid empirical evidence to show the effectiveness of these [plagiarism detection] tools in improving student practices". However, experience here is that the use of [[https://www.turnitin.com/][Turn It In]] makes a significant difference. I recall that a few years ago I did some pretty sound analysis of levels of plagiarism in MGMT 191/192 and in MGMT 101 and there was clear evidence of changes in behaviour ... as manifested in levels of plagiarism.

I do agree with Badge and Scott that the use of electronic detection tools are only a "first step" in addressing plagiarism. We (Lisa Callagher, Lynne Mitchelle, and I) developed a very good on-line tutorial (called AHA, Academic Honesty Assistance) that was used in MGMT 191/192 and MGMT 101 for many years. I think it was the combination of /Turn It In/ and /AHA/ that made the difference in the levels of plagiarism. Perhaps that is what Badge and Scott are meaning, it was not just the use of the detection tool that made the difference; it was the combination of factors.

As a something of an aside, Badge and Scott point out there is a [[https://www.citeulike.org/group/11256][CiteULike group of plagiarism articles]]. It contains many of the 'classics' to which I often refer, especially the [[https://www.jisc.ac.uk/media/documents/programmes/plagiarism/brookes.pdf][Good practice guide]] from [[https://www.brookes.ac.uk/][Oxford Brookes]].
