#+title: A vision of students ... tomorrow
#+slug: a-vision-of-students-tomorrow
#+date: 2009-06-08T17:08:00+12:00
#+lastmod: 2009-06-08T17:08:00+12:00
#+categories[]: Teaching
#+tags[]: Students MGMT716 INTBUS202 BUSADMIN768
#+draft: False

It's hard to believe that its been over two months since my post on [[{{< relref "20090403-a-vision-of-students" >}}][A vision of students today]]. Well I have been somewhat preoccupied with my thesis. Anyway, today I read [[https://web.archive.org/web/20090217151640/https://mediatedcultures.net/ksudigg/?p=188][Revisiting 'A Vision of Students Today']] by [[https://web.archive.org/web/20080913062647/https://mediatedcultures.net/about.htm][Michael Wesch]]. It has re-invigorated me. I'm started to finalise my teaching outlines for MGMT 716, INTBUS 202, and BUSADMIN 768, and as I do so I am keen not to fall into the trap of making those classes high-tech information-dumps.

No. What I hope to do is to help the students in my class to develop better judgement in the topics I am teaching (Extending software engineering, Foundations of strategy, and Strategic Management). In a practical sense, that means I have to find ways to connect those topics to real world concerns for the students. Only then, can I (and they) hope to break out of the "getting by" game can pervade students' experiences of University.

(Of course, there are big links here to my research topics, and in particular the notion of communities of practice)

I think for MGMT 716, Extending software engineering, the current structure of course will pretty much achieve those goals. Having students help real firms apply the [[https://www.iamot.org/paperarchive/GSTBB.PDF][Cambridge 'fast start' technology road mapping model]], whilst working with senior management should be a recipe for success. Of course the devil is in the detail.

For INTBUS 202, Foundations of strategy, the move to [[https://web.archive.org/web/20100901055818/https://teambasedlearning.apsc.ubc.ca/][Team-based learning]] has the potential to succeed in those goals. But, I need to spend a week or two sorting out the detailed structure--otherwise I'm likely to meet my first goal but not the second.

Probably, the biggest challenge (for me) is BUSADMIN 768. Traditionally, I would do this as a pure case course. However, I need to spend time considering how I connect it to the students real-world concerns. This is a similar problem to that with INTBUS 202---event though the teaching methodology is different (TB vs. case-based teaching). Perhaps I should consider using TBL in both classes.
