#+title: The 2004 Douglas Robb Lectures and Functioning Knowledge
#+slug: the-2004-douglas-robb-lectures-and-functioning-knowledge
#+date: 2004-03-30T22:18:00+12:00
#+lastmod: 2004-03-30T22:18:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301 Knowledge Psychodram Sociodrama
#+draft: False

Lisa and I went to see [[https://www.marinawarner.com/][Marina Warner]] give the first [[https://www.alumni.auckland.ac.nz/2446.html][2004 Douglas Robb]] lecture tonight. The topic was /After The Arabian Nights: Daemons & Alters/. After the lecture, I mentioned to Lisa that, for me, in delivering her lecture, Marina had achieved the holy trinity of breadth, depth, and humour. Often a lecture only delivers one or two of these[fn::I expect I am as guilty of doing this as anyone. But then again, taking in everything from such a lecture is hard work.], but tonight we got all three in spades. Of course one might expect such a performance from a world class writer and academic, such as Marina , but, in the past, I have sometimes been disappointed. As we walked onward to the car park, I began to reflect on how difficult it is to comment on what Marina had said. The difficulty comes from her use of words. The problem isn't in her choice of words, or her vocabulary. Nor is it in the she marshals them and organises them. The difficult isn't in /what/ she says or even how she says it. At the heart of this 'problem' is the way in which she uses words that to reveal /how/ she is thinking about her topic.

I don't know where I read it, but I recall that one of the greatest difficulties encountered by academics doing inter-disciplinary work is coming to terms with the way people in their 'non-main' discipline think. The challenge is to understand the world in as others (in the other discipline) do. For example, most of the content of what is taught in [[https://web-beta.archive.org/web/20100505010923/https://www.business.auckland.ac.nz/][MER]] isn't hard. The hard part is learning how to think like a manager, or an academic, or a strategist, and so on. For those students who are doing a double major, or a minor, or a con-joint degree, they must run into this problem all the time. Knowing /what/ is the easy part, knowing /how/ is difficult because managers do think about the world different from scientists, differently from artists, etc. [[https://www2.auckland.ac.nz/cpd/staffpages/SF-Breakthroughs.pdf][Stanley Frielick]] talks about it like this:

#+BEGIN_QUOTE

Declarative or propositional knowledge is typically the type of knowledge dominant in university curricula; the 'what' of a subject, abstract, conceptual, and concerned with labelling, differentiating and justifying. Functioning knowledge is based on performance of understanding in professional contexts?it involves the application of declarative knowledge in enacting skills and knowing when and why to perform them. Universities may espouse the development of professional functioning knowledge, but in practice the focus is on declarative knowledge which students often perceive as irrelevant and consequently adopt a surface approach [to learning].

#+END_QUOTE

The differences between the way in which groups (disciplines, occupations, ?) think is manifest in the way Darl and I identify, hopefully in a light hearted manner, engineers in the class. It isn't /what/ they say, or even their behaviour that reveals them as engineers. It is they /way/ in which they think about things that distinguishes them (of course this isn't an exact 'science' and sometimes we do misidentify some).

I believe that functioning knowledge is often learnt, alas at university, through a process of osmosis; by seeing how others do it, rather than being proactively taught. In fact social learning, like this, is a crucial part of human development. Last week, [[https://web.archive.org/web/20050307052941/https://www.colearnz.co.nz/][Judith McMorland]] and I ran a sociodrama [[/blog/2004/03/11/sociodrama/][seminar]] for post graduate students. Before the it began, we had laid the room out in the 'traditional' psychodrama[fn::Psychodrama--sociodrama. I wouldn't worry to much about the difference here.] manner, and we were sitting talking. To my surprise, I realised that as we were talking we had adopted the 'psychodramatic voice'. The particular rhythm and cadence, together with the vocabulary of that has been evident (to me) in every psychodrama training session I have ever attended. We were being sociodramatists. For the seminar, we were adopt the ways of thinking and the ways of acting that are dominant in the New Zealand psychodrama community. The tacit, functioning, knowledge was manifesting itself. No one has ever said to me, this is how a sociodramatists talks, or this is how they think, or even, this is how they see and understand the world. It is something that I have been acquiring over time (and I think it is why I struggle so much to make sense of sociodrama).

The way this plays out in class, and in assignments, is in the way students seek evermore concrete definitions of what they are required to know -- the quest of declarative knowledge, where as lecturers are really looking for functioning knowledge. No wonder the two sides sometimes fail to meet.

Earlier, I was talking with my Research Assistant about how, in MGMT 301, some people can identify the gender of applicants on anonymous CVs from the style of the writing. She is strongly of the view that this is a relative straight forward procedure, as the handwriting can show,broadly, how the writer thinks, and given that the genders think differently it isn't a large step to guess the gender. We then discussed an extension of that, whereby it isn't too hard to guess the general grade of an assignment from the nature/pattern/type of references that accompany an assignment. The references reveal, what sometime is called the quality of thinking, but really is a measure of how much the author of the assignment is thinking like an academic, or a manager, etc. i.e their functional thinking. Some of these points are evidenced [[{{< relref "20040326-scholarly-works" >}}][here]] and [[{{< relref "20040320-testing-maps" >}}][here]].

This also reminds me of an article I was reading yesterday by [[https://webs.wichita.edu/marketing/Faculty%20Information.htm#Terry_Noel][Terry Noel]] in the [[https://ariel.ingentaselect.com/vl=732628/cl=94/nw=1/rpsv/ij/sage/10525629/v28n2/contp1-1.htm][Journal of Management Education]]. In his article /Lessons from the learning classroom/ he describes a situation which parallels the problems discussed here. I Now all of this has a direct and immediate relevance to my PhD study. My topic, in case I haven't mentioned it often enough is /Strategising in professional service firms/. In particular I'm using the framework/world view of [[https://www.strategy-as-practice.org/][strategy-as-practice]] to explore strategy making (aka strategising). Part of my problem in that research is how do I come to understand how strategists think about the world? What is their functioning knowledge. Again, the content of what they do, their declarative knowledge, is relatively, straight forward. But, their functioning knowledge is much more difficult to grasp. Simply watching them do their work may not reveal the logic behind it. This is the challenge faced by ethnographers throughout academe, and this is the challenge faced by students 'watching' their lecturers.

