#+title: Project communication
#+date: 2021-10-17T15:25:00+1300
#+lastmod: 2021-10-17T15:25:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

* Tips for effective communication

As the project manager, it is important to develop a communication plan for the duration of your project. Good communication helps your project run smoothly, leads to better outcomes, and supports a healthy team culture. You can use these four tips to foster effective communication within your team:


** Recognize and understand individual differences

You can encourage open, inclusive communication by:

- Not making assumptions about your audience’s backgrounds, identities, or experiences.
- Being mindful of your own biases.
- Using appropriate, professional, and neutral language.
- Including, respecting, and being curious about diverse points of view.

As the project manager, you will undoubtedly work with a diverse group of team members and stakeholders on each project. You will need to understand each team member’s background, experiences, perspectives, and biasesas well as your ownto  communicate effectively.

** Brainstorm and craft the appropriate message
:PROPERTIES:
:ID:       b4fab633-3631-4f8c-96f2-53966147c7e2
:END:

Communicate the right message by thinking about your intended audience. With whom are you communicating? In your communications, always be clear about your reasons for reaching out:

- What channels can your audience use to contact you or the team?
- Are you conveying information?
- Are you asking for input?
- Are you clarifying an issue?
- Are you resolving a problem?

Some team members may require detailed information, while others may only need an overview of the situation. No matter your audience, you should be sure to identify the purpose of the message, state the information or request clearly and concisely, and stay on topic.

** Deliver your message

As you craft your message, think about which methods are available and appropriate for communicating with various members of your team, whether that is in person, in a video conference, over the phone, via email, or in a meeting. Choosing the right method is especially important if you have team members or stakeholders in different regions and time zones. Also, be sure to:

- Avoid including any sensitive or potentially private information.
- Assume everyone at the company will receive the communication.

** Obtain feedback and incorporate that feedback going forward

Communication doesn’t end when you deliver your message, so be sure to follow up with your audience by:

- Checking to make sure your message was clear.
- Asking them for feedback.
- Encouraging open communication.
- Responding to questions quickly.

In this final step, you will obtain feedback from your audience to ensure that your message was received as you intended.

** Key takeaways

You now have the steps to communicate effectively as a project manager! You have learned how to foster open, inclusive communication by recognizing and understanding individual differences among your team members. You know how to craft and deliver an appropriate message and the importance of obtaining and addressing feedback. Most importantly, make sure your communications are clear, honest, relevant, and frequent. Following these guidelines will set you up for successful communication throughout your projects

* A communication plan
A communication plan organizes and documents the process, types, and expectations of communication for the project.

It should answer these questions:
- What needs to be communicated
- Who needs to be communicated too
- When communication needs to happen
- Why and how to communicate
- Where the information being communicated is stored

The communication plan also helps with effective change management.

You can use the stakeholder map and the  [[{{< ref "202109251549-raci-charts" >}}][RACI chart]] to help figure out who how and what to communicate.

** Best practices for building a communication plan

Tips for creating your communication plan: Identify, identify, identify

Before you begin creating the plan, answer these questions to ensure that you have all of the relevant information:

- Project stakeholders: Have you created a RACI chart or stakeholder map of all your stakeholders? Who is your audience? Who will need to be informed at different points during the project life cycle?
- Communication frequency and method: When and how often should you check in with your stakeholders? What methods of communication do they prefer? How much detail does each stakeholder need?
- Goals: What is the goal of your communication? Do you need a response? Are you trying to encourage engagement or simply providing an update?
- Barriers: Are there any time zone limitations? Language barriers? Do some stakeholders require time to reply or respond (e.g., an executive)? Are there any privacy or internet access issues?

*** Document and develop

Choose a tool or template to document all of your communication needs, and begin developing your plan. Once you understand the basic elements (stakeholders, communication methods, goals, and barriers), it’s time to work out the details! Here are some tips:

**** Add a column for notes.
Project management is not one-size-fits-all, and there are a lot of pieces that need to be tracked. For instance, if you are reaching out to a senior leader or executive, do you need to copy anyone else on the email? If a stakeholder is out of office or unavailable on certain dates, do you have a backup plan? Add notes to set reminders and any additional relevant details.

**** Use formatting to highlight any key details in the plan.
 Is there a launch announcement or an urgent decision needed for the project to move forward? Highlight these pivotal elements in a different font color or size to stress their importance.

**** Ensure that the team can access your document.
Share the plan with your team. Allowing your team to review the document ensures that they are aware of the plan and gives them a chance to offer feedback. Sharing the document also serves as an extra check to make sure you aren’t missing any crucial pieces.

**** Test your plan.
If you are sending a team-wide email or link, send a test email to yourself or a colleague. If you are planning a virtual presentation, be sure to test the visual, audio, and other technical aspects in advance. That way, you can minimize any technical problems.

*** Check in

Once your communication plan is out in the world, check in with your audience about the effectiveness of your plan. Scheduling routine check-ins will help you understand what is and is not working so you can improve your plan. You want to ensure that your communication plan gets the right information to the right stakeholders at the right time. Additionally, make sure to double check that key stakeholders have not changed over time.

Evaluate where you may be over- or under-sharing information or missing stakeholders. You can do this through:

- Anonymous survey forms
- Polls or open feedback sessions during team meetings
- One-on-one conversations and check-ins with key stakeholders

Keep these tips in mind as you build your next communication plan and you will be set for communication success!


* Backlinks
- [[{{< ref "202109121932-project-phase-planning" >}}][Project phase - planning]]
