#+title: Summits
#+slug: summits
#+date: 2004-03-29T21:36:00+12:00
#+lastmod: 2004-03-29T21:36:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301
#+draft: False

We've started the first of the summits. In these, the various functional specialists get together, hopefully, to share knowledge about their roles (rather than to share competitive information). I suspect, well know, that I didn't explain the point of them well today.

But nevertheless, there is a strange paradox that occurs when we hold summits. It takes a while before people begin to appreciate the usefulness of the summits; but it is necessary to do the CEOs and CFOs first ((I'll leave it to the reader to decide why this is the case.)). Consequently, some of the benefits of the summit are lost.

It's probably worth me commenting of the efficacy of the summits. Firstly, I don't believe that these sessions disadvantage any team; /i.e.,/ if they were going to win, they will win. What they do is to build capacity in all of the companies; /e.g.,/ Last semester only a few teams were insolvent at the end of the simulation, whereas, without the summits, as many as one third of the teams may become insolvent.
