#+title: Why people come to this site
#+slug: why-people-come-to-this-site
#+date: 2005-06-06T20:21:00+12:00
#+lastmod: 2005-06-06T20:21:00+12:00
#+categories[]: Tech
#+tags[]: Blogging Website Mikesbikes
#+draft: False

I was looking at my web logs and the statistics that are produced for this site, and I was curious why people come here. As you probably know, when you use a search engine such as [[https://www.google.com/][Google]] or [[https://www.yahoo.com][Yahoo]] information is passed about the site that referred you (Yahoo or Google) along with the search terms that were used.

So what patterns do I see? Well firstly, some people come here looking for information on strategy cases---I presume they are looking for some insight that they can use in their class. I can't be certain if they are staff or students, but from the IP/DNS entries, I suspect they are students. Cases such as Swatch, and Karl Zeiss Jenna from the [[https://www.strategy3rd.com/3rdedition/][de Wit & Meyer]] text book appear frequently.

There are another group who seem to be looking for information on [[https://www.smartsims.com/][Mike's Bikes]]. If anyone is interested I have "sure fire" strategy for winning the first three (and sometimes more) rollovers. Alas, the downside is that it hard to continue that winning into rollovers five and six. As [[https://www.sbs.ox.ac.uk/html/faculty_profile.asp?ID=5786][Ken Simmonds]] often states, anyone can increase profit by sacrificing the future value of the company.

Finally, a few people looking for [[https://www.aus.ac.nz/branches/auckland/Akld.htm][Prof. Nigel Haworth]] also end up here too. I wonder what they want to know about him. Isn't his [[https://staff.business.auckland.ac.nz/nhaworth][university web page]] enough?
