#+title: MBA Reunion
#+slug: mba-reunion
#+date: 2005-04-09T23:58:00+12:00
#+lastmod: 2005-04-09T23:58:00+12:00
#+categories[]: Teaching
#+tags[]: MBA
#+draft: False

It's been 10 years since I graduated with my MBA from the [[https://www.auckland.ac.nz/][University of Auckland]]. When I was doing the MBA there were two streams. One stream was called the Management MBA, the other stream was known as the Executive. There were two differences between the two groups. Firstly, the MMBAs had an average age of about 35, whilst the EMBAs where about 10 years older with an average age of 45. The other difference was that in the second year the EMBA had to write a four point 4 (1 term) thesis, whereas the MMBAs did courses instead.

Well the EMBAs organised a reunion for this evening---and very kindly invited any of the MMBAs who wanted to come too. So six of us turned up.

There was me (of course), John Brunton (who acted a liason with the EMBAs), Sandy McCaulay, Hamish Stevens (and partner), Greg Batkin, and Lynne Richardson.

It was really nice to catch up with everyone, but it was a disappointment to me that there weren't more MMBAs there (our class actually numbers 40). However, we did manage to exchange a lot of gossip about everyone.

It was very moving when the EMBAs were talking about one another, the way they remembered the three people in their class who have since died.

That particular event has yet to hit our (younger) class. As an aside, the reunion was held at Pontoon. I had beetroot carpaccio as my entry, roast chicken with kumara mash as my main. Food and service was competent as ever from Pontoon.

In my role with the Auckland MBA program, I'm supposed to be organising a reunion later on in the year. I hope I do the same sort of high quality job as the EMBAs achieved.
