#+title: Spelling
#+slug: spelling
#+date: 2004-03-13T10:18:00+12:00
#+lastmod: 2004-03-13T10:18:00+12:00
#+categories[]: Tech
#+tags[]: MovableType Zempt
#+draft: False

Sometime the interface to [[https://www.movabletype.org/][MovableType]] can be a little hard to work with; especially for that simple task of creating a journal entry. I find a lot of spelling mistakes slip through. So, at the moment, I am trying out [[https://www.zempt.com/][MovableType]]. Zempt allows me to create the entry on my computer, /check the spelling/ and then upload the entry to my blog. I'll be interested to see how it works out.

Of course, a program like Zempt can't fix all the other problems, such as: grammar, coherence, flow, etc. (but maybe one day).

I'm also trying out a program called [[https://wbloggar.com/][w.bloggar]]. I'm not sure which is better yet---I'm still weighing up the pros and cons of each.

What I will say is that the spell check on each system is rather idiosyncratic. Zempt seems to work best; but it doesn't remember new words ((It seems that the dictionary problem is known to the folks at Zempt, and they are working on it.)). (i.e. the dictionary add function doesn't seem to work). W.bloggar, on the other hand, doesn't handle URLs well and doesn't have a British dictionary (and the US dictionary throws /British/ up as an error).

Also, Zempt, being targeted solely at MovableType, does seem to handle the features of the underlying blogging system better (e.g.  formatting, categories, etc.).

