#+title: The paragraph
#+slug: the-paragraph
#+date: 2011-03-05T11:54:00+12:00
#+lastmod: 2011-03-05T11:54:00+12:00
#+categories[]: Research
#+tags[]: Writing
#+draft: False

The paragraph is a continuing source of mystery to me. What makes a really good paragraph? Is it as formulaic as suggested by [[https://secondlanguage.blogspot.com/2010/09/paragraph.html][Thomas Basbøll]]?

Actually, I'm doing a Thomas a great disservice when I caste his writing on paragraphs as being formulaic. He, has written at length in a very nuanced manner about the paragraph (and most other aspects of writing). I highly admire his approach as I've said elsewhere.

What I'm rebelling at is those who actually take Thomas' prescriptions at face value and say things like, "Every paragraph must comprise five sentences", or "It's best practice to have paragraphs of five sentences". It's the unthinking and superficial application of what he says that troubles me. I have a colleague who recently told me that best practice was to have sentences of 22 to 25 words.

There is, I think often a mistake made whereby people confuse the what needs to be achieved with the manner in which it is done. They conflate or confuse the ends and the means. The work that a paragraph seeks to do, might typically require five sentences. But, depending on the work of the paragraph, it might be more or less than that. Although we might generally avoid the single-sentence paragraph, there are times when that is all that is needed.

Differing levels of expertise requires differing types of "explanation" or instruction. So, while something like [[https://www.indiana.edu/~wts/pamphlets/paragraphs.shtml][this]] might be highly appropriate and digestible at one level of expertise---say that of a regular (Unruh, 1979)---something like Thomas'es work might be more appropriate at another level---say that on an insider (Unruh, 1979). The more explicit rules required by, say, strangers, are fine ... but where does one transition to using the general principles that underlie them?

We often hedge our bets by using words and phrases such as "Generally", "Often", "For some people", and so on. This works well, but the consequence is that others don't always appreciate the contingentness of what we say, or they focus on the exceptions to the extent the exceptions are taken to be a significant---almost a majority---incidence/occurrence. This isn't helpful either.

My overall, point is how do we advise in a manner that still allows progress to the next level of expertise, without locking one's thinking into a particular level.

* References
Unruh, D. R. (1979). Characteristics and types of participation in social worlds. /Symbolic Interaction/, 2(2), 115-130. doi:10.1525/si.1979.2.2.115
