#+title: The Method
#+slug: the-method
#+date: 2006-07-22T23:12:00+12:00
#+lastmod: 2006-07-22T23:12:00+12:00
#+categories[]: Arts
#+tags[]: Movies
#+draft: False

One of my favourite film genres is "get the guest". I also enjoy films that have a few twists in the plot. So is it any wonder that I really enjoyed the Spanish Argentinian co-produced [[https://www.imdb.com/title/tt0427582/][El Metodo]] (The Method). I wonder how long it will be before Hollywood does a remake.

At times the film felt a bit like a play (as does [[https://www.imdb.com/title/tt0108149/][Six Degrees of Separation]]) but that doesn't stop the movie from holding your interest for the full two hours of running time (as did /Six Degrees/).

The plot revolves around a group of managers who are applying for a job at a corporation and the novel selection method they use to decide who will be hired (and, of course, who won't).

I'll give this movie five out of five.

For an OB perspective or a HR selection perspective, this film could be the basis for a whole course.

As it happens, we me Natalie at the [[https://www.skycity.co.nz/][theatre]] (those seats are awful). Anyway, Natalie is doing some work for the [[https://www.nzff.telecom.co.nz/][festival]] and as we went in, she laughingly suggested that perhaps she should be doing /Recruitment and Selection/ as her [[https://www.mba.auckland.ac.nz/][MBA]] research [[https://mbanotebook.ac.nz/index.php/BUSADMIN_798][project]]. Having seen the film I can understand what she was getting at.
