#+title: The women
#+slug: the-women
#+date: 2004-10-23T23:25:00+12:00
#+lastmod: 2004-10-23T23:25:00+12:00
#+categories[]: Arts
#+tags[]: Theatre
#+draft: False

Lisa, my darling wife, and I went and saw the latest play at the Silo theatre. It's call [[https://www.imdb.com/title/tt0032143/][The Women]], and it's by the outspoken congresswoman [[https://www.loc.gov/exhibits/wcf/wcf0010.html][Clare Booth Luce]]. Written about 70 years ago, I can imagine it was considreed risque in its day. The latest edition of [[https://www.thelistener.co.nz/][The Listener]] magazine gives ten quotes by Clare Booth Luce, and these give a sense of her progressive attitudes:

1. Nature abhors a virgin---a frozen asset.
2. I'm in my ancedotage.
3. I don't have a warm personal enemy left. They've all died off. I miss them terribly because they helped define me.
4. Lying increases the creative faculties, expands the ego, and lesses the frictions on social contact.
5. Communism is the opiate of the intellectuals with no cure except as a guillotine might be called a cure for dandruff.
6. No good deed goes unpunished.
7. There is nothing like a good does of another woman to make a man appreciate his wife.
8. All autobiographies are alibi-ographies.
9. A man's home may be his castle on the outside; inside, it is more other his nursery.
10.Censorship, like charity, should begin at home, but unlike charity, it should end there.

Actually, a couple of these seem familiar and might actually be lines from the play.

Anyway, the eight women actors play an astonishing number of characters ([[https://www.imdb.com/][IMDB]] says 130, but that seems too many). The dialogue is witty and fast moving; however the skill (as Lisa told me), is the way in which the plot is slowly revealed. I really enjoyed it. The whole caste were good, and notable performances were turned in by /Anna Hutchison/ (ex Shortland Street), /Hannah Tolich/ (also, ex Shortland Street), and /Lucy Wigmore/ (yes, another from Shortland Street---is there anyone in New Zealand theatreland who hasn't been on that show?).

Given the size of the theatre, I was surprised to see that the performance was done "in the round' and it worked really well. I do like the intimacy of the Silo, and this made it even more intimate. All, in all, a big thumbs up for /The Women/.

Other reviews of this production can be found [[https://www.nbr.co.nz/home/column_article.asp?id=10497&cid=6&cname=Arts][here]], and [[https://www.nzherald.co.nz/entertainment/entertainmentstorydisplay.cfm?storyID=3601375&thesection=entertainment&thesubsection=arts&thesecondsubsection=reviews][here]].
