#+title: AMBA
#+slug: amba
#+date: 2007-02-18T19:12:00+12:00
#+lastmod: 2007-02-18T19:12:00+12:00
#+categories[]: Teaching
#+tags[]: AMBA
#+draft: False

I seem to have spent most of the weekend working on the paperwork for our upcoming [[https://www.mbaworld.com/][AMBA]] review. I've been sending versions of our self-report document backwards and forwards to [[https://staff.business.auckland.ac.nz/s.laurenson%20%22Sue's%20staff%20page%22][Sue Laurenson]].

It really is a time consuming process, but it is really helpful to take stock of the MBA programme this way. It reminds me of what Sarah Kennedy of [[https://www.healtheries.co.nz/][Healtheries]] was saying at the MBA Business Breakfast last Wednesday. Talking to the MBA students she talked about how Healtheries had been put up for sale and had to go through vendor diligence. As part of that process they were reviewed by [[https://www.pwc.com/%20%22PriceWaterhouseCoopers%20NZ%22][PWC]] and found the process very helpful in highlighting some of the gradual changes that might have otherwise been unnoticed.

Anyway, for me, and I hope for our MBA programme the AMBA self-review has been very useful.
