#+title: Agile development manifesto -- principles
#+date: 2020-09-04T23:10:00+1300
#+lastmod: 2020-09-04T23:10:00+1300
#+categories[]: Zettels
#+tags[]: Project_management

* Principles behind the Agile Manifesto

We follow these principles:

1. our highest priority is to satisfy the customer through early and continuous delivery of valuable software.
2. welcome changing requirements, even late in development. agile processes harness change for the customer's competitive advantage.
3. deliver working software frequently, from a couple of weeks to a couple of months, with a preference to the shorter timescale.
4. business people and developers must work together daily throughout the project.
5. build projects around motivated individuals. give them the environment and support they need, and trust them to get the job done.
6. the most efficient and effective method of conveying information to and within a development team is face-to-face conversation.
7. working software is the primary measure of progress.
8. agile processes promote sustainable development. the sponsors, developers, and users should be able to maintain a constant pace indefinitely.
9. continuous attention to technical excellence and good design enhances agility.
10. simplicity---the art of maximizing the amount of work not done---is essential.
11. the best architectures, requirements, and designs emerge from self-organizing teams.
12. at regular intervals, the team reflects on how to become more effective, then tunes and adjusts its behavior accordingly.

* Notes
These can be grouped in to four areas
** Value delivery
Delivering the work as quickly as possible in order to get feedback and mitigate time risk.

1. Our highest priority is to satisfy the customer through early and continuous delivery of valuable software.
2. Deliver working software frequently, from a couple of weeks to a couple of months, with a preference to the shorter timescale.
3. Working software is the primary measure of progress.
4. Simplicity---the art of maximizing the amount of work not done---is essential.
5. Continuous attention to technical excellence and good design enhances agility.

** Business collaboration
Collaborating with your customers helps the team get critical business information immediately, allowing them to adjust and adapt to any new information instantly

1. Welcome changing requirements, even late in development. agile processes harness change for the customer's competitive advantage.
2. Business people and developers must work together daily throughout the project.

** Team dynamics and culture
Create an effective team culture that is inclusive, supportive, and empowering.

1. Build projects around motivated individuals. give them the environment and support they need, and trust them to get the job done.
2. The most efficient and effective method of conveying information to and within a development team is face-to-face conversation.
3. Agile processes promote sustainable development. the sponsors, developers, and users should be able to maintain a constant pace indefinitely.
4. The best architectures, requirements, and designs emerge from self-organizing teams.

** Retrospective and continuous learning
Strive to continuously learn and adapts to what's working and what's not working.

1. At regular intervals, the team reflects on how to become more effective, then tunes and adjusts its behavior accordingly.


* Backlinks
  - [[{{< ref "202009042320-agile-development-manifesto-values" >}}][Agile maniefesto values]]

* References
[[http://agilemanifesto.org/principles.html][source]]
