#+title: The Hollow Crown
#+slug: the-hollow-crown
#+date: 2002-04-17T15:14:00+12:00
#+lastmod: 2002-04-17T15:14:00+12:00
#+categories[]: Arts
#+tags[]: Theatre
#+draft: False

We went to see The Hollow Crown at the [[https://www.the-edge.co.nz/venues/centre.htm][Aotea Centre]]. It is an production by the [[https://www.rsc.org.uk/][Royal Shakespeare Company]]. It was wonderful.

The cast was outstanding; Diana Rigg, Derek Jacobi, Ian Richardson, Donald Sinden, and a "minstrel" Stephen Gray. I think the four main players are at the zenith of their professional skills.

According to the program, it is:

#+BEGIN_QUOTE
An entertainment by and about the Kings and Queens of England. Music, poetry, speeches, letters and other writings from the chronicles, from plays, and in the monarchs' own words---also music concerning them and by them.
#+END_QUOTE

Indeed it is the tale of the Kings and Queens from William I (1066--1087), through to Victoria (1830--1901).

On reflection, one of the most interesting things was the degree to which the players could shape the meaning of what was said by their tone and body language. It highlights to me how sterile the write word can be, and how easy it is to apply other interpretations to it.

