#+title: Post Exec
#+slug: post-exec
#+date: 2004-07-27T07:46:00+12:00
#+lastmod: 2004-07-27T07:46:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301 Grading
#+draft: False

After the 'exec' meetings yesterday, the three of us ([[{{< ref "dpe" >}}][DPE]]) got together to talk about the teams we had seen during the morning. Despite that debriefing, it still takes me a long time to process what I have seen and heard, and to think about the /Learning journals/ that people have written.

When we, DPE, originally talked about the learning journals, we thought that it would take a few weeks before people got 'into their stride' and began to do well in them. Judging by the current crop that I've read, some people are setting a cracking pace already. Not only that, most of the anticipated grades[fn:1] (of the ones I read) are close, if not identical, to the grade I'm going to give them. For a long time, I've said that students know the grade their work deserves; this just seems to re-enforce my position.

There were a number of discussions that I found particularly helpful (in the sense that I feel I understand a little better where the students are coming from). Firstly, with one team we had a robust discussion about the pros and cons of making assumptions--I think this really leads into a discussion of how we construct our own theories of the world. Perhaps so of the later readings will be helpful with this, but many theories of learning, such as the Kolb cycle (1976), are not predicated on the individual discovering some fundamental, or scientific, truth. Rather, they are geared towards people find out how to function 'better' in the world in which they inhabit[fn:2]. This leads us to a very subjective view of the world -- and I'm aware that some, or even many, students find that an uncomfortable thought.

Second, is the issue of sharing information and learning. I hear that with in some departments or faculties, with regard to team projects, there is a culture of deliberately misleading other teams--I presume this means feeding them wrong information. I struggle to understand why someone would do this (either in a course, or outside of university). It isn't as if there are a finite number of As to go around[fn:3]. Related to that, was this issue of the ranking of team members, and the intra-team competition that this might generate. True, it is possible to construe it that way; however, it isn't the only construction that can be placed on it. Later on, one of the readings discusses catalytic mechanisms; and forced ranking is an okay catalytic mechanism[fn:4].

* References
Collins, J. C. (2001). /Good to great: Why some companies make the leap--and others don't/. New York: HarperBusiness.

Kelly, G. A. (1955). /The psychology of personal constructs/ (1st ed.). New York: W. W. Norton.

Kolb, D. A. (1976). Management and the learning process. /California Management Review, 8/(3), 21--31.


[fn:1] The grade that the students expected to get for their journal.

[fn:2] See also something like George Kelly's [[https://www.pcp-net.org/encyclopaedia/creat-cycle.html][experience cycle]].

[fn:3] The argument for grading on the curve (and thus having a finite number of As) is sometimes based on the idea that it encourages competition, and thus raises standards. In this [[https://web-beta.archive.org/web/20100505010923/https://www.business.auckland.ac.nz/][department]], we mark to a standard, rather than to a bell-curve.

[fn:4] I've read this in Jim Collins book, /Good to great/, but I think the class get it as an article (by him again) in the [[https://harvardbusinessonline.hbsp.harvard.edu/relay.jhtml?name=itemdetail%20&id=4312&referral=8636][Harvard Business Review]].
