#+title: Scrum - Sprint Review
#+date: 2021-10-03T09:13:00+1300
#+lastmod: 2021-10-03T09:13:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management Scrum

The Sprint Review is a meeting with the entire Scrum Team where the product is demonstrated in order to determine which aspects are finished and which aren't.

This is crucial to the Scrum Pillars of inspection and adaptation

The review covers:
- Which items should be considered done in the Product Backlog
- Demonstrate and inspect the product

The advantages of the Sprint Review are;
- It makes the feedback and immediate as possible
- Everyone has a voice
- The team learns more about how their teammates do their job, leading to greater trust and understanding between team members

During the Sprint review, the team releases the *Product Increment*
- What is produced after a given Sprint

A product is *Releasable* when the team have developed a minimum viable product, which has a set of implemented features or requirements.

A *Minimum Viable Product* is a version of the product with just enough features to satisfy early customers. More completely, it is "that version of a new product which allows a team to collect the maximum amount of validated learning about customers with the least effort."

A minimum viable product is a package of features that may take several sprints to develop, but every sprint’s goal is to produce a product increment.

Anything not done, goes back into the Product Backlog.


* Backlinks
- [[{{< ref "202110021152-scrum-sprints" >}}][Scrum - Sprints]]
- [[{{< ref "202109281944-the-three-pillars-of-scrum" >}}][The three pillars of Scrum]]

