#+title: Governing variables
#+slug: governing-variables
#+date: 2004-04-27T10:23:00+12:00
#+lastmod: 2004-04-27T10:23:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301 Double-loop
#+draft: False

I was reading Argyris' /Double-loop learning, teaching, and research/ again today, and I was struck by his comment that: "Model I theory-in-use is composed of four governing variables: (a) to be in unilateral control; (b) strive to win and not lose; (c) suppress negative feelings; and (d) act rationally" (2002, p. 312). But what does that mean? Well, does that prohibit other governing variables.

I'd say no. Well, I actually say "No, /but/".

The thing is that there might be other governing variables, but they are probably going to be subordinate to the /big four/. In every example I've seen A & S work with, they are always tackle the big four. Now, these are probably the hardest to work with, but they also have the most impact. So let's go back to my example of my espoused desire for participation in the class. What is the really driving that? I'll leave you to work out (there I go saving face-again).
