#+title: Understanding strategic change: The contribution of archetypes
#+slug: understanding-strategic-change-the-contribution-of-archetypes
#+date: 2005-06-13T17:07:00+12:00
#+lastmod: 2005-06-13T17:07:00+12:00
#+categories[]: Research
#+tags[]: PSFs
#+draft: False

A romp through:

#+BEGIN_QUOTE

Greenwood, R., & Hinings, C. R. (1993). Understanding strategic change: The contribution of archetypes. /Academy of Management Journal/, 36(5), 1052---1081.

#+END_QUOTE

The abstract says:

#+BEGIN_QUOTE

We examined the concept of archetype, implicit in a number of contemporary approaches to the study of organizational design and change. Despite an emerging interest in archetypes, the concept has received inadequate investigation. The present article offers a basis for definition of the concept and sets down three assumptions, which we tested using data collected longitudinally from 24 organizations. We present a number of theoretical and methodological implications of the archetype approach to the study of organizational change.

#+END_QUOTE

I was reading an old article by Miller (1987) on the relationship between strategy and structure (or is it structure and strategy), and in my notes I asked the question "Is there a link between the notion of organisational gestalts", which was very contemporary then, "and the idea of archetypes?" The answer, based on this article is yes. Organisational archetypes, configurations, and gestalts are all part of the same quest to study how organisations are transformed and develop---or to put it another way it is "a central thrust of organizational theory ... the need to understand organizational diversity through typologies" [fn::We westerners seem to love to [[{{< relref "20040907-western-and-eastern-thought" >}}][classify and clarify]] (to mis-quote /99 Red Balloons/ by Nina). And yet, and yet this form of knowledge making (as exemplified by the 2 x 2 matrix) is often something academics look down upon.] (Greenwood & Hinings, 1993, p. 1053).

Anyway, as I've said [[{{< relref "20040412-the-structuring-of-organizational-structures" >}}][elsewhere]], "An archetype is ... a set of structures and systems that reflects a single interpretive scheme" (Greenwood & Hinings, 1993, p. 1052). The article seeks to provide an understanding of large-scale change as an organisation moves from one archetype to another (as opposed to micro or incremental changes within the organisation).

Again, this article has a common heritage with other articles from these authors. For example, it relies on the article by Miller (1987) that started this current discussion---i.e. the three dimensions of decision making; rationality, assertiveness, and interaction---and Greenwood;s & Hinings own work on tracks (1988).

One of the things that struck me in reading this article is the hypothesis that "organizations will develop structures and systems consistent with /a single interpretive scheme/" (emphasis added, Greenwood & Hinings, 1993, p. 1056). Why should this be so? Surely a firm could be developing multiple, contested structures and systems? Greenwood and Hinings bring together a number of ideas to explain why this isn't the case. The ideas of best, dominant coalitions and shared culture are the main reasons given.

The second idea I took away from the reading is that an archetype would be specific to an institution---that is to say they would not be "generic" in nature. I always assumed that an archetype would be more like an "ideal-type' of configuration.

From the point of view of /writing an article/ I was struck that in a prestigious journal, such as the Academy of Management Journal, the fact that the results were ambiguous did not preclude the article from being published. That is good-news.

* References

Greenwood, R., & Hinings, C. R. (1988). Organizational design types, tracks and the dynamics of strategic change. /Organization Studies, 9/(3), 293--316.

Greenwood, R., & Hinings, C. R. (1993). Understanding strategic change: The contribution of archetypes. /Academy of Management Journal, 36/(5), 1052--1081.

Miller, D. (1987). Strategy making and structure: analysis and implications for performance. /Academy of Management Journal, 30/(1), 7--32.
