#+title: Self review of INTBUS 202
#+slug: self-review-of-intbus-202
#+date: 2008-06-24T10:44:00+12:00
#+lastmod: 2008-06-24T10:44:00+12:00
#+categories[]: Teaching
#+tags[]: INTBUS202
#+draft: False

I've just received the /Student Evaluations of Teaching/ or [[https://web.archive.org/web/20081014020737/https://www.cad.auckland.ac.nz/index.php?p=survey_types][University Lecturing Questionnaire]] for INTBUS 202: Foundations of strategy.

Such evaluations have both [[https://web.archive.org/web/20081014020700/https://www.cad.auckland.ac.nz/index.php?p=218][supporters]] and [[https://www.aus.ac.nz/Policy/StudentEvaluation/policy.asp][detractors]]. Anyway, back to my results ...

The students seem to fall into three camps. First, there are those who liked what I did and marked me highly in all areas. This is typified by the student who said:

#+BEGIN_QUOTE

One of the best lecturers in my opinion. I came to university to learn and not to be taught or spoon-fed everything. His vast understanding across many areas prove useful and which I deem ought to be necessary for a paper of this calibre.

#+END_QUOTE

Secondly, there are those students who marked me down in all areas. The comments from those students are of the form:

#+BEGIN_QUOTE

Slides!

#+END_QUOTE

or

#+BEGIN_QUOTE

More structure

#+END_QUOTE

and

#+BEGIN_QUOTE

Did you talk about the course material? I might have missed it during your other insights

#+END_QUOTE

Finally, there are those students who had a more 'normal' distribution in their evaluation.

To some up; some students really liked what I did, some really disliked what I did, and a group were moderate in their opinions. The split is something like 10%, 30%, 60%.

So what do I take away from this, and what do I plan to change?

I think there was a gap between myself and many of the students. Despite both my comments and [[https://web.archive.org/web/20080226134731/https://staff.business.auckland.ac.nz/dtisch][Dan's]] (the other person who taught this course), most of students didn't read the textbook ahead of the class. For Dan's sessions that didn't matter too much; but for my sessions, I relied on the fact that the student's had read the book--and I was unwilling to compromise on that. Without the background knowledge provided by the book, I can understand and believe that many of the students had a hard time following along with me. Thus, for many it would have felt unstructured. This would be especially so, given Dan's sessions that very heavily followed the book.

Was I unstructured? I don't think so. I had a very clear and detailed 'lesson plan' for each class. What I did not provide is step-by-step slides. Could I do slides? Yes. Yet, as I pointed out to the students at the beginning of the course, the evidence is that providing slides detracts from students learning (even if they fell the opposite).

Having said all that, and re-read it, I sound defensive and perhaps I
am.

The more I think about it, the more I regard the contrast between Dan's approach an my approach as being a challenge for the students. When I have co-taught with others (say [[https://web.archive.org/web/20080227000626/https://staff.business.auckland.ac.nz/lerakovic][Liliana Erakovic]] or [[https://web.archive.org/web/20080226141920/https://staff.business.auckland.ac.nz/dkolb][Darl Kolb]]) my style has been close to the other teacher. Having said that, it does not mean my style is the same with both--Liliana's and my style is very different to that when I'm teaching with Darl. Dan and I are yet to find a common approach.

I think the new structure will help. Next semester, I imagine the general pattern will be:

- First class (Two hours)

  - Administriva
  - Review (and show) one good and one poor example of the case analyses
    handed-in the previous week
  - Provide some overarching comments on what was seen in the case
    analyses (30 minutes to here)
  - Answer questions about the readings and the questions (30 minutes)
  - Discuss a relevant news story/case/mini-case and the tools/theory
    that help to understand it (30 minutes)
  - Class exercise based on the "small group" exercises from the text
    (20 minutes)

- Second class (One hour)

  - Walk through and discuss the case of the week
  - Apply the Business, Customer, Industry framework (apply the new
    tools as they are acquired)
  - Talk about the possible strategies and the insights that students
    have developed

(I'm haven't talked this through with Dan yet, so it will be interesting to get his comments)

At the end of the day, we want the students to be adept at using the tools of strategy (and not just one or two of them). And I think this will do it better than before.
