#+title: How long does a team agreement need to be?
#+slug: how-long-does-a-team-agreement-need-to-be
#+date: 2004-08-03T15:14:00+12:00
#+lastmod: 2004-08-03T15:14:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301 Teams
#+draft: False

One team asked Darl and me 'How long should a team agreement be?' Echoing the mantra of management, we replied 'It all depends'. In some ways, a team agreement is there as an insurance policy in case things go wrong--it may never be used (but it will be because of the marks). The team agreement may also be a tool to ensure teams and the lecturers understand each others positions. In other ways, the team agreement is a vehicle to build trust and commitment (think back to Katzenback & Smith).

Charles Handy tells the following story:

#+BEGIN_QUOTE

I remember my first exposure to the 'Chinese Contract'. I was a manager in South Malaysia for an oil company, responsible amongst other things for negotiating agency agreements with our Chinese dealers. I was young, enthusiastic and, I suppose näI've. After the conclusion of one such negotiation, the dealer and I shook hands, drank ritual cups of tea, and were, I felt, the best of friends. I took the official company agency agreement out of my case to fill in the figures, preparatory to signing it. 'Why are you doing that?' asked the dealer with some alarm. 'If you think I am going to sign that that you are much mistaken.' 'But I'm only writing in figures which we have agreed.' 'If we agreed them, why do you want a legal document? It makes me suspect that you have got more out of this agreement than I have, and are going to use the weight of the law to enforce your teams. In my culture,' he went on , 'a good agreement is self-enforcing because both parties go away smiling and are happy to see that each of us is smiling. In one smiles, and the other scowls, the agreement will not stick, lawyers or no lawyers' (Handy, 1994, p. 80).

#+END_QUOTE

So, one issue is how much you trust each other, and how much we (DPE) trust you. After all, you have been entrusted with something quite valuable--that is to say, 20 per cent of your marks. My sense is that some teams have higher levels of genuine trust, rather than the rosy glasses of norming, and commitment than other teams. So, the length of each team's agreement will be different.

* References

Handy, C. (1994). /The empty raincoat: Making sense of the future/. London: Arrow Books.

Katzenbach, J. R., & Smith, D. K. (1991). /The discipline of teams/. Boston, M: Harvard Business School Pub.
