#+title: Scrum - User stories
#+date: 2021-09-30T19:06:00+1300
#+lastmod: 2021-09-30T19:06:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management Scrum User_Stories

A short simple description of a feature told from the perspective of the user.

"As a <user role" I want this <action> so that I can get this <value>"

This can be done through /Personas/, detailed descriptions of my different users. Personas put you in the mind of the user. Each user story should meet six criteria:

1. I - Independent
2. N - Negotiable
3. V - Valuable
4. E - Estimable
5. S - Small
6. T - Testable

While the Product Owner is the main person responsible for writing user stories, the team has a responsibility to give feedback on whether the user story is clear and fits the invest criteria before they invest any time into it.

When writing user stories, you will need to include the following components:

- *User persona*. What is your user like? What is their relation to the project? What goals do they have?

- *Definition of Done*. This refers to an agreed upon set of items that must be completed before a user story can be considered complete.

- *Tasks*. What are the key activities needed to complete the user story?

- *Any feedback already provided*. If you are adding features to an existing product and you have already received feedback from customers on a past iteration, make sure to consider this feedback.

** Epics

An epic's purpose is to help manage related user stories. In this post, Mike Cohn, the inventor of the term "epic" as it relates to Scrum, describes epic as a "very large user story" one that could not be delivered within a single iteration and may need to be split into smaller stories. The team should discuss together and reach a shared view of how to write and capture their user stories and epics. Keep in mind, epics are just larger user stories that are there to help organize the project.

Let’s imagine you are creating user stories and epics based on the previous example. User stories may include customers wanting to read reviews of books on the website or wanting to add books to their cart. These user stories could fall into the "website creation" epic.

Another user story could be that customers want to walk into the library and easily find the non-fiction section. This would fall under the “organization of the physical space” epic.

So rather than those various user stories appearing in a list together, they are organized into sections, or epics.


* Backlinks
- [[{{< ref "202109131858-scrum" >}}][Scrum]]
- [[{{< ref "202109301840-scrum-product-backlog" >}}][Scrum - Product Backlog]]

