#+title: Looking ahead to 2016
#+slug: looking-ahead-to-2016
#+date: 2014-12-20T17:35:00+12:00
#+lastmod: 2014-12-20T17:35:00+12:00
#+categories[]: Teaching
#+tags[]: BUSINESS304 MGMT300 BUSINESS102 ACADPRAC703
#+draft: False

2015 is not over yet, but I'm already thinking about my teaching and learning activities for 2016.

The three courses that I am teaching next year are:

/BUSINESS 304 Strategic management/: This case-based course is one of my favourites. It it's various incarnations--as MGMT 302--I have been teaching it on an off since 1999. The fundamental pattern is:

- Pre-test to ensure the readings have been done; i.e., to make sure
  that the basic theoretical content is in place.
- Followed by a case discussion, where students are graded on the
  quality of their participation.

This works, Both Liliana and I are very experienced with this model, and the students seem to really enjoy it.

This year, we are moving to a custom-print text book. That should make the transitions between lectures much smoother.

Also of note, the class is moving from two sessions--a one-hour class and a two-hour class--to a single three-hour class. Given the scheduling of the new class, I am thinking it is going to be very popular; it will fit with many people's schedules. That might create problems if the number of enrolments go to far over 70. I can case teach with up to 100, but after that, it gets rather tricky as students get concerned about not getting enough time to speak. That fear is possibly unfounded, but it is often very present for them.

/MGMT 300 Management in dynamic contexts/: Based on the simulation Mike's Bikes, I've also been teaching this class for over 15 years. It has morphed over time and is quite 'clean' now. Again, this is a very successful course that also faces the challenge of increasing student enrolments. Over the past two years, I've made some structural changes to the course requiring less class time. It seems to work, but it is not clear to me if it will continue to 'hang together' if enrolments increase further.

/BUSINESS 101 Business and enterprise/: This will be really interesting as the core team have done a major redesign of this course and BUSINESS
102.

In additional, I'll also be doing:

/ACADPRAC 703 Engagement in Digital Learning and Teaching/: I doing this course through the Faculty of Education and the good folk at [[https://www.clear.auckland.ac.nz/en.html][CLeaR]]. The prescription for the course is:

#+BEGIN_QUOTE

How can we provide a 'high quality learning environment that maximises the opportunity for our increasingly diverse, demanding and technologically sophisticated student body' (The University of Auckland Strategic Plan 2013-2020)? In Rethinking the Classroom, we draw on international best practice in the use of new technologies to promote and support research-informed innovation in teaching and learning that enhances student engagement and achievement.

#+END_QUOTE

Some of the folk I've talk to describe it as doing (making) a mini-MOOC.

Overall, it sounds pretty interesting.
