#+title: Referencing here and now
#+slug: referencing-here-and-now
#+date: 2009-12-22T10:49:00+12:00
#+lastmod: 2009-12-22T10:49:00+12:00
#+categories[]: Research
#+tags[]: APA Zotero Libx
#+draft: False

As I look back at [[{{< relref "20091222-whither-learning-styles" >}}][my last entry]] it occurs to me that I use two distinct approaches to citing and referencing ideas, works, /etc/. Specifically, I use a mixture of [[https://en.wikipedia.org/wiki/Hyperlink][hyperlinks]] and [[https://www.apastyle.org/][APA referencing]].

My habit seems to be that for non-academic works, I tend to use hyperlinks that go to appropriate sources. This seems consistent with normal practice of web-based publishing.

For scholarly works I follow APA conventions for citing and referencing. This seems more consistent with the academic expectations and practices. In acknowledgement of the fact this is electronic or web-based publishing I use [[https://en.wikipedia.org/wiki/COinS][COinS]] to ensure there is enough information so that programmes such as [[https://www.zotero.org][Zotero]] or [[https://libx.org][LibX]] can scrape/find all the information they need to quickly locate an electronic copy/source of the document.

However, I feel mildly uneasy about this situation. Should I use only APA (albeit with COinS); after-all it does have citation styles for blogs etc? Or should I only use hyperlinks; after all, this is the web? For some things, such as blog entries, APA seems entirely sensible for paper-based writings. However, for this (and other e-media), APA feels out of place. I am use to clicking hyperlinks to take to "more information". I think I can live with the mixed method of referencing. At the end of the day, I do try and acknowledge my sources, and perhaps it doesn't matter what means I do that by, providing most people recognise that I am doing it; /i.e/., most people recognise the practices that I am using.
