#+title: Wagamama
#+slug: wagamama
#+date: 2005-04-28T12:29:00+12:00
#+lastmod: 2005-04-28T12:29:00+12:00
#+categories[]: Arts
#+tags[]: Dining
#+draft: False

The movie [[https://www.imdb.com/title/tt0092048/][Tampopo]], spawned a restaurant in London called [[https://www.wagamama.com/][Wagamama]] (and that in turn spawned a cookbook). If you've seen the movie, then you won't be surprised to find out it's a noodle house. And now there is [[https://www.wagamama.co.nz/][one in Auckland]].

Lisa and I went there for lunch, and despite the queue it was well worth it. The [[https://www.wagamama.com/pdfs/menus/auckland.pdf][menu]] was full of tempting dishes---it was hard to choose what to have. However, I ended up having a chilli chicken ramen (which was super---I the soup base was particularly good), and Lisa went for the hottest dish on the menu---according to the waitress---the spicy chicken itame.

Despite being busy (we had to queue for five minutes) we were still in-and-out in under 30 minutes. The seating is what the Americans call "family style", you sit at long tables with whoever else is there. A great lunch. I recommend it.
