#+title: A consideration of learning and PowerPoint
#+slug: a-consideration-of-learning-and-powerpoint
#+date: 2013-11-19T21:12:00+12:00
#+lastmod: 2013-11-19T21:12:00+12:00
#+categories[]: Teaching
#+tags[]: Powerpoint
#+draft: False

The usage of PowerPoint in the classroom was raised (again) at MIB's Staff Student Consultative Committee meeting yesterday. I made a few comments about the topic, and I was asked to provide some of the background articles for students. And so, this rather long jotting has sprung into existence.

My starting point is the assumption that (Kinchin et al., 2008, p. 339):

#+BEGIN_QUOTE

... that true knowledge and understanding can be developed in the learner and by the learner through the transformation of fragmented, compartmentalised knowledge into knowledge of personalised meanings. The development and sharing of personalised meanings is a goal of the approach to teaching and learning embodied within human constructivism (sensu Mintzes, Wandersee, and Novak 1997). This can be outlined in three key assertions:

- Human beings are meaning makers, with the human brain endeavouring to construct order from apparent chaos.
- A goal of education is the construction of shared meanings, allowing a community of learners (students and teachers) to exchange ideas within a common framework of understanding.
- Shared meanings may be facilitated by the active intervention of well-prepared teachers. Such preparedness refers not only to subject expertise, but also to an appreciation of the students' perspectives on the world

#+END_QUOTE

Having said that, I would probably replace the word 'shared' in the above quote, with that of 'congruent'. The notion that knowledge--or a practice--can be shared is somewhat problematical (Turner, 2002). But anyway, given that the goal is to bring about congruent understandings, what role does PowerPoint typically play in that process? For now, let's set aside the use of PowerPoint slides in class (which is generally seen as endemic) and is associated with shallow/superficial forms of learning (Kinchin et al., 2008). Instead, let's focus on the issue of PowerPoint slides as handouts. Generally, is that a good thing or not?

There is evidence that student should engage in note-taking. In their review of the literature, Raver and Maydoz (2010) note that:

- Active learning is reduced when students do not engage in note taking
- Students who engage in note taking are better able to recall high-importance concepts
- Student made notes are more readily recalled than those provided by the instructor

However, they also report that weaker students are less able to effectively take notes, and in those cases instructor produced notes are better than having those 'tail' students rely on their own notes. Both students and faculty believe that the use of PowerPoint (rather than the provision of PowerPoint slides as handouts) improves the quality of students' notes (James et al., 2006).

Despite student's reporting that the provision of PowerPoint slide as handouts does not affect the likelihood of them attending class, there is evidence that the provision of PowerPoint slide does reduce attendance (James et al., 2006).

#+BEGIN_QUOTE

Lecturers typically spend hours designing and refining their PowerPoint slides, but when it comes to producing a handout to complement the presentation, a printout of the slides (usually six per page) is often produced, suggesting little thought about how it will be used by students, and is simply a repeat of the presentation. Rather than supporting and directing further learning from the presentation, the handout merely acts as a record of what it was that was seen. We would argue that the handout should do more than this. It should provide challenge for the students and have its own role in promoting student learning. Typically, the six-slides-to-a-sheet printout does not do this (Kinchin et al., 2008, p. 341).

#+END_QUOTE

#+BEGIN_QUOTE

Tufte (2003, 22) states that 'PowerPoint slides are a lazy and ridiculous way' to format handouts and describes how printed material in PowerPoint slide format typically offers 2--10% of the typographical richness of non-fiction bestsellers. Doumont (2005, 66) concludes that 'presentation slides do not double up effectively as presentation handout', but does not offer any practical suggestions that may be followed to improve the situation. Atkinson (2005) makes the greatest contribution to the debate by suggesting that a printout of slides is not helpful and that a handout made up of speaker's notes pages is the preferred option as this divorces the slides from the narration. This helps to avoid the overloading of text on the slides (Atkinson and Mayer 2004), and also allows increased typographical richness (called for by Tufte 2003) (Kinchin et al., 2008, p. 341)..

#+END_QUOTE

* References

James, K. E., Burke, L. A., & Hutchins, H. M. (2006). Powerful or pointless? Faculty versus student perceptions of powerpoint use in business education. /Business Communication Quarterly/, /69/(4), 374--396. doi:10.1177/1080569906294634

Kinchin, I. M., Chadha, D., & Kokotailo, P. (2008). Using powerpoint as a lens to focus on linearity in teaching. /Journal of Further and Higher Education/, /32/(4), 333--346. doi:10.1080/03098770802392923

Turner, S. P. (2002). /Brains/practices/relativism: Social theory after cognitive science/. Chicago: University of Chicago Press.
