#+title: Cost Benefit Analysis
#+date: 2021-09-19T16:23:00+1300
#+lastmod: 2021-09-19T16:23:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

The process of adding up the expected value of the project---the benefits---and comparing them to the dollar costs.


* The benefits of a cost-benefit analysis

A cost-benefit analysis can minimize risks and maximize gains for projects and organizations. It can help you communicate clearly with stakeholders and executives and keep your project on track. Because this type of analysis uses objective data, it can help reduce biases and keep stakeholder self-interest from influencing decisions.

Comparing a project’s benefits to its costs can help you make a strong business case to stakeholders and leadership and ensure your organization pursues the most profitable or useful projects. Organizations use cost-benefit analyses to reduce waste and invest their resources responsibly.
Guiding questions for a cost-benefit analysis

When you’re pursuing a project, the benefits should outweigh the costs. It’s important for you and your stakeholders to consider questions like the ones that follow early on, while you prepare the proposal.

* To determine the benefits of a project
You might ask:

- What value will this project create?

- How much money could this project save our organization?

- How much money will it bring in from existing customers?

- How much time will it save?

- How will it improve the customer experience?

* To determine the costs of a project
Consider questions such as:

- How much time will people have to spend on this project?

- What are the one-time costs?

- Are there any ongoing costs?

- What about long-term costs?

* You might also consider intangible benefits
These are gains that are not quantifiable, such as:

- Customer satisfaction. Will the project increase customer retention, causing them to spend more on the company’s products or services?

- Employee satisfaction. Is the project likely to improve employee morale, reducing turnover?

- Employee productivity. Will the project reduce employee’s overtime hours, saving the company money?

- Brand perception. Is the project likely to improve the company’s brand perception and recognition, attracting more customers or providing a competitive advantage?

You can also flip these questions to consider intangible costs. These are costs that are not quantifiable. For example, might the project put customer retention, employee satisfaction, or brand perception at risk?

When assigning values to tangible or intangible costs and benefits, you can reference similar past projects, conduct industry research, or consult with experts.
Calculating costs and benefits

The process of calculating costs and benefits is also called calculating return on investment, or ROI. There are many ways to determine a project’s ROI, but the easiest way is to compare the upfront and ongoing costs to its benefits over time.

One common ROI formula is:
 ROI = (G - C) / G

In this formula, *G* represents the financial gains you expect from the project, and *C* represents the upfront and ongoing costs of your investment in the project.

* Summary

Performing a cost-benefit analysis can help you and your stakeholders determine if it makes sense to take on a new project by evaluating if its benefits outweigh its costs. When conducting cost-benefit analyses for your prospective projects, you can use the guiding questions and ROI formula provided in this reading as a reference.

* Backlinks
- [[{{< ref "202109121929-project-phase-initiation" >}}][Project phase - initiation]]
-

* References


#+CATEGORY: Notes
#+STARTUP: showall
