#+title: Confusion reigns
#+slug: confusion-reigns
#+date: 2004-05-19T07:46:00+12:00
#+lastmod: 2004-05-19T07:46:00+12:00
#+categories[]: Home
#+tags[]: Psychodrama
#+draft: False

I end up at a psychodrama class to night. I say /ended/ because I only popped in to drop off some books to the library at [[https://www.psychodrama.org.nz/atcp.html][ATCP]].

I'd had some confusing calls during the day about classes being on, so I went in just in case I was still confused (about the class being on or off). It was on.

It was an unusual class. I wasn't really expecting to attend class I wasn't warmed up (in the way that I usually am) for class. I was strangely disengaged. Of course, that could be related to the other things that are [[20040508-a-wake-up-call][going on for me]]. But I did leave feeling somewhat unsatisfied. All the more so, because Vivienne had challenged me with a line like "Are you getting what you deserve? Are you going for gold in your life?"

I found these two seemingly simple questions difficult to answer, and actually, I didn't answer them in any meaningful way. I recall that I called my answer "unsatisfying". It was then, and it still is now.

Having slept on it for a while, it occurs to me that I tend to take two different roles. Firstly, there is the /happy rambler/, cheerfully wandering through life, finding enjoyment in most things. Secondly, there is the /focused achiever/, determined reach whatever goal he wants. The interesting thing is the /focused achiever/ sometimes pretends to be the /happy rambler/ (especially, when things aren't going as expected), and sometimes the /focused achiever/ is subsumed by the other. I suppose that only having these two roles is limiting, so I wonder how my role repertoire in these areas can be expanded.
