#+title: The flow of assignments
#+slug: the-flow-of-assignments
#+date: 2004-05-16T22:05:00+12:00
#+lastmod: 2004-05-16T22:05:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301 Assignments
#+draft: False

When we, that is DPE, were putting the course together we had a logical, albeit obtuse, link between the assignments.

I don't think it matters if that logic is known or not, and I suspect that some people have already spotted the link. Nevertheless, for the sake of transparency, I thought I'd write a little about that link. However, I should point out, before anyone gets too anxious, this is how we constructed the assignments--it isn't about what the assignments should be--or what the students need to deliver.

Standing back, and looking at the first assignment two themes emerge for me--the 'theory' of teams and the role(s) the student will have in the team. Because of the timing of the assignment, there is often little to write about the team per se. Rather, it is about the student's anticipation of the team life.

Whereas, the second assignment, coming much later in the course, allows the student, and given the nature of the assignment, compels the student to explore the relation between them self and the team at large. In this way the assignments move from something reflective, and largely geared to the individual, to a reflection on the individual /in relationship/ with the team. Casting this in socio-dramatic terms it is really about the social-atom that is the team, The final assignment, hopefully, is still reflective but continues to expand the circle of interest. Thus, the student now needs to make sense of the whole course which entails moving beyond the relationship with the team and put themselves (and there learning) in a broader relationship.

The 'ideal-type' of final assignment will draw on the prior two assignments to provide a rich insight into a 'critical incident'. Drawing on sense-making that has already occurred (via their journals), student's will be able to demonstrate the value of their learning.

I think next semester, we'll make the link a little more explicit and reshape the assignments a little ...
