#+title: Chocks away on the search engines
#+slug: chocks-away-on-the-search-engines
#+date: 2004-04-01T16:25:00+12:00
#+lastmod: 2004-04-01T16:25:00+12:00
#+categories[]: Tech
#+tags[]: Website Awstats Google
#+draft: False

For many years, my robots.txt file has barred ever robot from the site.  Well that has changed now. So now I'm sitting back waiting for [[https://www.google.com][Google]], [[https://www.yahoo.com][Yahoo]], and all the other engines to start coming.  I'm fascinated by who comes to the site, so the [[https://awstats.sourceforge.net/][web stats package]] behind the site is quiet comprehensive. But, it is also interesting to see how people get here from the various search engines. Enter [[https://twiki.tensegrity.net/bin/view/Main/SearchReferralZeitgeist][Zeitgeist]]. In case you didn't know, when you use an search engine to find a site, when you click the link to go to a site, the details of the search you used is sent to the site you're going to. Does that make sense? Maybe an example will help.

If you go to [[https://www.google.com][Google]] and search for [[https://www.google.com/search?q=BBIM+psychodrama][BBIM psychodrama]] you end up with one link to [[https://www.thereflectivepractitioner.org][The Reflective Practitioner]].  When you click the link on Google for here, the details of you search (BBIM psychodrama) come with you. Every few hours Zeitgeist checks the logs here and builds a [[https://www.thereflectivepractitioner.org/zietgeist.html][Zeitgeist page]] which show the search terms people used to find the site. At the moment it is largely rubbish, as it is the result of my trying the technology out. But over time it should be pretty reliable.  All I need know is those search engines to come and index the complete site (at the moment they have only done the first "page').

In case you're interested Google has it's own [[https://www.google.com/press/zeitgeist.html][Zeitgeist page]] so you can see what are the current "hot" search terms.

