#+title: Telecom - Customer Service of the year (Yeah. Right!)
#+slug: telecom-customer-service-of-the-year-yeah-right
#+date: 2005-10-25T19:45:00+12:00
#+lastmod: 2005-10-25T19:45:00+12:00
#+categories[]: Tech
#+tags[]: Internet ADSL Jetstream
#+draft: False

I went to use the Jetstream usage meter to day, and instead of the usual terse message I got:

#+BEGIN_EXAMPLE

-------------------------------------------------------------
Caught SCLMessage exception.
-------------------------------------------------------------
DETAILS :
Source Module : IafTranslate.C
Source Line : 102
Message Symbol :
Message Text : error opening language map[./LanguageMap.txt]
reason[No such file or directory]

#+END_EXAMPLE

Now I had this problem once before about 4 years ago[fn::[[https://www.unixathome.org/adsl/archives/2001_02/0108.html][Posting]] to the [[https://www.unixathome.org/adsl/][ADSL list]] that chronicles my first encounter of the problem.]. It was a nightmare because most of the people I talked to at Telecom thought the error message was being generated at my end. In fact it is an error message generated by the server at Telecom. --- If only I could remember the fix[fn::Cookies---surely no error message could be that obscure.].

Anyway, I dialed 123 (Telecom's help-desk). After navigating my way through the menus the system eventually told me to go away (because I'm using someone else as my ISP).

But the fault isn't with my ISP it is with Telecom.

So, I try 123 again and this time I try the good old /0/ to get an operator. I get nice music for a few minutes. Then I get a few minutes of ring-tone. Then the line hangs up! I try again. Same result. This all takes about 30 minutes. I dial 123 and this time I pretend to be a customer of Xtra (Telecom's ISP).

The person who answers the phone is keen to tell me my Internet usage, but doesn't want to take any details of the problem. Instead he says "That belongs to a different company, they'll look at it tomorrow and get it working". Yeah. Right. I'm filled with confidence.

I explain to him the problems I had last time getting it fixed. But no, he doesn't want to do anything else (except mail me my usage). /Arrgh!/ It will be interesting to see if it is fixed tomorrow. For those wondering about the /Yeah. Right/ comment, it is a Kiwi reference to a series of [[https://www.istart.co.nz/index/HM20/PC/PV23539/EX2342/CS27126][commercials]] for a beer. As in:

#+BEGIN_QUOTE

  "We'll keep your CV on file"

  "Yeah. Right"

#+END_QUOTE

*** Update to the story

Okay, I confess. I did try and circumvented the system---perhaps I should have talked to my ISP. And yes, despite the warnings on the site about enabling cookies---and I hadn't---and yes, the problem was caused by a lack of cookies. But seriously, this has to be one of the silliest messages [fn:: The first time I had the problem they had never head of the error message.] ever for saying "Turn cookies on". Having searched [[https://www.google.com/search?q=IafTranslate.C][Google]] for the problem, it seems that not many people encounter this. I wonder why.


and I had to figure out the solution myself. You'd think after all this time Telecom would have a better error message.
