#+title: Hooked on audio books
#+slug: hooked-on-audio-books
#+date: 2005-05-12T15:24:00+12:00
#+lastmod: 2005-05-12T15:24:00+12:00
#+categories[]: Arts
#+tags[]: AudioBooks
#+draft: False

We are only allotted a certain amount of time to do what we want to do. There will never be more than 24 hours in the day. But sometimes, I feel like there isn't enough time.

For some time I've been saying I'd like to do more reading. Of late most (all) of my reading has been linked to my research and teaching. There has been little time for "recreational" reading. That was before I got my [[{{< ref "recording-on-the-ipod" >}}][iPod]] and before I found out about [[https://www.audible.com/][Audible]]. Now I'm hooked on buying and downloading audio books. The beauty of audio books on the iPod is that you can listen as you are walking from place to place. Now I can get through two or three books a month extra---it doesn't sound like much, but it really makes a difference. Consequently, I'm taking the opportunity to "read" things for which I would normally not have time. For example, I've just finished /The life of Pi/, and I thoroughly enjoyed /The white Russian/ (Thanks for the recommendation Leone).

Of course, sometimes I drift back into /research mode/, and so I'm currently listening to Jack Welsh's biography /Jack: Straight from the gut/.
