#+title: Persuasive technology
#+slug: persuasive-tech
#+date: 2017-05-09T16:57:24+12:00
#+lastmod: 2017-05-09T16:57:24+12:00
#+categories[]: Tech
#+tags[]: Productivity
#+draft: False

Andrew E. and I had a really interesting talk about persuasive technology (captology) yesterday. His comments made me realise how much (and how cleverly) a lot of modern technology fosters engagement.

All the different ways in which websites work to either keep glued to them, or all the things they do to get me to return---those endless reminders that stuff is happening out in the 'social world'.

That conversation has prompted me to do one of my infrequent tidy-ups. Unsubscribing from maillists, squaring away accounts and deleting them (yammer), turning of notifications (on my phone).

Trying to get back to a quieter, less interrupt driven life. Some might even say 'mindful'.

That said, its not all about lost productivity and superficial engagement. At a larger social scale, persuasive technology can be used to [[https://www.theguardian.com/technology/2017/may/07/the-great-british-brexit-robbery-hijacked-democracy][undermine democracy]].

The Guardian article, highlights just how sophisticated and extensive attempts to 'persuade' can be.
