#+title: Project governance
#+date: 2021-09-16T18:47:00+1300
#+lastmod: 2021-09-16T18:47:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management Governance


As a project manager, you will be responsible for project governance. Project governance is the framework for how project decisions are made. Project governance helps keep projects running smoothly, on time, and within budget. Project governance involves all the key elements that make a project successful. It tells you what activities an organization does and who is responsible for those activities. Project governance covers policies, regulations, functions, processes, procedures, and responsibilities.

* How project and corporate governance intersect

Project governance needs to be tailored to your organization's specific needs. These needs will influence how you implement and monitor the governance framework on your project. Project governance concerns those areas of corporate governance that are specifically related to project activities. Effective project governance ensures that an organization’s projects are aligned to the organization’s larger objectives, are delivered efficiently, and are sustainable. This includes:

- Considering the long- and short-term interests of your organization

- Making thoughtful decisions about which projects to take on and avoiding projects if you do not have sufficient resources

- Providing timely, relevant, and reliable information to the board of directors and other major stakeholders

- Eliciting the input and buy-in of senior managers since they are the decision-makers

- During the initiation phase, prioritizing clear, reachable, and sustainable goals in order to reduce confusion and conflict

- During the planning phase, assigning ownership and accountability to an experienced team to deliver, monitor, and control the process

- During the execution phase, learning from mistakes and adapting to new or improved knowledge

Corporate governance can involve clearing many hurdles before making decisions. These decisions can influence not only a single project, but the entire corporation.

At the same time, corporate governance can help support project governance, as it provides oversight on compliance and mitigating risk and offers guidance and direction for project managers. Good corporate governance can also help project managers secure resources, get issues addressed, avoid delays in decision-making, get buy-in from stakeholders, and achieve visibility for projects on the executive level.

* Key takeaway

You should think about an organization’s culture and structure when you are interviewing for a new role and as you begin a new role or project. You should consider an organization’s governance processes and practices in the same way. This will help you understand how decisions are made, who is responsible for what, and what are the potential issues and areas of concern.
* Backlinks
- [[{{< ref "202109111145-project-management" >}}][Project management]]
- [[{{< ref "202109161846-governance" >}}][Governance]]
