#+title: One ring to rule them all
#+slug: one-ring-to-rule-them-all
#+date: 2015-11-20T20:30:00+12:00
#+lastmod: 2015-11-20T20:30:00+12:00
#+categories[]: Tech
#+tags[]: Blogging HTML Pelican
#+draft: False

I am in the process of trying to simplify my life a little. That has seen me leaving Daily Mile (I think the site was dying anyway), and removing Facebook from my iPhone.

In conjunction with that, I am trying to automate some process, such as when I blog here, I want it to be tweeted out, and (eventually) posted to Facebook.

The first problem was trying to get my RSS feed to be clean; well, to get past the W3C RSS validator. This took a little bit of tweaking some source files. E.g., feedburner.py and changing:

#+BEGIN_EXAMPLE

handler.addQuickElement("guid", item['unique_id'])

#+END_EXAMPLE

to

#+BEGIN_EXAMPLE

handler.addQuickElement('guid', item['unique_id'], attrs={"isPermaLink": "false"})

#+END_EXAMPLE

That fixed a problem with Pelican's GUIDs, but I could not get the RSS feed to be accepted by dlvr.it (the service I am trying to use to propagate my posts). So, I switched to using atom.xml. That sees to be okay.

This will be the first post that should be tweeted out for me. Let's see what happens.
