#+title: Scrum - Product Backlog
#+date: 2021-09-30T18:40:00+1300
#+lastmod: 2021-09-30T18:40:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management Backlog

The Product Backlog is the single authoritative source for things that a team works on. It contains all the features, requirements and activities associated with deliverables to achieve the goals of the project. As such it is the guide and roadmap to the product.

It is:

1. A living artefact
2. Owned and adjusted by the Product Owner
3. A prioritized list of features

* Key components of items on the backlog
** The description
It describes an item.

** The value
How much business value the item delivers to the customer, the team, or the business

** The estimate
How much effort the Scrum Team thinks the item will take to deliver. It is owned by the development team.

** The order
The priority of the item. The Product Owner will often base this on a combination of the value and the estimate. This is often known as a stacked-rank.

* Commitment: Product Goal
:PROPERTIES:
:ID:       63355a7e-dbae-48bb-aefd-dda16bdf959f
:END:

The Product Goal describes a future state of the product which can serve as a target for the Scrum Team to plan against. The Product Goal is in the Product Backlog. The rest of the Product Backlog emerges to define “what” will fulfill the Product Goal.

- A product is a vehicle to deliver value. It has a clear boundary, known stakeholders, well-defined users or customers. A product could be a service, a physical product, or something more abstract.

The Product Goal is the long-term objective for the Scrum Team. They must fulfill (or abandon) one objective before taking on the next.


* Backlinks
:PROPERTIES:
:ID:       94c1e6b2-db54-4959-99ee-3f62023918c2
:END:
- [[{{< ref "202109131858-scrum" >}}][Scrum]]

