#+title: Class format
#+slug: class-format
#+date: 2004-07-24T00:17:00+12:00
#+lastmod: 2004-07-24T00:17:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT302 Cases
#+draft: False

After class today, a number of people came up to me and asked if the format of the class, in particular the type of questions I asked, would be the same each week.

I think my opening question on the Telecom Case was something like, "In 1999 would you have bought shares in Telecom?" A simple question, but to answer the question well it is necessary to have a sound understanding of the situation Telecom found itself in, and the problems it faced. Anyone, who had a prepared position on the case should have been able to provide a robust answer to that question (and some did).

We then sort of plodded through the [[https://www.bcg.com][BCG]] / [[https://www.amazon.com/exec/obidos/tg/detail/-/0960191038?v=glance][Minto-esque]] approach of /situation, complication, solution, and impact/. I doubt we will tackle a case using this approach (in this course). Firstly, using a structured approach, like this, is useful for those who find it hard to know /where to begin/ with a case. But, in future, students will have a larger body of theory and experience on which to draw. In fact, each case is can be well address based on the readings for the week.

Actually, now I say it I wonder what Mason & Mitroff would have to say...

* References

Mason, R. O., & Mitroff, I. (1998). Complexity: The nature of real world problems. In B. de Wit & R. Meyer (Eds.), /Strategy process, content, context: An international perspective/ (2nd ed.). Minneapolis, MN: Thompson Learning.
