#+title: Trust
#+slug: trust
#+date: 2004-03-22T20:58:00+12:00
#+lastmod: 2004-03-22T20:58:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301
#+draft: False

I've known Darl for over ten years now. I have a lot of trust in him. I've known Emma for two years, and she has never done anything to make me think I can't trust her. So why was I worried about today's class? Perhaps, at the heart of it, is trust in the technology. One thing we know about virtual teams is that problems with technology are not unknown---especially when trying something new. Having been in the I industry for a long time, I'm well aware (or is it overly sensitive) to the problems that can arise. I've seen so many projects stumble on the first trial. And, because of the unique characteristics of MGMT 301, every session is 'first time' in some way or another---and thus, there is the 'opportunity' for failure (or is it to learn). And so, trust isn't only about people, its about trusting systems too.

After class, Darl, Emma, and I were talking about what went on in the class and in the subsequent meetings with students. Darl made some really good points and I hope he has time to journal them (for all to see). Typically, in total, we spend several hours together each week talking about the class (how we did---what we learnt from the students---what might be different---where the class is going---etc). Is sometimes wonder if students talk about use as much as we talk about them. We seek to be reflexive in our work---in fact peer review (by our peers) forms an important part of our process. Relatively speaking, very little time, when we are together as a team, is given over to 'content'. We trust that if our processes are good (we've been working on them for years, and I think they are good) then the content will follow. Most of the content work is done individually and then bring it together for integration. That almost sounds like a Mike's Bikes team, doesn't it.

So, to my point. I trust my colleagues and I trust our process; but, there are some things that lie outside of those two things. Micro processes, such as today's email in class, need to attended to---possibly more than the big things. As the saying goes, "For want of a nail, the shoe was lost ..."
