#+title: Project risk mitigation
#+date: 2021-10-17T13:26:00+1300
#+lastmod: 2021-10-17T13:26:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management


Risk mitigation planning is about finding ways to eliminate or reduce the impact of potential risks to your project. There are four common ways to mitigate risk:
- Avoid it
- Accept it
- Reduce or control it
- Transfer it

* Building a risk management plan
A living document that contains information regarding high level risks and the mitigation plans for those risks.

The plan should be updated regularly to add newly-identified risks, remove risks that are no longer relevant, and include any changes in the mitigation plans.

It includes the risk register, and the mitigation plans.

It can also include the risk matrix


* Communicate risks to stakeholders
If you don't tell stakeholders about important risks, they may be less equipped to help you if an issue arises.

Failing to communicate risks to stakeholders can erode their trust in you as the leader of the project.

Communicate early with stakeholders about high- and medium-level risks.

The serious nature of high-level risks requires direct communication with stakeholders.


* Backlinks
- [[{{< ref "202110171207-project-risk-management" >}}][Project risk management]]
- [[{{< ref "202109121932-project-phase-planning" >}}][Project phase - planning]]
