#+title: Lean six sigma project management
#+date: 2021-09-13T19:06:00+1300
#+lastmod: 2021-09-13T19:06:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management Six_Sigma

Lean Six Sigma is a project management methodology that is combination of two parent methodologies, Lean and Six Sigma.

The uses for Lean Six Sigma are common in projects that have goals to save money, improve quality, and move through processes quickly.

It focuses on team collaboration which promotes a positive work environment. The idea is that when your team feels valued, motivation and productivity increases and the whole process functions more smoothly.


There are five phases in the Lean Six Sigma approach commonly known as DMAIC:
- define,
- measure,
- analyze,
- improve, and
- control.

These steps are somewhat different to the usual [[{{< ref "202109121327-project-life-cycle" >}}][project life cycle]] phases.

DMAIC is a strategy for process improvement, meaning you're trying to figure out where the problems are in the current process and fix them so that everything runs more smoothly.

The goal of each step is to ensure the best possible results for your project.


DMAIC process is that it can be used to solve any business problem.


Data analysis is important for project managers regardless of which method  choosen.


* When to use Lean Six Sigma
:PROPERTIES:
:ID:       1fa5476d-67a0-497b-b35e-37bbf87aebc9
:END:
Lean Six Sigma and the DMAIC approach are ideal when the project goal includes improving the current process to fix
complex or high risk problems

Implement Lean project management when you want to use limited resources, reduce waste, and streamline processes to gain maximum benefits. You can achieve this by using the [[{{< ref "202109141856-pillars-of-the-lean-5s-quality-tool" >}}][pillars of the Lean 5S quality tool]]. The term 5S refers to the five pillars that are required for good housekeeping

* Summary
Lean Six Sigma is a combination of Lean and Six Sigma approaches. It is often used in projects that aim to save money, improve quality, and move through processes quickly. Lean Six Sigma is also ideal for solving complex or high-risk problems. The 5S quality tool, the DMAIC process, and the use of Kanban boards are all components of this approach.

* Backlinks
- [[{{< ref "202109121956-project-management-methodology" >}}][Project management methodology]]
- [[{{< ref "202109141856-pillars-of-the-lean-5s-quality-tool" >}}][Pillars of the Lean 5S quality tool]]  
