#+title: RACI charts
#+date: 2021-09-25T15:49:00+1300
#+lastmod: 2021-09-25T15:49:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management RACI

A RACI chart helps to define roles and responsibilities for individuals or teams to ensure work gets done efficiently. It creates clear roles and gives direction for each team member.

There are four types of participation included in a RACI chart:
- Responsible: those doing the work to complete the task
- Accountable: those making sure the work gets done - *only one of these per task*
- Consulted: those giving feedback, like subject matter experts or decision-makers.
- Informed: those just needing to know the final decisions or that a task is complete

*Pro tip*: You could end up with a large number of team members and stakeholders who are placed in the “informed” role. If so, make sure that you have a plan to keep them informed that is not labor-intensive. Something as easy as view-only access to your project plan or meeting notes could prevent you from having to create separate communications along the way.

* Getting the most out of a RACI chart

** Workload balance

Are there too many tasks assigned to one stakeholder? When you complete your chart, it is a good idea to go back through and tally the number of Rs assigned to each stakeholder. This can help you identify potentially overloading one team member with work. Using a RACI chart to determine responsibility for tasks can help mitigate single points of failure (known as creating silos, where the knowledge and responsibility for a task falls on one person) and allow you, as the project manager, to delegate tasks and avoid burnout. Maintaining workload balance is a critical part of project management. It is easy to fall into the pattern of relying on your top performers to keep the project moving forward. But this isn’t always healthy for the project or your team. If you find that you don’t have the right people to assign responsibilities to, take a step back and evaluate your team.

** Put your RACI into practice

Once you have created your RACI chart, it is time to put it into practice. You will first *need to share your RACI chart with your sponsors and stakeholders to get buy-in and sign-off*. When you get stakeholder buy-in, you will be able to set clear expectations for your team and ensure that everyone is aligned on their responsibilities.

You can document your team and stakeholders’ acknowledgment of these expectations through the project charter, meeting notes, and in the RACI chart itself. Think back to a time when you were expected to do something you did not agree with, or weren’t clear on. That disagreement or lack of clarity made it difficult to do your best work, right? Getting buy-in and continually checking in with your stakeholders and your team is the way to avoid this potential pitfall!

As you take the time to ensure that each task has an owner identified with the appropriate level of engagement, you are streamlining your communication and decision-making process over the life cycle of your project.

** When should you use a RACI chart?

If you are wondering if you should use a RACI chart on your project, it is a good idea to evaluate the complexity of the effort. For example, if you have a very small project team with a small amount of stakeholders, clearly defined roles, and a short timeline, introducing a RACI chart could possibly slow down the project. However, larger projects, or even projects that involve a large number of stakeholders, could greatly benefit from a RACI chart. It is always a good idea to work through the creation of a RACI chart and evaluate the outcome. Even if you do not end up using the RACI chart, you will have a better understanding of the project, and your effort will contribute to your project management experience overall.

* Backlinks
:PROPERTIES:
:ID:       5290367f-94f7-4113-a3f0-a472c57ea9c5
:END:
- [[{{< ref "202109251428-project-stakeholders" >}}][Project stakeholders]]
- [[{{< ref "202109121929-project-phase-initiation" >}}][Project phase - initiation]]
- [[{{< ref "202109191642-project-charter" >}}][Project charter]]

