#+title: Formal analysis in strategic decisions
#+date: 2004-08-05T15:56:00+12:00
#+lastmod: 2004-08-05T15:56:00+12:00
#+categories[]: Research
#+tags[]: Article Strategy
#+slug: formal-analysis-in-strategic-decisions
#+draft: False

I try to be active in the [[https://www.strategy-as-practice.org/][strategy-as-practice]] community. One of the ways I do this is by maintaining a bibliography of readings that is available through the [[https://www.strategy-as-practice.org/][web-site]]. A few weeks ago, I asked people for any suggestions to add to the bibliography. [[https://www.strath.ac.uk/gsb/staff/johnson_g.html][Gerry Johnson]] sent me a list he has been working on with [[https://www.ihh.hj.se/eng/research/emm_faculty/emm_leif_melin.htm][Leif]] [[https://www.ihh.hj.se/info/nyheter/2003/2003_06_19_leifmelin.htm][Melin]]. I've start to work through the list, getting copies of the articles and reading them, as I add them to the bibliography. The first article is:

#+BEGIN_QUOTE

Langley, A. (1990). Patterns in the use of formal analysis in strategic decisions. /Organization Studies, 11/(1), 17--45.

#+END_QUOTE

The abstract says:

#+BEGIN_QUOTE

An empirical study examined how formal analysis is used in strategic decision making in 3 organizations of different structural types. In-depth investigation was made of the role of formal analysis at top levels in 3 organizations---a machine bureaucracy, a professional bureaucracy, and an adhocracy. It was found that formal analysis is used for a variety of purposes in organizations, and the way in which it is used varies from organization to organization. Three patterns of use were identified: 1. Analysis is used for substantive input to decisions, to control implementation, and to ensure convergence toward action. 2. Analysis becomes a key tool of persuasion and verification in the negotiation process between levels of the hierarchy concerning actions to be taken. 3. Analysis appears unproductive as people use it to put forward contradictory positions and to gain time in an atmosphere of indecision and divergence. This suggests that organizational structure is a key factor affecting the decision process.

#+END_QUOTE

There are a number of things that stand out after reading this article. Firstly, it reminds me that formal analysis is more prevalent in the later stages on strategising, e.g. in the evaluation of strategies or in filling in the details---maybe through into implementation, rather than in the earlier, dare I say more intuitive, formulation stages. I expect this is due the greater reliance on creativity in the 'earlier' part of strategising. Secondly, the nature or configuration (e.g. Mintzberg, 1983) of the firm---in a structural sense---impacts the ways in which formal (and informal) analysis is used. I think this can be linked to [[{{< relref "20040412-the-structuring-of-organizational-structures" >}}][Ranson, Hinings, & Greenwood's]] (1980) idea that structure and the way the organisation things are intertwined (the archetype as they call it)---although that explicit link is not made in the article.

Finally, it reminds me that I have to get around to reading Linblom's classic 1959 article on /muddling through/.

** References.

Lindblom, C. (1959). The science of muddling through. /Public Administration Review, 19/(2), 79--88.

Mintzberg, H. (1983). /Structure in fives: Designing effective organizations/. Upper Saddle River, NJ: Prentice Hall.

Ranson, S., Hinings, C. R., & Greenwood, R. (1980). The structuring of organizational structures. /Administrative Science Quarterly, 25/, 1--17.
