#+title: OKR - Objectives and Key Results
#+date: 2021-09-22T18:36:00+1300
#+lastmod: 2021-09-22T18:36:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

Like the SMART method, OKRs help establish and clarify goals or objectives for an organization, department, project or person. OKRs take SMART goals a step further by combining a goal and more detailed metrics to determine a measurable outcome.

OKR stands for objectives and key results. They combine a goal and a metric to determine a measurable outcome.
- Objectives: Defines what needs to be achieved; describes a desired outcome.
- Key results: The measurable outcomes that objectively define when the objective has been met

The O stands for objective, and defines what needs to be achieved. It describes the desired result or outcome, such as an increase in customer retention, or an improvement on the employee onboarding process.


KR stands for key results. These are the measurable outcomes that define when they objective has been met.

Organizations often set OKRs at different levels, such as the company level, department or team level, and project level. Company-level OKRs are commonly shared across an organization so that everyone is clear on the company's goals. They are usually updated on an annual basis to help drive the organization in the direction it wants to go. These high-level OKRs support the mission of the organization. Project-level OKRs should support and be aligned with company-level OKRs.

OKR stands for objectives and key results. They combine a goal and a metric to determine a measurable outcome.
- Objectives: Defines what needs to be achieved; describes a desired outcome.
- Key results: The measurable outcomes that objectively define when the objective has been met


** Strong objectives meet the following criteria. They are:

- Aspirational
- Aligned with organizational goals
- Action-oriented
- Concrete
- Significant

To help shape each objective, ask yourself and your team:

- Does the objective help in achieving the project’s overall goals?
- Does the objective align with company and departmental OKRs?
- Is the objective inspiring and motivational?
- Will achieving the objective make a significant impact?


** Strong key results meet the following criteria:

- Results-orientednot a task
- Measurable and verifiable
- Specific and time-bound
- Aggressive yet realistic

To help shape your key results, ask yourself and your team the following:

- What does success mean?
-  What metrics would prove that we’ve successfully achieved the objective?


* OKR development best practices

Here are some best practices to keep in mind when writing OKRs:

- Think of your objectives as being motivational and inspiring and your key results as being tactical and specific. The objective describes what you want to do and the key results describe how you’ll know you did it.

- As a general rule, try to develop around 2-3  key results for each objective.

- Be sure to document your OKRs and link to them in your project plan.

* Using OKRs to evaluate progress

** Communicating and tracking OKRs

Conducting regular check-ins and actively tracking progress with your team can help ensure that objectives are being met and that any issues are resolved as soon as possible.

Share your OKRs with your team. Once you’ve created OKRs for your project, it’s important to communicate them to your team so that everyone knows how to focus and align their efforts. You can do this by sharing a digital document, presenting them in a meeting, or adding them to an internal website. OKRs can help your project team stick to its goals, monitor which are falling short, and be continuously motivated to meet project objectives.

Assign owners. Assign an owner to every key result so that everybody knows who’s responsible for what. This helps add clarity and increases accountability.

** Measuring progress

Measuring your OKRs is an important part of tracking and sharing your progress. One shortcut to determining the status of a project is to score or grade your OKRs. While scores or grades don’t provide a complete assessment of a project’s success, they’re helpful tools for determining how close you came to achieving your objectives. You can then share your OKR scores with project stakeholders and team members as part of your overall project updates.

Determine how you will score your OKRs. OKRs can be scored in different ways. You can score based on a percentage of the objective completed, the completion of certain milestones, or a scale of 1 to 10, for example. You can also use a “traffic light” scoring approach, where red means you didn’t make any progress, yellow means you made some progress, and green means you completed your objective.

The simplest approach to scoring OKRs is the “yes/no” method, with “yes” meaning you achieved your objective and “no” meaning you didn’t. Using this approach, a key result such as “Launch a new widget marketing campaign” might be graded a 1 or 0 depending on whether it was launched (1) or not (0).

A more advanced scoring approach is to grade your key results on a scale. With this method, if a key result was to “Launch six new features” and only three new features were launched, the OKR might be graded 0.5. Generally, if the KR helped you achieve the objective, your OKR should receive a higher score; if it didn't, your OKR should receive a lower score.

At Google, OKRs are usually graded on a scale of 0.0 to 1.0, with 1.0 meaning the objective was fully achieved. Each individual key result is graded and then the grades are averaged to determine the score for that OKR.

Set your scoring expectations. With Google’s 0.01.0 scale, the expectation is to set ambitious OKRs and aim to achieve an average of at least 0.6 to 0.7 across all OKRs. For OKRs graded according to percentage achieved, the sweet spot is somewhere in the 6070% range. Scoring lower may mean the team is not achieving what it could be. Scoring higher may mean the aspirational goals are not being set high enough.

Schedule checkpoints. It’s important to regularly communicate the status of project OKRs with your team and senior managers. For example, it can be helpful to have monthly check-ins on the progress of OKRs to give both individuals and your team a sense of where they are. Typically, at the end of the quarter, you’ll grade each of your OKRs to evaluate how well the team did to achieve its goals.

* Key takeaway

OKRs can help you define and measure your project’s success criteria. In order for OKRs to be used to effectively meet your project’s success criteria, it’s important to share them with your team, assign owners to each key result to ensure accountability, measure your OKRs’ progress by scoring them, and track your OKRs’ progress by scheduling regular check-ins with your team.


* Backlinks
- [[{{< ref "202109191731-project-goals" >}}][Project goals]]
