#+title: Of maps
#+slug: of-maps
#+date: 2004-03-11T11:48:00+12:00
#+lastmod: 2004-03-11T11:48:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT301 Maps
#+draft: False

I've been doing some prep (I was looking up some information on the London Underground. In particular, see Tufte on the [[https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=00005W][Beck's map of the London Underground]]) for next weeks lecture, and I stumbled across [[https://www.simiandesign.com/blog-fu/2004/01/information_design.php][Blog-Fu]].

Whilst that site is mainly about information design (Is information design an oxymoron?. Can information be designed? I expect many people may want to argue that point.) it does also link to the work of [[https://www.edwardtufte.com/tufte/][Edward Tufte]]. He was the person who revitalised interest in Minard's stunning 'map' of [[https://www.edwardtufte.com/tufte/minard][Napoleon's March]].

It suppose it is at least two years ago that [[https://www.geocities.com/drdavidbarry/][David Barry]] and I were talking about these issues (of maps and meanings). Strangely, I had forgotten about that discussion until I saw the Napoleon's March map again.

The maps that we have, either on paper or in our head, shape our understanding of the world. I wonder how many people have taken a half-an-hour journey on the tube (/The tube/ is the colloquial name for the London Underground)) (changing trains or lines) because the map indicated that was the most direct route; when it would have been quicker in time, and shorted in distance to walk from the station. The problem is that people forget that the map isn't geographically accurate.

This applies to many maps we use. Whilst they are accurate on some level, e.g. the connection between stations, the implicit simplification that a map introduces also means that it must be inaccurate at some other level (e.g., the physical distance between stations).

It is this duality of maps, being accurate and necessarily inaccurate at the same time that piques my interest.
