#+title: In Zürich
#+date: 2023-04-07T14:27:49+02:00
#+lastmod: 2023-04-07T14:27:49+02:00
#+categories[]: Travel Academia
#+tags[]: RSL Sabbatical

I arrived in Zürich on Monday to continue my sabbatical (Research and Study Leave) at the University of Zürich.

As always, I broke the trip to Europe with a stopover; this time spending a couple of days in Los Angeles (but that´s another story).

The University of Zürich sits besides ETH Zürich (the federal technical university). Both have similar numbers of students and it seems as if there is a healthy rivalry between them.

# more

I´m being hosted by David Siedl and the OMT team. They are a great, smart, and hard-working bunch of people. It promises to be a very rewarding stay.

Today, Good Friday, is the start of the Easter weekend, and pretty much everything is closed except for a few shops at the Central Station. It´s going to be like that on Easter Sunday and Easter Monday, so I´ve had to make sure I´ve got enough supplies in for the weekend (there will be no dining out, except on Saturday ... and even then I hear the shops will probably close early).

All in all, I am really impressed by the University and by the city. As I say, it´s going to be a good trip.

As an aside, I´ve been practising my German (not Swiss German) and so I have reconfigured my keyboard to allow easier typing of the various accented characters such as ä and ß. It works rather well, except occasionally my fingers slip and I get somewhat ´random´ characters such as á or ǘ.



