#+title: Mintzberg on management and strategy
#+slug: mintzberg-on-management-and-strategy
#+date: 2004-07-22T14:09:00+12:00
#+lastmod: 2004-07-22T14:09:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT101 ICANZ
#+draft: False

Yesterday, in MGMT 101--/organisation and management/, I was laying out some of the territory that the class (and I, I suppose) will be covering in the coming weeks. For whatever reason[fn:1], much of the course is structured around PLOC[fn:2]; planning, leading, organising, and controlling. As I pointed out in class, this is not an accurate description of what managers do. I mentioned that since the 1970s we (academics) have had a much richer view of the work of managers. In fact, I was alluding to the early (earliest) work of Henry Mintzberg[fn:3].

Anyway,as I was reading today, I came across a nice introductionary article to Henry Mintzberg. It's well worth reading by stage I students, and is called:

#+BEGIN_QUOTE

de Holan, P. M., & Mintzberg, H. (2004). Management as life's essence: 30 years of The nature of managerial work. /Strategic Organization, 2/(2), 205--212.

#+END_QUOTE

Additional, the article shows the serendipitous way in which new management ideas are 'discovered' and how they rise to prominence. There is a link here for later--in future we'll talk about /In search of excellence/, by Peters & Waterman. At that time, remember to ask why the book was so successful. Henry also makes a point of saying how hard it is to teach management to those people who aren't managers--he is so right. Until you've been there it doesn't make much sense. Management is a practice (in Turner's sense) more than it is a science (or even an art), and so there is a significant element of management that is tacit (as there is in most parts of social life).

* References

Inkson, K., & Kolb, D. G. (2002). /Management: Perspectives for New Zealand/ (3rd ed.). Auckland: Pearson Education.

Peters, T. J., & Waterman, R. H. (1982). /In search of excellence: Lessons from America's best-run companies/ (1st ed.). New York: Harper & Row.

Turner, S. P. (1994). /The social theory of practices: Tradition, tacit knowledge and presuppositions/. Cambridge: Polity Press.

[fn:1] Well, a good part has to do with the requirement that [[https://www.icanz.co.nz/][ICANZ]] put on institutions about the content that wanabe accountants have to be exposed to.

[fn:2] Mintzberg is mentioned quiet early on in the textbook---Inkson & Kolb, 2003---but I dont' think it explains how he debunked the myth of the manager spending her/his time.

[fn:3] Which of course is based around Henri Fayol's ideas of planning, organising, commanding, co-ordinating, and controlling--the commanding was reinvented as leading, and co-ordinating became organising.
