#+title: Piazza
#+slug: piazza
#+date: 2014-03-15T08:34:00+12:00
#+lastmod: 2014-03-15T08:34:00+12:00
#+categories[]: Teaching
#+tags[]: BUSINESS304 Piazza
#+draft: False

I did a soft-launch of [[https://piazza.com/][Piazza]] with my /Strategic management/ class yesterday. Piazza is described as:

#+BEGIN_QUOTE

... an online platform where students and instructors come together to learn and teach. It offers a refined Q&A environment along with key features for effective course collaboration.

We built Piazza to model the face-to-face discussion among students and instructors. To do this effectively, Piazza displays updates as soon as they happen so you see changes in real time.

Piazza uses the power of community to increase collaboration through wiki-style editing, endorsed posts, student-to-student learning, and instructor feedback.

#+END_QUOTE

There have been a lot of good comments going around both staff and students who are current users of the system here. Indeed, students of courses using Piazza are increasingly asking for other courses to use it as well.

I can see why/how Piazza works for a large class. There are comments coming out from the Faculty of Engineering (who were early adopters) that it does not work so well in smaller classes where there is not the volume of of questions--and more importantly--answers to make it as powerful.

So, I am keen to see how it works in my, relatively small, class.

I'll be trying a few things to encourage folk to use it, such as:

- Putting up class announcements there, rather than using Cecil
- Adding some extra feedback about the class; hopefully the 'insights' I give will make Piazza more useful to some of the class
- Redirecting generic questions there

Having said that, I suspect that unless the class start contributing to it, then Piazza (in my class) will wallow some what.
