#+title: The Science of Sleep
#+slug: the-science-of-sleep
#+date: 2006-07-22T23:25:00+12:00
#+lastmod: 2006-07-22T23:25:00+12:00
#+categories[]: Arts
#+tags[]: Movies
#+draft: False

So, having watched [[{{< ref "the-method" >}}][The Method]] we rushed down to the Civic for the 21:15 showing of [[https://www.imdb.com/title/tt0354899/][The Science of Sleep]]. As we were waiting for the film to start, I made the comment that the seats at the [[https://www.civictheatre.co.nz/][Civic]] are much more comfortable than those at the [[https://www.skycity.co.nz/][Sky City Theatre]]. The people sitting next to us piped up and agreed. Talking with them, it seems they are going to /35/ films during the [[https://www.nzff.co.nz/][festival]]. Wow! What stamina. However, they reported that there is someone who is seeing over /60/ of the films.

Back to the film.

With films late in the evening you need something that is going to keep you attention, and this one did. The "TV Studios" set where Stephane plays out/creates his dreams was wonderfully kitsch. I also liked the way the film drifted between French and English in quite a seamless way.

Being a French film, it did have the French /J ne sais quoi/ about it, which I always find endearing.

For this film, I'll go with three out of five (worth seeing).
