#+title: Performance reviews
#+slug: performance-reviews
#+date: 2016-05-24T20:50:26+12:00
#+lastmod: 2016-05-24T20:50:26+12:00
#+categories[]: Service
#+tags[]: Productivity
#+draft: False

The University of Auckland is going through the process of reviewing its system of Academic Performance Reviews (which are meant to do what it is says on the box, review the performance of academics). After a period of consultation, the 'process' has provided its responses to the feedback it obtained on the current system of APRs. Here are my notes on those responses.

Thank you for this opportunity to comment on the responses to the feedback on the proposed changes.

In reviewing the themes of the feedback that was received it appears as if the responses focus on addressing what were--in the initial round of consultation--the issues raised by staff regarding the current system. It is not clear that the causes of those  symptoms have been investigated let alone addressed. The result is a set of proposals that do not seem to be closely tied to the evidence we have about performance review processes in general.

I wish to put forward the notion that the root cause of many--if not all--of the symptoms identified in the first phase of consultation arise because, as Forbes in 2013 put it, it is "Time to scrap performance appraisals". A review of the current trends seems to explain "Why the annual performance review is going extinct" (Fast Company, 2015). Even the Society for Human Resource Management asks, "Is the annual performance review dead?" (2015) arguing that:

#+BEGIN_QUOTE

Performance reviews are based on several long-held assumptions that don’t hold up to scrutiny.

#+END_QUOTE


Reading articles like those highlights the facts that the problems that we face--and as identified in the initial feedback--are generally not unique. And yet ...

... and yet well resourced firms such as GE, Adobe, Accenture, Microsoft, Google have given up trying to make what seems to be a fundamentally broken system work. Instead they are trying new approaches to performance management (beyond the annual reviews). I am not against performance management and rewarding performance, far from it, but a system grounded in annual reviews (especially in a knowledge intensive business rather than a manufacturing business) seems unlikely to deliver the desired outcome.

However, that is just what the 'popular press says'. Is there hard academic evidence that the annual performance appraisal system delivers appropriate outcomes in terms of either organisational performance or career development. It is true that once upon a time (in the 60s and 70s) the annual performance review was put forward as an almost universal panacea; and even today many HR consultancies advocate for their use. But that is not surprising as "fixing" annual performance review systems is a source of ongoing revenue for those same consultants. The truth is that it is nigh-on impossible to fix the fundamental issues of such systems.

This is doubly true in our situation where--even with the best will in the world--the 'managers' of academic staff are relatively short-term managers, and rarely have the opportunity or the time to develop the skills to be truly effective in administrating and conducting annual reviews. Indeed, the literature on the professions is rife with empirical and theoretical evidence for the very significant difficulties that the 'producing manager' has to contend with in what is essentially a fixed term role; a role in which your subordinate may well be your supervisor at some stage in the future.

But returning to the specific evidence and research on annual performance reviews.

There is actually little research in the area. Looking for recent research (post-1990), there are no well cited articles that demonstrate a meaningful link between annual performance reviews and organisational or individual outcomes. For example, in their meta-analysis Smithern, London and Riley (2005) found that "improvement in direct report, peer, and supervisor ratings over time is generally small"; actually they later say it was "very small".  Given that, and given the challenges of developing a system of annual review that is not seen a problematical one needs to question why do them in the first place. 

What is clear is, that if there are performance problems then the evidence is unambiguous--they should be addressed immediately. If the intent is to provide career development, then that is a wholly different process requiring a different approach.

As I say, I am not against performance management. Indeed I applaud efforts of firms such as Merrill Lynch who:

#+BEGIN_QUOTE

[have] changed from having simply a performance appraisal system to now having a performance management system. Merrill Lynch is one of the world’s leading financial management and advisory companies, with offices in 36 countries and private client assets of approximately US$1.1 trillion (https://www.ml.com/).  As an investment bank, it is a leading global underwriter of debt and equity securities and strategic advisor to corporations, governments, institutions and individuals worldwide.  Recently, Merrill Lynch started the transition from one performance appraisal per year to focusing on one of the important principles of performance management: the conversation between managers and employees where feedback is exchanged and coaching is given if needed.


#+END_QUOTE

That attitude, of regular and frequent conversations and coaching seems to be the hallmark of the effective modern approach to performance management. It should not be grounded in what is essentially an annualised process. 


