#+title: Well, that didn't go quite as expected
#+slug: well-that-didnt-go-quite-as-expected
#+date: 2014-07-23T20:42:00+12:00
#+lastmod: 2014-07-23T20:42:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT300
#+draft: False

It was an odd day in MGMT 300. As I was talking to the students, I became increasingly concerned that many of them had not done this week's readings; the conversation just wasn't at the right level.

Yes, there were some good/interesting/useful ideas coming out, but the level just ... the degree of participation is what I expect for a stage 3 class, but the intellectual depth felt 'off'. When I tested my assumption, it turned out that a large majority (maybe as many as 90%) had not done the readings.-I was rather discombobulated by this, and I never really got the conversation going again--instead I drifted into a rather poor attempt at 'saving' the class by becoming somewhat 'lecture like'. Not the best response.

So, I'm sitting here wondering what I might have done differently. First, what might I have done (what might I do in the future), to get a higher uptake with the readings. -Secondly, when a class--as a whole--has not done the expected pre-work what is a more helpful (in the long term) response.

I think I might take these themes up with the class at our next session.
