#+title: Project closure
#+date: 2021-11-06T10:32:00+1300
#+lastmod: 2021-11-06T10:32:00+1300
#+categories[]: Zettels
#+tags[]: Coursera Project_management

The process performed to formally complete the project, the current phase, and contractual obligations.

Three criteria that make up a project closing.
- Assure all work is done
- Ensure all agreed upon project management processes are executed
- Get formal recognition from stakeholders that the project is done

Avoid the:
- Never-ending project: Where the deliverables and tasks cannot be completed
- Abandoned project: When inadequate hand-off or transition of the project deliverables occurs

* The closing process for clients and stakeholders
- Is there a need for a small closing process at the end of each milestone, or a formal larger comprehensive closing phase at the very end only? (or Both)
  - Does the milestone need to be revisited later? If so, probably not closed.
**  Steps for closing process after each phases or milesetone
 - Refer to prior documentation (SoW, RFP, Risk register, RACI chart)
   - Was all the work done?
 - Put together closing documentation
 - Conduct administrative closure of the procurement process
 - Execute any necessary follow-up work; e.g., Final feedback, surveys ...
** Steps for closing process at the end of the process
- Provide the necessary training, tools, documentation, and capability to use your product
- Ensure the project has satisfied its goals and desired outcomes
- Document acceptance from all stakeholders (written proof)
- Review all contracts and  documentation (SoW, RFP, Risk register, RACI chart) with the team
- Conduct a formal retrospective
- Disband and thank the project team

* Impact reporting
A presentation that is given at the end of a project for key stakeholders.
- How the project landed in terms of scope, time, and budget.
- State when the new service or product launch and discuss any available feedback from users
- Explain how the desired outcomes were achieved

** Demonstrating project impact to stakeholders

Previously, you learned why completing the closing phase of the project life cycle is important. As we discussed, a formal closing process is essential because improper closing may leave you at risk for incomplete contracts and scope. It is also important to make sure that all stakeholders feel like their needs are met and to review areas for improvements in the future.

*** Highlight key performance areas

The purpose of your impact report is to show your key stakeholders the impact your project had on the organization. Goals, objectives, budget, schedules, and key performance indicators (KPIs) need to be determined at the beginning of your project. Your impact report should demonstrate how well you did against those early targets. In your report, you should also answer the question: What was the problem we were trying to solve, and how did we solve it? This will help you showcase the value your project outcome brought to the business.

Highlight these key performance areas to demonstrate to your stakeholders how you achieved successful results and outcomes:

- First, describe the goals and objectives you set for the project and what you hoped to have achieved by the end.

- Then, describe how you met those objectives against your KPIs. A KPI is a measurable value that demonstrates how effective a company is at achieving their objectives. In your impact report, review how you defined the success of your project at the beginning, and highlight the outcomes you achieved that demonstrate this success.

- Finally, showcase your schedule and budget performance by outlining your cost savings and efficiencies. Demonstrate that you met the deadlines set in your project scope and that your project was completed within budget.

*** Use metrics to showcase your results

Use facts and statistics to highlight the results you achieved related to the performance areas described in the section above. Examples of common metrics you might include to demonstrate a positive impact could include:

- Improvement in schedule performance

- Revenue growth

- Positive return on investment (ROI)

- Increased external user counts

- Increased percentage of internal users

- Cost vs. margins

- High percentage of customer satisfaction

- Reduction in overhead

- Reduction in technical issues

- Time saved

Metrics and data points are one of the best ways to present impact. Throughout your project, collect data and track progress in each of the areas you want to measure. If you can complement your metrics with the appropriate visuals and tie them back to the project’s larger goals, you can quickly demonstrate your project’s success and value.

*** Prepare an effective impact report presentation

An effective presentation can help your stakeholders understand your project’s impact. In order to successfully convey all of the information you have prepared:

- Be concise.
- While you should share metrics that illustrate how you achieved your project goals, you do not need to include extraneous details. For clarity, organize information by using bullet points instead of paragraphs.

- Understand your audience.
- Make sure that your report does not use too much technical language or jargon to help your stakeholders understand it.

- Use visuals.
- Use a digital presentation application, such as Google Slides, Microsoft PowerPoint, or Canva to present your impact report. Add diagrams, such as charts and graphs, to illustrate your results. Use images to add visual interest. Add icons to draw attention to information and help your stakeholders quickly understand information.

- Describe your learnings.
- Discuss lessons you learned during the course of the project and any areas you have identified for improvement.

- Keep your stakeholders engaged.
- Grab and keep your stakeholders’ attention by varying the way that you present your data:

- Show: Play videos of demos, testimonials, or case studies.

- Storytell: Tell a story or anecdote related to the data in the report.

- Engage: Ask for audience participation through questions, surveys, or quizzes.

* Backlinks
- [[{{< ref "202109121935-project-phase-closure" >}}][Project phase - closure]]

