#+title: Crafting and executing strategy
#+slug: crafting-and-executing-strategy
#+date: 2004-08-25T21:18:00+12:00
#+lastmod: 2004-08-25T21:18:00+12:00
#+categories[]: Teaching
#+tags[]: MGMT302 Textbooks
#+draft: False

I've just finished reading:

#+BEGIN_QUOTE

Thompson, A. A., Strickland II, A. J., & Gamble, J. E., (2004). /Crafting and executing strategy: Text and readings/ (14th ed.). New York, McGraw-Hill.

#+END_QUOTE

The preface of this text books says it aimed at the senior-level or MBA student, and so I'm considering it as a replacement for MGMT 302: Business policy & strategy, because our existing text book is no longer available.

As this is the 14th edition, you can tell it has been around for some time (looking at the frontispiece, it looks like it first came out in 1978). The book is quite unitarist in its views. For example the question "What is strategy?" (let alone "Do strategies actually exist at all?") is answered in a straight forward manner, with none of the nuances or dilemmas that something like de Wit & Meyer (2003) or Mintzberg, Lampel, Quinn, & Ghoshal (2003) insist on presenting. The emphasis of the book is largely on the /content/ of strategy with little regard for the /process/ or /context/ of strategy. Consequently, the book does go somewhat 'against the grain', in as much as the mandate of the course is to focus on the process side of strategy; whereas, [[https://www.business.auckland.ac.nz/comwebContent/index.cfm?fs=pgv&pageid=3621][International Business]] to be more focused on the content issues.

That's not to say the book is bad; far from it. It does the job it sets itself admirably--it's just not what is needed for MGMT 302

* References

de Wit, B., & Meyer, R. (2003). /Strategy process, content, context: An international perspective/ (3rd ed.). Minneapolis, M: Thompson Learning.

Mintzberg, H., Lampel, J., Quinn, J. B., & Ghoshal, S. (2003). /The strategy process: Concepts, contexts, cases/ (4th ed.). Upper Saddle River, N: Prentice-Hall.
